### ISSUE TITLE
small issue: first launch

### ISSUE THREAD

**Issue by mgrn0** [bdkjones/CodeKit2#1]
when launching the app for the first time, there is this introduction screen with the rotating wheels. 
I immedeately went to "File > Edit Defaults for new Projects", the yellow animated bar appeared, but I could not set the defaults (wheel animation stayed on screen instead). After Closing and Re-launching the app I could successfully edit the presets.

**Comment by bdkjones** [comment]
Excellent. The first issue. I'll take a look!

**Comment by bdkjones** [comment]
Fixed. Will be in the next beta release. Thanks!
