### ISSUE TITLE
Can't add any project to CK2

### ISSUE THREAD

**Issue by guill3m** [bdkjones/CodeKit2#10]
I'm trying to add a project to CodeKit2 (both with drag&drop and with the + button) and it just crashes (I'm now in the 15th or so crash).

At first I thought it could be because of the unzip app (I've had problems with that before) so I've unzipped it both with "The Unarchiver.app" and the default "Archive Utility", but not luck with that.

I'm on OS X 10.9.1
MBPRetina first gen (mid 2012)

Here is the last crash report, let me know if you need any more information.

[CrashReport](http://cl.ly/0Z14330p1Y3G)

**Comment by bdkjones** [comment]
What is the full path to the project you're attempting to add?

**Comment by guill3m** [comment]
I've tried with a big ass project with 1661 items inside:
`/Users/guill3m/Work/Netdudes/u2/src`

A small projec with 25 items:
`/Users/guill3m/Work/Personal/ehemm`

And an empty folder (thats the last one, the one from the crash report:
`/Users/guill3m/Work/Personal/untitled folder`

**Comment by bdkjones** [comment]
Ok. Please zip one of these projects, throw it on Dropbox and send me a link to download it so that I can test with a debugger running on my end. Thanks.

**Comment by guill3m** [comment]
Ok, here it is one of them, thanks: [ehemm project](http://cl.ly/0W2b2r3Z3T3K)

**Comment by pmeissner** [comment]
Same deal here. I can't create any projects or frameworks — even completely empty folders. [crash report](https://www.dropbox.com/s/1bm8164aqly8kvy/CodeKit_2013-12-18-152508_Phils-iMac.crash)

![screen shot 2013-12-18 at 3 37 23 pm](https://f.cloud.github.com/assets/392386/1777345/5d666c40-6824-11e3-8a38-76bc391b8be5.png)

**Comment by mdavis1982** [comment]
@pmeissner What are the full paths of the projects you've tried to add?

@bdkjones I'm wondering if this is a case-sensitivity issue - the provided paths so far all have uppercase letters - and although not likely, it may be a case-sensitive filesystem?

**Comment by cdharrison** [comment]
My first try to load a project failed. I then quit the app and then reopened it and tried again and it worked.

**Comment by pmeissner** [comment]
Full path for my project:
`/Users/whitney/Desktop/MAMP/AAWH/_themes/hah`

It also crashed when I tried to create a "New Zurb Foundation project…"

**Comment by bdkjones** [comment]
Ok. I've been able to reproduce this over here. Looking into it.

**Comment by bdkjones** [comment]
Question: have each of you added one or more CodeKit Frameworks to the app?

**Comment by bdkjones** [comment]
Also: please try quitting the app and relaunching it while holding down shift. Try adding projects again and see if the issue persists.

**Comment by pmeissner** [comment]
I am unable to add Projects OR CK Frameworks. Relaunched it several times while holding shift — still no joy when trying to add a project or framework. It crashes in both instances.

**Comment by guill3m** [comment]
Not really, actually, if I try to add any folfer as a project I get a crash too.

Regarding the case-sensitivity, my system is not case-sensitive.

**Comment by noahfrederick** [comment]
@bdkjones 

> Question: have each of you added one or more CodeKit Frameworks to the app?

No. Attempting to add a framework causes a crash too. Tried both drag-n-drop and through the file browser.

> Also: please try quitting the app and relaunching it while holding down shift. Try adding projects again and see if the issue persists.

The issue persists here.

**Comment by bdkjones** [comment]
@!(#&^^!_&@#^$)!_#%R

I have found the problem. It's a Core Data issue. Fixing now and I'll push a new beta up here. I swear I know how to write apps....

**Comment by mdavis1982** [comment]
^^ That's what I sound like every day when I'm coding... :grin:

**Comment by guill3m** [comment]
If it's worth something, my keyboard layout is Spanish-ISO. Thinking stuff that can be different from your setup.

The Shift-Start Trick isn't working for me either.

**Comment by guill3m** [comment]
Great, I won't be able to test it until tomorrow morning (here in Germany is 22:40 now), but definetly try first thing tomorrow if it's already here.

Thanks.

**Comment by bdkjones** [comment]
Figured it out. This issue only manifests if you follow this process:

1) Modify any value for JSLint, JSHint or CoffeeLint in the "New Project Defaults" area.
2) Attempt to add any project.

It's step 1 that produces the bug. I just never messed with the new project defaults because I already had my starting values set.

**Comment by bdkjones** [comment]
Just pushed Beta 2, which resolves this issue. Give it a whirl.

**Comment by guill3m** [comment]
I've deleted the preferences via terminal AND restarted (wasn't worling without the restart) and now I can add projects and frameworks to CodeKit2, in the "old" beta.

I'll try the new beta in some hours, thank you.

**Comment by pmeissner** [comment]
I may have to try your fixes @guill3m  Beta 2 is still crashing on me. FYI @bdkjones I never modified any values for JSHint, JSLink etc.

**Comment by pmeissner** [comment]
Tried deleting the preferences via terminal AND restarting and no joy. Maybe I'll have better luck on my home computer.

**Comment by noahfrederick** [comment]
@bdkjones Yep, Beta 2 has resolved this issue for me.
