### ISSUE TITLE
Feature request: Autoprefixer 1.0

### ISSUE THREAD

**Issue by maxlapides** [bdkjones/CodeKit2#101]
It would be awesome if you could update Autoprefixer to 1.0 - really I just want some of the bug fixes :)

Oh also, super minor suggestion: when you select "Special Language Tools," the header is spelled "AutoPrefixer" but everywhere else it's spelled "Autoprefixer." I think the way they brand themselves is the latter with the lowercase p.

**Comment by bdkjones** [comment]
Implemented in Beta 5. Thanks.
