### ISSUE TITLE
Compass Config File Suggestions

### ISSUE THREAD

**Issue by maxlapides** [bdkjones/CodeKit2#102]
After I modify my config.rb file manually, if I go back to the Compass settings in CodeKit, those changes aren't reflected. It's not that big of a deal, it was just a little confusing at first. 

Also, it's pretty simple to get source maps working with Compass already by adding `source map = true` to the config.rb file, but it would be sweet if there were a way to do this from the user interface.

**Comment by bdkjones** [comment]
The options in the UI do NOT reflect your current settings. That's just a worksheet to create a new config file.
