### ISSUE TITLE
Crash when adding projects

### ISSUE THREAD

**Issue by devilskitchen** [bdkjones/CodeKit2#104]
As requested by @bdkjones on issue #93, I am opening this as a new issue.

In both Beta 3 and Beta 4, CodeKit 2 crashes whenever I attempt to add a project. These projects have all been previous added to CK1, and successfully compiled on that application.

I have tried Shift-restart and deleting the Preferences through the Terminal, as outlined in the Read Me.

I have emailed crash reports.

All running on a Late 2006 Mac Pro 2x2GHz, 5GB RAM, running 10.7.5 (because I can't upgrade any further—thanks Apple!).

**Comment by bdkjones** [comment]
Is anyone else here still on OS 10.7? If so, please chime in and let me know if CK2 is working properly for you.

**Comment by bdkjones** [comment]
I need the crash reports posted here, please. I get SO much email I can't keep it straight.

**Comment by devilskitchen** [comment]
Will post them when I get home. If you get a chance to search your email, they will have come from chris.mounsey@gmail.com

**Comment by devilskitchen** [comment]
Sorry for the delay in posting the crash reports. Here are links to two of them (both tested on Beta 6 just a few minutes ago).

https://www.dropbox.com/s/vemqm8otdikp6px/CodeKit_2014-01-07-195141_DK-Mac-Pro.crash
https://www.dropbox.com/s/4r6hcaunj1gkwcu/CodeKit_2014-01-07-195237_DK-Mac-Pro.crash

**Comment by bdkjones** [comment]
Okay. I need the entire project folders that you're adding to the app to produce the crash. 

Please zip them and post download links here so I can test on my end. There's a crash happening while CodeKit is recursing down the directory tree. This _could_ be caused by a corrupt file/folder on your disk. I need the exact folders and their contents to see what's happening.

**Comment by devilskitchen** [comment]
It's crashing with every, single project that I try to add—regardless of size, location on the disk, Dropbox or not, etc. I also tried adding a folder with no sub-folders; then I added a single LESS file—CK2 crashes every time.

I've tried adding several different projects (just in case there was something corrupt), but here are three that I tried this evening (the third is the same one that I gave you for #72).

https://www.dropbox.com/s/4n09rtp8a06hwmt/Flagship-RFT.zip
https://www.dropbox.com/s/xe2rjkn4icfiufb/Universal-Sandbox.zip
https://www.dropbox.com/s/5cdk8diqtezyp8t/guess2give.zip

**Comment by bdkjones** [comment]
All three projects add perfectly on my end. This is definitely something that's isolated to your system. The likely culprit is the old OS you're running. 

Do you have another Mac available for testing? I need someone else to add these projects to the beta running on OS 10.7 on a different Mac to see if they get the same crash.

**Comment by devilskitchen** [comment]
I think that one of my colleagues may have a 10.7 machine. I'll check and get back to you asap.

**UPDATE:** it looks like it's a 10.7 issue—exactly the same thing happens when adding files or folders on my colleague's machine (Mac Mini 2011, running 10.7.5)*.

Crash Report: https://www.dropbox.com/s/96uskt9739khys5/CodeKit_2014-01-08-105050_Nora-Harriss-Mac-mini.crash
- Don't worry—she's in a meeting so she didn't see the application!

**Comment by bdkjones** [comment]
I think the solution may be making CodeKit 2.0 a 10.8+ application. I think the reason it's crashing on 10.7 is because I might be using an API that's only valid on 10.8 plus.
