### ISSUE TITLE
Crash when saving included `.scss` for first time

### ISSUE THREAD

**Issue by sathomas** [bdkjones/CodeKit2#105]
1. In parent style sheet add `@import "child"` but don't save.
2. Create `child.scss` and add content.
3. Save `child.scss` --> CK2 Beta 4 crashes.

Crash report [here](https://www.dropbox.com/s/9aqcbvydrmm5f1f/ck2b4.rtf)

**Comment by sathomas** [comment]
Changed from libsass to ruby and no longer crashes

**Comment by yratof** [comment]
This might be related, but a new project added to codekit beta 4, chose LibSass as the compiler and it crashes upon every save.

Here's the error report: http://cl.ly/T7CI

**Comment by bdkjones** [comment]
This is a problem with libsass. It's fixed in the next Beta, which I'll post probably late tomorrow.
