### ISSUE TITLE
Bourbon with sass, not libsass

### ISSUE THREAD

**Issue by yratof** [bdkjones/CodeKit2#106]
When using bourbon without libsass, i get this error

DEPRECATION WARNING on line 44 of /Users/yratof/Downloads/codekit2beta-master/CodeKit.app/Contents/Resources/engines/bourbon/bourbon/app/assets/stylesheets/bourbon/addons/_html5-input-types.scss:
Assigning to global variable "$all-text-inputs-focus" by default is deprecated.
In future versions of Sass, this will create a new local variable.
If you want to assign to the global variable, use "$all-text-inputs-focus: append($all-text-inputs-focus, $input-type-focus, comma) !global" instead.

**Comment by yratof** [comment]
obviously this isn't a direct codekit2 error, but since i cannot edit the source, might be worth mentioning

**Comment by bdkjones** [comment]
This needs to be filed on the Bourbon github page. Please close this issue and file it over there.

-Bryan
