### ISSUE TITLE
Browser Refreshing / WordPress

### ISSUE THREAD

**Issue by chriscoyier** [bdkjones/CodeKit2#107]
CSS style injection works just fine for me in Chrome with a very simple test (Using .scss).

But in my "real" project (a WordPress theme), I can't get it to work in Chrome or Safari. Sass runs, Autoprefixer runs, the .css file is created correctly, but no refresh or style injection happens. 

I'm using the .local:5757 address provided by the internal server, which serves up the site fine, just no refreshing. I'm using MAMP to run the the site, so External Server address is pointed to that (it doesn't work otherwise).

I've tried adding refresh delay, but no amount of delay seems to help.

**Comment by smlombardi** [comment]
Indeed.  See #57

**Comment by bdkjones** [comment]
Hey Chris, 

Is this Wordpress installation using permalinks or any other Wordpress plugins? Can you share the project with me so I can test it over here?

**Comment by chriscoyier** [comment]
I'll get as close to a reduced test case as I can together for you.

**Comment by mdavis1982** [comment]
@chriscoyier Does this happen every single time with this particular project?

**Comment by chriscoyier** [comment]
Yes I haven't gotten it to work at all yet. (just the refreshing / style injection part)

**Comment by bdkjones** [comment]
Just to confirm, you are running Beta 4?

**Comment by chriscoyier** [comment]
Is this latest? 

![img](http://f.cl.ly/items/3Y121T2o0c1e3B1q061j/Screen%20Shot%202013-12-29%20at%205.44.57%20PM.png)

**Comment by chriscoyier** [comment]
(I know no screenshots, that's essentially private since this is a private repo and there is no public listing of my screenshots like that).

**Comment by mdavis1982** [comment]
@chriscoyier I think posting screenshots is okay in these issues as long as they're uploaded to GitHub directly rather than being hosted elsewhere :smiley_cat:

**Comment by bdkjones** [comment]
Yep; that’s the latest. And screenshots/videos posted here are strongly encouraged!

**Comment by smlombardi** [comment]
As posted on #57, I confirm this.  I have the WP running fine in CK2, just no style injection.

**Comment by chriscoyier** [comment]
I'm uploading a video called codekit-wp.mp4 to the shared Dropbox folder that is me explaining the issue and all the players involved.

**Comment by maxlapides** [comment]
Hi Chris:

First, the reason why style.scss is compiling uncompressed is because you're using Autoprefixer, which does not have the minification capability in version 0.8. But, version 1.0 does and @bdkjones said that he's updating to Autoprefixer 1.0 in beta 5: https://github.com/bdkjones/codekit2beta/issues/100

The reason why live injection isn't working for you is because you have CodeKit watching only your theme folder. Try having it watch your entire WordPress installation - that's the only way I've gotten it to work.

**Comment by smlombardi** [comment]
@maxlapides I have it watching my entire WP folder, still no style injection.

**Comment by maxlapides** [comment]
Wait actually I'm testing it again and the page refreshes when I save a script, but when I update a style, it's not injected. I'm pretty sure it was working before, but maybe not since the latest beta?

**Comment by maxlapides** [comment]
On at least one of my WordPress projects, I got the CSS injection working my using the Non-Bonjour Address instead.

**Comment by hartless** [comment]
Seeing same issue with live injection using Ghost. Watching the root Ghost folder. CK2b4.

![image](https://f.cloud.github.com/assets/1090636/1829230/e99b7348-728a-11e3-977c-1bf0248f2551.png)

**Comment by bdkjones** [comment]
As in, Ghost the app?

**Comment by hartless** [comment]
sorry, yes https://ghost.org/ 

Running locally.

**Comment by smlombardi** [comment]
Bryan here's the site I have been working on https://dl.dropboxusercontent.com/u/67226/FileChute/for-bryan-jones.zip

**Comment by bdkjones** [comment]
Okay; I've narrowed down what's causing this. It's got to do with the root-relative paths that Wordpress generates and the fact that CodeKit currently violates the "same-origin" policy when it rewrites the root-relative paths for CSS files and scripts to support mDNS (bonjour hostnames). 

The good news is I can fix it. I'll do that later today and post an updated beta.

**Comment by mdavis1982** [comment]
:+1:

**Comment by bdkjones** [comment]
Fixed in Beta 6. 

Will push that release shortly.
