### ISSUE TITLE
JSHint Settings Don't Stick

### ISSUE THREAD

**Issue by maxlapides** [bdkjones/CodeKit2#108]
I keep trying to check off the "devel" option for JSHint, but it won't stick. After I check off "devel," I tried going to the JavaScript settings and pressing the sync button, but to no avail. When I save a JavaScript file, it just checks all of my imports assuming the "devel" option is off. Then when I go back to the JSHint settings, the option is unchecked again.

**Comment by maxlapides** [comment]
Just tested this again in beta 5. Steps to reproduce:
- Open project settings for any project
- Under JSHint, check off "devel"
- Save a script in your project (it should lint properly, using the "devel" environment)
- Click refresh (or wait until the project auto-refreshes)
- Save script again and now the "devel" environment is unchecked and a bunch of warnings appear if you're using alert, confirm, etc.

**Comment by bdkjones** [comment]
Ok. I've been able to replicate this on my end. Fixing.

**Comment by bdkjones** [comment]
Fixed in Beta 8. 

It helps if you type variable names correctly when programming.
