### ISSUE TITLE
Feature suggestion: Add Bundler to CodeKit

### ISSUE THREAD

**Issue by rpkoller** [bdkjones/CodeKit2#109]
I ran into some serious gem dependency troubles lately. Along the way solving those issues i got always one recommendation for preventing troubles like that - i should give bundler ( http://bundler.io ) a spin for managing gems in a project taking care that the dependencies are matched. I guess bundler alongside bower would complement one another more than well.

**Comment by bdkjones** [comment]
Thanks for the suggestion, but this is not really a road I want to go down with CodeKit at this time.
