### ISSUE TITLE
Multiple browser refreshes

### ISSUE THREAD

**Issue by sathomas** [bdkjones/CodeKit2#110]
With this project: https://www.dropbox.com/s/suhsd0ghb9ypgrg/atltrails.zip

When saving a file, the local browser is refreshed multiple times. Definitely annoying with larger pages.

Possibly, this is because the project uses `.kit` includes to include intermediate outputs from other processors (e.g. markdown and LESS files processed to HTML and CSS respectively). If so, issue #97 would presumably address the problem.

**Comment by maxlapides** [comment]
This may also be related to this issue: https://github.com/bdkjones/codekit2beta/issues/98

**Comment by bdkjones** [comment]
What files in the attached project are you saving to generate the multiple refreshes?

**Comment by sathomas** [comment]
just about any one iirc, I'll verify later tonight

**Comment by sathomas** [comment]
`index.kit` will do it. Here's a complete sequence from a computer reboot:
1. Open CK2 (it restores project from last session)
2. Click "Preview" button in upper right to open browser (Safari 7.0.1 in OS X 10.9)
3. Open project in Chocolat.app
4. Open `index.kit` (in Chocolat.app)
5. Cmd-S to save
6. The browser window refreshes twice. It's indicated in the CK2 logs as such:

![screen shot 2014-01-02 at 6 06 54 pm](https://f.cloud.github.com/assets/1731910/1836351/966ca2fe-7402-11e3-98de-b5c8739ffbd9.png)

I'm pretty sure it happens on saving any file. FWIW, Chocolat.app doesn't store a hidden file or such in the directory, and I've disabled the open to auto-save on loss of focus (which wouldn't apply here, anyway, since I'm not leaving Chocolat.app between refreshes).

**Comment by bdkjones** [comment]
This should be resolved in Beta 5, thanks to the "duplicate compile" fix.
