### ISSUE TITLE
App window dimensions reported incorrectly to OS X screen capture

### ISSUE THREAD

**Issue by sathomas** [bdkjones/CodeKit2#111]
When doing a screen capture of the CK window using Shift-Command-4, spacebar, OS X seems to think the window dimensions are those of the initial load; it doesn't take any resizing into account. This can be seen in 

![screen shot 2014-01-01 at 9 46 10 am](https://f.cloud.github.com/assets/1731910/1829729/9f565b5e-72f3-11e3-8808-40493b07e7ce.png)

where the dimensions of the screen shot are significantly larger than the actual app window.

**Comment by bdkjones** [comment]
Good catch. Resizing the window did not automatically resize the overlay that comes in when you drag something onto the window. Fixed in Beta 5.
