### ISSUE TITLE
JavaScript and TypeScript should be spelled with a capital S

### ISSUE THREAD

**Issue by maxlapides** [bdkjones/CodeKit2#113]
Super minor thing: I'm pretty sure JavaScript and TypeScript should be spelled with a capital S. This is an issue in:
- Project settings (for JavaScript and TypeScript)
- About screen (for TypeScript)
- Preferences (for TypeScript)

**Comment by bdkjones** [comment]
I'm willing to do this for TypeScript. But everyone and their grandmother uses "Javascript" with a lowercase 's'.
