### ISSUE TITLE
The application crashes when opening project in browser

### ISSUE THREAD

**Issue by jornki** [bdkjones/CodeKit2#114]
**Description**
When trying to preview a basic project CodeKit quits.

**Steps to recreate**
1. Creates a folder called "test" on the Desktop
2. Creates a file "index.html" in "test" (basic HTML page)
3. Adds project to CodeKit (beta 5)
4. Selects the «server» button and clicks the ip address or computer name
or
4. Types the ip address into the browser nav field

**What happens**
- The browser opens
- CodeKit crashes
- The browser alert dialog goes into a infinite loop with the message «Failed to establish a connection to CodeKit. Live refreshes will not work.»

**Setup**
- MacBook Pro (latest)
- OS X 10.9.1
- TextMate 2
- Browsers Safari and Chrome (latest stable versions)

**Comment by projekt8** [comment]
Got the same problem... 

The error message says:
**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]'
terminating with uncaught exception of type NSException
abort() called

I've send you the whole crash report via email (can't attach .crash files in github...)

**Comment by jornki** [comment]
Yep, the same crash report is generated for me.

**Comment by hartless** [comment]
Same here. After launching Codekit, switched projects—crash.
1. Restarted CK2b5 with Shift key.
2. added basic project as above
3. Click Preview button
4. Browser opens
5. Codekit crashes

Even opening previous (working in Codekit) projects crashes every time.

Crash Report here: http://cl.ly/1k3i2m3G3C1h

**Comment by johnsardine** [comment]
Same here on my side.
1. Unzip latest beta
2. Replace current app
3. Open with shift pressed
4. Add simple project with index.html and style.less
5. Press preview
6. Browser opens and CodeKit crashes

Crash report: http://cl.ly/TBsK

**Comment by verpixelt** [comment]
Same here. After opening the the preview Codekit tells me it can't establish a connection and than the app crashes.
Crash report: http://goo.gl/N6fO9A

**Comment by sathomas** [comment]
Found one cause of this. If the page requests a resource that doesn't exist (e.g. a 404), CK crashes. (Check your spelling in `href` attributes ;^)

**Comment by bdkjones** [comment]
Fixed in Beta 6.
