### ISSUE TITLE
CSS Autoprefixer failing in Beta 8

### ISSUE THREAD

**Issue by sathomas** [bdkjones/CodeKit2#115]
Autoprefixer has become unusable with beta 5. It fails with error message:

> Autoprefixer failed to process the CSS file. It returned this error message: Can't parse CSS: Unclosed block at line 1:4076 in /Users/stephen/Software/atltrails/build/css/styles.css

On lines (found by commenting out) such as:

```
@media screen and (min-width: 801px) { #about { background-image: url('../img/autumn-lg.jpg'); } }
```

It even fails on popular third-party style sheets such as Font Awesome

**Comment by sathomas** [comment]
Note: After disabling autoprefixer in CK I can run it from the command line on the output file with no problem.

**Comment by bdkjones** [comment]
Which _version_ of Autoprefixer are you running on the command line? Are you sure it's the same version as the one in CodeKit Beta 5?

**Comment by sathomas** [comment]
```
$ autoprefixer --version
autoprefixer 1.0.20131222
```

Should be the same if CK -> About isn't fibbing

**Comment by sathomas** [comment]
Seems to be related to libsass compiler. Falling back to ruby solves the problem.

**Comment by bdkjones** [comment]
Ah. Well, that's an issue for the libsass guys then. Please open a report on the libsass project; it's quite likely that the libsass compiler is generating incorrect CSS. Either way, this is not a CodeKit issue.

**Comment by sathomas** [comment]
I'm not certain about that. If I disable autoprefixer in CK but keep libsass enabled, the resulting css file works fine with autoprefixer on the command line. It only fails when run in CK. (Judging from the error message, perhaps there's some sort of race condition which causes CK to trigger autoprefixer before libsass has finished?)

**Comment by bdkjones** [comment]
Please post a link to download a demo sass stylesheet that shows this issue. Thanks.

**Comment by bdkjones** [comment]
Also:

Which release of libsass are you running on the command line and how are you running it? (I assume sassc.)

Make sure you’re running the absolute LATEST version of sassc, with the latest version of libsass.

**Comment by sathomas** [comment]
Here's the whole project: https://www.dropbox.com/s/suhsd0ghb9ypgrg/atltrails.zip

The bug triggers when I compile `/src/styles/styles.css`. (Of course, if it _is_ a timing problem, it may not behave the same on other systems.)

**Comment by sathomas** [comment]
I'm not running libsass from the command line. I'm using autoprefixer from the command line. (I'm only running libsass from within CK.) To be clear:

**Option 1: Run libsass and autoprefixer from within CK:** Autoprefixer fails with indicated error message.

**Option 2: Run libsass from within CK and then manually run autoprefixer on the resulting output:** No errors.

**Option 3: Run autoprefixer from within CK (no libsass):** No errors

**Comment by bdkjones** [comment]
Please test with Beta 6. I updated both libsass and autoprefixer to their very latest releases.

**Comment by sathomas** [comment]
I'm unable to test this with Beta 6 because of bug #124. Whenever I try to change project settings to enable libsass, CK locks up.

**Comment by sathomas** [comment]
After blowing away all CK config and settings I was able to get past #124. The problem still persists with Beta 6.  Sure seems like some kind of timing problem / race condition where CK is firing up autoprefixer before libsass is finished. Here's the CK error message:

> Autoprefixer failed to process the CSS file. It returned this error message: Can't parse CSS: Unclosed block at line 1:77816 in /Users/stephen/Software/atltrails/src/intermediate/_initial.css

Again. There's nothing wrong with autoprefixer or libsass themselves. If I use the CK-builtin libsass and then run autoprefixer manually from the command line, all is fine. It's only a problem when CK tries to run autoprefixer.

The workaround of disabling libsass still works. I'm thinking CK's implementation of libsass is pretty much useless (to me, anyway).

**Comment by sathomas** [comment]
Probably not a surprise, but problem persists in beta 7

**Comment by sathomas** [comment]
Still there in beta 8 in case there's doubt.

**Comment by bdkjones** [comment]
Please send me just the stylesheets for this project. I deleted it a few days ago and no longer have a copy.

**Comment by sathomas** [comment]
Here's a link to the full project on [dropbox](https://www.dropbox.com/s/suhsd0ghb9ypgrg/atltrails.zip)

The two main stylesheets are `src/styles/initial.scss` and `src/styles/styles.scss`. Compiling either one will trigger the bug.

**Comment by bdkjones** [comment]
Fixed in Beta 10. 

Issue was that CodeKit was keeping a file pointer open to the output path after running libsass. Closing the file pointer before firing autoprefixer corrects the problem.

**Comment by bakura10** [comment]
I'm sorry, but it does not seem to work on beta 12 (didn't try with earlier versions though). I'm using a Compass project. I tried very experimental properties and none of them is processed.

**Comment by bakura10** [comment]
I had a look at the config file, and there is:

``` php
"\/sass\/screen.scss" : {
      // things...
      "shouldRunAutoprefixer" : 0,
      // things...
      "useLibsass" : 0
    }
```

However in the "project settings", the shouldRunAutoproxifer is to 1. Hope it helps :).

**Comment by bdkjones** [comment]
Autoprefixer and Bless are not available for Compass projects.

**Comment by bakura10** [comment]
Hi @bdkjones , why such a limitation for Compass project? To deal with this, I tried to use a hook, but I'm not sure how I should use hook.

I tried adding a hook, with "outputFullPath" ends with ".css", and run the following command:

autoprefixer -b "> 1%, last 20 versions, ff 17, opera 12.1" $outputFullPath

But it seems I got the syntax wrong as it does not work.

**Comment by bdkjones** [comment]
The limitation is due to the fact that CodeKit does not control output paths for Sass files in Compass projects. Those paths are managed by Compass itself, using the config.rb file you edit outside of CodeKit.

That said, Compass itself is evolving to ditch Ruby. As it does, CodeKit will keep up. I plan to remove this limitation when it's feasible to do so.

**Comment by bakura10** [comment]
So my method of using hook is not feasible too?

**Comment by pmeissner** [comment]
May recommend that if a CodeKit user selects Autoprefixer and libsass is ALREADY selected as the sass compiler, that CK notifies the user that Autoprefixer and Bless are incompatible with libsass?

And of course, if Autoprefixer/Bless is ALREADY selected, the user would be warned before selecting libsass.
