### ISSUE TITLE
Problem when using -webkit-calc()

### ISSUE THREAD

**Issue by sebastiannm** [bdkjones/CodeKit2#117]
I found a bug when compiling a sass file with libsass.

The problem occurs when I use for example:

width: -webkit-calc(100% - 50px);

I get the message -> error: cannot add or subtract numbers with incompatible units

It only happens when libsass is activated for the file. Using beta 5

**Comment by bdkjones** [comment]
This is not an issue with CodeKit; it is an issue with libsass. Please file a bug report on that project's GitHub page.

**Comment by ryansnowden** [comment]
For those who are having an issue with Foundation 5.5 and come here, just update your settings file with the new config.

**Comment by RobertoCMCosta** [comment]
I'm having exactly this issue here. (scss/config/settings:42: cannot add or subtract numbers with incompatible units). Which new config must I update _settings.scss with? Comparing it with the one that came with Foundation 5.5 I see no new config. Can you point me in the right direction?
