### ISSUE TITLE
Infinite Loop

### ISSUE THREAD

**Issue by Horttcore** [bdkjones/CodeKit2#118]
I created a project and pressed „Preview“, it opened the Webserver URL in my default browser ( Chrome ) and throwing infinite alerts and crashed, as I noticed that my MAMP wasn't runing.

Can anyone reproduce it?

**Comment by Horttcore** [comment]
Crashreport is sent via email.

**Comment by bdkjones** [comment]
I need the _exact_ steps to reproduce this, along with a demo project.

**Comment by Horttcore** [comment]
It was the preview bug which is fixed in Beta 6
