### ISSUE TITLE
Unknown crash, but error report generated

### ISSUE THREAD

**Issue by yratof** [bdkjones/CodeKit2#119]
http://cl.ly/TBqN

Don't know if I should be emailing these to you or issuing them.

I had saved a project, then suddenly it CK2 Crashed. Unknown reason at this time

**Comment by sathomas** [comment]
Possible duplicate. Crash report here: https://www.dropbox.com/s/nnbnqr0h51inq8g/CodeKit_2014-01-04-092231_MacBook-Air.crash

**Comment by sathomas** [comment]
Here's another one: https://www.dropbox.com/s/62mzu2hnkbnxb1b/CodeKit_2014-01-04-094435_MacBook-Air.crash

This happened while I was playing around re-sizing my browser window; not using CK actively at all.

**Comment by sathomas** [comment]
Possible duplicate of #114 (Sorry, didn't see that one earlier.)

**Comment by bdkjones** [comment]
Fixed in Beta 6
