### ISSUE TITLE
Splash screen 'header'

### ISSUE THREAD

**Issue by mdavis1982** [bdkjones/CodeKit2#12]
When on the splash screen, if I select "Files" from the "View" menu, I see this:

![screen shot 2013-12-18 at 11 17 11](https://f.cloud.github.com/assets/199807/1772677/f9826f9c-67d5-11e3-946b-a50c93e3740b.png)

If I then click on the "Log" button, I see this (although selecting "Log" from the "View" menu doesn't exhibit this behaviour):

![screen shot 2013-12-18 at 11 17 47](https://f.cloud.github.com/assets/199807/1772679/0bab07a6-67d6-11e3-8a05-cfb5d9789261.png)

Clicking the "Close" button gives me an empty file list.

**Comment by bdkjones** [comment]
? This looks like it should.
