### ISSUE TITLE
Feature Request: Launch preview from menubar

### ISSUE THREAD

**Issue by sathomas** [bdkjones/CodeKit2#120]
Since I often find myself navigating away from the preview page, it would be handy if there were a quick way to re-launch directly from the menu bar instead of having to open CK.

**Comment by Horttcore** [comment]
Creating a menubar entry only for this feature seems a bit overkill. If there would be more option ok, but for one url?!

**Comment by sathomas** [comment]
At least for me, just this option makes perfect sense for my normal workflow. I find that I generally use CK in a couple of different modes.

In the first mode, I'm setting up a project, changing project configuration, adding new files, etc. In that mode it makes perfect sense to interact directly with the main CK window.

Once my project is set up and configured, however, I'm using CK in a different mode. In this second mode, I just want CK to do it's magic (compiling, compressing, etc.) behind the scenes. In that mode, I'd prefer CK to be invisible as possible so I can focus on developing my site. Now I run CK minimized (with beeps and "bring to front" disabled) to minimize distractions from coding. Ideally, I wouldn't have to interact with the main CK window at all. I can monitor CK status and errors via notifications, and if I need to force a rebuild, I can do that from the menu-bar icon (or cmd-R). But the one thing I do need to do in this mode is relaunch the preview. (As noted in my original request, I often find that I've navigated away from the preview window, e.g. to check on syntax or usage.) It's not a big deal, but having to open the CK window, find the preview button, and click it, does cause a disruption of my coding flow. Having the menu bar option would eliminate that disruption.

**Comment by bdkjones** [comment]
I've decided to close feature request issues on the beta repo. The reason is that I _have_ to get this app shipped and that means locking the feature set so I can concentrate on killing bugs. 

Once the app goes public, I'll take feature requests again and start implementing them for the 2.x releases.
