### ISSUE TITLE
Skip items relative to project root

### ISSUE THREAD

**Issue by marcaube** [bdkjones/CodeKit2#121]
I'd like skip `/vendor` but not `/web/js/vendor`.

I tried entering the following in my project settings, like I would do in a `.gitignore` file

```
.svn, .git, .hg, log, /vendor
```

But it does not work as I intended, and doesn't even skip the vendor folder. I there a way to do it? It'd be a nice feature if not.

**Comment by marcaube** [comment]
Oops, possible duplicate of #59

**Comment by bdkjones** [comment]
Implemented in Beta 6.
