### ISSUE TITLE
Codekit Crashes using CK server

### ISSUE THREAD

**Issue by yratof** [bdkjones/CodeKit2#122]
Started a new website from fresh, added index.html and some assets. Previewed the index.html in chrome, when I switch back to coda 2, codekit crashes.

Now when i'm switching, all i'm doing is going CMD + TAB to switch between them.

Here's everything for you:

4 Crash files: http://cl.ly/TC0c
Project zip: http://cl.ly/TC3N

Chrome version: Version 31.0.1650.63
Coda 2.0.12
OSX 10.9.1

**Comment by yratof** [comment]
![screen shot 2014-01-04 at 19 50 08](https://f.cloud.github.com/assets/1001935/1845235/b6a382c2-7579-11e3-98f2-72eeff76c33f.png)

Also, there is a character in the title of the project "å" <-- Perhaps that is causing issues?

**Comment by bdkjones** [comment]
Fixed in Beta 6. Posting later tonight.

**Comment by yratof** [comment]
Fantastic
