### ISSUE TITLE
Project settings help text incorrect

### ISSUE THREAD

**Issue by sathomas** [bdkjones/CodeKit2#123]
The **Bower Components Folder:** setting has the following help text in Beta 5:

> To relocate the 'bower_components' folder, enter the relative path from the project root folder to the subfolder that should contain 'bower_components'.

That's actually **_not_** how CK behaves. Instead, it uses this setting as the relative path from _the folder specified in `.bowerrc`_ in the project root folder.

It would be ideal if CK behaved as the help text currently specifies **and** updated `.bowerrc` appropriately.

**Comment by bdkjones** [comment]
Yea, but most people will never see or concern themselves with the .bowerrc file.

Between us, I despise how Bower is set up. I think it's really badly done for anything other than a command line junkie. When you let programmers build things for programmers, Bower is what you end up with.

**Comment by bdkjones** [comment]
Also, the .bowerrc file does not exist unless YOU create it manually. CodeKit doesn't automatically create it. If you're savvy enough to know about .bowerrc files, then you're expected to understand how that file affects Bower.
