### ISSUE TITLE
Infinite Alerts

### ISSUE THREAD

**Issue by Horttcore** [bdkjones/CodeKit2#126]
Closing CodeKit 2 while a tab with xxx.local:5757 is still open will produce infinite javascript alerts.

**Comment by zengabor** [comment]
This has happened to me too with Beta 6 but only once. Cannot reproduce it anymore. Maybe the old JS was cached?

**Comment by maxlapides** [comment]
I just experienced the same issue.

**Comment by bdkjones** [comment]
Well that's interesting. What do these Javascript alerts say?

**Comment by maxlapides** [comment]
"Failed to establish a connection to CodeKit. Live refreshes will not work."
![2014-01-07_14-44-32](https://f.cloud.github.com/assets/1874682/1862600/22103062-77d4-11e3-9d37-0002fbf6445f.png)

**Comment by bdkjones** [comment]
Fixed in Beta 8.
