### ISSUE TITLE
Beta 6 crashes on launch with missing config.codekit

### ISSUE THREAD

**Issue by sathomas** [bdkjones/CodeKit2#127]
Trying to come up with a workaround for bug #124, I deleted the project's `config.codekit` file and started CK. App crashed immediately. Crash report at https://www.dropbox.com/s/opp0p6w7eezzfth/CodeKit_2014-01-07-080149_MacBook-Air.crash

**Comment by sathomas** [comment]
Shift-startup fixes it FWIW

**Comment by bdkjones** [comment]
Fixed in Beta 7.
