### ISSUE TITLE
Javascript and CSS files being transferred as MIME Type text/plain when using external server for all requests

### ISSUE THREAD

**Issue by guill3m** [bdkjones/CodeKit2#129]
With plain html projects that don't require a server works fine, but with projects that need the “Use this external server for all requests”, the JS and CSS files are being transferred as `text/plain` instead of `application/javascript` and `text/css` respectively.

Having the `type` attribute defined in the `link` or `script` element doesn't change anything, it happens the same whether this attribute is defined in the HTML or not.

The Type is correct for inline styles and scripts, and for the `lpckrp.js` file too.

Tested on a simple node.js project with no fancy setups (just node running on that project folder) and in a more complex Symfony2 project (the server is in a VM with Vagrant). In both projects the Type is served correctly when using the external server URL instead of CodeKit’s.

OS X 10.9.1
CodeKit 2 Beta 6 (15860)
If it helps, the node project I'm using (is a theme for a Ghost blog): http://cl.ly/0q0G191C1U1k

![Console](http://f.cl.ly/items/3q3x0W132r0W1J0L1n05/console.png)

![Network](http://f.cl.ly/items/172T1y0i2q3h1N390E33/network.png)

**Comment by bdkjones** [comment]
Fixed in Beta 7. Will post that tonight.
