### ISSUE TITLE
Content inside the different sections within the default project edit view get cut off the head

### ISSUE THREAD

**Issue by rpkoller** [bdkjones/CodeKit2#13]
Especially the the general tab content gets cut at the head regularly. In other sections it happens sometimes (e.g. Sass and Typekit). In the general tab i see as up to half of the field containing the "is not applicable" text. the rest is cut off. 

By the way is it ok to attach images on Github  within the specific issue?

**Comment by bdkjones** [comment]
Yes; please attach images.

Are you on 10.8?

**Comment by rpkoller** [comment]
The issues persists even after a reset of the Codekit plist settings (in order of the MAMP issues). And yes i am on 10.8.5 (all the latest patches applied).

first screenshot of the active General tab:
![1](https://f.cloud.github.com/assets/1665422/1772817/d0b91fa8-67d9-11e3-8322-ce59fd4e0958.png)

then i switched to the Sass tab
![2](https://f.cloud.github.com/assets/1665422/1772825/eb1324ca-67d9-11e3-8847-d79f09aeb23f.png)

then i've clicked the General tab again
![3](https://f.cloud.github.com/assets/1665422/1772829/f61b9a32-67d9-11e3-9d15-145f95d9d341.png)

**Comment by rpkoller** [comment]
Ok the issue also happens if i go into the settings of an imported project. It isn't limited to the default project but is a more of a global issue. ;)

**Comment by shshaw** [comment]
I've hit this same issue in regular Project Settings when switching between tabs, and a similar issue with scrolling where the scrollbar does not match the current tab's height.

![screen shot 2013-12-18 at 3 59 35 pm](https://f.cloud.github.com/assets/777155/1778108/af6c23e4-682f-11e3-9390-2da52cb82232.png)

**Comment by bdkjones** [comment]
Fixed in Beta 3. 

This issue only manifested if you had OS X set to always display scrollbars. (Which is crazy; overlay scrollbars were the best thing in 10.7.)

Either way, this won't be an issue any longer when I post Beta 3. Which I will do when I am no longer crammed into the middle seat of an airliner.

**Comment by rpkoller** [comment]
Yep works like a charm in Beta4
