### ISSUE TITLE
Strange compile error when incorrect variable used (SASS/Compass)

### ISSUE THREAD

**Issue by Chrisedmo** [bdkjones/CodeKit2#132]
I accidentally used a variable in my SASS that did not exist, and Codekitcorrectly  failed to compile. However, the error message was not that the particular variable could not be found, but that a font @import that i had used could not be found? (FYI I was using a px based sizing variable - nothing to do with font-files or imports).

Correcting the variable compiles just fine… 

EDIT: removing this line:

```
@include font-face("Mono Social Icons Font", font-files("MonoSocialIconsFont-1.10.woff", "MonoSocialIconsFont-1.10.ttf", "MonoSocialIconsFont-1.10.svg#MonoSocialIconsFont"), "MonoSocialIconsFont-1.10.eot", normal, normal);
```

from my SASS and then using a non existent variable, throws up a normal "undefined variable" message. So it looks like it's an issue with Codekit 2 and the Compass Font Files Helper.

---

Im on Mac OS X 10.9.1
Macbook Pro
SCSS file and using compass.

**Comment by bdkjones** [comment]
This is not a CodeKit issue. Please file the bug with the Sass and/or Compass teams.
