### ISSUE TITLE
Unable to preview Wordpress project in Beta 7

### ISSUE THREAD

**Issue by rpkoller** [bdkjones/CodeKit2#134]
I've tried to preview a Wordpress project in the latest beta (v7) but somehow it fails . I am pretty uncertain if it is a configuration error on my side or an issue in Codekit. 

My setup. I am running MAMP 2.2 (the basic version). The used port is the default 8888. My project directory "test" resides inside the MAMP htdocs folder (htdocs/test/).  The Wordpress files aren't located in the root of the test folder - i've moved everything to a subfolder so only a index.php file, pointing to the Wordpress installation inside the subfolder, and a .htaccess file are there. The project settings for browser refreshing are as follows: 

**browser refresh settings:**
website root subpath:                (---> left empty) 
animate changes: checked
also reload file: not checked

**external server:**
external server address: http://localhost
external server port:8888

If i only use http:localhost as external server address the preview with http://mybox.local:5757 shows the MAMP notifying page that the virtual host is successfully set up (the MAMP index.php in the root of the htdocs folder). If change the external server address in the settings to http://localhost/test/ i get NSURLErrorDomain:-1015 . If i enter http://mybox.local:5757/test/ or the non-bonjour equivalent directly in the browser i get the Ye Olde 404. If i enter http://localhost:8888/test/ instead it works. 

Best regards Ralf

**Comment by bdkjones** [comment]
Well, I need the entire Wordpress project as well as a dump of the SQL database for the Wordpress installation so I can set it up over here and test with it. 

I have a feeling that this is related to the fact that you've moved Wordpress files, but I need to run the site over here to trace things and confirm. 

Please zip the project and the SQL dump and post a link to download them here.

**Comment by bdkjones** [comment]
Also, the external address in your case should definitely be: '`http://localhost/test`. 

Are you doing anything fancy with Gzip? The 1015 error code translates to: "Cannot decode Raw Data", meaning the browser could not decode the data that was sent back in the HTTP response.

**Comment by rpkoller** [comment]
i can send you the backed up site when i am back at home later tonight. will send you a mail with the link if that is ok. 

and nothing fancy, just taken the htaccess file from the html5 boilerplate

**Comment by bdkjones** [comment]
Thanks for sending the project @rpkoller. I've fixed the issue and your project is working great in Beta 8. I'll be posting that in a few hours.

**Comment by rpkoller** [comment]
@bdkjones retested in beta 8. works like a charm now. double thumbs up!

**Comment by bdkjones** [comment]
Please verify that you can log in to wordpress's admin area.

**Comment by rpkoller** [comment]
uhhh i am unable to. only tested if i am able to preview the site via codekit but haven't tried to login the admin area yet.tested now and  i get: 

```
ERROR: Cookies are blocked or not supported by your browser. You must enable cookies to use WordPress.
```

on localhost it works with the same browser. happened with chrome. on safari i dont get to the login dialogue for quite some while. loading took seconds or a felt minute. two things i've noticed: 

chrome: i've expected: http://test.local:5757/wp-login.php but the adress changed to http://test.local:5757/dFGn2SxAy8Z7bnM/wp-login.php the subfolder my wp install is in, the one i've sent you before. 

safari: same. 

firefox:same. 

Opera: same

**Comment by smlombardi** [comment]
I get exactly the same results as above.
