### ISSUE TITLE
Syntax error: File to import not found or unreadable: compass (Beta 7)

### ISSUE THREAD

**Issue by rpkoller** [bdkjones/CodeKit2#136]
On the Wordpress testproject i get the following error if i try to preprocess the scss. 

```
Syntax error: File to import not found or unreadable: compass.
              Load paths:
                /Applications/MAMP/htdocs/testproject/dFGn2SxAy8Z7bnM/wp-content/themes/schmideinander/scss (DEPRECATED)
                /Applications/CodeKit 2.app/Contents/Resources/engines/bourbon/bourbon/app/assets/stylesheets
                /Applications/CodeKit 2.app/Contents/Resources/engines/neat
                /Applications/MAMP/htdocs/testproject/bower_components/foundation/scss
        on line 3 of /Applications/MAMP/htdocs/testproject/dFGn2SxAy8Z7bnM/wp-content/themes/schmideinander/scss/base/_gems.scss
        from line 16 of /Applications/MAMP/htdocs/testproject/dFGn2SxAy8Z7bnM/wp-content/themes/schmideinander/scss/base/_init.scss
        from line 1 of /Applications/MAMP/htdocs/testproject/dFGn2SxAy8Z7bnM/wp-content/themes/schmideinander/scss/style.scss
  Use --trace for backtrace.
```

if i perform a compass watch --trace inside the theme directory everything works. Same if i try to preprocess the scss with codekit1. 

i am using the external compass compiler option overriding codekits internal compass version. i am using compass (0.12.2). 

if i try to preprocess a small html/css test project there isn't any error too. means compass isn't broken in general. 

If you need any more informations let me know. Best regards Ralf

**Comment by rpkoller** [comment]
@bdkjones rechecked in beta8. the wordpress issue is fixed but this problem persists. still get the error: 

```
Syntax error: File to import not found or unreadable: compass.
              Load paths:
                /Applications/MAMP/htdocs/testproject/dFGn2SxAy8Z7bnM/wp-content/themes/schmideinander/scss (DEPRECATED)
                /Applications/CodeKit 2.app/Contents/Resources/engines/bourbon/bourbon/app/assets/stylesheets
                /Applications/CodeKit 2.app/Contents/Resources/engines/neat
                /Applications/MAMP/htdocs/testproject/bower_components/foundation/scss
        on line 3 of /Applications/MAMP/htdocs/testproject/dFGn2SxAy8Z7bnM/wp-content/themes/schmideinander/scss/base/_gems.scss
        from line 16 of /Applications/MAMP/htdocs/testproject/dFGn2SxAy8Z7bnM/wp-content/themes/schmideinander/scss/base/_init.scss
        from line 1 of /Applications/MAMP/htdocs/testproject/dFGn2SxAy8Z7bnM/wp-content/themes/schmideinander/scss/style.scss
  Use --trace for backtrace.
```

on a side note my gem list looks like that. 

```
breakpoint (2.0.7)
chunky_png (1.2.9)
color-schemer (0.2.7)
compass (0.12.2)
compass-blend-modes (0.0.2)
fssm (0.2.10)
modular-scale (1.0.6)
sass (3.2.13)
sassy-math (1.5)
sassy-strings (1.0.0)
singularitygs (1.1.2)
susy (1.0.9)
toolkit (1.3.8)
```

The whole wordpress project is imported into codekit and not only the theme directory, think to remember it was the recommended practice. but well the error still shows up. if i do "compass watch --trace" within the theme directory in the terminal everything works fine like in beta 7.

**Comment by bdkjones** [comment]
Have you been using CodeKit 1 to compile this file? I just tried in that version of the app and it's not compiling; it just spins forever.

**Comment by bdkjones** [comment]
Ah. I see. You're using Compass in this project, but there's no `config.rb` file anywhere to be found. That's likely the cause of the issue.

**Comment by bdkjones** [comment]
In fact, that's exactly what's happening. Since there is no "config.rb" file in this project, CodeKit does not recognize it as a Compass project. Therefore, your @import statement trying to bring in Compass's stylesheets is failing. 

You need to install Compass in this project properly.

**Comment by rpkoller** [comment]
@bdkjones  hm actually the config.rb file resides inside the theme folder.  but i've just dragged the whole  wordpress directory into codekit2  (since i thought it was recommended practice). the config.rb file is in a subfolder - the themes root folder and not in the wordpress root folder. so instead i should drag the theme folder instead of the whole wordpress folder into codekit?

**Comment by bdkjones** [comment]
No. Your Compass config.rb file needs to be in the project's root folder. It should specify output paths for assets relative to that location.

**Comment by rpkoller** [comment]
Ok works. So for the record the recommended way of usage for wordpress projects would be: 

1) the whole wordpress project folder dragged into codekit
2) the config.rb file should be placed into the wordpress folders root instead of themes root
