### ISSUE TITLE
Unchecking JS prepends/appends issue checking

### ISSUE THREAD

**Issue by maxlapides** [bdkjones/CodeKit2#137]
When there are a lot of imports for a js file, it's hard to check/uncheck the issue checking checkbox because the scrollbar often gets in the way. It's easy enough to wait for the scrollbar to go away, but it can be a little annoying.

![2014-01-08_18-28-43](https://f.cloud.github.com/assets/1874682/1873664/499498a0-78bd-11e3-9695-4ff42b3e9545.png)

(I don't know if you think this is a big enough issue to be concerned about, but I thought it couldn't hurt to bring it up!)

**Comment by bdkjones** [comment]
Yea. This is an annoying feature of OS 10.7+. The short answer is that there's nothing I can do to solve this. If I move the checkboxes to the left, they look terrible and waste space when the scrollbar is not showing. If I attempt to detect when the scrollbars appear and then dynamically move everything, I run into all sorts of edge cases where the view changes while the scrollbars are hiding/showing and everything gets mucked up.

This is a problem in other apps as well and Apple really ought to address it on their end by resizing the scrollView when they bring in the full scrollbars to replace the overlay ones.
