### ISSUE TITLE
Drag & Drop of Aliases not supported

### ISSUE THREAD

**Issue by shshaw** [bdkjones/CodeKit2#139]
I tend to have aliases to key folders set up in my base project directory, but if I want to  add one of those to CodeKit, I have to grab the original folder to drag & drop it in. Just a minor UI annoyance, but one that would be helpful to have resolved.

**Comment by bdkjones** [comment]
Yea, due to some very technical aspects of file-watching and how aliases are resolved, this isn't possible. You have to add the original folder.
