### ISSUE TITLE
Can't register license

### ISSUE THREAD

**Issue by Fequois** [bdkjones/CodeKit2#14]
Hey,

Not sure whether it's a bug or if it's a limitation in the betas to prevent long-term usage, but I can't use my license details to register. I assume the second, or similar at least, but thought I'd put it out here just in case. I haven't seen any info on this.

**Comment by matkovsky** [comment]
Hi.

According to README (in the Dropbox folder) this is not a bug. :)

**Comment by Fequois** [comment]
I can't find any mention of it in the readme, so hooray for my lack of reading comprehension! :)

**Comment by mdavis1982** [comment]
It says it in the readme in DropBox:

> ## Expiration
> 
> Your CodeKit 1.x license will not unlock CodeKit 2. That's no problem. Just use the app in the "free trial" mode. I  will update the private repository with a new release of the app every few days. Each time you replace the app with a freshly-downloaded copy from GitHub, the trial will reset.

**Comment by matkovsky** [comment]
Sorry, it's the README.txt in the Dropbox folder, not the README.md in this repo. :)
