### ISSUE TITLE
CK2 Does not remember last Desktop/Monitor location

### ISSUE THREAD

**Issue by edwardsdesign** [bdkjones/CodeKit2#140]
I have a multiple monitor setup and I keep CK2 open on monitor 2. When I close and reopen CK2 the app will always reopen on monitor 1's desktop unless I specifically have the desktop on monitor 2 active/selected.

**Comment by bdkjones** [comment]
MOTHER OF GOD I KNOW. 

This pisses me off to no end. I work on 3 monitors at my desk and every time I stop the app and re-build it from Xcode, it shows up in a completely new place. This is an OS X thing and it frequently makes me want to drive to Cupertino and set Tim Cook's car on fire.
