### ISSUE TITLE
Bower Components folder location is not retained when duplicating/copying a project folder 

### ISSUE THREAD

**Issue by newelement** [bdkjones/CodeKit2#142]
When I copy or duplicate a current project to another folder the bower components location folder setting is empty. OSX 10.9.1, CK b7. I'm currently putting the bower components folders in the project root /assets/

Cannot easily duplicate anymore but I did notice sometimes not all global settings, javascript, LESS, JS imports are carried over. I had to use the Apply Settings From File option and refer to the original CK config file even when that same settings file was copied over with the project.

**Comment by bdkjones** [comment]
Duplicating the project is not the correct way to do this. If you want to set a default bower_components location, you should choose "Edit Defaults For New Projects" and set it there.
