### ISSUE TITLE
External Server times out too early

### ISSUE THREAD

**Issue by zengabor** [bdkjones/CodeKit2#145]
After one or a few seconds CodeKit gives up when calling the external server and displays an error, saying:

```
CodeKit sent a request to the external server for this resource: http://localhost:8081/hello 
The error returned was: "The request timed out." (Code -1001)
```

Is there any reason CodeKit cannot wait a little bit more? I have some expensive application requests which require several seconds in the development environment.

**Comment by bdkjones** [comment]
I may have set the timeout value a little low. It's currently 5 seconds, which I assumed would be plenty for a server that's running on the local network. I can increase it.

**Comment by zengabor** [comment]
It's probably enough for the 99.9% of cases but for that very few users like me it hurts. It would be nice to have it much higher, e.g., 30s. It doesn't do any harm to CodeKit, does it?

**Comment by bdkjones** [comment]
Changed to 60 seconds for Beta 9.

**Comment by zengabor** [comment]
Thanks a lot, that's much better for me
