### ISSUE TITLE
Feature Request: Make engines downloadable on demand

### ISSUE THREAD

**Issue by rasmusbe** [bdkjones/CodeKit2#148]
Codekit 1 uses 25 mb of disk space. Codekit 2 uses 110 mb, that's a big difference.
Probably not an problem in most cases but it will cost you a lot more bandwidth for downloads of the app.

I suggest a solution where it downloads engines when they are first needed. For example I don't need 50 mb of git since I already have it installed.

This is maybe not a thing for Codekit 2.0, but for 2.1.

**Comment by bdkjones** [comment]
Yea... this one is just complicated to implement and irritating for users. No one wants to wait for a download to finish right in the middle of working. And 110mb is nothing, really.
