### ISSUE TITLE
Keyboard shortcut to remove imported asset

### ISSUE THREAD

**Issue by rasmusbe** [bdkjones/CodeKit2#149]
I would like to be able remove an imported asset by pressing backspace or delete.
![screenshot 2014-01-13 11 49 33](https://f.cloud.github.com/assets/2124386/1899695/aa44dc88-7c40-11e3-8608-e966d1157fd1.png)

**Comment by bdkjones** [comment]
Implemented in Beta 10. 

Note that you can only delete import links that were created by drag-drop inside CodeKit. If the link is due to an @import statement or @codekit-prepend/append statement in a file, you have to remove that statement for the link to be deleted.
