### ISSUE TITLE
External server and mod_rewrite

### ISSUE THREAD

**Issue by consindo** [bdkjones/CodeKit2#15]
If you're using something to make nice URLs (mod_rewrite), as the file doesn't really exist and isn't in CodeKit, it isn't served when using it with an external server.

**Comment by mdavis1982** [comment]
This sounds more like a feature request than anything else. I would suggest that maybe each file (maybe just HTML files or something) could have a 'preview url' property that would set what URL to go to to preview it.

@bdkjones What do you think?

**Comment by zengabor** [comment]
This missing feature means that CodeKit 2 is unusable for my projects. (I use AppEngine, an application server where URIs have nothing to do with real files on the disk, except for static files.)

Good thing that I can keep using version 1.9.3 :)

**Comment by bdkjones** [comment]
I'm about to post Beta 5, which _should_ resolve this issue.

Previously, if a file did not _require_ an external server (meaning it was a file type that CodeKit could serve itself, like HTML, JS, CSS, etc) AND that file did not exist locally on disk, CodeKit would simply return a 404. 

In Beta 5, if the file does not exist locally on disk (which it won't, for mod_rewrites), CodeKit now tosses the request to your external server, which should resolve the mod_rewrite and return the content of the asset back to CodeKit. 

I think this should fix this issue AND make permalinks work in Wordpress (hopefully).

**Comment by peterhartree** [comment]
Hi Bryan,
Your proposed modification for Beta 5 sound very sensible. The cache busting feature that ships as part of HTML5 Boilerplate's .htaccess is another casualty of the current behaviour (unless "always use my external server" is checked):

```
# ------------------------------------------------------------------------------
# | Filename-based cache busting                                               |
# ------------------------------------------------------------------------------

# If you're not using a build process to manage your filename version revving,
# you might want to consider enabling the following directives to route all
# requests such as `/css/style.12345.css` to `/css/style.css`.

# To understand why this is important and a better idea than `*.css?v231`, read:
# http://stevesouders.com/blog/2008/08/23/revving-filenames-dont-use-querystring

 <IfModule mod_rewrite.c>
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.+)\.(\d+)\.(js|css|png|jpg|gif)$ $1.$3 [L]
 </IfModule>
```

https://github.com/h5bp/html5-boilerplate/blob/master/.htaccess

**Comment by bdkjones** [comment]
Fixed in Beta 5. Hopefully.
