### ISSUE TITLE
Output Folder Creation Glitch

### ISSUE THREAD

**Issue by phyllisstein** [bdkjones/CodeKit2#151]
I just noticed what might be a teeny glitch in the way CodeKit creates output folders. Under my project's root, I have the folders `coffee` and `js`. Mostly I'm using CoffeeScript, but there's a JavaScript library that I'd like CodeKit to minify; since the default location for minified JavaScript is `/min`, I set the CoffeeScript output directory to `../js/min` so it all winds up in the same place. And all's right with the world, _unless_ the CoffeeScript gets compiled first. If it does, and the `min` subfolder doesn't exist, it isn't created; I get an error that reads, "The file compiled successfully, but CodeKit could not write the result to the output path. Verify that you have permission to write to the output folder and try again."

The JavaScript compiles fine, creating the directory if it didn't exist; and if `min` is already there, the compiled CoffeeScript lands in its assigned location. But in this one admittedly weird scenario, no dice.

Thanks in advance for looking into it! And, you know. For CodeKit.

**Comment by bdkjones** [comment]
Just gave this a go over here and it worked perfectly.

This sounds like a permissions issue on your end. If your user account does not have write permission to that "js" folder, the app can't create the "min" folder where the output file is supposed to be. 

I would start by verifying your permissions on the folder tree in question. If that still doesn't work, try creating a new project from scratch and setting up the same scenario.

**Comment by phyllisstein** [comment]
Gosh, you're absolutely right: I tried it again and it was just fine. I must've done something silly to the folders I was using---or allowed Dropbox to do something silly, since I know it has about the same respect for permissions as a frat boy with a Rohypnol scrip. Anyway, thanks for looking into it!

**Comment by phyllisstein** [comment]
Hey Brian! I hate to reopen this, especially since before I do you'd've just closed a solid 250 issues, but I bumped into the issue again. I had a CoffeeScript file called `coffee/index.coffee`, and when CodeKit tried to compile it, I got the following error:

![screen shot 2014-02-21 at 5 01 11 am](https://f.cloud.github.com/assets/2207980/2228682/ee88a632-9adf-11e3-8c2f-49d213074f26.png)

Additionally, this appeared in the Console:

```
2/21/14 5:00:50.483 AM CodeKit[57457]: BUG in libdispatch client: kevent[EVFILT_WRITE] delete: "No such file or directory" - 0x2
```

As far as I can tell, permissions are okay---here's a `tree` output from the relevant folder:

```
.
├── [drwxr-xr-x]  Static\ Demo
│   ├── [drwxr-xr-x]  coffee
│   │   └── [-rw-r--r--]  index.coffee
│   ├── [-rw-r--r--]  config.codekit
│   ├── [-rw-r--r--]  index.haml
│   ├── [-rw-r--r--]  index.html
│   └── [drwxr-xr-x]  stylesheets
│       └── [-rw-r--r--]  index.scss
```

And, as the thing de resistance, here's a shot of my settings---this time, I told CK to replace all `coffee`s in the path with `js`es:

![codekit002](https://f.cloud.github.com/assets/2207980/2228713/61500a0c-9ae0-11e3-821f-fda850da7e02.png)

Rooting for you on the home stretch here! Sorry again for the ajita.

**Comment by bdkjones** [comment]
I still can't duplicate this on my end. Is the project folder in question involved with any other file-watching app such as Dropbox, sugarsync, etc?

**Comment by phyllisstein** [comment]
Yes, I'm afraid it's a Dropbox folder. Could that be the trouble?

**Comment by bdkjones** [comment]
That is almost definitely the issue. Take the folder out of Dropbox.
