### ISSUE TITLE
Using build in Compass compiler failing in beta 9

### ISSUE THREAD

**Issue by jornki** [bdkjones/CodeKit2#152]
Using beta 9 and the build in Compass compiler the project does not compile and fails with a bunch of error messages from the Compass compiler. Switching to an external compass compiler (0.12.2) fixes the issue. See screen shots for error messages.
![screen shot 2014-01-14 at 14 21 17](https://f.cloud.github.com/assets/1160870/1910753/331a870e-7d1f-11e3-85d0-ac7ae8626853.png)
![screen shot 2014-01-14 at 14 21 37](https://f.cloud.github.com/assets/1160870/1910754/378a67e6-7d1f-11e3-9719-b98a3224e36f.png)

**Comment by bdkjones** [comment]
Do you have CodeKit set to use an external Sass compiler as well? (Not Compass; Sass)

**Comment by jornki** [comment]
Using the internal CodeKit version of SCSS, looks like it's just the internal version of Compass which fails. A small demo project which fails can be found here: https://dl.dropboxusercontent.com/u/309897/compassTest.zip

**Comment by bdkjones** [comment]
Fixed, for the 3,452th time in Beta 10.
