### ISSUE TITLE
Feature request: process CSS files

### ISSUE THREAD

**Issue by marcaube** [bdkjones/CodeKit2#154]
On simple projects, we still have some plain CSS files we'd like to minify without going to an online "YUI compressor".

I think it'd be an interesting feature to have. Is there a reason why CodeKit does not process those files?

**Comment by sathomas** [comment]
You can just rename a CSS file to .SCSS or .LESS. Both of those formats are backwards-compatible with CSS.

**Comment by marcaube** [comment]
I know I can, but it feels like a hack when you can compile JS files without using a pre-processor file extension but can't do the same with CSS.

**Comment by bdkjones** [comment]
Renaming to *.less or *.scss is the correct way to process CSS files.
