### ISSUE TITLE
File Output Path Issue

### ISSUE THREAD

**Issue by ghost** [bdkjones/CodeKit2#155]
When I add a new project into Codekit, the output path of files that compile are not correct. 

For example:

I added a new project and the output path of my site.scss shows this:

![screen shot 2014-01-14 at 1 18 34 pm](https://f.cloud.github.com/assets/4323734/1913457/314e7fb4-7d49-11e3-85f0-b96403212fbc.png)

And I have to manually go into each file that compiles and change its output path. When I do this it changes to this:

![screen shot 2014-01-14 at 1 19 21 pm](https://f.cloud.github.com/assets/4323734/1913474/6585fdd4-7d49-11e3-8de2-77502fea0606.png)

If I forget to manually change an output path, Codekit creates a rogue file structure somewhere inside my project for the output files:

![screen shot 2014-01-14 at 1 20 10 pm](https://f.cloud.github.com/assets/4323734/1913547/34558c38-7d4a-11e3-8eff-4ac11b18e83e.png)

**Comment by bdkjones** [comment]
Is this project folder on a remote disk?

**Comment by ghost** [comment]
No, it is local. But the file structure is named to match our remote disk.

**Comment by bdkjones** [comment]
Huh? What do you mean by the second statement?

**Comment by ghost** [comment]
It's a local folder, but it is named like this:

/Volumes/Macintosh HD/Users/jondagata1/Sites/thunderapps3.com/Thundertech/Portal/jondagata/resimg/ux/index.html

The "Sites" folder is where my team and I store our projects.

**Comment by bdkjones** [comment]
And the folder you added to CodeKit to form this project was "thunderapps3.com"?

**Comment by ghost** [comment]
I drop the "ux" folder into Codekit to create the project. It's how i've done it on Codekit 1 as well.

**Comment by bdkjones** [comment]
Okay, so the screenshot above with the green arrows shows the contents of the "UX" folder?

**Comment by ghost** [comment]
Correct.

**Comment by bdkjones** [comment]
What are your default language output path settings for this project and this language?

If you haven't changed them, this is exactly the right spot for the initial output path. CodeKit assumes that, by default, you have a folder structure like this:

```
/Sass
    file.scss
/CSS
    file.css
```

So the defaults for the output path is to go up one level, into a folder called 'css' and put the compiled output there. That's exactly what I'm seeing in your screenshot above. So, have you altered the default output paths in the "New Project Defaults" area?
