### ISSUE TITLE
Projects in Dropbox

### ISSUE THREAD

**Issue by donaldallen** [bdkjones/CodeKit2#158]
I thought I read somewhere that this was a no-no with CodeKit 2, but I haven't had any issues at all doing so. Is anyone else doing this and having issues?

**Comment by bdkjones** [comment]
My designer, @guymeyer, tells me it does not work.

However, it's entirely possible that he's lying to me in order to ruin my life.

**Comment by donaldallen** [comment]
Could be! I'm using a WordPress site in Dropbox nested deeply inside a bunch of directories:

Dropbox/Top Draw/Websites/GitHub/Shaw Conference Centre/www

And I have the www folder dragged into CodeKit 2. Using external server (MAMP is serving site as shawconferencecentre.dev) and it's all working fine and dandy. Even installed some stuff through CodeKit's bower integration.

I only bring this up because it's actually relatively common for web developers to have this type of setup. So I wouldn't want you to launch and say you can't have a folder in Dropbox, where it seems, to me, that you can.

**Comment by bdkjones** [comment]
I will take out a hit on @guymeyer in that case.

**Comment by bdkjones** [comment]
Out of curiosity: what happens if the folder you add to CodeKit is an immediate child of your Dropbox folder? It may be an issue only for top-level folders contained within Dropbox.

**Comment by donaldallen** [comment]
I'll give it a try when I'm at work tomorrow and let you know!

**Comment by mgrn0** [comment]
works perfectly here for me with a compass project that I put as a immediate child in my Dropbox home folder (running latest OSX 10.9, all updates applied).

Sass and JS compiling just fine.

Dropbox version is 2.4.11

**Comment by donaldallen** [comment]
Yeah, working here as well.

**Comment by brandondurham** [comment]
Doesn't work for me. Everything works perfectly on the work comp, where I created the project. At home I drag the project into CodeKit and edit files, but nothing (SASS/JS) gets compiled.

**Comment by bdkjones** [comment]
Create a new folder on your desktop. Move the contents of the problematic folder into the new one you just created. Delete the problematic folder. Move the new folder into the old one's place and rename it appropriately.

**Comment by ragzor** [comment]
I have something very weird to report.. When I try to compile a project on desktop it works fine. But when I drag it like 4-5 levels deep(folder/folder/folder/folder) inside a dropbox directory it stops compiling, However when i tried compiling the same directory by placing it in the root dropbox folder it works perfectly fine.

UPDATE: If I delete the folder chain (folder/folder/folder/folder) where I placed the project directory initially and create a new chain it starts working again

**Comment by bdkjones** [comment]
You're seeing a bug in Apple's FSEvents API. See here: http://feedback.livereload.com/knowledgebase/articles/86239-os-x-fsevents-bug-may-prevent-monitoring-of-certai

**Comment by ticktockdesign** [comment]
Just fyi - if anyone's still checking this thread, I have not found a solution to this. I've tried all the steps outlined here:

https://incident57.com/codekit/help.html#troubleshooting
and here: 
http://feedback.livereload.com/knowledgebase/articles/86239-os-x-fsevents-bug-may-prevent-monitoring-of-certai

I didn't have these problems before upgrading to Codekit 2 - but I also upgraded to Yosemite at about the same time, so I don't know which change caused the result. Frustrating - need to use Dropbox to keep files sync'd between office / home / different machines, but without Codekit my coding life seems hardly worth living!

If anyone has definitive solutions, please post here. Thank you!

**Comment by devilskitchen** [comment]
My stuff works perfectly with Dropbox. My structure is ~/Dropbox/Implementations/[project-folder]/[all-the-things]...

**Comment by martinschilliger** [comment]
@ticktockdesign I don't know if you found a solution, but maybe mirroring the CodeKit-Folder to the dropbox will do the trick? So you don't work in the Dropbox-folder, but you have all your data there?

**Comment by ticktockdesign** [comment]
Thanks Martin - everything was resolved with a new release of Codekit a couple of months after I posted. thanks!
