### ISSUE TITLE
Cannot uncheck frameworks

### ISSUE THREAD

**Issue by bakura10** [bdkjones/CodeKit2#16]
Hi,

I've added some CodeKit frameworks. When I want to uncheck one, all the frameworks are deactivated, and this part of the UI become unresponsive. If I change section and go back, all the frameworks are activated again.

I've made a video of the behavior so it's clearer: https://www.dropbox.com/s/0t9vvw8lpqdonh3/codekit.mov

**Comment by bdkjones** [comment]
Fixed in the next release. Thanks!
