### ISSUE TITLE
Possible caching/server issue with Codekit2?

### ISSUE THREAD

**Issue by rpkoller** [bdkjones/CodeKit2#162]
I am totally unsure if this is mainly browser related or if Codekit2 has its share too, or at least partially. It happened that my Wordpress project behaved odd when i was using or after i was using Codekit2. 

Somehow pathes for images haven't been found and returned 404. But the path was absolutely correct, the files are present at that location and it worked before with exact the same file, location and html/php code. 

on a svg background image it happened out of a sudden after weeks of displaying normally that i disappeared. on a few normal images (jpg) it happened too. only deleting the parts in html helped on a few. 

i did a complete cache swipe (alt + mouse click on the reload button hasn't helped) in chrome and safari. afterwards it worked again but since then i sticked to codekit1 for the moment -  things went stable and predictable again. 

well just an observation but i am quite uncertain up to which degree it is caused by codekit2 or if it is responsible at all. Anybody else has experienced something similar?

Best regards Ralf

**Comment by bdkjones** [comment]
CodeKit's server obliterates every cache-related HTTP header value from both incoming HTTP requests and outgoing HTTP responses. 

After clearing your caches, you should find that CodeKit always serves assets; it will never return a 304 response.

**Comment by ar-rm** [comment]
Is there a way to reverse this?

I've tried:
- Accessing the server without the `?ckcachecontrol=` appended to the URL.
- Adding `Cache-Control` directives to an `.htaccess` file and restarting the server.

I can totally understand why CodeKit opts for cache-busting. And 99% of the time it's exactly what I want/expect. But occasionally I need to test something (usually performance related) that works one way when an asset is cached and another when it isn't.

Thanks.

**Comment by bdkjones** [comment]
No, there is not a way to disable the cache buster. If you need to test something specific, I'd recommend doing so with MAMP instead.
