### ISSUE TITLE
Bower fails to install new assets

### ISSUE THREAD

**Issue by hartless** [bdkjones/CodeKit2#163]
1) Shift-open CodeKit2 beta 10
2) Drag new empty folder onto Codekit window
3) Click assets button
4) Click download button from Favorites and install 
5) After a couple minutes, CK gives the following error:

Bower failed to install 'normalize-css'. It returned this error information:

Code: ECMDERR
Message: Failed to execute "git ls-remote --tags --heads git://github.com/necolas/normalize.css.git", exit code of #128  

Internet connection was solid. Same result for jQuery, Modernizr, animate.css and HTML5BP

![image](https://f.cloud.github.com/assets/1090636/1923426/9b8f5d6e-7e14-11e3-838c-ed2f264af8a3.png)

**Comment by bdkjones** [comment]
Looks like your Git configuration is messed up. 

You're getting a git:// address when you should be getting an https:// address. All the components you listed are installing fine over here. See this thread for a command to reset this: https://github.com/bower/bower/issues/689

Has anyone else run into this issue? If not, I'm going to chalk it up to a misconfiguration on this machine.

**Comment by hartless** [comment]
Strange it worked fine up to beta 9. 
This fixed it: 

```
git config --global url."https://".insteadOf git://
```

**Comment by jambox** [comment]
I just followed this thread and it helped me fix a component install issue. @bdkjones, it seems like you're not really into expanding the help section on CK2's site, but it seems like this might come up for other users regularly and could be a valuable addition..."Getting errors when trying to install Bower assets?"... or something much much snarkier ;)
