### ISSUE TITLE
clear arrangement of the available projects window

### ISSUE THREAD

**Issue by rpkoller** [bdkjones/CodeKit2#168]
One detail about the available project window of Codekit2. I've added about 14 projects to Codekit1 and Codekit2 to compare how the display and usability are. 

In Codekit 1 you have much space in the sidebar:

![bildschirmfoto 2014-01-18 um 10 38 52](https://f.cloud.github.com/assets/1665422/1946789/d00cf08a-8024-11e3-8cf1-42bca991304d.png)

In Codekit2 you have only the floating window, allowing only 8 out of 14 added images to show: 

![bildschirmfoto 2014-01-18 um 10 31 30](https://f.cloud.github.com/assets/1665422/1946790/e920fd8c-8024-11e3-94c7-a9db6ddaa75d.png)

I think at least maybe some sort of ability to create folders for sorting purpose might be an idea - for people who have many projects in work at once.

**Comment by bdkjones** [comment]
Yea. The projects popover is intentionally short to discourage dumping 40 projects into CodeKit and leaving them sit there indefinitely. You should remove old projects from the app and keep only the ones that you're actively working on right now. That reduces overhead, memory usage, etc.

**Comment by rpkoller** [comment]
ahhhh it was an intentional decision. then it's fine with me. cool!
