### ISSUE TITLE
Preview is throwing an external server error in beta11 on a Wordpress project

### ISSUE THREAD

**Issue by rpkoller** [bdkjones/CodeKit2#169]
I can't preview the site at all. If test in Chrome in the adress bar directly with 

http://localhost:8888/test/

it works. But if i click the preview button in the codekit2 window, safari throws a external server error at me: 

![bildschirmfoto 2014-01-18 um 10 54 54](https://f.cloud.github.com/assets/1665422/1946804/9d5f220a-8026-11e3-9bc2-8faa0daaac69.png)

No matter if i use 

http://localhost/test/
http://localhost/test
localhost
localhost/test
localhost/test/
as external server adress. each setting is returning the 404 as error. happens on 10.8.5 with wordpress 3.8 on safari 6.1.1 and beta 11.

**Comment by tombonez** [comment]
Getting the same error here, only seems to appear for me if I don't have a trailing slash though.

**Comment by Andreyco** [comment]
I have very same issue.

I have running virtual host on MAMP, which URL is `http://bookia.loc:8888` and is shortcut to `http://localhost:8888/bookia/public`.

Whether I enter virtual host URL or full localhost URL (with port set, of course) I get this:

```
CodeKit sent a request to the external server for this resource: http://localhost:8888(null)/ The error returned was: "Could not connect to the server." (Code -1004)
```

**Edit**
As suggested by @tombonez I added trailing slash, now it works perfectly.

Could CK2 check and append `/` automaticaly?

**Comment by zengabor** [comment]
I also had to add a trailing slash to get rid of the error.

Would be nice if CodeKit could do this for me.

**Comment by frank-laemmer** [comment]
same behaviour here. the changelog of Beta 11 says:

-- External Server addresses that contain a trailing slash are now handled correctly.

so i guess this fix creates this here…

**Comment by johnsardine** [comment]
Same problem on my side, I had no issues in using an address with a trailing slash, such as `http://localhost/project/`

**Comment by marcaube** [comment]
Same problem with a Symfony2 project, except that, like the OP, having a trailing slash doesn't fix the issue.

**Comment by bdkjones** [comment]
Just pushed Beta 12 to resolve this. Long story short: I'm an idiot.
