### ISSUE TITLE
External server error with Symfony2 on Beta11

### ISSUE THREAD

**Issue by marcaube** [bdkjones/CodeKit2#170]
I have a Symfony2 project, I use MAMP and configured CodeKit like this:

![screen shot 2014-01-18 at 10 29 05 am](https://f.cloud.github.com/assets/1478986/1947429/590c213c-8055-11e3-9d36-cad31a5e3d70.png)

While it works if I copy the URL `http://localhost/myapp/web/` into my browser, the CodeKit preview returns this:

![screen shot 2014-01-18 at 10 29 15 am](https://f.cloud.github.com/assets/1478986/1947430/5a87c520-8055-11e3-9c6e-bd57426dd71e.png)

It seems related to #169 but the error code is not the same. Weird thing is, the error message says the request has been made to `http://localhost(null)/`

**Comment by Andreyco** [comment]
Yeah, looks like related to this #169

**Comment by marcaube** [comment]
Yeah, I re-read it ... it's pretty much the same. The message might be different only because of the port.
