### ISSUE TITLE
Website Root Subpath is ignored [beta 12]

### ISSUE THREAD

**Issue by Andreyco** [bdkjones/CodeKit2#173]
I tried to set external server address to `http://localhost` and port `8888` as my server (MAMP).

Then after setting `/bookia/public/` as **Website Root Subpath** CK2 `http://andrejs-macbook-pro.local:5757/` still points to webserver root (http://localhost:8888 is loaded)

Looks like Website Root Subpath is ignored.
Setting server address to `http://localhost/bookia/public/` just works.

Solving this might resolve issue #172  as well.

**Comment by bdkjones** [comment]
The subpath option at the top does not apply to External Servers. That subpath is used if you're running your site on CodeKit's internal server.

If you're going to use an External server, you need to enter the address to it (including any applicable subpath) into the address field in that section.
