### ISSUE TITLE
How to download?

### ISSUE THREAD

**Issue by CHH** [bdkjones/CodeKit2#174]
Hi, this might be a silly question, but how do I download the .zip from Github?

When clicking the "Raw" button for the file on Github, all that it says is "Blob too big". This is also displayed when I try with `curl`.

**Comment by Andreyco** [comment]
Download link
https://github.com/bdkjones/codekit2beta/archive/master.zip

But you should clone the repo so that you can pull future updates.
`git clone https://github.com/bdkjones/codekit2beta.git /some/dir/on/your/drive`

**Comment by zengabor** [comment]
Syncing via the [GitHub Mac client](http://mac.github.com) also downloads the ZIP file to the computer.

**Comment by CHH** [comment]
Thanks. Sorry guys for wasting your time.
