### ISSUE TITLE
Uninstall components/assets.

### ISSUE THREAD

**Issue by Andreyco** [bdkjones/CodeKit2#175]
How can I uninstall, or delete asset/component from the project?
I have set directory for assets. I found no way to uninstall asset from CK2, so I deleted it from the dir manualy.

I suppose CK2 uses Bower to dowbload assets and stores info about installed assets in its own config. Is it possible to store this info in `bower.json` instead, or at least let user decide?
## Update

Long ago before CK2 I created `.bowerrc` file in the project root, which is this simple

``` json
{
    "directory": "public/vendor"
}
```

I tried to install some assets thru CK2, so that I specified path for Bower components, exactly the same as above.
![image](https://f.cloud.github.com/assets/829963/1949284/5fdb3e82-80f8-11e3-8a7e-cf3202071913.png)

... but, after installing some assets they are located at `/public/vendor/public/vendor/`.
CK2 interfere with Bower in some way (do not know which fault this is) and the installation path is unexpected for me.
Or is this desired behavior?

Also, after I figured the destination location, after deleting the asset manualy it no longer appears in CK2, which is the way I can remove assets from **Installed** tab. But doing this manualy is not an option, not for the tool like CK2 is :)

Thanks

**Comment by bdkjones** [comment]
If you use a .bowerrc file, you should not specify the path in CodeKit's preferences. CodeKit is designed for people that don't want to muck around with invisible configuration files and crappy command line tools, so most folks will never use .bowerrc files.

**Comment by Andreyco** [comment]
Okay, this is the half of the issue.

I manage external components and assets with Bower, I just list then in bower.json
I do version everything except these external dependencies. Which make sense, why should I version something I do not develop, just pull that into project.

When deploying to production I run `boower install` or `bower update` to get them in.

In current situation, I cannot exclude dependencies from versioning, since they are not listed in bower.json file I cannot pull them in later so I cannot .gitignore them.
What I ask is to relocate this part from CK2 config file into bower.json file.
Those peope who do version projects but not dependencies will be happy, even those who don't version at all or version just everything.

Disadvantage - one more config file.

This other half may solve the origin of this issue - managing (installing or uninstalling) components/assets.

**Comment by Andreyco** [comment]
Still not convinced?
