### ISSUE TITLE
The remove project icon not showing after first removal in the projects popover (beta 12)

### ISSUE THREAD

**Issue by rpkoller** [bdkjones/CodeKit2#176]
-Move the mouse over a project you want to remove. The remove icon is showing on mouse over: 

![bildschirmfoto 2014-01-19 um 05 23 52](https://f.cloud.github.com/assets/1665422/1948878/8e138bb0-80c1-11e3-9f9d-8e1f752202c0.png)

-On mouse click the project is removed. -> don't move the mouse after the click.
-The mouse is over the next project in the list now. basically it should show the remove icon again now. but it isn't. but if you click the project it is removed anyway.

**Comment by bdkjones** [comment]
Yea... I was wondering when someone would turn this up. 

I'm aware of the issue. I've been putting off fixing it because doing "hover" effects in an application is ridiculously complicated. You wouldn't believe the amount of work it takes.

**Comment by bdkjones** [comment]
Okay, fixed in Beta 13. Don't even ask me how many hours it took.

**Comment by rpkoller** [comment]
@bdkjones works like a charm in beta 13 now. feels even more responsive and lighter than before. real cool. the only real tiny cosmetical issue which turned up, but i am unable to reproduce it yet,  is that it happens that a close button shows up on a project i am not on a mouse over. but i will open a separate issue if i am able to reproduce it. but in general the close buttons look fine and behave real real good. cool
