### ISSUE TITLE
Changing Generic Page Extensions requires app restart

### ISSUE THREAD

**Issue by kmmathis** [bdkjones/CodeKit2#179]
I'm working on a project that uses mustache templates that have a .mustache extension. After I figured out that I needed to add the extension to "Generic Page Extensions", I found that my templates would not show up in the CodeKit file browser or trigger a web browser refresh until I quit the app and started it back up again. Not sure if this is intended behavior or not; I figured I'd add it here just incase.

**Comment by kmmathis** [comment]
Ooops! Clicking the refresh icon does the trick. It just took a minute for CodeKit to refresh on its own. Should CodeKit automatically refresh the project after the "Generic Page Extensions" are changed?

**Comment by bdkjones** [comment]
No. You need to click refresh after modifying your settings.
