### ISSUE TITLE
A couple typos

### ISSUE THREAD

**Issue by maxlapides** [bdkjones/CodeKit2#180]
I hope you don't hate this type of feedback, but I found a couple little spelling issues:
- Under General Project Settings > Skipped Items & Paths, it says "comma-seperated" - should be "comma-separated"
- Same issue under General Project Settings > Generic Page Extensions, should be "comma-separated"
- In the menu bar, under Tools, "Mamp" should be "MAMP"

**Comment by bdkjones** [comment]
God no, I love these kinds of issues. Simple and quick to fix. Thanks!
