### ISSUE TITLE
Minor issue: Assets - Installed components - Sort by Name

### ISSUE THREAD

**Issue by edwardsdesign** [bdkjones/CodeKit2#181]
Under Installed Components the sort by name option seems to split the list into 2 alphabetical groups.

How to recreate:

 1) Open assets
 2) Select components tab
 3) Search for jquery (or any term with a large selection of components such as bootstrap, etc...)
 4) Sort returned list by name and scroll down.

Screenshot showing where list one ends and list 2 starts:

![ck2-beta-12-bower-sort-by-name-issue](https://f.cloud.github.com/assets/867897/1955611/2dea6972-81eb-11e3-8b13-13227fb811bc.png)

**Comment by bdkjones** [comment]
Dammit. It's sorting them in a case-sensitive manner where all uppercase letters A-Z are superior to all lowercase letters. Nice catch.

**Comment by bdkjones** [comment]
Fixed in Beta 13. Thanks!
