### ISSUE TITLE
Non-Bonjour Address points to http://33.33.33.1:5757

### ISSUE THREAD

**Issue by guill3m** [bdkjones/CodeKit2#184]
At work we use 33.33.33.10, .11, and .12 with Vagrant and VirtualBox for our projects, but I've shut down all the virtual machines and cleaned `/etc/hosts` and the server still points to that address, with every project.

I'm guessing it may have something to do with this lines in `Vagrantfile`?

```
# Define Variables
$vm_ip = "33.33.33.10"
$client_ip = "33.33.33.1"
```

and

```
      puppet.facter = {
         "client_ip" => $client_ip,
         "vm_ip" => $vm_ip
      }
```

I've closed CK, reseted the server, reseted the computer, but it keeps showing that one.

I can go to Network Preferences and get my actual local IP and it works fine, the only thing that seems to be failing is the link that CodeKit outputs. So its nothing like super important, but it's still something.

Has been happening as long as I can remember but I keep forgetting to write this issue... It happens for all the projects, either for that ones where we use Vagrant as for the ones that don't.

If I restart CodeKit's server several times there is some times when it will get the proper IP, but normally it gets 33.33.33.1

OS X 10.9.1
CodeKit 2 Beta 12
VirtualBox 4.3.6 r91406
Vagrant 1.4.3

![Screenshot](http://f.cl.ly/items/1T1V1o462J3A463v0v30/server.png)
![etc-hosts](http://f.cl.ly/items/3i402N123h2m0L381i0e/hosts.png)

**Comment by bdkjones** [comment]
The address in that location is NOT the address of your external server. It's the IP address of the machine that CodeKit is running on. 

You enter the address of your external server in the Project Settings area.

**Comment by guill3m** [comment]
I'm aware of that, but **it should look like `192.168.1.65`** so I can access from another device that's not the computer where CodeKit is running.

I've said the external server as it looked that it uses a similar IP, for if it was useful information, but it happens for CodeKit in general, either with projects that use external server as for servers that don't use any external server.

**Comment by bdkjones** [comment]
Open Terminal, type `ifconfig` and paste the entire output here, please.

**Comment by bdkjones** [comment]
Haha, yes, you need to be connected to the network in order for me to debug something involving your network-assigned IP address. Re-run the above command when you're on the network and give me the output.

**Comment by guill3m** [comment]
OK, so here it is:

```
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
    options=3<RXCSUM,TXCSUM>
    inet6 ::1 prefixlen 128 
    inet 127.0.0.1 netmask 0xff000000 
    inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
    nd6 options=1<PERFORMNUD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
    ether b8:f6:b1:1b:06:a9 
    inet6 fe80::baf6:b1ff:fe1b:6a9%en0 prefixlen 64 scopeid 0x4 
    inet 192.168.1.65 netmask 0xffffff00 broadcast 192.168.1.255
    nd6 options=1<PERFORMNUD>
    media: autoselect
    status: active
en1: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
    options=60<TSO4,TSO6>
    ether 32:00:16:4d:df:80 
    media: autoselect <full-duplex>
    status: inactive
en2: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
    options=60<TSO4,TSO6>
    ether 32:00:16:4d:df:81 
    media: autoselect <full-duplex>
    status: inactive
bridge0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
    options=63<RXCSUM,TXCSUM,TSO4,TSO6>
    ether ba:f6:b1:b1:c9:00 
    Configuration:
        id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
        maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
        root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
        ipfilter disabled flags 0x2
    member: en1 flags=3<LEARNING,DISCOVER>
            ifmaxaddr 0 port 5 priority 0 path cost 0
    member: en2 flags=3<LEARNING,DISCOVER>
            ifmaxaddr 0 port 6 priority 0 path cost 0
    nd6 options=1<PERFORMNUD>
    media: <unknown type>
    status: inactive
p2p0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 2304
    ether 0a:f6:b1:1b:06:a9 
    media: autoselect
    status: inactive
vboxnet0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
    ether 0a:00:27:00:00:00 
    inet 33.33.33.1 netmask 0xffffff00 broadcast 33.33.33.255
```

**Comment by bdkjones** [comment]
Okay. Fixed in Beta 13 by adding some logic that always perfers 192.x, 172.x, and 10.x IP addresses over all others available.
