### ISSUE TITLE
Application Icon black pixel at 32x32px

### ISSUE THREAD

**Issue by Vastyles** [bdkjones/CodeKit2#185]
Very small issue, there seems to be a black 1px on the 32x32 size of the application icon. Noticing it in finder (list view). (Beta 12)

Screenshot:
![screenshot 2014-01-22 08 55 50](https://f.cloud.github.com/assets/4094812/1974316/114587b0-836d-11e3-8a5a-69c5060dbc14.png)

**Comment by zengabor** [comment]
Can't imagine myself buying CodeKit 2 until this is fixed. ;)
I like this new icon, by the way.

**Comment by bdkjones** [comment]
The people responsible for this error (@agenericguy) have been shot.

**Comment by bdkjones** [comment]
Fixed in Beta 14.
