### ISSUE TITLE
Image Compression

### ISSUE THREAD

**Issue by Horttcore** [bdkjones/CodeKit2#186]
While I was working on a project which has a very big sprite file ([read more about sprite files](http://css-tricks.com/css-sprites/)), I checked the CodeKit 2 image compression. The File is 1MB png exported for web by Photoshop CC, after CodeKit 2 reduction it has 880KB ( -12% ). Which isn't very bad. But I've tried [TinyPNG](https://tinypng.com/) with the same image and it is reduced by 82%!

Maybe we should look for some other image compression libraries?

**Comment by bdkjones** [comment]
What settings did you use for TinyPNG? CodeKit’s image compression is _always_ lossless. If you set TinyPNG to use lossy compression, you get a better result but your image loses quality. That’s likely what explains the difference.

**Comment by Horttcore** [comment]
Ah you got the point, maybe you should offer various options in the image compression.

**Comment by bdkjones** [comment]
Feature requests are currently closed. Please file this once 2.0 ships. I do plan to offer configuration options for the image compressors, but in 2.1+
