### ISSUE TITLE
CodeIgniter, session/cookie problems

### ISSUE THREAD

**Issue by thierrymichel** [bdkjones/CodeKit2#187]
I experienced some problems using Codeigniter with sessions (especially `session->flashdata()`).
Everything works correctly on my local server (MAMP Pro with virtualhost).

With CK server, it doesn't work in Chrome, failed to establish connection in Firefox and works very very slowly in Safari (30sec latence)…
I also encountered problems when switching between projects… 

I decided to create a special "test project" without login or database requests to isolate the problem. I think CodeIgniter uses cookies to manage sessions. May be this is the concern...

With this test:
- Safari is ok.
- Chrome and Firefox create data but don't update or delete.
- Opera totally fails. 

Online test : http://playground.thierrymichel.net
Test to download : https://dl.dropboxusercontent.com/u/3548964/codekit-codeigniter.zip

**Comment by thierrymichel** [comment]
I checked without MAMP Pro virtualhost, CK server settings via localhost:8888

Safari still ok.
Chrome, Firefox and Opera do the same.

**Comment by bdkjones** [comment]
Fixed in Beta 14.
