### ISSUE TITLE
Building a site located in Google Drive changes scss output file location

### ISSUE THREAD

**Issue by yratof** [bdkjones/CodeKit2#188]
Have you tried build a site within a google drive folder?

I've notices that every time I open codekit 2, the styles all change to /Users/Andrew/Google Drive/sites/wordpress/wp-c...

Instead of being local to just /css

It seems to try to give it an absolute URL, so when it compiles, it puts a new folder in my scss folder with that string of folders /users/andrew/goo... etc

**Comment by yratof** [comment]
This might be caused by the config file being clones when a project is cloned

**Comment by bdkjones** [comment]
This was fixed in 2.0.3.
