### ISSUE TITLE
Vagrant / PHP

### ISSUE THREAD

**Issue by jayfreestone** [bdkjones/CodeKit2#19]
I'm trying to integrate Codekit 2 into my Vagrant workflow and I'm having a few issues.

I'm using the same setup as [Varying Vagrant Vagrants](https://github.com/10up/varying-vagrant-vagrants) for Wordpress sites. I visit sites locally using a predefined url e.g. (dev.xxxx.com) that I've set up in my localhost and in an nginx config file (192.168.50.4, port 80).

No matter what I put in the 'External Server Address' field I haven't been able to get Codekit to work with it. Entering the url rewrites the URLs in the source but doesn't serve up the PHP files properly (?)

![screen shot 2013-12-18 at 12 03 13](https://f.cloud.github.com/assets/3719745/1772952/7b110194-67dc-11e3-92e9-cb6a9a0c2739.png)

Works fine on the actual address.

Possible I'm being stupid or missing something.

Edit:

This might be due to me having the core Wordpress files in a subdirectory, I'll look into it.

**Comment by bdkjones** [comment]
Hi Jay,

What was the resolution on this?

**Comment by jayfreestone** [comment]
The empty/redundant <?php?> at the start. 

Removing it fixed the issue. I have no idea why it only caused a problem with the Codekit url, though.
