### ISSUE TITLE
Autoprefixer makes less source map invalid

### ISSUE THREAD

**Issue by rasmusbe** [bdkjones/CodeKit2#191]
If I create a less source map and then use autoprefixer the map becomes invalid.

Seems like autoprefixer have support for modifying the previous source map according to https://github.com/ai/autoprefixer/

**Comment by bdkjones** [comment]
Beta 15 now pipes the source map to autoprefixer, so this should be fixed.

**Comment by devilskitchen** [comment]
This is fixed for the first page load. After that—using the auto-reload—the source map is lost again. Not a killer problem, by any means—perhaps for 2.1 or something.

Mac Mini / Mac OS 10.9.1 / CK2 Beta 15 / Coda 2 Editor

**Comment by bdkjones** [comment]
Huh? What do you mean "lost again"?

**Comment by devilskitchen** [comment]
Damn—should have screen-shotted it. Have to wait till I'm back at work for that.

However, when using the web inspector (Safari, latest version) when the source map is working, the rules in the CSS panel show the name of the originating LESS file, e.g. <code>03-03-panels.less</code>.

After an automatic reload, the rules no longer show the originating LESS files—only the name of the compiled stylesheet, e.g. <code>style.css</code>.

I'll grab a screen first thing on Monday.

**Comment by devilskitchen** [comment]
So, here is what the CSS source looks like when the page is first loaded...

![page-reload](https://f.cloud.github.com/assets/1190864/2124422/2b042668-923e-11e3-8a2f-6fd48a4a30d1.png)

... and here is what the CSS source looks like after CK2 has done a save-LESS-triggered refresh...

![after-ck2-reload](https://f.cloud.github.com/assets/1190864/2124424/459e5282-923e-11e3-8878-1e565165fff9.png)

Regards,

c

P.S. CK2 is _still_ awesome...

**Comment by bdkjones** [comment]
I need the Less files (all the ones in the chain). And an index.html file that uses the compiled CSS so that I can duplicate the issue and debug it on my end. Thanks.

**Comment by devilskitchen** [comment]
Here you go: https://www.dropbox.com/s/6cv3zsw0kqzri6c/bkj-pkg-autoprefixer.zip

I've taken the source code from the page, rather than packaged up the whole product—which (as with the other packages I sent you) runs in Node, and locally through Vagrant.

Let me know if you need anything else.

**Comment by rasmusbe** [comment]
I think the problem @devilskitchen has is browser related, seems to work fine in Chrome but not in Safari. I suggest you close this issue.

**Comment by devilskitchen** [comment]
That might be it (I do use Safari as my primary browser).
