### ISSUE TITLE
Local preview pulling favicons from other projects

### ISSUE THREAD

**Issue by geebru** [bdkjones/CodeKit2#194]
Whenever I start a new project and preview it locally, the favicon of the local test page pulls a (seemingly) favicon from another project within CodeKit.

For instance, I'm working on a form page for a client and have no favicon in the project folder, but the tab shows one from an existing CK project:

The favicon - http://cl.ly/image/2j1w3u2m2g0A
The project list - http://cl.ly/image/1c3G2u2I0T3H

The favicon being loaded for WEDC is actually from the HSP project. While not a major deal as it's local and when viewed elsewhere it has no favicon, I just find it odd that it's pulling favicons from other projects.

---

Mac OSX 10.9 (Mavericks)
Chrome
Build 16142

**Comment by bdkjones** [comment]
Disable your browser cache during development.

**Comment by geebru** [comment]
![screen shot 2014-03-06 at 12 23 01 pm](https://f.cloud.github.com/assets/806033/2348062/d1b3f4ac-a553-11e3-9875-816ff70626af.jpg)

Even with the new version and multiple (hundreds) of browser cache clears it's still pulling that one favicon. Is there somewhere in the CodeKit files or temp files it might be storing this? No amount of clearing seems to rid me of this favicon.

EDIT : "Fixes" itself if you set the favicon to nothing (`<link rel="shortcut icon" href="">`) but it looks like the default is some cached favicon from another project if you don't specify a new favicon or a blank favicon.

**Comment by sandralundgren** [comment]
I was having this favicon issue too. A simple hard refresh (Cmd + Shift + R) did the trick.
