### ISSUE TITLE
SCSS file fails to Compile after 50 Media Queries(Bourbon Neat) are used

### ISSUE THREAD

**Issue by koycarraway** [bdkjones/CodeKit2#195]
This may be an edge case scenario for most, but I am hitting this limit with a recent responsive site Im working on.

System Details:
- OSX 10.9.1
- Sublime Text 3, Build 3059
- Local Project (no cloud sync folder)
- Codekit Build 16142

Project Details
- SCSS
- Bourbon
- Neat

This is occuring when 50 or more "@include media();" bourbon neat mixins are used. I found this out by painstakingly removing them one by one until i hit 49, and CK compiled successfully. This is only for the media mixin, any other mixin works fine.

Proof Vid: http://cl.ly/461H0C1E0t0M

Is this a known limit or an issue? This is a mobile first project, so there are alot of MQs needed so far.

PS!! - Codekit 1 compiles it perfectly fine....no hiccups

**Comment by bdkjones** [comment]
This isn't a CodeKit issue. You need to file this with the Sass guys. That's definitely a problem with their compiler. Are you using Ruby or libsass?

**Comment by koycarraway** [comment]
Gotcha. Not compiling with libsass. What makes codekit 1 compile it fine but not ck2?

**Comment by bdkjones** [comment]
CodeKit 1 is running a different, older version of Sass.
