### ISSUE TITLE
sass source map (with compass) not being generated?

### ISSUE THREAD

**Issue by mgrn0** [bdkjones/CodeKit2#196]
Sorry if this might be a duplicate, I could not find any related entry in the closed issues:

Did anybody succeed in creating source maps project that use with sass and compass in the latest beta? I tried it on several machines (including a fresh clean OS installation) but could not get it to work.

I am not using the libsass compiler, and I am using Codekit's internal sass and compass compilers (as recommended).

Thanks for any advice/tips.

**Comment by bdkjones** [comment]
Compass does not yet support source maps.

**Comment by mgrn0** [comment]
ah, thanks. I completely missed that fact.
