### ISSUE TITLE
Would be nice to focus on a subfolder, especially in WP

### ISSUE THREAD

**Issue by smlombardi** [bdkjones/CodeKit2#197]
In Code kit 1, I only added the Wordpress theme folder to CK. 

In Code Kit 2, it seems we need to add the entire Wordpress directory to CK. This is getting to be a pain.

One, it takes a long time to scan and update all these folders compared to instantly for just the theme folder, and 

It's very difficult and tedious to find the CSS/LESS/SASS files for the theme you're working on, since even if you filter by "stylesheet" the scroll in the window is over 7000 pixels long (I  shot it with Snagit) and includes every css file in Wordpress itself and every loaded plugin and theme.

Not sure what the solution is, other than being able to only load the theme file or somehow highlight that folder and "solo" it.

**Comment by tombonez** [comment]
I'm working from my themes folder and having zero issues (excluding the annoying Chrome cookie issue), you just need to make sure the "This project requires an external server" is checked.

**Comment by smlombardi** [comment]
> I'm working from my themes folder and having zero issues (excluding the annoying Chrome cookie issue), you just need to make sure the "This project requires an external server" is checked.

Ah, thanks, I thought Bryan said we couldn't.  I'll go back to that.

**Comment by Horttcore** [comment]
As @tombonez said there is no problem except the Cookie issue.
