### ISSUE TITLE
HTML files prefixed with underscore do not refresh the browser on save

### ISSUE THREAD

**Issue by pixeljitsu** [bdkjones/CodeKit2#199]
Local folder, Sublime Text 3, 10.9.1 Build 13B42

I'm not sure if this is a bug or a feature request, but Codekit does not seem to watch html files that start with an underscore.  I have a partials directory where each file is prefixed with an underscore; this is a convention of the CMS I'm using which prevents the files from being loaded directly via their URL. 

partials folder
   fileA.html
   _fileB.html

Changes to fileA.html are detected and the browser is refreshed normally while changes to _fileB.html seem to be ignored and the browser has to be manually refreshed.

Is this the expected behavior?  If so, how hard would it be to have Codekit watch html files starting with an underscore?

**Comment by greystate** [comment]
I think it's the expected behavior - see _The "Partial" Convention_ paragraph on the [Kit Language page](http://incident57.com/codekit/kit.php)

As for how to circumvent it, I have no ideas...

**Comment by bdkjones** [comment]
Yep. CodeKit DOES see the change to the file, but because it starts with an underscore, the app goes and looks for any files that import the one that just changed. Because there are none, the app concludes that there's nothing to be done.

What CMS are you using?

**Comment by pixeljitsu** [comment]
I'm using Craft. See this page: http://buildwithcraft.com/help/entry-type-templates

In this example the media/_entry.html file is 'hidden' so that Craft would process the URI /media/entry if the underscore were not used. The way the routing works, any filename.html in the template structure would translate to /filename as an URI

http://buildwithcraft.com/docs/routing

"6. Finally, Craft will see if the URI is a valid template path. If it is, it will return the matched template. Note that if any of the URI segments begin with an underscore (‘_’), Craft will return a 404, since template path segments that begin with an underscore are considered “hidden” from direct access."

This is pretty common in Craft and in Expression Engine.

I can change the template extension to whatever I like if that would help any:  http://buildwithcraft.com/docs/config-settings#defaultTemplateExtensions

**Comment by bdkjones** [comment]
Try changing the extension and see what happens.

**Comment by pixeljitsu** [comment]
Just tried switching from .html to .twig with the same result.

**Comment by marflow** [comment]
Same here with ".twig", local on ST2. Would be great if ".twig" extension could trigger an exception from the "_" rule or if we could define exceptions. (No idea how much work that would mean, just naive question)

**Comment by bdkjones** [comment]
Add .twig as a generic page extension in the project settings.

**Comment by marflow** [comment]
No happy news.

**Comment by pixeljitsu** [comment]
I spoke with the developer of Craft and they will be adding in the option to switch the 'hidden' file character from (‘_’) to (‘.’) in the next release (not sure when that will be).  Will CodeKit watch folders and files that begin with a period?

**Comment by bdkjones** [comment]
No, actually. CodeKit ignores files that begin with a period because on OS X, those are always files that are _meant_ to be ignored.

**Comment by pixeljitsu** [comment]
About 80% of the files I work in are prefixed with an underscore, mostly twig extends and hidden partials.  I really hope there will be a work around or an additional option to rectify this.  Refreshing across multiple browsers looked so appealing.

**Comment by bdkjones** [comment]
You DID check the "Reload Browsers On Save" box, right?

![screen shot 2014-02-03 at 18 27 52](https://f.cloud.github.com/assets/926566/2072711/422d6a38-8d44-11e3-89b9-481cf149684b.png)

**Comment by gregblass** [comment]
I'm having the same issue - Codekit works great and refreshes my browser for my Rails project, but it won't refresh partials with an underscore preceeding them (very common in Rails). So index.html.erb refreshes fine, but _form.html.erb - no refresh. Any workarounds? If not unfortunately I'm going to have to look for another solution.
