### ISSUE TITLE
Beta 13 still not working flawlessly with Wordpress

### ISSUE THREAD

**Issue by rpkoller** [bdkjones/CodeKit2#200]
I've tried the latest beta few minutes ago. On the  first start all imported projects were gone so i did a clean reimport and setup of projects ( i might open a separate issue for the gone project settings - should i? )

the set up:  I've dragged only the themes folder into Codekit (in Wordpress 3.8.1. - the wp folder placed into a subfolder in the root, if you remember). In the settings external server required is switched on, the externalserver adress iss set to http://localhost:8888 and the preview subpath to testproject, the folder name in mamps (non-pro version) htdocs folder.

when i clicked onto the preview folder all worked fine and the site gets previewed and loaded. live injections worked too. also the login into the wordpress admin section with safari 6.1.1 worked fine. only problem if i click on visit site inside the admin-area things go nuts and the following screen is shown:

![bildschirmfoto 2014-01-28 um 18 32 26](https://f.cloud.github.com/assets/1665422/2021773/d0cf9352-8843-11e3-9d0f-9fe040129c98.png)
=> stating  that too many redirects have taken place -> happens if a open site redirects onto another site which is point back to the initial one. 

 a reload in this state doesn't help either. i have to close the safari tab and click on preview in codekit again. then all is back to normal.

best regards ralf

**Comment by rpkoller** [comment]
oh and one more observation. when i was in that state that the page wasn't loading and only closing the tab helped i tried one thing before i've closed the window (and after the try to just reload). I've entered only olymp.local:5757 (without the subpath) in the adress bar. the following mamp error page showed up: 

![bildschirmfoto 2014-01-28 um 18 33 19](https://f.cloud.github.com/assets/1665422/2022889/a50e61ca-8853-11e3-8d10-024ed2729ab6.png)
-> stating that the virtual host was successfully set up. 

if i try right now while safari and codekit are behaving normal again olymp.local:5757 just forwards me to project active in codekit.

**Comment by frank-laemmer** [comment]
i think that is a bug that only affects BETA 13, it used to work in BETA 12 – and it applies to all kind of projects, not only wordpress. i opened a similar ticket #205 (with a hopefully more descriptive title) – maybe one can be rejected/closed?

**Comment by bdkjones** [comment]
Fixed in Beta 14.
