### ISSUE TITLE
Trailing slash on external server request with subpath in Beta 13

### ISSUE THREAD

**Issue by zengabor** [bdkjones/CodeKit2#201]
Beta 13 always adds a trailing slash when calling the external server with a subpath, even if there is already a trailing slash there.

Some examples:

```
http://bryan.local:5757 >>> http://localhost:8080/ (okayish)
http://bryan.local:5757/ >>> http://localhost:8080/ (okay)
http://bryan.local:5757/hi >>> http://localhost:8080/hi/ (WRONG)
http://bryan.local:5757/hi/ >>> http://localhost:8080/hi// (WRONG)
```

It breaks my code until I handle this specifically. It would be really nice to have the same amount of trailing slashes in the URL bar and in the external server request. Thanks!

**Comment by bdkjones** [comment]
The trailing slash is necessary to avoid an issue where DNS lookup takes 30-40 seconds. The third example you list is correct. The fourth, however, is not. I'll take a closer look at that.

**Comment by zengabor** [comment]
I've tried to learn more about this "dns lookup takes 30-40 seconds" but could not find anything describing exactly that, with such extreme timeouts.

For me this issue is quite annoying because none of my POST handlers work and I cannot access important parts of my application. These URLs have nothing to do with actual directories and files in my application server (Google AppEngine). I simply find this behavior wrong when I enter a http://x.local:5757/something URL in the address bar then CodeKit 2 silently appends a trailing slash which is not even present in the URL bar so it's even undetectable.

If my application server does this 30-40 second timeout then I should suffer and learn to append that trailing slash in the links and form actions that I define. But it should not silently alter the URLs that I enter.

**Comment by marcaube** [comment]
I also have trouble with this ...
- `/path` MAY mean `/path/` but they are not equal.
- `/path/` IS NOT `/path`.
- `file.html/` DOES NOT EQUAL `file.html`

This is how Apache handles trailing slashes : If there is no trailing slash it looks for a _file_, and if there is it looks for a _folder_.

As a convenience for _end-users_, some frameworks will append a `/` to an URL (30x response) instead of directly throwing a 404. But this is not the standard behaviour, because the URL might very well be _without_ a trailing slash.

Unique URLs generally mean unique pages.

**Comment by bdkjones** [comment]
Fixed in Beta 14.

I've gone ahead and removed the trailing slash logic -- it's now up to you to include the slash when needed. If you don't, you'll see 30-40 second delays while the external server attempts to resolve things. Let me know if you see this behavior.

**Comment by zengabor** [comment]
That's very kind of you, Bryan. Thank you!

Will definitely let you know when I encounter a longer delay, although it won't happen with the application server that I use.
