### ISSUE TITLE
Is There A "Don't Compile" Option?

### ISSUE THREAD

**Issue by bobrocke** [bdkjones/CodeKit2#202]
Is there a way to mark a file, perhaps a .scss file, to not compile?

I want to remember such an option in CodeKit 1.

Bob

**Comment by bdkjones** [comment]
Someone didn't pay attention to the screencast!

You uncheck the box next to "Output File" in the right-hand inspector. To skip all Scss files in a project, add `*.scss` to the skipped items list in the project's preferences.
