### ISSUE TITLE
Duplicate Help texts on General Project Settings screen

### ISSUE THREAD

**Issue by greystate** [bdkjones/CodeKit2#203]
Just noticed (in Beta 13) that the _popup_ text in the **General Project Settings** for the **Generic Page Extensions** repeats the "This list should always contain .git, .svn, .hg, [...]" message of the  **Skipped Items & Paths** field above it.

Likewise, the help text for the **Bower Components Folder** seems to be a duplicate of the help text for the **Icon and Name** field at the top of the screen.

**Comment by bdkjones** [comment]
Fixed in Beta 14. Thanks!

**Comment by greystate** [comment]
These doesn't actually seem to be fixed in Beta 14 - am I seeing ghosts or is there maybe some kind of resource cache playing tricks on me?

**Comment by bdkjones** [comment]
No, they're definitely gone. Just checked.
