### ISSUE TITLE
Keyboard shortcut for "Preview"?

### ISSUE THREAD

**Issue by greystate** [bdkjones/CodeKit2#204]
I keep searching the menus for a keyboard equivalent of pressing the **Preview** button... :)

Something along the lines of `⌃` + `⌥` + `⌘` + `P` would make sense, I guess?

**Comment by rpkoller** [comment]
+1

**Comment by bdkjones** [comment]
Implemented in Beta 14. I simply hijacked the command+p shortcut. Hope nobody was printing stuff with CodeKit.
