### ISSUE TITLE
Redirect loops with CK2 BETA 13 (16338) & external webserver

### ISSUE THREAD

**Issue by frank-laemmer** [bdkjones/CodeKit2#205]
Basically the same thing as described in #200 – but i think it has only to do with BETA 13 (worked in BETA 12) and it applies to all kind of projects, not only wordpress (at least in my case):

**my test setup**
- MAMP pro with custom vhosts
- a laravel project and a wordpress project
- using external server

**behaviour**
- doc root renders as expected (base URL) http://fuckup.local:5757/
- any deep links (click on any internal link) brings up a browser error page "redirect loop" http://fuckup.local:5757/besucher/
- tested with chrome & firefox

**Comment by johnsardine** [comment]
I can confirm this with WordPress

**Comment by Andreyco** [comment]
What happened to beta 13?
I get redirect loop all the time using external server.
Worked fine until beta 12.

Details
- MAMP and virtual hosts, Laravel codebase.
- behaviour very same as original poster

**Comment by zengabor** [comment]
It may be related to the "trailing slash" issue: #201 
I had a similar experience with my project.

**Comment by shshaw** [comment]
Having the same problem in Wordpress with Beta 13. Beta 12 was fine.

For me, the .local:5757 address redirects correctly and the page renders fine. However when CodeKit appends the ?ckcachecontrol= URL parameter, I get a redirect loop error.

I've tried with localhost:8888 and localhost:8888/ as the external server address.

**Comment by bdkjones** [comment]
Fixed in Beta 14.

**Comment by frank-laemmer** [comment]
glad to confirm that the fix works.
