### ISSUE TITLE
Beta 14 : projects and frameworks deleted... -> saving project's name in config.codekit?

### ISSUE THREAD

**Issue by thierrymichel** [bdkjones/CodeKit2#207]
I replaced codekit.app with the latest version and all my projects /  frameworks have disappeared… :(

So I could verify that the config.codekit worked well! :)
Is it possible to save the project's name (instead of the folder's name) into the config?

**Comment by yratof** [comment]
This has happened since Beta 12

**Comment by thierrymichel** [comment]
Ok, thanks (I thought I only missed the Beta 13).
Whatever I think saving the project name is a friendly feature (I recovered too many "htdocs" projects)… ;)

**Comment by bdkjones** [comment]
It's a beta guys; I'm not going to waste time writing code to migrate data models. When I update the data model, I simply have the new beta start fresh. Migration is a pain and I only worry about it for production releases.

This is not a bug.

**Comment by yratof** [comment]
Makes sense. You've just built a tool that's good enough to make us forget it is only beta

**Comment by thierrymichel** [comment]
Don't get me wrong, it was about this suggestion : **saving project name into "config.codekit"**.
Nothing more. I enjoy myself working with this new version…
