### ISSUE TITLE
Project is replaced by a new project.

### ISSUE THREAD

**Issue by Horttcore** [bdkjones/CodeKit2#21]
I added a project 'horttcore-manufacturing' which is a WordPress theme folder, then went to the project settings and renamed it to 'Horttcore'. After that I added the whole WordPress project called 'horttcore' to CodeKit and the 'Horttcore' project was replaced by the new project called 'horttcore'.

**Comment by bdkjones** [comment]
This is expected behavior. When you add a parent folder, CodeKit checks to see if any child folders are already projects and, if so, removes them.
