### ISSUE TITLE
Drag files onto codekit to add to project

### ISSUE THREAD

**Issue by yratof** [bdkjones/CodeKit2#211]
Not sure if this was removed, but in Cokekit 1.x, you had the ability to drag files onto the codekit window and it would either start a new project with it, or tell you it was added to a previous library already.

This was massively handy when using Coda 2, as it isn't very good at seeing file changes outside of it. I could drag my .css or my .min files onto codekit & know that everything was cool.

Now codekit doesn't see that i'm holding a file over it, it just ignores anything if it's dropped too.

Is this something that has been overlooked, or was it removed on purpose?

**Comment by bdkjones** [comment]
Yep. The app now accepts only folder drops. The reasons are a bit technical. 

As for Coda 2: I'm one of Panic's beta testers and the issue where Coda 2 doesn't notice that files have changed outside of the app... will not be an issue much longer.

**Comment by yratof** [comment]
Such a tease. But cheers for the update!
