### ISSUE TITLE
Extreme long first load for Wordpress sites in Beta 14

### ISSUE THREAD

**Issue by rpkoller** [bdkjones/CodeKit2#213]
my stopwatch showed 30 seconds on each first hit of preview in codekit. once the site was loaded all is fine and fast. but on every initial load it takes ages.

**Comment by bdkjones** [comment]
What did I say in the cookies thread? Add the trailing slash and close this.

**Comment by rpkoller** [comment]
uhhhh my bad sorry! overread it. :s

**Comment by bdkjones** [comment]
Meant to say changelog, not cookie issue. Adding the trailing slash fixed it?

**Comment by rpkoller** [comment]
yep the trailing slash fixed it. now the adress also shows olymp.local again instead of olymp.localdomain
