### ISSUE TITLE
Is .min as output file suffix not allowed?

### ISSUE THREAD

**Issue by rpkoller** [bdkjones/CodeKit2#214]
I've tried to enter .min as file suffix

![bildschirmfoto 2014-01-31 um 02 48 45](https://f.cloud.github.com/assets/1665422/2047319/09fa9f96-8a1a-11e3-9a6c-56521e2e6486.png)

but codekit sticks to -min. is something wrong about .min and codekit prevents me from doing something silly or is it more of a misbehaviour? 

![bildschirmfoto 2014-01-31 um 02 50 02](https://f.cloud.github.com/assets/1665422/2047320/1322139c-8a1a-11e3-8222-08dcd8dea3ac.png)

**Comment by rpkoller** [comment]
that is strange. i've built a small test project few minutes ago. there it was possible to switch from -ck to .min and codekit is sticking to it afterwards. thats odd :/

**Comment by Andreyco** [comment]
Tried, can confirm this.

The only way I was able to change `-ck` to `.min` is:
- focus the input, change `-` to `.`, leave the input
- focus the input, change `c` to `m`, leave the input
- focus the input, change `k` to `i`, leave the input
- focus the input, add `n`, blur

But I don't think it is the proper way to have the field filled :)

**Comment by rpkoller** [comment]
hm i've started codekit with a pressed shift key and removed the config.codekit file. then i've made the settings seen on the right which lead to the output seen on the left. :/  quite strange. happened on 10.8.5 and beta 16. 

![bildschirmfoto 2014-02-10 um 09 33 40](https://f.cloud.github.com/assets/1665422/2123514/7e48adc2-922e-11e3-8a43-489d3331995e.png)

**Comment by rpkoller** [comment]
@bdkjones I've tried the described flaw in a small sample project today with the intention to sample the process in the terminal for beta 18. The odd part was it worked in the sample project. Then i've retried it in my main project i am working on right now, where i initially ran into that issue. i've deleted the min js files and tried rewriting them again. What hasn't worked in beta 16 works in beta 18 now even i haven't found anything specifically referring to that issue in the change log. i don't know if for @Andreyco the issue is also gone, but for me it seems it is.

**Comment by rpkoller** [comment]
ok have to correct myself it isn't working again. don't know why it did the last time i tried.

**Comment by rpkoller** [comment]
@bdkjones the issue still presists even in the final. today i've created a small sample project and ran into the issue @Andreyco described. i finally made it to name it with .min as suffix but see for yourself:

![bildschirmfoto 2014-03-09 um 19 58 53](https://f.cloud.github.com/assets/1665422/2368803/8fad8aca-a7bd-11e3-92e1-8fa3927aba86.png)

the suffix is set to .min but it writes out -ck anyway. shall i upload the sample project somewhere or is the suffix renaming reproduceable on your side? 

am running codekit on 10.8

**Comment by bdkjones** [comment]
Did the output file already exist before you made the change to the suffix? If so, CodeKit isn’t going to automatically change the output path; you’ll need to do that manually.

**Comment by bdkjones** [comment]
Actually, it doesn’t matter if the output file existed or not. Once the project is added to CodeKit, the output suffix is already set for the output path of each JS file. You need to edit the New Project Defaults BEFORE adding your project to CodeKit. You’ll also need to delete the config.codekit file in each project you’ve already added so that the app uses the global defaults (including the different suffix) when you add those projects to the app.

**Comment by rpkoller** [comment]
ahhhhhhhhhh after changing the default settings things turned much more sane and comprehendible. thanks.
