### ISSUE TITLE
Weak contrast on a selected output files in the file list. 

### ISSUE THREAD

**Issue by rpkoller** [bdkjones/CodeKit2#215]
![bildschirmfoto 2014-01-31 um 02 52 39](https://f.cloud.github.com/assets/1665422/2047338/85dd74c6-8a1a-11e3-9895-e7bb9faca7f9.png)

the typo is nearly invisible - quite a hard read.

**Comment by rpkoller** [comment]
Source files are ok

![bildschirmfoto 2014-01-31 um 03 02 01](https://f.cloud.github.com/assets/1665422/2047371/cde19724-8a1b-11e3-92a7-bf1dbc7dcd29.png)

**Comment by bdkjones** [comment]
Colors tweaked for Beta 15.
