### ISSUE TITLE
The preview in Mission Control does not correspond with what's being shown in the app

### ISSUE THREAD

**Issue by guill3m** [bdkjones/CodeKit2#216]
Nothing really important, but here it is.

It happens in any part of the app, in Mission Control will always be shown the drop layout. The project icon does correspond with the project selected, it happens only for the bottom part of the app.

A screenshot is clearer than my english:

![screenshot](http://f.cl.ly/items/1V1c3o2z340N3s463G3Y/mission-control.jpg)

**Comment by bdkjones** [comment]
Good catch. Fixed for Beta 15.
