### ISSUE TITLE
Sass variable names with dashes and underscores

### ISSUE THREAD

**Issue by Fequois** [bdkjones/CodeKit2#217]
Whilst compiling Sass, CodeKit is too strict with variable names. Namely, it interprets dash (-) and underscore (_) as different entities while according to Sass' specifications they should be treated the same. The result is that you get a compilation error.

I'm not 100% this is an issue with CodeKit so I apologise if it isn't.

See https://github.com/nex3/sass/issues/1096

**Comment by bdkjones** [comment]
This is definitely not a CodeKit issue. 

CodeKit 2 is using Sass 3.3, which is in pre-release. You'll want to file an issue on the Sass page against that version.
