### ISSUE TITLE
Do not compile settings? (minor feature/question)

### ISSUE THREAD

**Issue by frank-laemmer** [bdkjones/CodeKit2#218]
Maybe i am just missing something here?

While working on my project: i take notes what still needs to be done. I store them in a markdown textfile within the project, so that they are always at my fingertips. I just realized that CK2 compiles that file to a HTML file, well thank you, but MD is all i need (don't want another file in my Git).

GUI: So i was looking around for a setting where i can turn off to compile certain languages at all. there is this "skipped items & paths" thing in the general project settings, but i was actually looking at the MarkDown section itself for a compile markdown yes/no.

USE CASES: i admit, my case is edgy, but i thought about static site generators like octopress, you might want to work with CSS and JS here, but the md files should be handled by something else. probably other cases as well?

BEHAVIOUR: i tried to include markdown files in the "skipped items & paths" with all kind of syntaxes ("md", ".md", "*.md" …) – but still they compile. but i can't see them in the files overview from CK2.

SETUP: CK2 Beta 14

**Comment by bdkjones** [comment]
You uncheck the "Output File" line in the right-hand inspector when you select the file.

**Comment by frank-laemmer** [comment]
understand.
