### ISSUE TITLE
How to use WordPress with CodeKit preview?

### ISSUE THREAD

**Issue by Horttcore** [bdkjones/CodeKit2#22]
In CodeKit 1 I only added the theme folder as project folder and used the browser reload function which worked fine. Now in CodeKit 2 I can't get it to work.

I'm using MAMP PRO as webserver on my local machine on port 80.

Here is what I did, added the theme folder as project, went to project settings, changed the port setting to 80 and kept the http://localhost setting.
Opened a file and saved, in the preview I don't see the WordPress site but the default localhost site.

Went back to project settings and changed it to point at the right subdirectory in my case localhost/horttcore. Now I see my page but without images/css as CodeKit replace the paths to point to xxx.local:5757

This is prolly cause WordPress don't use relative paths..

Then I tried to use the whole WordPress installation as project, but with the same result.

**Comment by jayfreestone** [comment]
I think you have to point it to your actual installation, not just the theme directory.

**Comment by mdavis1982** [comment]
@Horttcore I think the problem here is that you're accessing your site by accessing a folder, rather than setting a up a proper virtual host for it. Could you try setting up a virtual host to view the WordPress site with please?

@bdkjones I don't think this is an issue with CodeKit - but could you confirm please?

**Comment by Horttcore** [comment]
A missed to wrote that I also tried to use the whole WordPress folder as project…

**Comment by Horttcore** [comment]
Ok when using a virtual host it works, but I can't visit any subsites in the installation. So this is pretty bad, as I wanna preview also other sites then just the front page. 
Also my setup 'localhost' with subdirectories is pretty common this could be a big hassle.

**Comment by mdavis1982** [comment]
@Horttcore Can you try checking the "Always use my external server for this project" checkbox in the project general settings and let us know if that resolves it please?

**Comment by Horttcore** [comment]
Something new happens instead of a white screen I get an Error 500.

WordPress is using pretty permalinks, without pretty permalinks it works.

"Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, you@example.com and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log."

**Comment by mdavis1982** [comment]
@Horttcore Is that when using the virtual host or when trying to use the folder?

**Comment by Horttcore** [comment]
Virtual host, WordPress folder as project and without pretty permalinks.

**Comment by mdavis1982** [comment]
@Horttcore So does this happen both with a virtual host, and with a folder?

@jayfreestone Can you help with this? I noticed you had your WordPress setup and closed the issue you were getting before?

**Comment by jayfreestone** [comment]
The issue I was having before is that Codekit was being unforgiving with my (unnecessary) <?php?> tag. Removing it solved my issue. This is unrelated.

I now have Wordpress working fine, using the root folder as the project directory in Codekit, but use a Vagrant VM not MAMP. No idea about the issue here as it's a totally different setup.

**Comment by Horttcore** [comment]
@mdavis1982 it breaks when using folders in my case 'http://localhost/horttcore'. What I notice the preview server opens with this 'http://xxx.local:5757/' URI. Other links on the site pointing to 'http://xxx.local:5757/horttcore/?page_id=30'. All stylesheets and images are broken.

While using a virtual host all assets are loaded correctly. But browsing the site isn't possible until I remove pretty permalinks.

**Comment by mdavis1982** [comment]
@Horttcore I think this is more of a local machine configuration issue rather than anything else, but I think @bdkjones will be able to help you more than I can at the moment.

**Comment by Horttcore** [comment]
I think this is related to ticket #15

**Comment by mdavis1982** [comment]
@Horttcore I'm not convinced that it is as I think @jayfreestone is also using `mod_rewrite` successfully with his WordPress project.

**Comment by jayfreestone** [comment]
What I can confirm is that if I want pretty permalinks then I need to tick the 'Always use my external sever...' box that you suggested earlier or I'll just get a white page for anything other than the homepage.

If I do that then everything works fine.

**Comment by mdavis1982** [comment]
@jayfreestone That's what I imagined... I think this is a local configuration issue rather than a problem with CodeKit itself.

**Comment by Horttcore** [comment]
Ok got it, the htaccess broke it…

**Comment by mdavis1982** [comment]
@Horttcore is everything working now, then?

**Comment by Horttcore** [comment]
Just a last comment, I have to use a virtual host which is no problem for me, but I think most users use a subfolder in localhost...

**Comment by mdavis1982** [comment]
@Horttcore I agree... but only because that's what MAMP encourages you to do by default. I think it's actually a bad practice to do that and results in paths to assets such as `../images/something.png` or, even worse, `../../../images/something.png`. It's much better to use a virtual host and paths such as `/images/something.png` which also has the benefit of working in partials that may be included in various parts of the site at different levels.

**Comment by mdavis1982** [comment]
@Horttcore I'm glad you got things fixed though! :)

**Comment by jayfreestone** [comment]
I just want to follow up on what I mentioned earlier (not sure if I should open a new issue):

Ticking the 'Always use my external sever...' box appears to fix things _but_ using pretty permalinks actually stops refreshes (at least for me).

To rephrase: using pretty permalinks means that on any page other than the homepage the browser is never refreshed after an edit. Doesn't matter what file type is edited (SCSS/PHP), no refresh happens.

Switching back to the default link style fixes it.

**Comment by Horttcore** [comment]
@jayfreestone I opened the ticket earlier today #57
