### ISSUE TITLE
Server Interferes With concrete5

### ISSUE THREAD

**Issue by bobrocke** [bdkjones/CodeKit2#220]
When using the ProBlog add-in to the concrete5 CMS, linking pages within a blog post generates links of the form http://rockbox.local:5757/index.php?cID=131 instead of http://www.concrete.dev/index.php?cID=131 that are created without the CodeKit server.

The CodeKit server links won't work when deployed, of course.

**Comment by bdkjones** [comment]
That's how it's supposed to work. CodeKit is a proxy server. If you're viewing your site through CodeKit's server, the links have to be re-written to keep pointing at the proxy. This is done on the fly as HTTP responses are sent.

If you preview your site directly on your external server, you'll find the links are not rewritten.
