### ISSUE TITLE
[UX] Annoying alert/popup window

### ISSUE THREAD

**Issue by Andreyco** [bdkjones/CodeKit2#224]
If I clear input field for _Output file suffix_ or I make selection from `-ck` in input filed and somehow I delete it (backspace, delete, or any key that might delete selection) I get this popup/alert window.

That should show up after I leave the input field and it is left blank, not while I am editing it.

![image](https://f.cloud.github.com/assets/829963/2058881/f0b6d762-8b8a-11e3-8acd-7b1403ffb6db.png)

**Comment by newelement** [comment]
I brought this up in issue #49 .

**Comment by Andreyco** [comment]
Nothing on this? Why not show this alert after input loses focus and is left empty, then insert `-ck`?

**Comment by bdkjones** [comment]
Dude, calm down. On my list of things to fix before shipping, this is a little lower on the priority list. 

I am working until 3am every night just trying to get the app out the door at this point. I will get to this.

**Comment by Andreyco** [comment]
Was I offensive? Sorry then.

**Comment by bdkjones** [comment]
Version 2.1 removes this suffix requirement. Thanks!
