### ISSUE TITLE
baseFile is a required value.

### ISSUE THREAD

**Issue by shshaw** [bdkjones/CodeKit2#228]
Left my desk for a few minutes with CodeKit opened. No files should have changed, but when I got back, CodeKit was showing a "baseFile is a required value" error. I hit "OK" and the error came back up. Hit OK again and it took a while, but it came back and continues to come back. Compiling some code didn't change anything.

I have Chrome and Firefox both open on the Preview site. OS X 10.9.1

**Comment by bdkjones** [comment]
Hmm. You’ve got a corrupt data file. Quit the app and relaunch while holding shift. Let me know if you can reproduce this in the future.
