### ISSUE TITLE
Visual Bug: CK2 About Window

### ISSUE THREAD

**Issue by edwardsdesign** [bdkjones/CodeKit2#229]
The drop shadow flows under the library icons and text vs on top of it.

![ck2-b14-about window](https://f.cloud.github.com/assets/867897/2068617/11815246-8d0d-11e3-804f-b45ef472cef9.jpg)

**Comment by bdkjones** [comment]
Yep. This is because I don't use layer-backed views, since they increase the app's memory footprint by about 400-500%. Without that, I'm very limited in how I can draw "overlapping" views. It's a compromise for performance.
