### ISSUE TITLE
"This page has lost its connection..." visual is covered half way under WordPress admin bar

### ISSUE THREAD

**Issue by rpkoller** [bdkjones/CodeKit2#230]
![bildschirmfoto 2014-02-03 um 22 16 10](https://f.cloud.github.com/assets/1665422/2070245/f679a140-8d18-11e3-93d1-73542d18bf06.png)

just a cosmetical glitch (beta 14)

**Comment by rpkoller** [comment]
the wp-admin bar has a z-index of 99999 while the lost connection note only 9999

**Comment by bdkjones** [comment]
I added a few more 9's to the z-index. We'll see if that beats Wordpress (I'm not sure if browsers have an upper limit on the z-index property).

**Comment by rpkoller** [comment]
one stackoverflow thread lists: 

Browser         Max z-index value  When exceeded, value changes to:
Internet Explorer 6 2147483647  2147483647
Internet Explorer 7 2147483647  2147483647
Internet Explorer 8 2147483647  2147483647
Firefox 2           2147483647  _element disappears_
Firefox 3           2147483647  0
Safari 3            16777271    16777271
Safari 4            2147483647  2147483647
Chrome 29           2147483647  2147483647
Opera 9             2147483647  2147483647

still a bit room for a few more 9's ;)

**Comment by rpkoller** [comment]
Tried in beta 15 (also deleted caches in Chrome after first failure) but the lost connection notice still has a z-index of 9999 and is getting trumped by the 99999 of the wp-admin bar

![bildschirmfoto 2014-02-05 um 11 19 57](https://f.cloud.github.com/assets/1665422/2085977/50d367de-8e4f-11e3-9992-851287cfc485.png)
![bildschirmfoto 2014-02-05 um 11 22 41](https://f.cloud.github.com/assets/1665422/2085983/84cfd48c-8e4f-11e3-81c6-f2e571b7da0f.png)

**Comment by bdkjones** [comment]
Fixed in Beta 16.
