### ISSUE TITLE
Updating single assets from Bower

### ISSUE THREAD

**Issue by donaldallen** [bdkjones/CodeKit2#233]
I threw this together as an example. If there's an update, it's clearly defined. You click on the button, a menu appears that shows the version number and an update option. Right now it's pretty hard to tell what needs to be updated, and it would be nice if we could update individually.

This was probably already requested and you're probably already planning, but just throwing it out there. Thanks Bryan!

![update-available](https://f.cloud.github.com/assets/453784/2091403/18a4328a-8e9f-11e3-85a0-4c6d19160c0e.png)

**Comment by bdkjones** [comment]
Implemented, minus the fancy button, in 2.1. Thanks!
