### ISSUE TITLE
Libsass compiler - extra warning pop-up

### ISSUE THREAD

**Issue by maxlapides** [bdkjones/CodeKit2#235]
When I'm in the file view and select a Sass file, I now see a pop-up box when I check off "Use the libsass compiler" on the right (as noted in the changelog). However, when I uncheck this checkbox, I get the same warning message again.

One other little tiny thing (so small I didn't think it was worth opening a new issue) - the copyright in the About window says 2013 and, as much as I still can't believe it, it's 2014 :)

And on an unrelated note, I wanted to say how amazing CodeKit is. I've been using it for years now and it is seriously the best. I know this beta period has yielded a number of really challenging bugs, but I've been incredibly impressed with how quickly you resolved the issues and how much thought you put into coming up with ideal solutions. I was SO EXCITED to be a part of this beta (not exaggerating...I was waiting and waiting for you to announce more about CK2 and when you gave me access to this beta I was SO PUMPED to try it out). The latest version is really, really solid. I'm excited to see the reception to CK2 when you release it - I'm positive the Internet is gonna explode in awe. There are other pieces of software out there like CodeKit, but none that compare. Hell, there's not even anything out there that compares to CK1. I can't even begin to estimate the number of hours that CodeKit has saved me. Thank you so so much!

**Comment by C-Benz** [comment]
+1
Literally the first thing I do every morning is check this github project for updates. So stoked for CK2 to drop.

**Comment by bdkjones** [comment]
Fixed in Beta 16.

And thanks for the kind words! I think we're getting pretty close to an app I can actually ship.
