### ISSUE TITLE
Drag and drop folder from finder does not add new project

### ISSUE THREAD

**Issue by smlombardi** [bdkjones/CodeKit2#237]
I have the CK2 (b15) window open, and a finder window in column view.  I drag my new project folder onto the CK window and it just snaps back.  Does not add.

(Retina MBP, 10.9.1)

**Comment by guill3m** [comment]
It does for me. Either with actual projects or empty folders.

Finder with column view (both in the background with CK at the front, and Finder at the front and CK at the back).

CK2 b15
Retina MBP 1st gen
OS X 10.9.1

**Comment by rpkoller** [comment]
works here

b15 / 10.8.5 / mbp 13" early 2013

**Comment by smlombardi** [comment]
Wonder why it refuses here.  Perhaps Parallels "coherence" mode is interfering somehow.  I'll try it without Parallels running...

**Comment by bdkjones** [comment]
So where are we on this?

**Comment by smlombardi** [comment]
It works now, beta 16.  not sure what the story was.
