### ISSUE TITLE
'Copy' button doesn't work

### ISSUE THREAD

**Issue by jayfreestone** [bdkjones/CodeKit2#24]
This 'copy to clipboard' button doesn't do anything for me.

![clipboard](https://f.cloud.github.com/assets/3719745/1773816/8750b748-67ef-11e3-8d28-34dab08cd58e.jpg)

Doesn't apply to all of them.

**Comment by mdavis1982** [comment]
@jayfreestone This is definitely a bug - I've confirmed it locally. Could you also confirm that it's only the Bourbon Neat button that doesn't work please? The rest seem to for me.

**Comment by jayfreestone** [comment]
Yep, same, it's just the neat button.

**Comment by bdkjones** [comment]
The answer is: I'm an idiot. 
Fixed in the next release.
