### ISSUE TITLE
Image got removed from project on optimization (beta 15)

### ISSUE THREAD

**Issue by rpkoller** [bdkjones/CodeKit2#240]
I have two background images in my wp themes image folder: texturetastic_gray.png and  texturetastic_gray_@2X.png . I manually optimized the two, one after the other. with texturetastic_gray.png everything worked normally. but when i optimized texturetastic_gray_@2X.png it just disappeared out of my projects file view. Inside the folder it was still present. after a project refresh the file showed up again.when i retried to optimize the image it stayed inside the project file list and the  green check mark appeared. Tried on another file afterwards and the disappearing happened again (also a png file). :/ 

10.8.5 / beta15

**Comment by rpkoller** [comment]
happens too in beta 16. takes place on every try. but only on each first optimization. if you try a second time and do a rerun the image stays visible.

**Comment by rpkoller** [comment]
in the following example https://dl.dropboxusercontent.com/u/8578/disappear.mov the first image i optimize was already optimized before therefor it hasn't disappeared. but the second one is a first timer and it takes place again. after a reload it is reappears. 

on a side note i've started codekit with a pushed shift key to reset everything. so the video took place in a complete reseted state - but no change in behaviour.

**Comment by sethta** [comment]
I can confirm this behavior on Beta 17. Once optimized CK2 is treating the image as though it was deleted and a new one was added, meaning you can see the comparison between the initial and current file sizes.

**Comment by rpkoller** [comment]
@bdkjones ok same like with the .min issue i've reported. I've tried it in beta 18 again, out of curiosity since the other issue worked even i haven't found anything specifically related in the changelog but the file names don't get remove anymore from the file list. i've made a video illustrating as well as pointing to another minor glitch possibly related: 

https://dl.dropboxusercontent.com/u/8578/doubletimeimageoptim.mov

as you can see if i click optimize the first time, the filenames remain, but the checkmark appears only for a fraction of a second and disappears again you have to click a second time that it stays. i've packed together the small sample project you could try with:

https://dl.dropboxusercontent.com/u/8578/bkgrdCheck%20Double%20Time.zip

and @sethta is the confirmed issue also fixed for you in beta 18?

**Comment by JesusGarciaValadez** [comment]
I agree with that. Same problem since beta 17 and 18 with any image.
OS X 10.9.1

**Comment by bdkjones** [comment]
Fixed for Beta 19.

**Comment by rpkoller** [comment]
I can confirm. Works properly in beta 19
