### ISSUE TITLE
A Bourbon Neat Issue

### ISSUE THREAD

**Issue by bobrocke** [bdkjones/CodeKit2#241]
Neat is causing CodeKit to throw warnings:

DEPRECATION WARNING on line 6 of /Applications/Development/CodeKit 2.0b15.app/Contents/Resources/engines/neat/grid/_span-columns.scss:
Assigning to global variable "$parent-columns" by default is deprecated.
In future versions of Sass, this will create a new local variable.
If you want to assign to the global variable, use "$parent-columns: get-parent-columns($container-columns) !global" instead.

DEPRECATION WARNING on line 27 of /Applications/Development/CodeKit 2.0b15.app/Contents/Resources/engines/neat/grid/_private.scss:
Assigning to global variable "$parent-columns" by default is deprecated.
In future versions of Sass, this will create a new local variable.
If you want to assign to the global variable, use "$parent-columns: $grid-columns !global" instead.

It's not CodeKit's problem, but I'm not sure I should contact the Neat people with CodeKit2.0b15 in the strings. I suppose I can edit them out.

But have you heard anything from them? Or I should I just contact them (and edit the errors)?

Bob

**Comment by bdkjones** [comment]
Mentioned this in the changelog. Not a CodeKit problem; Bourbon needs to be updated to work with Sass 3.3.
