### ISSUE TITLE
Constantly compiling

### ISSUE THREAD

**Issue by jeremysexton** [bdkjones/CodeKit2#247]
Using Coda 2, working on with a relatively new Statamic install, using Bourbon and Neat, not compiling with libsass. Viewing the site on my iPad, as well as in Safari.

It's happened a few times where I work for a few minutes and then it starts compiling over and over with no stopping until I restart the server or open the project preferences.

Edit: Opening project preferences seems to have not actually made a difference. It's just restarting the server that for sure stops it.

**Comment by pixeljitsu** [comment]
This is happening to me also. 10.9, Local, Bourbon, Compass as plugin, Statamic also.

My project folder looks like this:

![codekit](https://f.cloud.github.com/assets/2178979/2140270/062fbf3e-934a-11e3-8e9e-39b28f502eb1.jpg)

I have the /assets folder compiling into /public_html/assets with whatever subdirectory is appropriate.
In my project config I have the website root path set to /public_html 

On any compile it will loop forever unless I restart the server.   This is also causing the browser to reload continually also.

**Comment by C-Benz** [comment]
Are you on Beta 16? I was getting this same issue with Bourbon and Neat but it seems to be fixed in Beta 16.

**Comment by jeremysexton** [comment]
Yep, I am for sure.

**Comment by pixeljitsu** [comment]
Yes.  I even tried moving all folders under public_html.

**Comment by bdkjones** [comment]
Okay, I need a demo project and a set of steps to recreate the issue. Please zip and attach a download link here.

**Comment by pixeljitsu** [comment]
Just sent you an email.

**Comment by jeremysexton** [comment]
Is pixeljitsu's project sufficient? Or do you need another?

**Comment by pixeljitsu** [comment]
I think I have this fixed by ignoring the "_" folders except for _content, _config, and _themes.  Try that and see if it still happens.

**Comment by jeremysexton** [comment]
That's working for me!

**Comment by bdkjones** [comment]
Please give me an exact list of the items you added to the Skipped Items list so that I can add this to the help page of the website.

**Comment by pixeljitsu** [comment]
Bryan,

I hid these folders:

_add-ons
_app
_cache
_logs

And left these unhidden:

_config
_content
_themes

I suspect that I only needed to hide _cache and _logs but the other folders
are just the cms system and don't really need to be worked in.

_config is needed for the subfolders fieldsets and users.

Thanks for making CK2 awesome!

Steve

**Comment by bdkjones** [comment]
Ok. I've set CodeKit to add _cache, cache, _logs, and logs to the Skipped Items list by default. Those of you in the beta will need to add those yourself in the "Edit Defaults For New Projects" section. Thanks.
