### ISSUE TITLE
Crash when compiling a Drupal theme that compiles on CodeKit 1.

### ISSUE THREAD

**Issue by jbloomfield** [bdkjones/CodeKit2#25]
Opened it for the first time and added a Drupal theme project that I have been working on for about 3 weeks with CodeKit 1. Tried to compile and got the following error.

![screen shot 2013-12-18 at 10 19 41 pm](https://f.cloud.github.com/assets/869070/1773832/d30fd25e-67ef-11e3-8a74-faaf98192653.png)

**Comment by jbloomfield** [comment]
It worked the second try.

**Comment by mdavis1982** [comment]
@jbloomfield Did anything change between tries?

**Comment by jbloomfield** [comment]
Actually, I take that back. Error code below:

Compass was unable to compile one or more files in the project: 

```
/Library/Ruby/Gems/2.0.0/gems/sass-3.3.0.alpha.141/lib/sass/script/literal.rb:7:in `<module:Script>': superclass mismatch for class Literal (TypeError)
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.3.0.alpha.141/lib/sass/script/literal.rb:1:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches/browser_support.rb:2:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:2:in `block in <top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:1:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:1:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions.rb:9:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass.rb:5:in `block in <top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass.rb:4:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/compass-0.12.2/lib/compass.rb:4:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:110:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:110:in `rescue in require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:35:in `require'
    from /Applications/CodeKit 2.app/Contents/Resources/engines/compass/bin/compass:32:in `block in <main>'
    from /Applications/CodeKit 2.app/Contents/Resources/engines/compass/bin/compass:20:in `fallback_load_path'
    from /Applications/CodeKit 2.app/Contents/Resources/engines/compass/bin/compass:31:in `<main>'
```

**Comment by bdkjones** [comment]
So CodeKit 2 currently has pre-release versions of both Sass and Compass in it. 

This may be related to that. If you can, try installing the pre-release versions of Sass/Compass at the command line using the `-pre` flag. Then try compiling the file at the command line. If the same error shows up, it's an issue with the beta versions of sass/compass.

**Comment by bdkjones** [comment]
Any result trying to compile these directly from the command line using the prerelease versions of sass/compass?

**Comment by jbloomfield** [comment]
Sorry for the delay.

I installed pre-releases of Sass & Compass (sass-3.3.0.rc.2 & compass-1.0.0.alpha.17) and did a "compass watch" on my project.

I got a bunch of DEPRECATION WARNINGs and an error as follows:

Errno::EACCES on line ["1143"] of /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb: Permission denied - /Library/Ruby/Gems/2.0.0/gems/compass-core-1.0.0.alpha.16/stylesheets/.listen_test

So, I guess it could be down to the pre-release versions.

**Comment by bdkjones** [comment]
Please upload the file causing the issue (and any files it imports) and post a link to that here so I can download and test with it.

**Comment by bdkjones** [comment]
I need the file that's causing the issue. Otherwise, I'll have to close this and move on.

**Comment by frankyonnetti** [comment]
Beta 6 has been working great so far for my Drupal projects. I am using my local version of non pre Compass and CK2's version of Sass.

**Comment by bdkjones** [comment]
Okay. In that case, I'm chalking this up to a Compass bug. Please file a report with the Compass team so they can get the problem fixed.
