### ISSUE TITLE
Questions about CK and Git...

### ISSUE THREAD

**Issue by thierrymichel** [bdkjones/CodeKit2#250]
Is Git only used with Zurb Foundation project ? Only for cloning the repo ?
In my case, it produces a nested repo…
So, asked differently, can I remove the .git folder created by CK ?

Thx

**Comment by bdkjones** [comment]
Ah. Excellent point. You can safely trash that .git folder; it's a byproduct of cloning Foundation's git repo. I'll update CodeKit to delete that folder automatically after the clone completes.

**Comment by bdkjones** [comment]
Wait. Actually, there's already code in the app to remove that folder. Do you see a message in the log telling you that CodeKit was unable to remove Git from the project folder?

**Comment by thierrymichel** [comment]
.git folder and .gitignore file are not removed by CodeKit.
No log at all…

Mac OS X Mavericks 10.9.1
CodeKit Beta 16

**Comment by bdkjones** [comment]
Okay. I'll update the app to nuke those items.

**Comment by bdkjones** [comment]
Fixed for Beta 17
