### ISSUE TITLE
Foundation with or without Compass : compiled but with warnings...

### ISSUE THREAD

**Issue by thierrymichel** [bdkjones/CodeKit2#252]
It's not a CodeKit issue but maybe you did not see it.

When creating a Foundation project WITHOUT Compass, app.scss compiles but there are warnings (log here : http://thi.me/TtSi).
Perhaps it comes from the 'foundation-libsass-package' ?

Just for information...

**Comment by pixeljitsu** [comment]
I switch to libsass and it stopped giving me the warnings.

**Comment by bdkjones** [comment]
Not a CodeKit issue. Foundation needs to be updated to be compatible with Sass 3.3 syntax.

**Comment by bdkjones** [comment]
libsass hasn't been updated to Sass 3.3 syntax yet, so it's unaware of the `!global` modifier and will actually choke if it you add it. It's an open issue on the libsass page.
