### ISSUE TITLE
project "choser" popup and selected project/checkbox

### ISSUE THREAD

**Issue by mgrn0** [bdkjones/CodeKit2#253]
Whenever I open the "project choser" popup I have a hard time to tell whether the current project is active or not - clicking the checkbox does not help, only selecting another project makes the current one more visible to recognize.

I made a quick screencast of the issue, I am using the latest beta
(the red rings visualize clicks with the left mouse button): 

http://dl.dropboxusercontent.com/u/81358/jing/ck-projects.mp4?dl=1

**Comment by bdkjones** [comment]
Do you have any accessibility features enabled in OS X? Here is what the popover SHOULD look like with a disabled project:

![screen shot 2014-02-13 at 16 56 50](https://f.cloud.github.com/assets/926566/2167157/f81c0036-9512-11e3-909e-5b53aa99d775.png)

Yours is not displaying the correct "empty" checkbox in a selected row.

**Comment by mgrn0** [comment]
it looks like your screenshot whenever I have clicked another project and then back on the disabled project. the project 'autoselected' when opening the popup however is undestinguishable. will check for accessability features and post about it.

**Comment by mgrn0** [comment]
you were right - turning off "full keyboard access" (or setting it for text boxes and lists only) in the accessability settings of OSX made the issue go away. 

![2014-02-14_09-16-23](https://f.cloud.github.com/assets/3019226/2169001/9b8dcf28-9550-11e3-8909-eb8e8af613fc.jpg)

maybe you could take a look at it, I don't know how many people use this feature actively, and if it would be able to fix?

**Comment by greystate** [comment]
FWIW I'd noticed the same issue but never attributed it to that setting. I use the keyboard extensively in all apps, so have always used this setting.

**Comment by mgrn0** [comment]
> I use the keyboard extensively in all apps, so have always used this setting.

me, too. This is the exact reason why I have activated this setting system wide.

**Comment by bdkjones** [comment]
Fixed in the next beta.

**Comment by mgrn0** [comment]
awesome, thanks a lot!
