### ISSUE TITLE
Can't open .zip file for Beta 17

### ISSUE THREAD

**Issue by peterhartree** [bdkjones/CodeKit2#254]
Hi Bryan,
I'm having trouble unzipping the latest Beta 17. Have tried The Unarchiver as well as OS X's default Archive Utility. This hasn't been a problem for me with the other betas - maybe it's something at your end? 

All the best,
P

**Comment by dcsturm** [comment]
No problem here! Did you re-download the file and try again?

**Comment by jonnitto** [comment]
I've also got no problems...

**Comment by peterhartree** [comment]
Okay - sorry for the hassle folks. I was downloading the .zip by pressing "raw" from Github. Downloading the entire repo as a .zip, then unzipping the zip within the repo - works as expected.
