### ISSUE TITLE
How do you "un-skip" a folder?

### ISSUE THREAD

**Issue by smlombardi** [bdkjones/CodeKit2#255]
If there's a folder I don't want to  be scanned, I found "skip this folder" context menu item.

But what if, at some point in the project, you need to get the folder watched by CK again (essentially, returning it to the way it was before you skipped it).

**Comment by bdkjones** [comment]
You remove the folder name from the Skipped Items list in Project Settings.

**Comment by smlombardi** [comment]
Damn it, I missed that completely.  Thanks.
