### ISSUE TITLE
Feature Request: Automatically return to back when compile without error

### ISSUE THREAD

**Issue by mkoistinen** [bdkjones/CodeKit2#258]
If CodeKit was brought to the front due to an error, return it to where it came from on next non-error compile.

If CK was moved or otherwise interacted with while it was the front window, then, probably should cancel the auto-return-to-back.

**Comment by bdkjones** [comment]
Can't. There is no way for me to order CodeKit's window to a specific place in the window hierarchy; the API does not exist. WindowServer (the daemon responsible for ordering and drawing windows) will only allow me to bring CodeKit to the front. It does not record the spot in the window order that the app left.

**Comment by mkoistinen** [comment]
I was afraid of that =/
