### ISSUE TITLE
Feature request: Hide old log entries

### ISSUE THREAD

**Issue by mkoistinen** [bdkjones/CodeKit2#259]
Does anyone need log entries for old compiles? I don't think I've ever gone back through old compile logs for any reason. If they're useful to some people, I don't want them to be gone entirely, but I do wish that the latest compile was shown at the top of the "log" and 95% of the real-estate wasn't used to show past logs.

**Comment by bdkjones** [comment]
Ok, I had officially closed feature requests to ship the app. But since you were one of the originals from before CodeKit 1.0 ever went public, I've added the ability to have the latest log entry shown at the top. It'll be a preference in the next Beta.

**Comment by zengabor** [comment]
Thank you, I will also use this preference

**Comment by mkoistinen** [comment]
Yay! Thanks again, Bryan!
