### ISSUE TITLE
Typo in Bower components warning dialog

### ISSUE THREAD

**Issue by noahfrederick** [bdkjones/CodeKit2#260]
There's a duplicated word in the popup warning when you switch to the Components tab of the Assets view (beta 17). Extra "the" highlighted below:

> This tab shows every component registered with Bower, but the names can be misleading because some entries are the **the** un-built, development source code for projects rather than the final, production release that you want. (The latter code is sometimes called a 'shim' repository and usually has a different name.) The Favorites tab already has the correct entries for the most popular components.

Also, you should remove the commas after "un-built" and "final". There's no need to separate the adjectives from the following descriptors "development" and "production" with punctuation since they are nouns.

**Comment by bdkjones** [comment]
Fixed for Beta 18.
