### ISSUE TITLE
Compiling CoffeeScript results in "empty" JavaScript file when "minify" is checked

### ISSUE THREAD

**Issue by jornki** [bdkjones/CodeKit2#262]
A simple project containing one html file and one CoffeeScript file. «Minify compiled JavaScript» is checked. When compiling the CoffeeScript file, a JavaScript file is produced in the correct location, however the only JavaScript code written to the file is the function wrapper.

Tested using both the internal CoffeeScript compiler and using the external compiler, same result, in CodeKit nothing but the function wrapper is written to the JavaScript file if the «Minify compiled JavaScript» box is checked.

Unchecking the «Minify compiled JavaScript» box fixes the issue.

![screen shot 2014-02-17 at 19 48 15](https://f.cloud.github.com/assets/1160870/2188352/4f438db8-9804-11e3-8c46-798e3215fbd2.png)
![screen shot 2014-02-17 at 19 48 22](https://f.cloud.github.com/assets/1160870/2188353/52acccb2-9804-11e3-9da6-9dfd973b6c74.png)

**Comment by bdkjones** [comment]
Have you changed any of the default options for Uglify.js?

**Comment by bdkjones** [comment]
Please post an example file I can debug with.

**Comment by jornki** [comment]
After having reinstalled CodeKit I cannot recreate this bug at all, weird. I'll reopen this issue if I ever manage to recreate it, but for now it looks like this wasn't a bug at all. Sorry about this.
