### ISSUE TITLE
Codekit stuck in loop when project has node modules and bower files

### ISSUE THREAD

**Issue by smlombardi** [bdkjones/CodeKit2#265]
I am working with a co-worker on a project, he does not have code kit.

I originally hid the folder his work was in: `/samples`. However, now I need to have CK place my compiled css into `/samples/css`.  So I went to project settings, "un-hid" the samples folder. Now codekit is refreshing for 10 minutes with no sign of finishing since he has these huge `node_modules` and `bower` folders.

Now, I know I can exclude them, but how -- the project file is endlessly refreshing and there's no way to get to project settings.

**Comment by smlombardi** [comment]
FWIW, to get out of this mess here's what I did:

1- open CK with shift down
2- drag the "samples" folder that contained the offending folders to desktop
3- added the root site folder to codekit, creating a project
4- went to project's settings and typed in `node_modules` and `bower_components` to exclusion list
5- dragged "samples" folder back to where it was in the Finder
6- refreshed codekit

now I am able to set the less file to compile to `/samples/css`

**Comment by bdkjones** [comment]
The way to do this would be to choose `File > Edit Defaults For New Projects` and then modify the GLOBAL skipped items list that is used for all new projects before adding your project to the app.

In CodeKit 1.0, that option was in the preferences window. In 2.0, it was relocated.
