### ISSUE TITLE
Markdown refresh but not compile

### ISSUE THREAD

**Issue by jeremysexton** [bdkjones/CodeKit2#266]
This may be a minor thing, or I may be overlooking it, but is there a way to have CK2 refresh the browser when a Markdown file is saved, but not compile it?

I mean, I know I could go to each individual file and untick the Output File box, but is there a way to set it for the whole project? Would be super handy for Statamic projects.

**Comment by bdkjones** [comment]
No. The fast way to do this is to select all Markdown files at once and then uncheck the output file box.
