### ISSUE TITLE
ui glitch: string got cut off in the preferences (beta 18 on 10.8.5)

### ISSUE THREAD

**Issue by rpkoller** [bdkjones/CodeKit2#267]
in the preferences the "when a file has syntax issues" got cut off at the end. 

![bildschirmfoto 2014-02-20 um 13 27 12](https://f.cloud.github.com/assets/1665422/2218219/814170fa-9a2a-11e3-9f9b-9e50ea1081ae.png)

**Comment by bdkjones** [comment]
Fixed in 19. I love easy bugs.
