### ISSUE TITLE
Internal server: Missing files gets status 200 instead of 404

### ISSUE THREAD

**Issue by rasmusbe** [bdkjones/CodeKit2#268]
Request to missing files getes invalid status header when using the internal server.

Screenshot from Chrome inspector:
https://www.dropbox.com/s/w3bqvy3ojg1rbwu/Screenshot%202014-02-20%2014.44.17.png

**Comment by bdkjones** [comment]
Details man! 

What kind of resource is it: image, html?

Internal server only or are you using an external server with this project. 

Demo project I can test with!

**Comment by rasmusbe** [comment]
Oh, sorry!

Its the internal server and every missing resource in any project since requests when file not found gets status 200 OK instead of 404 File not found.

A demo-project to prove when this can be problem:
https://www.dropbox.com/s/5tag3k6ycmyspbp/codekit%20demo.zip

Run it thru the internal server, a request for a missing file is made with javascript, but since the 404-page has incorrect response header the javascript thinks everything is fine.

**Comment by bdkjones** [comment]
Fixed for Beta 19. Good catch.

Also: Excellent demo project --- that's exactly what I need to work through these things quickly; a test case that clearly delineates success from failure. +2 internet points.
