### ISSUE TITLE
Odd issue with CK2 not auto-compiling a sass project

### ISSUE THREAD

**Issue by edwardsdesign** [bdkjones/CodeKit2#269]
I have a very simple sass project that CK2 will not compile automatically. I can manually compile the file from CK2 but that is it. None of my other sass projects have this odd behavior with CK2.

I have sent you the project via email.

**Comment by C-Benz** [comment]
Try refreshing that project in CK2. That fixed it for me.

**Comment by edwardsdesign** [comment]
No go.

I have tried launching CK2 while holding shift and adding the project as new, moving the project to another location, removing the project and deleting the Codekit file. None of those worked.

FYI: I have the same results with beta 17 and 18.

**Comment by bdkjones** [comment]
Works fine over here. I saved the sass file in sublime and codekit compiled it instantly. Try rebooting your Mac.
