### ISSUE TITLE
Project-Level Components Custom Output Directory

### ISSUE THREAD

**Issue by jayfreestone** [bdkjones/CodeKit2#27]
There should be a way to install components not in the root of the project but in another (specified) subdirectory.

The primary use for this off the top of my head is to install components into the WordPress theme directory instead of the root of the WordPress install (since making the theme the project root breaks asset URLs for the preview).

**Comment by mdavis1982** [comment]
@bdkjones I believe this can be achieved by using a `.bowerrc` per project which overrides the `directory` parameter. I :+1: this as it would be a really nice feature.

**Comment by bdkjones** [comment]
I definitely agree this would be a great feature. Bower is not very flexible, though. I'll look into it.

**Comment by mdavis1982** [comment]
@bdkjones I actually saw your tickets on the Bower repository the other day. It seems that the `.bowerrc` file cascades, so it may be that you can store a custom one in each project?

**Comment by rpkoller** [comment]
Would be a great addition!

**Comment by sathomas** [comment]
+1

**Comment by bdkjones** [comment]
Implemented in Beta 4. Found on the General project settings pane.
