### ISSUE TITLE
Not an issue, but what are people doing with hooks?

### ISSUE THREAD

**Issue by yratof** [bdkjones/CodeKit2#273]
It's been noted that Hooks were a highly requested feature, and that they hold the power of a thousand sands, but what are people actually using them for?

It'd be great if you could post some of your examples in here, for myself to get better equated with their power, and possibly for other beta testers that, like me, haven't really caught on to what they can do.

**Comment by devilskitchen** [comment]
Seconded!

**Comment by guill3m** [comment]
I've just set up one to dump all my assets when changing any JS file (I kept forgeting about doing this), something necessary in this Symfony 2 app, an AppleScript hocked to `inputFilename ends with .js`:

```
using terms from application "Terminal"
    tell application "Terminal"
        do script "app/console assets:install && app/console assetic:dump" in front window
    end tell
end using terms from
```

I know it won't be the best way to do this, not the most efficient for sure (is overkill to dump all the assets for just changes in one file), but it works for me at the moment and now I don't get angry that something doesn't work because I forgot to do this, I just need to remember to have Terminal open and logged into Vagrant, and I normally have that anyway.

**Comment by bdkjones** [comment]
Is it actually working reliably? 

Hooks are the one part of CodeKit 2 that I have done almost zero testing on. During development, I just used an AppleScript that told iTunes to play or pause. When I got that working:

![closeenough](https://f.cloud.github.com/assets/926566/2269042/c8ba3ed8-9ed2-11e3-85e1-7469e1309ea7.jpg)

**Comment by guill3m** [comment]
It's working great for me. I only use that one (actually, I've simplified the ApplesScript a little now, edited in the original comment with the new one, but the hook is the same) in two different projects and it works without problems. I've only been using it for two days, so I haven't done an intensive use of it yet.

The only problem I see is that `assets:install` and `assetic:dump` can take some seconds to compete so if you modify and save a JS file while this is still running (less than 5 seconds in one projects, about 10-15 in the bigger one), Terminal will just ignore it the second time. But I imagine this has nothing to do with CodeKit, more with the AppleScript, I could make it to work arround that but is not a really worth it for me at the moment, I prefer the simplicity here, I don't save _that_ fast normally.

Something that could be nice is if it had an option to **do a page refresh after a hook has finished, or after a definite period of time** (for cases like this one where the AppleScript will say it's finished but the Terminal is still running stuff, up to 15 seconds in one of my projects). Nothing really important, but it would make it even more awesome.

**Comment by jonnitto** [comment]
I use a hook for uploading the files after processing:

```
tell application "Transmit"
    set myFave to item 1 of (favorites whose name is "NameOfFavorite")
    set myRules to (skip rules whose name is "codekit")
    tell current tab of (make new document at end)
        connect to myFave
        change location of local browser to path "~/Codekit/Projekt"
        change location of remote browser to path "domains/domain/assets"
        synchronize local browser to remote browser using skip rules myRules
        close remote browser
        close
    end tell
end tell
```

Works great!

**Comment by jensimmons** [comment]
I can imagine a whole industry of productivity tools... Haven't saved a code file in 5 minutes? CodeKit asks you — "Hey. What are you doing? GET OFF FACEBOOK!!!!"

**Comment by bdkjones** [comment]
The following is a completely, 100% true story:

We debated adding ‘modes’ to CodeKit. 

“Friendly” mode would write success messages like, “Your file compiled! You’re so awesome!” Error messages would be the downy-soft kind: “Whoops! Looks like someone messed up.”

“Normal” mode would be what you see in CodeKit now.

“Negative Renforcement” mode would have seen error messages like, “Hey, dumbass, your file sucks.” and success messages like, “Oh good, it actually compiled this time. Here’s a cookie.”

And then there was “hardcore” mode. In hardcore mode, if your file produced an error, CodeKit would just quit with a sarcastic message like, “CodeKit is ashamed to be seen with you and will now quit.”

And finally, there was God mode, which could only be accessed after a streak in hardcore mode. In God Mode, if you compiled with an error, CodeKit deleted your file.

Of course, there were many warnings and “Are you absolutely sure you want CodeKit to be mean to you?” alerts along the way… but this was actually something we were tossing around.

**Comment by zengabor** [comment]
This is hilarious. Love the idea. However, isn't God mode supposed to mean the opposite? When you are invulnerable and can walk through walls?

**Comment by bdkjones** [comment]
Ha. Well, given that the guys on Hacker News couldn't figure out if my website testimonials are real or not, it's a good thing we didn't do this. The internet would have been filled with screenshots of my app being mean and people wouldn't know the context. That's why we didn't do it.

**Comment by NeosinneR** [comment]
How about paid upgrade for those modes?

**Comment by johnsardine** [comment]
I definitely support this one

> I can imagine a whole industry of productivity tools... Haven't saved a code file in 5 minutes? CodeKit asks you — "Hey. What are you doing? GET OFF FACEBOOK!!!!"

**Comment by GlynnJohnson** [comment]
I would love it if codekit blocked Facebook whenever I hadn't saved a file for 5 minutes! Oh well you can't be responsible for everybody's procrastination!

**Comment by jensimmons** [comment]
I was not thinking these are features Bryan should bake into CodeKit, I was thinking these are scripts _we_ all could write and share with each other. An open source CodeKit extension community... :P That is what the hooks are for, right?

**Comment by bdkjones** [comment]
I would love to put an example gallery of hooks on the website! If you write one, please share it with me!

**Comment by marcaube** [comment]
**To answer the OP**
I use a hook to generate our style guide every time a `.scss` is updated. It's just a simple bash script that calls [styledocco](http://jacobrask.github.io/styledocco/) with the proper args (input and output files).

**Comment by bdkjones** [comment]
Post an example with a short website-ready blurb describing it. I want to start a gallery!

-Bryan
