### ISSUE TITLE
Minor issue with no. of compiling files

### ISSUE THREAD

**Issue by jslaterTO** [bdkjones/CodeKit2#277]
If I select x Sass files (I assume this applies to anything else as well) and compile all, CK will say in the status bar at the bottom "compiling x files".  If I then choose another y files and compile them, the status bar will say "compiling y files" instead of "compiling x+y files".

**Comment by bdkjones** [comment]
Yea. Each group is dispatched separately. If the 2nd group finishes compiling before the 1st group, the bottom bar will go back to displaying the count of the first group.

This is a really bad idea. Hooks and browser refreshes are run at the end of each compiling group. Dispatching multiple groups simultaneously will lead to bad things.
