### ISSUE TITLE
Feature Request: re-order Projects in alphabetical order

### ISSUE THREAD

**Issue by BabylonSix** [bdkjones/CodeKit2#278]
I have a certain naming convention for all my projects parent folder names, and i have a lot of them, it would be awesome to organize everything in order. Dragging items around is great, but when you have like 30 folders you throw into CK2, it gets to be a bit too much.

Seems like an easy thing to do, and it would actually be pretty useful

**Comment by C-Benz** [comment]
+1

**Comment by bdkjones** [comment]
Keeping 30 projects in CodeKit at once is not a good idea. 

It's REALLY resource intensive to track that many files and relationships between them. Remove old projects you're not working on right this minute and add them back when you are. The settings are saved automatically in 2.0, so they come back exactly like you left them.

**Comment by bdkjones** [comment]
I really want to discourage the folks that add huge numbers of projects to the app. This is why I don't do things like folder groups for projects, etc. The fewer projects in the app, the faster it's going to be.
