### ISSUE TITLE
CK still creates /min/*-ck files although I thought I said no

### ISSUE THREAD

**Issue by smlombardi** [bdkjones/CodeKit2#279]
I am using CK2 solely for the LESS capabilities on this project.

So, I went to project settings and set check with nothing, do not minimize

![image](https://f.cloud.github.com/assets/835148/2283314/7b3aea24-9fbb-11e3-9df8-6390bb678f31.png)

However, whenever I update via SVN and someone has made a change to a JS file, Codekit re-creates min folders and puts *-ck.js files in them, which I then need to delete.

I  found I need to go into every folder where there are JS files, select the file(s) and un-check the box.  

![image](https://f.cloud.github.com/assets/835148/2283331/d96f0fa8-9fbb-11e3-93a0-46d2e6f67481.png)

Couldn't there (or isn't there) a way to just turn this off per project?

**Comment by Andreyco** [comment]
Happens to me as well after I re-import project.

**Comment by bdkjones** [comment]
Goddammit. Now I remember why I had the "none" option there. 

The quick way to do this is to simply add *.js to the Skipped Items list for this project.
