### ISSUE TITLE
Compass Process Error (Beta 19)

### ISSUE THREAD

**Issue by noelforte** [bdkjones/CodeKit2#281]
I tried installing Compass on a WordPress theme and got the following error. (See screenshot.)

![screen shot 2014-02-27 at 9 47 56 pm](https://f.cloud.github.com/assets/2560683/2290595/30c5558e-a023-11e3-9b4f-4d57128736d6.png)

**Comment by bdkjones** [comment]
Reboot your Mac.

**Comment by noelforte** [comment]
Nope. Didn't solve it. Still returning this. I tried shift-starting, and re-adding the project.
![screen shot 2014-02-28 at 10 51 38 pm](https://f.cloud.github.com/assets/2560683/2300505/3560af9e-a0f5-11e3-9ef4-81de7b679d5a.png)

**Comment by frankyonnetti** [comment]
Try using your local install of compass. You can set this from ck2's prefs. I think this is the path. 
/Volumes/DRIVENAME/Library/Ruby/Gems/2.0.0/gems/compass or it's in Volumes/usr/bin/compass
Sorry, I'm on my ipad right now and can't remember exactly.

**Comment by noelforte** [comment]
Hey, @frankyonnetti.
Using my local install of Compass works, however, I don't think that that should be **the** solution. We can't have every user of Codekit reprogram their app to use the local install.

Also, yes, I realize that Bryan is less than a week away from shipping CK2, so I wanted to make sure this got filed.

(@bdkjones If you need a test project, I'm using the same one that I sent you in issue #280. Can't wait to see CK2 go live! Very, very, very excited!)

**Comment by bdkjones** [comment]
Please repost the test project download link here.

Also, your locally-installed version of Compass: is it the 1.0-alpha version, or the current stable release, 0.12.x?

-Bryan

**Comment by frankyonnetti** [comment]
I believe this is an issue of combining the correct versions of ruby, sass and compass that work well together. This has been a slight pain in the ass for me ever since I updated to Mavericks.

**Comment by noelforte** [comment]
On second thought, a test project isn't needed, as Compass won't even install into an empty folder. By creating a new folder and clicking "New Compass Project", and installing the defaults, you get the above error message.

@bdkjones - My compass is 0.12.2, the current stable release.

I'm also running Mac OS X v10.9.2

**Comment by bdkjones** [comment]
Yea, I think this is just a bug in the pre-release of compass

**Comment by noelforte** [comment]
Right. So is this good enough to be closed, assuming that with the release of compass 1.0, things will be all good?

**Comment by bdkjones** [comment]
Oh, no, I see what's happening.

You're attempting to run Compass 1.0 alpha but you have Sass 3.2 installed. You need Sass 3.3+ to use Compass 1.0. Install the latest release candidate of Sass 3.3.

(You must have CodeKit switched to an external Sass compiler, because the app ships with Sass 3.3 bundled internally.)

**Comment by noelforte** [comment]
Follow-up: I ran `gem uninstall` and removed the versions of Sass and Compass that I had installed previously. I don't think I had switched compilers, so it's weird that Codekit was using 3.2 instead. Regardless, everything is working now. I may run a test to see if I can reproduce the issue again by installing Sass again.
