### ISSUE TITLE
FINAL CALL

### ISSUE THREAD

**Issue by bdkjones** [bdkjones/CodeKit2#282]
Well folks, it's time to expand the Beta to more people. And by that I mean... ship the app.

Tuesday is the day.

If you've got any last minute issues, please file them now. I'm essentially looking for stuff that's broken. Feature requests and minor edge-case stuff will have to wait until after the initial ship date. (These sorts of things always exist.)

Thanks for all your help!

**Comment by ChristiaanKZ** [comment]
Can't wait

**Comment by dcsturm** [comment]
Wow, I'm sorry for closing this - need more coffee.

**Comment by locii** [comment]
Codekit2 is awesome. Big thanks from me too. Can we line up to buy it somewhere?

**Comment by guill3m** [comment]
I agree, we need to be able line up to buy CodeKit 2, like when a new iPhone comes out.

**Comment by jonnitto** [comment]
I agree. Codekit2 is just awesome!

**Comment by Veraxus** [comment]
Where do I pitch my tent for said line?

**Comment by noelforte** [comment]
I second partaking in said tent pitching.

**Comment by guymeyer** [comment]
There's your tag line Bryan. "CodeKit, pitches tents like a 12 year old boy"

**Comment by coreyallen** [comment]
Dang! Now how will I feel like I'm a member of some secret society?  
Hey maybe start a codekit3 repo just so I can feel elitist?

**Comment by jensimmons** [comment]
Seems all good to go to me. 

The only problem I've ever had is that the CodeKit 2 trial keeps running out and I keep having to download new copies. :P And re-add my current projects to the list each time I've got fresh software. Today I accidentally obliterated my copy of CodeKit 1 in the process and had to redownload that too. _So_ much work! (lol). Releasing Codekit 2 and collecting our money will fix all this. 

Congrats!

**Comment by mgrn0** [comment]
jeah, excited for the countdown!!! congrats for the launch!!

**Comment by yratof** [comment]
Nice website

**Comment by devilskitchen** [comment]
Really hope the launch is going well! Nice to have CK2 licensed and running beautifully...

**Comment by mgrn0** [comment]
uhm, did anyone notice the following line in the release notes:

> "For every bug that shipped, I kill a beta tester."

Let's hope the app works flawlessly now :) -> I am confident it will!

**Comment by yratof** [comment]
haha, i saw that. It's true though. 

Anyone noticed you can't update the beta to the release?

**Comment by mkoistinen** [comment]
I had absolutely zero trouble doing so.

**Comment by yratof** [comment]
Hmm, I keep getting this:

**Comment by mgrn0** [comment]
I updated successfully a swell, the "final" build removed all my projects, though - but that was understandable..

**Comment by sathomas** [comment]
Hmmm...

![screen shot 2014-03-05 at 8 22 12 am](https://f.cloud.github.com/assets/1731910/2333332/4269b97a-a469-11e3-8f67-892f7d6b1277.png)

Seems to be persistent.

BTW, I don't mind paying the full price even as a beta tester, but I'm going to feel foolish if there's a discount or some such that I only hear about after paying

In any case, congrats. Superb tool.

**Comment by yratof** [comment]
If you bought CodeKit 1, you can get discount

**Comment by mkoistinen** [comment]
@sathomas I got a discount for being a CK 1 user, but I was delighted that I was able to pay more. It would be difficult for me to even estimate how much time CK saves me in my daily grind, so I didn't hesitate to pay the maximum I could.

**Comment by sathomas** [comment]
Nice, Saw the CK1 discount, took advantage (so I wouldn't feel foolish), and then added a bit extra for the worthwhile product.

**Comment by mgrn0** [comment]
> Nice, Saw the CK1 discount, took advantage (so I wouldn't feel foolish), and then added a bit extra > for the worthwhile product.

That is what I did as well. If the product would be, like 500 bucks a beta discount would have been nice. but at this price point CK is absolutely worth every dollar / euro multiplied a couple of times...

**Comment by ChristiaanKZ** [comment]
Did you trashed the beta first? If not trash the beta first and then download the final Version —

**Comment by mgrn0** [comment]
I updated directly from within the beta when I was prompted to... worked without a hitch, did not have to trash anything!

**Comment by ChristiaanKZ** [comment]
Had the same thing only thing worked for me was trash the beta version—

**Comment by BabylonSix** [comment]
Thank you for the early access, ability to test, and just an overall awesome App ^_^

**Comment by Chrisedmo** [comment]
Great to see the cat out of the bag! I've just purchased the upgrade.

However, I am unable to download the zip file - I keep getting network errors, so it bombs out when downloading. Never makes it to 100%. (Tried it numerous browsers - and other sites and downloads are working fine?)

**Comment by mgrn0** [comment]
Bryan put up a mirror at dropbox: https://t.co/5fuT6QK6Gp
