### ISSUE TITLE
Minor interface glitch: lost connection browser overlay adapts content of css

### ISSUE THREAD

**Issue by rpkoller** [bdkjones/CodeKit2#283]
i have a small test case i play around to see the resulting css https://dl.dropboxusercontent.com/u/8578/mscale.zip . there i ran into a minor glitch when i quit codekit while the project is active. somehow the overlay adapts the p:after css definitions from the project as you can see. all the shown values are modular scale ones

![bildschirmfoto 2014-02-28 um 11 00 40 2](https://f.cloud.github.com/assets/1665422/2292818/41f1e7f4-a060-11e3-9839-bc832bfb32ea.png)

happened on beta 19. before i haven't tried it on that particular case.

**Comment by bdkjones** [comment]
Well... yea. 

I mean, if you have a CSS rule on your page that adds content after every <p> tag, the <p> tag in that message is going to get the content as well. There's nothing I can do about that, unless I went through and added a `:none !important` rule for every possible style that could be applied to the box.

This is a pretty far-out edge case, though.

**Comment by rpkoller** [comment]
ahhhhh true. i haven't considered that. only saw the misbehaviour in the first place. but if i think about it again you are absolutely right. more than rare edge-case.
