### ISSUE TITLE
Autorefresh isn't working after OSX update...

### ISSUE THREAD

**Issue by Veraxus** [bdkjones/CodeKit2#284]
I just installed a major OSX Mavericks update (10.9.2), and now CSS auto-injection has stopped working (all browsers).

I had a similar problem once with the first CodeKit, and the problem was resolved by reinstalling OSX on top of itself (something weird must have gone wrong with OSX).

I suspect the problem is the same here unless everyone else starts reporting the same problem.

I never found out what the problem was. Does CK2 generate a log somewhere that might shed light on what is going on here? Since this is the second time this has happened I'd like to dig a little deeper into WHY this happens before I go straight to the "reinstall OSX" solution.

**Comment by Veraxus** [comment]
The original version of CodeKit appears to be working, however. Projects compiled with CodeKit 1 are correctly auto-refreshing Chrome and Safari.

Sidenote: I am **not** running both CK1 and CK2 simultaneously.

**Comment by Veraxus** [comment]
Nevermind. Seems to be a case of PEBCAK. I was doing things the old way... navigate directly to my vhost in the browser and expecting CK2 to automatically detect the URL (as entered in the project's External Server Address field) and refresh the window.

BUT... when I use CK2's preview button (as designed) everything works precisely as expected, auto-refresh, navigation, and all.

Blargh!

Recommendation: Add to the help text under the External Server project settings... "Note that you will still need to use the Preview button to get live browser updates." Because **_some**_ people are just oblivious dunder-heads. :-P

**Comment by bdkjones** [comment]
And the oscar for "Didn't watch the video everyone was supposed to watch" goes to...
