### ISSUE TITLE
Name Typo

### ISSUE THREAD

**Issue by achendrick** [bdkjones/CodeKit2#288]
So I'm pretty sure you typo'd my name here: http://d.pr/i/X4mn
Everybody knows I lowercase!

JK
Congrats on the launch Bryan, it's been fun to see the progress.
Oh, and thanks for the mention. (saw the hooks note too!)

**Comment by bdkjones** [comment]
It’s showing up as lowercase on my end. I dunno. Must be your ancient Macbook Air and its non-retina screen.
