### ISSUE TITLE
Coda 2 Open With Codekit... 

### ISSUE THREAD

**Issue by yratof** [bdkjones/CodeKit2#29]
I'm unsure how much this is related to CK2, but I thought i'd mention it on the off chance that it's related to a bug or issue.

Coda 2 cannot see the files that CodeKit makes when it compiles, unless you open the files with CodeKit THROUGH coda after adding a project.

@bdkjones explained that for CodeKit 1, which then kicks Coda2 to see the file changes & allows you to publish it etc.

Now with CodeKit 2, you cannot drag single files into a project to make coda see them, so going via the OPEN WITH > route on a file and selecting CodeKit 2 (which used to work with 1) now crashes Coda 2 like a car crash.

I don't know if this is because Coda2 hasn't been updated enough for them to fix it, or if CodeKit 2 uses a different way of seeing files and casts some form of spell on coda to put it to sleep.

**Comment by mdavis1982** [comment]
Could you record a short video demonstrating this behaviour please?

**Comment by yratof** [comment]
Sure thing: http://cl.ly/T18s

**Comment by mdavis1982** [comment]
I think that may be a Coda issue more than anything, but @bdkjones will know better than me. Thanks for the video!

**Comment by yratof** [comment]
Yeah I think it might be more to do with coda than codekit, but since it did work with codekit 1, I thought it might be worth mentioning in case.

However, let me check that it's not just local to coda, might be all programs, which then points to CodeKit...

**Comment by mdavis1982** [comment]
@yratof Let us know what you find :smile_cat:

**Comment by bdkjones** [comment]
I'm one of Panic's beta testers and have discussed this with the Coda team. While I can't talk about future updates to Coda, I can say that this issue will resolve itself soon.
