### ISSUE TITLE
JS File set to no output still creates file

### ISSUE THREAD

**Issue by rasmusbe** [bdkjones/CodeKit2#291]
Very small issue:
If I have disabled output file and then click the Process button it still creates a new file.

![screenshot 2014-03-05 15 55 13](https://f.cloud.github.com/assets/2124386/2334266/c8f68e70-a476-11e3-827a-ac39a735a90c.png)
![screenshot 2014-03-05 15 58 12](https://f.cloud.github.com/assets/2124386/2334267/cf550012-a476-11e3-918f-45a352d7afca.png)

**Comment by bdkjones** [comment]
Well… yea. That’s what the process button does. It’s meant to be an override. If you want to check the syntax, click the other button.

**Comment by rasmusbe** [comment]
Yes, but where should it output since no output is chosen?
I still thinks this is a small issue, but wouldn't it be more logical if process-button were disabled?
This prevents random files being created if I press Process by mistake.

**Comment by bdkjones** [comment]
Ah. I see the point. The output path is whatever it was last set to. I’ll take a look at it.
