### ISSUE TITLE
Codekit 2 overwrites Codekit 1, but not the icon...

### ISSUE THREAD

**Issue by yratof** [bdkjones/CodeKit2#296]
Dragged Codekit 2 to applications, due to the name being the same, it overwrote CK1, but kept the icon. I don't even know where that sits in terms of issues. Could be OSX being a massive dick. Most likely Is. But filed just incase...

![screen shot 2014-03-06 at 15 17 32](https://f.cloud.github.com/assets/1001935/2346490/9cc182a2-a542-11e3-9f1b-964731fcee9e.png)

**Comment by noelforte** [comment]
But CodeKit 2 is there in the dock next to CK1 in your screenshot...

**Comment by bdkjones** [comment]
Standard OS X behavior. To remove the old icon, drag it out the dock and hold it until the trash cloud appears above your mouse cursor. Let go.

**Comment by yratof** [comment]
That's a beta version, I'm not that silly

**Comment by bdkjones** [comment]
? 

Did you miss the launch? Better check http://incident57.com/codekit

**Comment by yratof** [comment]
Ok, this is getting out of hand now. Launch page is gorgeous, and i have got the latest full version. The icon was just being a dick yesterday, it's now showing right and has put me into a mood like no other. It's like i'm hungry, but only device browser refreshing will satisfy me...

&
