### ISSUE TITLE
Can't login to WordPress (Cookies not Enabled)

### ISSUE THREAD

**Issue by noelforte** [bdkjones/CodeKit2#297]
I'm getting this error message whenever I try to log into WordPress. Yes, I realize this issue has come up before. Is there any way to fix it, or there something I'm doing wrong?

![screen shot 2014-03-06 at 10 15 57 pm](https://f.cloud.github.com/assets/2560683/2353659/e5d6e720-a5a6-11e3-83e8-f216d36f5e38.png)

**Comment by bdkjones** [comment]
Are you running any browser plugins? 

Do the siteURL and siteRoot options in your Wordpress settings database _exactly_ match the external server address you entered into the project settings in CodeKit?

-Bryan

**Comment by noelforte** [comment]
I'm running MAMP on port 8888, and my WordPress install is located in a subfolder called "nf", so I set the server URL to http://localhost:8888/nf, and set my WordPress install URLs in siteURL and siteRoot to the same. The site works and loads correctly, and all the URLs and permalinks work. I just can't log in.

**Comment by bdkjones** [comment]
Set MAMP to host the wordpress install folder directly, then update your siteURL and siteRoot options to be: http://localhost:8888 and make sure that same address is what you enter in CodeKit project settings.

**Comment by noelforte** [comment]
But if I'm running multiple websites, I'll have to switch the root folder every time I want to switch projects, which will be a mild inconvenience.

**Comment by bdkjones** [comment]
Yea, but at this point I’m trying to debug the situation. This is the next step in that process. Let me know if it works.

**Comment by noelforte** [comment]
That works.

**Comment by bdkjones** [comment]
Okay. I’ll have to do some testing on my end and see what’s up. In the meantime, just set MAMP to host your folder directly.

**Comment by noelforte** [comment]
Kk. A temporary fix would be to host http://localhost:8888/as the root in codekit, then run the site out of a subfolder as such: `http://noelforte.local:5757/nf/`.

It's more of a convenience to be able to switch projects in codekit, and run them all as if they were root, directly at `http://noelforte.local:5757/`

**Comment by noelforte** [comment]
Any word on this issue?

**Comment by tomvdv** [comment]
Same issue here.

**Comment by Allgemeindesign** [comment]
Same issue here. Multiple WordPress installations in different MAMP subfolders and no access to WP backend. I now simply use the MAMP localhost URL to access the backend, because I don't need CodeKit browser refreshing there.

**Comment by noelforte** [comment]
I didn't think of that as a workaround, @Allgemeindesign! Thanks!

**Comment by danilowm** [comment]
Same issue here. anything new?

**Comment by josephhinson** [comment]
Same issue here.

**Comment by sethta** [comment]
I don't have this issue (but I did in the past), but I also have a setup where each site is added to it's own domain. I work on too many sites all at once that switching my directories repeatedly would really slow my workflow.

Here's the setup which I have using the free version of MAMP (but it's an older version at 2.2 - I haven't had the time to modify and test my conf file): https://github.com/bdkjones/codekit2/issues/144#issuecomment-32112372

Hopefully this may help with your issue.

**Comment by jjack1** [comment]
I have the same issue here with cookies not enabled but I'm running moodle not wordpress.

**Comment by jjack1** [comment]
My issue was a setting in moodle with cookie path set /mysite/ which of course will not work with new server Url, changed this to / and it works.

**Comment by landwire** [comment]
I have the same issue when working with multiple sites each in a subfolder in MAMP. So what is the best set-up to get this working? Using the wordpress install folder directly (as described above) works btw. But I really would like to use subfolders.

**Comment by bdkjones** [comment]
Well, the trouble on my end is that I don't do WordPress multi-site development, so I don't have a reliable way to test the situation and debug it. 

If anyone is willing to put together a detailed, exact set of steps for me to follow to create the environment that's not working, I can look into this issue.

**Comment by landwire** [comment]
So to be clear:
Problem is logging into Wordpress backend when done through the CodeKit preview button, results in the "cookie error". You can browse the site ok, but you cannot log in at all.

To test, it's quite simple:
1. Install MAMP (just MAMP not Pro) - no need to change any settings
2. create a few directories in 'htdocs' -> "site1.com", "site2.com", "site3.com"
3. install a wordpress site into each of those directories (or one should be enough really)
4. Browse site at "localhost:8888/site1.com" etc.
5. You can log in etc. no problems if you go through MAMP
6. Browse through CodeKit: you get the cookie error on trying to log in with all browsers -> not a Chrome only issue

It likely is enough if you just create one directory actually! Things should go "wrong" as soon as you are working within a directory and not in the root (htdocs).

In Wordpress "home" and "siteurl" are automatically set as: "http://localhost:8888/site1.com" etc for each site.

Once you change MAMP to host a folder/directory directly (as described by you above), then it works fine through CodeKit. However if working on 2-3 sites at the same time, that is not possible or convenient.

**Comment by landwire** [comment]
Another thing: If you log in through CodeKit (when MAMP is set to host the folder directly), the siteurl and home settings in Wordpress change automatically to the following: "http://localhost:5757". Not sure if that is relevant at all for the problem...

**Comment by dlosie** [comment]
Just thought I'd add that if you use the Non-Bonjour address this issue does not happen. Not sure if the problem might have something to do with that.

**Comment by landwire** [comment]
So was anyone able to reproduce the problem or has even come up with a solution? I did not think I was using a bonjour address, but then I am not sure what a bonjour address is...

**Comment by pandaguojian** [comment]
Guys, the solution that has worked for me is disabling the problematic plugins. 

First add this into your wp-config.php to show the error log:

# this goes into wp-config.php

define('WP_DEBUG', true);
define('WP_DEBUG_DISPLAY', true);

This will print some errors at the top of each page.

It will help you to identify the plugin that has issues. For me, it was an seo plugin.

I went into "Plugin" and then just renamed the plugin name, then it all worked. 

I don't know how to re-enable the plugin for this MAMP local site but at least this will allow you to get in WP first and investigate further.

**Comment by JayHoltslander** [comment]
Same issue. And none of the solutions in here worked for me.

**Comment by JayHoltslander** [comment]
Just arrived here via Google and was about to reply with "Same issue" but I see that I already have. :-P

**Comment by bdkjones** [comment]
This is the old CodeKit2 repo. This should no longer be an issue in 3.1

**Comment by Nugerama** [comment]
This issue persists for me, using 3.5.1. Can't log into my WordPress multisite using any of the CodeKit local URLs.
