### ISSUE TITLE
Setting SASS_PATH

### ISSUE THREAD

**Issue by yratof** [bdkjones/CodeKit2#298]
I've been getting a bunch of these bastard warnings:

`DEPRECATION WARNING: Importing from the current working directory will not be
automatic in future versions of Sass.  To avoid future errors, you can add it
to your environment explicitly by setting 'SASS_PATH=.', by using the -I command
line option, or by changing your Sass configuration options.`

Is there a way to set the sass_path through codekit? Documentation on 3.3 is poor, it's either you already know, or you'll figure it out on your own.

**Comment by bdkjones** [comment]
I'll take care of it.

**Comment by bdkjones** [comment]
Implemented in 2.0.1

**Comment by yratof** [comment]
Such a babe :)

Kind regards

Andrew

**Comment by metaskills** [comment]
How did you implement this in v2.0.1? Did we just set it in our current `$SHELL`? In a Mac OS X plist? HALP!

**Comment by metaskills** [comment]
@bdkjones Can you detail how `SASS_PATH` is used?

**Comment by bdkjones** [comment]
CodeKit does not set the SASS_PATH environment variable. It simply passes the path to the folder containing the file you're compiling with the `-I` flag.

**Comment by metaskills** [comment]
> CodeKit does not set the SASS_PATH environment variable.

Yea, setting it does not make sense. I was hoping that it read it, but wanted to confirm that and then how it used it afterward. I know libsass does yet support it but will likely soon. Ruby Sass in 3.3.0 does and encourages individual Sass gems/libs to add to it. Susy does this and I have recently made sure Bourbon and Breakpoint have done the same.  

> It simply passes the path to the folder containing the file you're compiling with the -I flag.

So it sounds like you are saying that it reads `SASS_PATH` and then passes it down to which ever compiler the user has configured using -I flags. Which is cool, and solves the issue with libsass not supporting `SASS_PATH` yet. However, I am still unclear how CodeKit reads the environment variable and from what locations?

Sorry for being a pest, but I really do want to understand this so I can leverage it.

**Comment by bdkjones** [comment]
CodeKit does not read the variable at all. The sass compiler does, however.

-Bryan
