### ISSUE TITLE
I can reload the spinning wheel animation

### ISSUE THREAD

**Issue by mdavis1982** [bdkjones/CodeKit2#3]
When the app initially launches, I can right-click on the spinning wheel animation and select "Reload" which reloads the animation. Not sure that this is a bug, but I would have expected that the animation would just be there once and that "reload" would actually apply to refreshing a project.

**Comment by bdkjones** [comment]
Good catch. Fixed.

Fun fact: you're looking at an HTML/CSS page on that splash screen. We have some fun things planned for that area moving forward.
