### ISSUE TITLE
When renaming a project the input box has white text

### ISSUE THREAD

**Issue by geebru** [bdkjones/CodeKit2#30]
http://cl.ly/image/403t2S3b2l42

Basically can't see what you're typing until you input the new name.

**Comment by rpkoller** [comment]
Same here. You can see the typo as long it is highlighted. As soon as you start typing you go blind - white on white.

**Comment by danielbaars** [comment]
Same here.

**Comment by bdkjones** [comment]
Fixed in Beta 4.
