### ISSUE TITLE
CSS Live Reload Issue (Node Does Not Exist - lpckrp.js)

### ISSUE THREAD

**Issue by sethta** [bdkjones/CodeKit2#301]
I'm not quite sure if this is something with my setup or not, but since the launch of the CK2 or since I updated to 10.9.2 (not sure as I did both on the same day), the live reload feature hasn't been working on CSS files after the second save.

OS: 10.9.2
Editor: Sublime Text 3
File Types: PHP (WordPress), Javascript, CSS (using Compass)
Server Setup: MAMP with multiple sites through custom VHOST files (Setup explained in #144)

When I load up a project, all is working well. When I do my first save of a CSS file, the reload feature works as intended. When I do my second save, it doesn't reload. I have to do a manual reload. The only error I can find is listed in the Chrome Console:

> Uncaught NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node. lpckrp.js:1
> i.ckrstyl lpckrp.js:1
> ckReload lpckrp.js:1
> n.onmessage lpckrp.js:1

I have also tried using Safari and receive a similar error:

> [Error] NotFoundError: DOM Exception 8: An attempt was made to reference a Node in a context where it does not exist. (lpckrp.js, line 1)

Any help would be appreciated. Let me know if you need more information.

Thanks!

**Comment by bdkjones** [comment]
Sounds like the markup of your page is screwed up. 

Codekit is attempting to insert a new `<link>` element into the `<head>` tag of the page. Verify that your HTML document is structured correctly and has no syntax errors.

**Comment by sethta** [comment]
Hmmm... I didn't think to check for that. It's been so long since I've ran my code through a validator (bad habit, I know).

It was definitely a problem with the code. I had a plugin that was appending the `<link>` to the bottom of the page. This happens occasionally in WordPress if a plugin is called after the `<head>` has been built.

My guess is that CK searches for the last `<link>` element and then appends it after, but inside the head. Considering my last `<link>` element was outside the head, this is probably where the problem came from. If I manually put the code within the `<head>`, then it all works well.

I'll just need to remember to keep an eye out for stray `<link>` elements while developing locally.

**Comment by bdkjones** [comment]
Yep. That's exactly what the app does --- search for the last `<link>` element and then append things next to it.

**Comment by ghost** [comment]
Same problem here.. Newest wordpress version seems to add an `<link>` element to the body when the editor is on the current page.

```
<link rel='stylesheet' id='editor-buttons-css'  href='http://dev.local:5757/wp/wp-includes/css/editor.min.css?ver=3.8.1' type='text/css' media='all' />
```

**Comment by bdkjones** [comment]
Wordpress is in the wrong and is violating the HTML5 spec. 

A `<link>` tag may only appear in `<body>` if the `rel` attribute is not used. See this statement from the HTML5 spec:

```
If the rel attribute is used, the element is restricted to the head element. 
When used with the itemprop attribute, the element can be used both 
in the head element and in the body of the page, 
subject to the constraints of the microdata model.
```

Link: http://www.w3.org/html/wg/drafts/html/master/document-metadata.html#the-link-element

If someone would care to tell Wordpress to get their shit together, that would be awesome. CodeKit looks at the value of the `rel` tag, so this issue should resolve when WordPress starts behaving correctly.

**Comment by maziarom** [comment]
Does anyone have any idea how to fix this issue until Wordpress does something about it?

**Comment by ghost** [comment]
Seems to be fixed in 3.9. 
If you still get this problem you are probably using the wp_editor() on an admin page which normally doesn't use the editor (in a plugin or so) so Wordpress just prints the css link in the body. 

To prevent this just enqueue 'editor-buttons' before using wp_editor().

**Comment by maziarom** [comment]
Thanks for finding the issue, it's probably a plugin then.

How do I "enqueue 'editor-buttons' before using wp_editor()" ?

Thank you

**Comment by maziarom** [comment]
I found the culprit plugin, it's:
WooCommerce Bulk Discount

I couldn't find "wp_editor()" anywhere in the php code for the plugin though. So I don't know exactly what it's doing that's breaking Live Reload.

**Comment by maziarom** [comment]
I have run into another WordPress plugin that is causing the same issue:
Gravity Forms Widget

**Comment by bdkjones** [comment]
Version 2.0.6 will tolerate `<link>` tags outside of the `<head>` element, even though it's a really, really bad idea.

**Comment by sethta** [comment]
@maziarom Gravity Forms is where I first found this issue. Currently, I drag my form widget to inactive widgets so it will keep my widget settings when I'm working locally. It's annoying, but at least it fixes the live reload.
