### ISSUE TITLE
Invalid font on swedish character

### ISSUE THREAD

**Issue by rasmusbe** [bdkjones/CodeKit2#302]
Very small issue, but the swedish character å gets invalid font properties.

![screenshot-2014-03-12-16 13 10](https://f.cloud.github.com/assets/2124386/2398832/66329a1c-a9f9-11e3-9f99-82ac7c1aa5a7.png)

**Comment by bdkjones** [comment]
Mother of God... I am going to murder my designer.

**Comment by guill3m** [comment]
I see this happens for the spanish `ñ` too, or for `é`, `ü`, and some more non-english characters. Didn't noticed before since I tend to avoid those characters in my files and folders.

My guess is that the font being used does not have those characters.

**Comment by bdkjones** [comment]
Yep. That's almost certainly the issue.

**Comment by guymeyer** [comment]
I just want to say Bryan and I just looked at this, he will not be murdering me and his response was "$&*@ me".

**Comment by bdkjones** [comment]
Fixed in 2.0.6. 

I will still be murdering @guymeyer.
