### ISSUE TITLE
Request: Multi-Markdown

### ISSUE THREAD

**Issue by bdkjones** [bdkjones/CodeKit2#304]
I"ve a suggestion for the Markdown compiler. Now you use a "normal' markdown compiler, maybe the Multi Markdown is a better one on github.
This version supports meta-data (so you can add f.e. css links)! Other MD apps like "the one" Marked from Brett Terpstra also use this compiler.

**Comment by feekApp** [comment]
Hi Bryan,
maybe a suggestion to my above mentioned request, you could implement an option to use your own compiler like you've done for several other languages. So one can choose the internal compiler of an other.

**Comment by bdkjones** [comment]
Implemented in 2.3.1
