### ISSUE TITLE
Don't get preview in wordpress site

### ISSUE THREAD

**Issue by smlombardi** [bdkjones/CodeKit2#31]
Here's what I do (as in CK1):

-- add my theme folder "mytheme" (in /wpcontent/themes/mytheme) to codekit
-- running my site on MAMP pro at the url "http://hith3" on the standard port
-- view site in browser
-- change my LESS file, it compile
-- nothing happens in the browser

I have gone to project settings and set the server to the mamp path

still nothing

![screen shot 2013-12-18 at 2 46 32 pm](https://f.cloud.github.com/assets/835148/1776920/2c9ce4b0-681d-11e3-8e82-38febc22c9f5.png)

**Comment by smlombardi** [comment]
Note:  I also tried entering http://charizard.local:5757 in the browser and get the external server error page

**Comment by mdavis1982** [comment]
@smlombardi Could you try this with an extension on your vhost please? So, something like `http://hith3.dev`. Thanks

**Comment by bdkjones** [comment]
Add the full wordpress site as a project, not just the theme folder. Then edit the project settings again and let me know what happens.

We definitely need to iron this out before I launch the thing; Wordpress is popular.

**Comment by mdavis1982** [comment]
@smlombardi Do you actually get any of the site output before you resave a file and it recompiles?

**Comment by donaldallen** [comment]
If you're running MAMP Pro and PHP 5.5, make sure you have OPCache disabled.

**Comment by sethta** [comment]
I remember with CK1, there was a limit to how many files I could have in CodeKit. I work with a lot of WordPress sites so I always just use the theme directories. Does CK2 have this same issue?

**Comment by smlombardi** [comment]
also, I use the theme directory only since it cluttered the project with files I am never touching

**Comment by smlombardi** [comment]
@mdavis1982 I tried running it as hith.dev, no change.

**Comment by donaldallen** [comment]
This works for me: dragging just the theme folder into CodeKit 2. Running MAMP Pro. My server address is set to http://enterprise.dev, server port 80 (that's in my MAMP setup). Going to my computername.local:5757 works.

**Comment by smlombardi** [comment]
@donaldallen I got it now.  
@mdavis1982 The combination of the .dev worked.  When I made the change and tested it, I forgot about always using the computername.local:5757.  I see that as being potentially confusing...

**Comment by sethta** [comment]
@donaldallen What does your wp-config file contain, because WordPress is pulling up the wrong paths for everything. I believe these lines are the issue with mine, but I haven't figured out a way to get them to display without pulling in the fill WP install.

```
// ===================
// Set Domain Settings
// ===================
define('WP_HOME',    'http://' .$_SERVER['SERVER_NAME']. '');
define('WP_SITEURL', 'http://' .$_SERVER['SERVER_NAME']. '');

// ========================
// Custom Content Directory
// ========================
define( 'WP_CONTENT_DIR', dirname( __FILE__ ) . '/content' );
define( 'WP_CONTENT_URL', 'http://' . $_SERVER['HTTP_HOST'] . '/content' );
```

**Comment by donaldallen** [comment]
@setha Yeah mine's pulling in wrong paths too. On first page load, all path's are correct. If I click a menu item and load a new page, the URLs revert back to my enterprise.dev, instead of the CK local.

**Comment by smlombardi** [comment]
I used the theme folder.  Note:  if you edit your url in Mamp pro, you need to fix the site url in 2 places in the wp_options table to point to new URL.  I did this in phpmyadmin.

**Comment by mdavis1982** [comment]
This isn't a CodeKit issue, but is a local configuration issue with WordPress. 

@bdkjones This issue seems to be cropping up quite a bit, but I don't think it's a CodeKit issue. Can we safely close this ticket?

**Comment by donaldallen** [comment]
@mdavis1982 Just to confirm, there's no way to use a custom domain like enterprise.dev with CodeKit 2? You have to use the localmachine.local:5757?

**Comment by smlombardi** [comment]
I think it can be closed.  I can work the way I did in CK1, drag the theme folder in.

HOWEVER site name should have an extension/domain, CK2 needs to be told what the url is, and we need to remember using the new CK url.

**Comment by smlombardi** [comment]
@donaldallen Apparently.  You can set up the custom domain, but can't use it in the browser.

**Comment by sethta** [comment]
I use MAMP (not Pro) with about 50 different custom vhosts. I also define my page urls through the config file instead of the DB. I also use a custom content directory, which is where some of the issues are coming from, so I guess I'll just have to play around with my WP settings until I figure out something that works. As @mdavis1982  just said, this is more of a local WordPress issue. I just need to rework my WordPress settings.

**Comment by mdavis1982** [comment]
I'm going to close this, but I absolutely agree with @bdkjones that this should be ironed out in some way before launch.
