### ISSUE TITLE
Wordpress Bloginfo name becomes server address

### ISSUE THREAD

**Issue by yratof** [bdkjones/CodeKit2#312]
This might be a rarity, but when using the CK2 external server with MAMP and wordpress, if the URL is the same as part of the website's name, then that part gets replaced with the codekit URL. 

It'll make more sense with these images.

Local:
![screen shot 2014-03-14 at 11 04 53](https://f.cloud.github.com/assets/1001935/2420028/f3304160-ab68-11e3-8a93-0b8aa5e1e40f.png)

IP:
![screen shot 2014-03-14 at 11 04 59](https://f.cloud.github.com/assets/1001935/2420030/f7737396-ab68-11e3-8a90-0b1a45a485bc.png)

BlogInfo Name:
![screen shot 2014-03-14 at 11 05 09](https://f.cloud.github.com/assets/1001935/2420038/02ec5760-ab69-11e3-9f9b-47de3df043fe.png)

General Settings:
![screen shot 2014-03-14 at 11 05 44](https://f.cloud.github.com/assets/1001935/2420046/264f43c0-ab69-11e3-9f90-5e6b036466d3.png)

Your Profile Page:
![screen shot 2014-03-14 at 11 05 55](https://f.cloud.github.com/assets/1001935/2420050/30b40936-ab69-11e3-81c3-dd0030dbff76.png)

MAMP Setting:
![screen shot 2014-03-14 at 11 15 03](https://f.cloud.github.com/assets/1001935/2420078/f8dc691c-ab69-11e3-8e03-02972924876b.png)

As you can see by the footer, it's replaced "green" in from the name "Team Green" to "Team 192.168.1.71:5757"

![screen shot 2014-03-14 at 11 15 46](https://f.cloud.github.com/assets/1001935/2420081/02d20d1e-ab6a-11e3-9bdd-53381de50eac.png)
### Software Details

Wordpress 3.8.1
Codekit 2 - 16844
OSX 10.9.2
MAMP PRO: 2.2 (Just purchased 3, but haven't updated yet)

**Comment by yratof** [comment]
Infact, any mention of "Green" through wordpress gets replaced, widgets, menus' etc. I imagine this is how you inject the url into the links, so perhaps this issue is something that cannot be avoided

**Comment by bdkjones** [comment]
Yea, but naming your site http://green is retarded. That's not a valid URL, can't work on the Internet and should really pop up a giant red flag saying, "name stuff correctly"

Your site url and local host should follow standard URL patterns. So, green.dev or green.something would be appropriate.

**Comment by yratof** [comment]
Never really thought about using .dev or .anything really before, codekit 2 was the first time i've encountered this kind of behaviour. 
But I'm glad I've seen what happens, and i'll suffix from now on. Cheers Bryan

**Comment by yratof** [comment]
I like to look back at this issue once in a while and laugh to myself

**Comment by bdkjones** [comment]
Ha, sorry about that. My responses can sometimes be a bit shorter and more sarcastic than they should be.
