### ISSUE TITLE
Autoprefixer not working in 2.01?

### ISSUE THREAD

**Issue by rpkoller** [bdkjones/CodeKit2#313]
So far i thought it is a save package. Using a compass mixin e.g.: 

```
@include background-image(linear-gradient(left top, rgba(75,80,86,1.0) 0%,rgba(26,24,30,1.0) 100%));
```

then autoprefixer is doing a recheck in postprocessing, adding and removing vendor prefixes necessary. Testing a page in ie 10 brought me onto this since no transparent linear gradient was shown at all there. Consulting the output css showed that the ms vendor prefix was missing. i thought maybe i am missing a switch in compass to set an experimental variable for ie. but then basically autoprefixer should add the missing ie string. i am using the default string shipped in codekit:

```
> 1%, last 2 versions, ff 17, opera 12.1
```

but i did a simple test with the above compass and autoprefixer settings:

```
.footinger {
    background: linear-gradient(left top, rgba(75,80,86,1.0) 0%,rgba(26,24,30,1.0) 100%);
}

.footerwrap {
    @include background-image(linear-gradient(left top, rgba(75,80,86,1.0) 0%,rgba(26,24,30,1.0) 100%));
}
```

the results:

```
.footinger {
  background: linear-gradient(left top, #4b5056 0%, #1a181e 100%); }

.footerwrap {
 background-image: -webkit-gradient(linear, 0% 0%, 100% 100%, color-stop(0%, #4b5056), color-stop(100%, #1a181e));
  background-image: -webkit-linear-gradient(left top, #4b5056 0%, #1a181e 100%);
  background-image: -moz-linear-gradient(left top, #4b5056 0%, #1a181e 100%);
  background-image: -o-linear-gradient(left top, #4b5056 0%, #1a181e 100%);
  background-image: linear-gradient(left top, #4b5056 0%, #1a181e 100%);
```

the class footinger where only autoprefixr gets applied shows no vendor prefixes at all. would have expected webkit, moz, o and ms. footerwrap is missing the ms one the rest is appended by compass i guess. 

running codekit 2.01 and compass 0.12.2

best regards ralf

**Comment by bdkjones** [comment]
As explained on the help pages, autoprefixer and bless do not currently work with compass. Support planned for the future. Please close.

**Comment by rpkoller** [comment]
ups sorry! missed that...
