### ISSUE TITLE
CodeKit 2 remembers where you were on previously visited pages

### ISSUE THREAD

**Issue by pierrepavlov** [bdkjones/CodeKit2#314]
Hi,
I've searched around the tracker but can't find anything about this.

To replicate you need a website with multiple pages and visit it through [user].local:5757.

Go to a sub-page of your website, scroll down a bit and click a link to another sub-page.

Now if you click Back in the browser you'll go back and the browser will position you at the place you were when you left that page, as it should.
But if you instead click a link that will take you to that same page you previously were on, it will also position you at the place you were when you left that page.

It seems like CodeKit 2 remembers where you were/how far you've scrolled on every page you previously visited.

I'm using CodeKit 2.0.1 (16844).

**Comment by bdkjones** [comment]
Yep. This is intentional.

CodeKit does this so that when a page is reloaded completely (in response to a change in the HTML), it can restore your previous scroll position. Otherwise, you'd have to scroll back to where you last were each time the page reloaded.

**Comment by pierrepavlov** [comment]
Kinda figured. Never really thought about it until I showed a client some progress through the [user].local:5757 and the sub-pages kept showing up half way down.

Lesson learned. Love the software btw!
