### ISSUE TITLE
Request: Support asset downloads while behind a proxy?

### ISSUE THREAD

**Issue by erikwoods** [bdkjones/CodeKit2#317]
I apologize if this has already been addressed. I have a feeling it might be a duplicate or related issue to #223 - I'm not sure. I have already searched through open and closed issues and I don't think I've found a solution yet.

I get the following errors when attempting to create a new Zurb Foundation project (see screenshot):
![screen shot 2014-03-19 at 11 07 35 am](https://f.cloud.github.com/assets/689000/2461618/bc490b6e-af78-11e3-9a06-567957a20845.png)

My company uses an https proxy and I suspect that that has something to do with it. Looking for someone to confirm my thoughts on this.

**Comment by bdkjones** [comment]
Well, the first thing to try is attempting to install Foundation without being behind the proxy. Let me know if that works.

Can you install other Bower components from the asset area?

**Comment by erikwoods** [comment]
Yep - everything works fine when I'm not behind the proxy. :/

**Comment by bdkjones** [comment]
Yea, in that case I don't think there's anything I can do here.

**Comment by erikwoods** [comment]
That's unfortunate - I was hoping to get more developers to try it out at QL. Now I can't really recommend that they do so, since they will all have the same issues in the office. I suspect that other companies may run in to the same issues and for that same reason, be unable to recommend that it be used to replace any existing process.

Is it for similar reasons noted in #223? I'm not asking to run browser refreshing through a proxy so I'm not sure if that's a different issue or not. As a front end developer (primarily), I don't know much about proxies or package managers or ruby - that's why I'm using CodeKit! I don't think it's too much to ask for this capability or at least an explanation on why you can't help.

I can understand the frustrations of supporting an application especially when you're dealing with users who don't understand a lot of important things behind your decisions... but if you find the time, please consider this request.

In the meantime, I will probably just use CodeKit for personal projects where I'm not behind a proxy. Thanks for your time.

**Comment by bdkjones** [comment]
Hi Erik,

I can't solve the problem because I have no idea what your proxy does or how its configured. Does Bower work if you try to install a component using the command line interface? I'm guessing that will fail with the same error. 

In that case, what I would recommend is contacting your network administrator and asking him to configure the proxy to allow Bower to function correctly. 

There simply isn't anything to fix on my end --- this is a network configuration issue at your company.

**Comment by erikwoods** [comment]
I have no issues using Bower via command line while behind the proxy. What can that information tell us?

**Comment by bdkjones** [comment]
Interesting. What exactly does your proxy do — reroute all HTTP traffic through HTTPS?

**Comment by erikwoods** [comment]
Good question. I'm not sure if I can obtain that info or not. I'll try to find out.
Also... your recent update to CK2 has resolved the issues I had with creating new Foundation projects. Not sure what you did, but it worked!

Now the only problem I have is installing assets... from assets.
