### ISSUE TITLE
Several issues: CSS auto-refresh not working, can't turn off growl notification

### ISSUE THREAD

**Issue by leongaban** [bdkjones/CodeKit2#319]
When I update basic SASS colors, it does not auto update in the browser. I have to refresh the page.

Also could not find the setting to turn off the growl notification, don't need to be alerted every time I save the SASS file.

Had to revert back to Codekit 1.9

**Comment by cdharrison** [comment]
@leongaban Did you hit Preview in the app?
![Preview](https://f.cloud.github.com/assets/210943/2463362/3e7bed2e-af8b-11e3-97a8-2dbe82c25169.png)

**Comment by leongaban** [comment]
Oh I just did, interesting, thanks... seems like it's running another version of my local server, it's nice, but I think the way the CodeKit 1.9 worked was better. No need for a different url...

Any tips on removing the growl notification for every change?

**Comment by bdkjones** [comment]
Notifications are controlled in OS X system preferences. Or Growl. Like EVERY OTHER APP on the system. 

The new browser refreshing behavior is here to stay. It's superior in every way. Watch the tutorial video on the website to see why.
