### ISSUE TITLE
Unable to Rename from Context Menu in Projects Dropdown

### ISSUE THREAD

**Issue by shshaw** [bdkjones/CodeKit2#32]
When selecting "Rename '{Project}'" from the context menu in the Projects dropdown, nothing happens.

**Context Menu:** http://cl.ly/image/052h3D173p0F
**After:** http://cl.ly/image/3c3m0G162v2U

A bit of unexpected behavior here as well when you select "Rename '{Project}'" from the main window, it opens the sidebar instead of having an inline text box like the Projects dropdown has.

**Context Menu:** http://cl.ly/image/2e2z1a1u2h3j
**Sidebar opens to edit title:** http://cl.ly/image/2K3Q0F283f09

**Comment by bdkjones** [comment]
Regarding the first issue: I can't reproduce this on my end. 

Regarding the second: Yep. That's needed for some technical reasons.
