### ISSUE TITLE
Request: Remember Last Project When Reopening

### ISSUE THREAD

**Issue by shshaw** [bdkjones/CodeKit2#324]
Minor annoyance, but whenever I restart my computer or reopen CodeKit, any browser tab pointing to the .local:5757 address no longer shows the last site I was working on; I have to select the project in CodeKit first.

It would be great if CodeKit would remember the last project I was working on, and start with that project selected.

**Comment by bdkjones** [comment]
It should and does on my computer. 

Are you quitting CodeKit normally, or letting Mac OS X force-quit the app when you restart your computer?

**Comment by shshaw** [comment]
I normally quit CodeKit via ⌘Q before restarting. Testing now quitting
CodeKit then reopening, the last project was selected. Next restart, I'll
double check what happens.

**Comment by shshaw** [comment]
Just tested and CodeKit remembered the last project open. I did quit CodeKit manually before restarting, so that may have something to do with it. If this Mac didn't take forever to reboot, I'd test again with having OS X quit it, but I'm gonna close the issue. Thanks!

**Comment by shshaw** [comment]
With the last shutdown, I didn't close out CodeKit 2 before OS X did and the last project setting wasn't remembered. Not a huge deal, but just following up to let you know!
