### ISSUE TITLE
Request: Support https for Bower git retrieval

### ISSUE THREAD

**Issue by mgeorgy** [bdkjones/CodeKit2#329]
For individuals behind corporate firewalls git ports maybe closed.  Support for https would make CodeKit much more useful to everyone affected by this situation.

REF: http://stackoverflow.com/questions/15669091/bower-install-using-only-https

Thanks

**Comment by bdkjones** [comment]
Implemented in 2.0.6.

See the "Tasks" menu for an option to switch Git to HTTPS
