### ISSUE TITLE
Importing files to a file with existing appends causes some weirdness

### ISSUE THREAD

**Issue by locii** [bdkjones/CodeKit2#330]
Hi,

Gush: I love Codekit.

Potential Bug report:
This has happened a few times now.

If I use the import function to a master .js file it works for the most part until I try to add a new file - usually after some period of time. or at least after Ive compiled the file with the existing file imports.

![screenshot_1286](https://cloud.githubusercontent.com/assets/799410/2677106/07439476-c14a-11e3-8005-5928e3ff01dd.png)

The template.js file originally has the 4 files you can see in the screenshot above but when I try to add a new file eg smoothscroll.js it goes into the list but then when I save template.js the newly added file does not get imported.

Then when I visit the file list again smoothscroll.js is not in the imported list but it's greyed out so I can't reimport or remove that file.

To add to the strange behaviour if I then remove one of the files from the list the file browser vanishes until I click on the app again. This is perhaps by design but feels a little odd.

If I restart then everything goes back to the normal level of Codekit awesomeness.

It may be just that the problem file is available but is just set to it's inactive state. I just tried to re-import the greyed out file after a restart and it worked.

Thanks!

**Comment by bdkjones** [comment]
Version 2.1.6 (which I hope to ship tomorrow night) addresses a bunch of issues with import links. It should resolve this.
