### ISSUE TITLE
Jade + Markdown

### ISSUE THREAD

**Issue by BabylonSix** [bdkjones/CodeKit2#331]
looking through the jade documentation online, using jade files with mixed in is supposed to be possible with a filter which looks like this:

![screenshot apr 13 02 46 42](https://cloud.githubusercontent.com/assets/829058/2689239/9962fa0c-c2f0-11e3-9199-57ecadf78847.png)

except when I try to do the same in codekit, I get an error suggesting I install something into the loader.
![screenshot apr 13 02 49 30](https://cloud.githubusercontent.com/assets/829058/2689242/fb53d3b2-c2f0-11e3-9e9b-59f778c38a6d.png)

It would be awesome if it just worked, after all -

![screenshot apr 13 02 44 15](https://cloud.githubusercontent.com/assets/829058/2689241/a2ff27d4-c2f0-11e3-923a-b59a850f0093.png)

**Comment by bdkjones** [comment]
Jade has "filters" to support lots of different languages. It would be virtually impossible for me to keep them all up to date and correct in the CodeKit bundle. 

So, to use external languages in Jade you need to install Jade at the command line and install whatever compilers are required to handle the filter you're trying to use. In this case, that would be a markdown compiler such as Discount (through NPM). 

Once you've got that installed, switch CodeKit to use the external Jade compiler in the Preferences area. Your filters will now work.
