### ISSUE TITLE
One project, two computers, not compiling on one

### ISSUE THREAD

**Issue by brandondurham** [bdkjones/CodeKit2#332]
I created a project on a work computer and it runs beautifully. I then drag that project's folder into CodeKit on my home computer and all seems to load just fine, but when I edit and save a JS or SASS file no compiling takes place at all. It's as iff CodeKit doesn't even know about it.

Any suggestions, or ideas around what might be happening?

**Comment by guymeyer** [comment]
Oh, I'll be Bryan for a second. :)

Is the project folder inside dropbox?

**Comment by brandondurham** [comment]
Uh oh. It is.

**Comment by guymeyer** [comment]
Naiiiiiiiled it. Bryan can go more in-depth on this, but if you take it out of dropbox it should work. If I recall correctly, the issue is on dropbox's end.

**Comment by brandondurham** [comment]
Ah. Yeah, can't do that. I develop entirely out of Dropbox.

**Comment by guymeyer** [comment]
I know, it's not ideal. Try pausing the sync while you work on it if you can.

**Comment by brandondurham** [comment]
Either way, thank you for the update!

**Comment by bdkjones** [comment]
Create a new folder on your desktop. Move the contents of the problematic folder into the new one. Delete the problematic folder under Dropbox. Move the new folder into place where the old one was and rename it appropriately. Should make it work, until the next time it stops working.
