### ISSUE TITLE
Request: alternate config.rb filename

### ISSUE THREAD

**Issue by erikwoods** [bdkjones/CodeKit2#333]
My apologies if this request is dumb or already made.

I see that there is an entry in config.codekit for config.rb and it specifies the path/filename.

I would like to have the ability to use a different filename for config.rb. If I try to rename it in config.codekit, it just re-writes it as config.rb after I restart codekit.

Use case:
I've got a team project I'm working on where not everyone on the team has CodeKit. We use compass via terminal, normally. This is fine for the most part... but I want to take advantage of CodeKit's auto-refreshing awesomeness.

It's complicated to explain, but the only way I can do that is if I have a different config.rb that's used by codekit while keeping the original config.rb intact (so that other team members can continue to do things the way they are already).

Thanks for your time.

**Comment by erikwoods** [comment]
I actually found a work-around that allows me to take advantage of CodeKit's auto-refreshing while still using the same config.rb that everyone else on my team uses. I just basically tell CodeKit to ignore all of my SCSS files and let <em>compass watch</em> via terminal handle changes. CodeKit still recognizes when there are new changes in the compiled output and will refresh my browser. Hooray!

It would still be nice to be able to specify a different config.rb, just in case... but for this specific problem I was having, I have an alternate solution just FYI.

**Comment by bdkjones** [comment]
Unfortunately, the name is a Compass convention; not a CodeKit one. I can't change it.
