### ISSUE TITLE
Codekit strips last 2 characters from Laravel output.

### ISSUE THREAD

**Issue by Andreyco** [bdkjones/CodeKit2#334]
Codekit strips last 2 characters from Laravel output.

**Most simple scenario to recreate the issue** is just a route, which returns short string. Expected output is just "abcdefgh".

```
Route::get('/', function()
{
    return 'abcdefgh';
});
```

**Actual CK output** - notice the empty first line which is prepended and uncomplete string which should be returned.

```

abcdef
```

Sample project here http://ck.andrejbadin.com/simple.zip

**Comment by bdkjones** [comment]
Which version of CodeKit are you running?

**Comment by Andreyco** [comment]
2.0, build 16377.

**Comment by bdkjones** [comment]
Yea. You're way out of date. Issue was fixed a long time ago.
