### ISSUE TITLE
Feature request : SFTP upload on change

### ISSUE THREAD

**Issue by potsky** [bdkjones/CodeKit2#337]
I use file monitoring in SFTP plugin of Sublime Text but sometimes it makes me crazy !

Given that CK already watch changed files and generates new one, it could be amazing if CK could be able to upload modified files on a server via SFTP.

**Comment by bdkjones** [comment]
There's a guy that wrote a Hook to do just this. I think it's in the issues section somewhere. That's what Hooks are designed for.

**Comment by potsky** [comment]
Nice, this is in issue #273 with Transmit. I will perhaps find a reason to buy Transmit now !

Thank you !
