### ISSUE TITLE
Feature request: Update bower.json

### ISSUE THREAD

**Issue by maikschneider** [bdkjones/CodeKit2#338]
It would be nice if CodeKit could update the bower.json. I'm missing the installed assets as dependancies in the created package config file.

**Comment by tingletech** [comment]
+1; see also https://github.com/bdkjones/codekit2/issues/112

There is someone on a project I'm working on who is planning to use code kit for sass etc; but I want to be able to build the site myself w/o code kit but he says there is no bower.json

**Comment by adyz** [comment]
This would be a great feature. 

I use a manual setup for a project and everything works great on codekit too, but if I install another bower component from codekit, the other devs will not see the new dependency and install the same version as mine.

**Comment by christianseel** [comment]
+1 Would be a really nice feature!

**Comment by guategeek** [comment]
+1 to this as well

**Comment by nick-lehmann** [comment]
+1 because then you could add the `bower_components`folder to the .gitignore and just push your `bower.json`to the server. Would be way more efficient and convenient...

**Comment by calvinjuarez** [comment]
+1

If CodeKit updated the _bower.json_, I'd totally use CodeKit for including components.

**Comment by bdkjones** [comment]
Implemented in 2.3.1.
