### ISSUE TITLE
"Failed to switch compilers" Error

### ISSUE THREAD

**Issue by vacquah** [bdkjones/CodeKit2#339]
I am looking to switch the complier to a system version at /usr/local/rvm/rubies/ruby-2.1.1/bin/  - for scss and compass.  I am using dvm installed in use/local to manage my gems.  I get the following message : 

CodeKit could not switch to the specified external Compass compiler. Make sure that the app is idle and that you are selecting an appropriate executable file, then try again.

Been at this for awhile and need help to troubleshoot.

**Comment by bdkjones** [comment]
If you read the note on the preferences screen where you switch compilers (or in the “external compilers” section of the help page on the website), you’ll note that RVM is NOT compatible with CodeKit. You need to install your gems in the standard system location (tell RVM to use system).
