### ISSUE TITLE
Pop up opens no matter what in Javascript Project Setting

### ISSUE THREAD

**Issue by JesusGarciaValadez** [bdkjones/CodeKit2#34]
The pop up with explication of how to write the output path for javascript preferences is always show it, no matter what I do. 

Even if dismiss it with the "Done" button or click on another textfield. 

![captura de pantalla 2013-12-18 a la s 14 34 21](https://f.cloud.github.com/assets/1066733/1777313/ce13aa08-6823-11e3-8217-5aded7163eec.png)

**Comment by mdavis1982** [comment]
I don't get the sticky behaviour. But what I do see is that clicking to get the initial popup in the field, and then pressing tab to go to the next field results in 2 tooltips:

![screen shot 2013-12-18 at 20 38 42](https://f.cloud.github.com/assets/199807/1777361/852ba1fa-6824-11e3-9a6f-6640fbe1f0d8.png)

**Comment by greystate** [comment]
I'm seeing this too - for CoffeeScript CSS and Kit files - often times it's impossible to change the setting.

**Comment by bdkjones** [comment]
which version of OS X are you running? Does the popover show when you select the "javascript" category from the left-hand list, or does it only show once you click on the textfield in the output path area?

**Comment by JesusGarciaValadez** [comment]
I have 10.9.1 and work with Coda 2.0.12. 

This happens when I try to change the path clicking on textfield. This also happens with Coffescript and some times with Stylus, but when at last write some path (even with /) this wild behavior doesn't happen again. Weird isn't?

**Comment by JesusGarciaValadez** [comment]
I take it back, after a while reappears the same error. This time in Jade file settings.

**Comment by bdkjones** [comment]
The popover should always show when you select the textfield. It should go away when you de-select the textfield. Is this what you're seeing?

**Comment by JesusGarciaValadez** [comment]
No, always is showing. No matter if you click on another option or if you try to write something on the own textfield. 

The popover interrupts everything what you try to do. Only with very much try of select another language setting is when could disappear. But, in some languages still showing like javascript, coffescript or typescript. It doesn't matter.

Even, in very few cases it possible to see two popovers overlapping.

**Comment by bdkjones** [comment]
Ok, I've been able to reproduce the issue on my end. Looking into it.

**Comment by bdkjones** [comment]
_Sigh_ Yet another thing Apple broke in 10.9. And their damn NSPopover class is completely opaque so I can't do anything with it. Going to have to move the popovers to help buttons.

**Comment by bdkjones** [comment]
Fixed in Beta 4.
