### ISSUE TITLE
Auto compile is not working

### ISSUE THREAD

**Issue by 7vs** [bdkjones/CodeKit2#342]
I've bought the application, and I don't know if it is an update problem.
It's driving me nuts 'cos I can not find what is wrong, but some day codekit stop to auto compile my less files and I can't find the error...?

**Comment by guymeyer** [comment]
Is the project in dropbox?

**Comment by 7vs** [comment]
No it isn't

**Comment by bdkjones** [comment]
Are you saving a Less file that is imported into another Less file? If so, select the Less file that does the importing in CodeKit and look at the "linked files" pane of the right-hand inspector. Do you see your imported files listed there?

Is the problem limited to one specific project, or are all of your projects affected? If limited to one project, try these steps: http://feedback.livereload.com/knowledgebase/articles/86239-os-x-fsevents-bug-may-prevent-monitoring-of-certai

**Comment by 7vs** [comment]
I'm still having the problem. I've tried with another project, and even in another computer. Issue remains. Any advice?

**Comment by bdkjones** [comment]
Please zip the entire project showing the issue and post a download link here. Indicate which file you're working on that's not compiling when saved.

Have you tried a different text editor?

**Comment by 7vs** [comment]
I don't understand why it's not working.
I've created a new project of a simple email in html and sass and it worked fine.
Then started another one and stop working. i don't get it. Looking and looking for an answer and i can not find a response. It must be simply.
Nothing is on Dropbox.

**Comment by bdkjones** [comment]
I need details to help you. What text editor? What version of OS X? What steps have you tried from the link above? Are you sure your markup is error-free? Do you have a proper `<head>` element in the page?
