### ISSUE TITLE
Bugs in "Initial output path"

### ISSUE THREAD

**Issue by Martinomagnifico** [bdkjones/CodeKit2#348]
Hi Bryan,

I have two issues with the "Initial output path" area in the languages section. (Haven't ried all languages, but the ones I use have this behavior).
• Typing in "By replacing..." will clear the typed text after a second or two. I can get around it by typing fast and hitting return. But it seems a bug to me. It might be similar to #78 . 
• The replacement has trouble going a level up. For example, in my project I have SOURCE and BUILD. In the SOURCE I have a folder HTML (in which I have the final Jade files), but I want them to be generated in the root of BUILD. One level up in the build directory in the project. So when I have:

By replacing all...
[SOURCE/HTML]

With this one:
[BUILD]

it tries to generate this: (visible in files/Output file)
/BUILD/index.jade/index.html 

Which doesn't really work. 

When I look at the Config file, I can see it has indeed applied the wrong path:

"\/SOURCE\/HTML\/index.jade": {
        "compileDebug": 1,
        "fileType": 512,
        "ignore": 0,
        "ignoreWasSetByUser": 0,
        "inputAbbreviatedPath": "\/SOURCE\/HTML\/index.jade",
        "outputAbbreviatedPath": "\/BUILD\/index.jade\/index.html",
        "outputPathIsOutsideProject": 0,
        "outputPathIsSetByUser": 1,
        "outputStyle": 0
        },

Can this be fixed easily? Thanks!

**Comment by Martinomagnifico** [comment]
Anyone else have any of these 2 issues?

**Comment by bdkjones** [comment]
If you have a file at this path:

`source/html/file.jade`

and you want it to output here:

`build/file.html`

And `source` and `build` are both sibling folders at the root of the project, then the correct way to do that would be to set Jade's initial output path as follows:

![screen shot 2014-06-17 at 10 57 58](https://cloud.githubusercontent.com/assets/926566/3304284/fbb456fc-f648-11e3-9eb1-d0d748d8b1da.png)

The "clears text after a few seconds" thing is definitely a bug. I'll look into that. You can get around it by simply waiting for the app to clear the field once and then typing after that.

**Comment by bdkjones** [comment]
This was fixed quite a few versions ago now, so closing. Thanks.

**Comment by Martinomagnifico** [comment]
Thanks!!!!

Martijn
