### ISSUE TITLE
Crash in Syntax Checkers settings view

### ISSUE THREAD

**Issue by noahfrederick** [bdkjones/CodeKit2#35]
CodeKit crashes whenever I try to change syntax checker settings.

To reproduce:
1. Go to **Edit Defaults for New Projects**
2. Go to any of the **Syntax Checkers** sections
3. Check or uncheck any checkbox

CodeKit crashes immediately without saving the new state of the checkbox.

The Uglifier.js settings do _not_ exhibit this behavior.

(I can't test this on the settings for an individual project because I'm getting a crash when trying to add a project as described in #10.)

I'm running OS X 10.9. I can provide the crash reporter log if needed.

**Comment by mdavis1982** [comment]
@bdkjones This also happens for me. I'm also on Mavericks.

**Comment by bdkjones** [comment]
I've replicated the issue on my end and am working on a fix.

**Comment by rpkoller** [comment]
Crashes on 10.8 too. I could send a crashlog too if necessary or take a sample.

**Comment by bdkjones** [comment]
Fixed in next release. It's like I didn't even test anything when I wrote it. Embarrassing.
