### ISSUE TITLE
Implement generic file handlers

### ISSUE THREAD

**Issue by rotx** [bdkjones/CodeKit2#350]
I would like the option of having CodeKit call external (shell) scripts based on file extensions that it currently doesn't handle. For some file types, I would rather call an external tool instead of the built-in version.
For some languages there are already configurable options, but I am proposing a more generic system.
Since CodeKit is already watching the file system for changes, this would simplify life™.

Examples:
- The built-in JPEG stripper removes everything, including the Copyright notice. I would like to instead call exiftool (with parameters "-all= --iptc:all -IPTCDigest="). Also, the built-in JPEG stripper doesn't run automagically and overwrites the original. Plus, I could use all kinds of other tools to auto-generate thumbnails based on a source image, for example.
- The Kit compiler is great, but currently doesn't implement conditionals. Since it's open source I would like to modify it and use my own version. To do this, I need to be able to use an external script for ".kit". This would in general also apply to "beta" versions of any built-in language.
- I understand that HTML minifiers are iffy, but if I could call a script to do this then any problems would be my fault and not CodeKit's.
- Other classes of files (such as .psd) aren't currently handled at all, but would benefit from CodeKit's automation and browser refreshing capabilities.

*\* Thanks **

**Comment by bdkjones** [comment]
Add the file extensions for unsupported files to the "generic page extensions" list under the "General" section of project settings. Then, use Hooks to run shell scripts when those files change.
