### ISSUE TITLE
external server address substitution in sending mail

### ISSUE THREAD

**Issue by pdesterlich** [bdkjones/CodeKit2#354]
I have a very strange behaviour with my current php project and i've tracked it down to what appears to be a codekit "issue" (don't know if bug or normal behaviour).

i have a simple function that returns current server address

``` php
public function siteUrl()
{
    $protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off' || $_SERVER['SERVER_PORT'] == 443) ? "https://" : "http://";
    $domainName = $_SERVER['HTTP_HOST'].'/';
    return $protocol.$domainName;
}
```

which return the correct url both when in production (https://www.real_server_address.com/) and when developing on my machine (http://my_computer_name.local:5757/)

then i compose the body of an email message, with current server address in it, and i send the mail with swiftmailer using an external smtp server.

from my local machine, before sending the message correctly state http://my_computer_name.local:5757/ as site url, but in the received mail the url is replaced by the external server address configured in codekit for the project (https://www.local_server_address.dev/ - served by mamp).

This is not a blocking issue (i just need to manually change the url and it's only for developing purpose) but i don't understand why it behave this way

**Comment by bdkjones** [comment]
Because swiftmail is running on MAMP. It knows absolutely nothing about CodeKit's proxy server. When your PHP script fires, it's running on the Apache server inside MAMP; not on CodeKit's server.

**Comment by pdesterlich** [comment]
You're absolutely right, but ... why should swiftmail replace some text **inside** the body of the message? i'm not speaking about message's headers, i put an url in message's body and the url is changed on the mail i receive, and the only piece of software who knows both urls is codekit ...
anyway, this does seem strange to me, so i'm going to investigate further, eventually removing swiftmailer to see if something change

**Comment by pdesterlich** [comment]
made a test, here's the simple code to replicate:

``` php
<?php
  // test.php
  function siteUrl()
  {
    $protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off' || $_SERVER['SERVER_PORT'] == 443) ? "https://" : "http://";
    $domainName = $_SERVER['HTTP_HOST'].'/';
    return $protocol.$domainName;
  }

  echo siteUrl() . "<br>\n";

  $body = "hi, my name is mrPhelz and i'm writing you from " . siteUrl();

  echo $body . "<br>\n";

  $to = "name@example.com";

  mail($to, "let see how it works", $body);

  echo "message sent<br>\n";
?>
```

obviously change the $to = "..." to your email

this is what i get on screen:

```
https://macbookpro.local:5757/
hi, my name is mrPhelz and i'm writing you from https://macbookpro.local:5757/
message sent
```

https://macbookpro.local:5757/ is codekit address

and this is the text of the mail i receive

```
hi, my name is mrPhelz and i'm writing you from https://helpdesk.elcosistemi.dev/
```

https://helpdesk.elcosistemi.dev/ is mamp "real" address

result is: the text is replaced inside message body, and the only software who knows both https://macbookpro.local:5757/ and https://helpdesk.elcosistemi.dev/ is codekit (which act as a proxy).
there is no reason for php to replace a text inside a message body (as there is no reason for swiftmailer or even for mamp), so all i can think is that codekit for some reason does the replacement at some proxy level, even if i don't understand where (it's beyond my comprension) or why

**Comment by pdesterlich** [comment]
Same thing happens when i use a vagrant box with nginx instead of Mamp.
Text replacement happens only inside body of sent mail, very strange

**Comment by pdesterlich** [comment]
ok, my fault ... i've managed to understand where the problem is.
when i read (in php) the current domain, the function returns what is configured in MAMP, then (i assume) CodeKit translate it back to it's own domain (machinename.local:5757).
The mail message is sent directly from apache / php server, so it does not get the translation to codekit domain.
I was fooled by the fact that on the screen i saw the correct domain (codekit) and didn't understood why there was the "replacement".
