### ISSUE TITLE
Auto-refresh fails with insert node when link tag is self-closed

### ISSUE THREAD

**Issue by codebryo** [bdkjones/CodeKit2#356]
I saw there was an issue regarding this topic which helped to narrow down the problem. 
The CSS Autorefresh won't work when the last link tag is closed with /
So for example I have in my head

```
<link rel="stylesheet" href="/assets/website/css/website.css" />
```

I get the Error Message that there is no node to attach the new css to.
It would work for

```
<link rel="stylesheet" href="/assets/website/css/website.css">
```

though. I know that closing the link tags isn't very pretty. But thats the result when a link tag gets created using Slim. 
To complete the example:

```
link href='/assets/website/css/website.css' rel="stylesheet" type="text/css"
```

Hopefully this is easy to fix as it kind of breaks the codekit workflow of using slim and sass. Great work though. Love Codekit! <3

**Comment by bdkjones** [comment]
Is the link tag in question outside of the <head> element on the page?

**Comment by codebryo** [comment]
Nope is in the head. It’s all valid Markup.

2014-05-27 22:12 GMT+02:00 Bryan Jones notifications@github.com:

> Is the link tag in question outside of the <head> element on the page?
>

**Comment by bdkjones** [comment]
Show me the complete page source.

**Comment by codebryo** [comment]
Slim Code: 

```
doctype html
html lang="en"
  head
    meta charset='UTF8'
    link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700' rel='stylesheet' type='text/css'
    link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,200italic,400italic,600,600italic' rel='stylesheet' type='text/css'

    link rel="stylesheet"  type="text/css" href="/assets/website/css/website.css"

  body
    div.docsWrapper.wrapper
      h1.docsTitle Test - Website
      h2.docsSubtitle Living Documentation for the new UI
```

Generated HTML Code

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF8" />
    <link href="http://fonts.googleapis.com/css?family=PT+Sans:400,700" rel="stylesheet" type="text/css" />
    <link href="http://fonts.googleapis.com/css?family=Titillium+Web:400,200,200italic,400italic,600,600italic" rel="stylesheet" type="text/css" />
    <link href="/assets/website/css/website.css" rel="stylesheet" type="text/css" />
  </head>
  <body>
    <div class="docsWrapper wrapper">
      <h1 class="docsTitle">
        Test - Website
      </h1>
      <h2 class="docsSubtitle">
        Living Documentation for the new UI
      </h2>
    </div>
  </body>
</html>
```

**Comment by bdkjones** [comment]
Trying using a relative rather than root-relative path in the href for the stylesheet.
