### ISSUE TITLE
Feature Request: Ability to define empty Kit variables

### ISSUE THREAD

**Issue by jonathaneckmier** [bdkjones/CodeKit2#357]
It would be great to be able to define empty kit variables. Right now if you leave a variable empty CodeKit will not compile Kit files.

Let's say I have a nav, and I want to have the current page highlighted by adding a class of `active` to the `<a>` tag.

```
<nav>
    <ul>
        <li>
            <a href="/" class="active">Home</a>
        </li>
        <li>
            <a href="/about">About</a>
        </li>
        <li>
            <a href="/contact">Contact</a>
        </li>
    </ul>
</nav>
```

If I'm using Kit variables to determine when an item is active or not, the best I can do right now is to output the `active` class on the selected nav item and then also output superfluous `inactive` classes on all the other nav items. Because variables cannot be undefined and there's no conditional logic in the Kit language (as far as I know), this is what I currently have to do:

```
<!-- $homeNavClass = class="active" -->
<!-- $aboutNavClass = class="inactive" -->
<!-- $contactNavClass = class="inactive" -->

<nav>
    <ul>
        <li>
            <a href="/" <!-- $homeNavClass -->>Home</a>
        </li>
        <li>
            <a href="/about" <!-- $aboutNavClass -->>About</a>
        </li>
        <li>
            <a href="/contact" <!-- $contactNavClass -->>Contact</a>
        </li>
    </ul>
</nav>
```

Which of course would output:

```
<nav>
    <ul>
        <li>
            <a href="/" class="active">Home</a>
        </li>
        <li>
            <a href="/about" class="inactive">About</a>
        </li>
        <li>
            <a href="/contact" class="inactive">Contact</a>
        </li>
    </ul>
</nav>
```

As far as I know it's not possible to set those variables to an empty string so that I wouldn't have to output `class="inactive"` on all the "unselected" nav items. If variables were allowed to be empty, or if simple conditional logic was available to check the value of the variable before outputting it would be easy to accomplish the markup pattern I'm shooting for. Is this functionality currently possible (and I'm just missing it in the Kit documentation)? If not I'd love to see it added in CodeKit.

**Comment by bdkjones** [comment]
Ah dammit, I meant to do that in the last update. I'll get it in the next one.

**Comment by jonathaneckmier** [comment]
Hey, I didn't see it in the release notes for 2.1, just wondering if this made it in yet, or if it's still on the radar for later?

**Comment by bdkjones** [comment]
Not yet. I plan to redo the kit compiler with more robust options, including control flow statements. It'll be part of that. Ideally targeting the next release.

**Comment by jonathaneckmier** [comment]
Hey @bdkjones – just following-up, is this still in the works?

**Comment by bdkjones** [comment]
Yes.

**Comment by kylegach** [comment]
I also need this capability, but haven't noticed it in any of the changelogs since your last comment.

**Comment by calvinjuarez** [comment]
Looking forward to this one.  Any updates?

**Comment by Wakkos** [comment]
Pssst. Following into this too @bdkjones =D

**Comment by zengabor** [comment]
I miss this every day. Otherwise it is so easy to make html mockups with Kit. 

I wish the syntax would be so simple:

```
<!-- $var = -->
```

or

```
<!-- $var: -->
```

Currently this outputs the content of `$var` (as the `=` or `:` is optional, hence ignored). But this would be a perfect syntax to set the variable to an empty string.

**Comment by guymeyer** [comment]
Ill take care of this. 

Bryan,

If you do this, I'll go the BBQ on Saturday.

**Comment by bdkjones** [comment]
Deal.

**Comment by guymeyer** [comment]
You did it like a week ago and haven't released it yet, huh?

**Comment by bdkjones** [comment]
Done. The syntax for this will be as follows:

```
<!-- $myVar = nil -->
<!--$myVar=nil-->
<!--$myVar: nil-->
<!--$myVar:nil-->
```

`nil` is now a protected keyword in Kit; meaning it can no longer be set as a variable name or a string value of a variable. Assigning `nil` to a variable will clear any value already set for that variable. It is also a valid initial value for a variable.

Note: 
It is still an error to have an undefined variable. That is, if the Kit compiler cannot find a value for `$myVar` that is _either_ a string or the `nil` keyword, the file will fail to compile. 

This will ship in the next few days.

**Comment by guymeyer** [comment]
I have to go to a stupid BBQ cuz of ya'll. You're welcome.

**Comment by Madaish** [comment]
Thanks @guymeyer!

Sounds like he has everything done, looking for the exact moment to release it xD

**Comment by bdkjones** [comment]
Gotta wait for Donald Trump to say something ridiculous so I can write the release notes. Could be a while. The guy never says anything crazy.

**Comment by zengabor** [comment]
Thank you so much! I can now remove a lot of hacks from my code, like `<span></span>` and `data-x`

**Comment by bdkjones** [comment]
You’re very welcome. Sorry it took me a while.
