### ISSUE TITLE
Git Branch changes effect code kit behaviour

### ISSUE THREAD

**Issue by magicDamo** [bdkjones/CodeKit2#359]
I don't have the time right now to chase this one down, however, it appears that if i stash / unstash or change branches in git, the project that is open in code kit does not remember it's file level preferences. 
For example, if i have foo.js and explicitly set it to not check syntax and to not have an output file, and then i do some kind of git branch change / alteration, then the prefs for that file are not remembered.

**Comment by bdkjones** [comment]
That's exactly how it's supposed to work. Your other branch has a different config.codekit file with different settings. This is how settings are synced across teams as people push/pull repos.
