### ISSUE TITLE
Video tutorial not found

### ISSUE THREAD

**Issue by marcaube** [bdkjones/CodeKit2#36]
On first launch there is a video tutorial at the bottom with the URL `http://incident57.com/codekit/screencasts` and I get a 404 on BlueHost.

![screen shot 2013-12-18 at 3 53 33 pm](https://f.cloud.github.com/assets/1478986/1777484/7d0f2c74-6826-11e3-876a-17ebbee48301.png)

![screen shot 2013-12-18 at 3 52 34 pm](https://f.cloud.github.com/assets/1478986/1777496/8d3c1d78-6826-11e3-9844-becc22a1ffd9.png)

**Comment by mdavis1982** [comment]
I also see this, but I presume that @bdkjones hasn't put the video on the site yet so that it doesn't get leaked.
