### ISSUE TITLE
Unnecessary terminator semicolons in libsass' minified output

### ISSUE THREAD

**Issue by zengabor** [bdkjones/CodeKit2#362]
In version 2.0.6 (17018) of CodeKit minified scss produced by libsass looks like this:

```
*{margin:0;}html,body{padding:0;}
```

Whereas if I switch to the slower Ruby compiler the minified output is:

```
*{margin:0}html,body{padding:0}
```

So if libsass is enabled then the minified output contains unnecessary semicolons before the `}`

Is it really libsass who produces the minified output or does it go through something else inside CodeKit? Can we somehow change the behavior? Couldn't find a similar issue here: https://github.com/hcatlin/libsass/issues

**Comment by bdkjones** [comment]
This isn't a CodeKit issue; please open it on the Libsass page.
