### ISSUE TITLE
Failed slim imports

### ISSUE THREAD

**Issue by drgullin** [bdkjones/CodeKit2#368]
Slim imports don't work.

```
/partials/header.slim
index.slim
```

index.slim:
`== Slim::Template.new('partials/header.slim').render`

Here's an error:

```
Errno::ENOENT: No such file or directory - partials/header.slim
  Use --trace for backtrace.
```

This code works well in http://alphapixels.com/prepros/

**Comment by bdkjones** [comment]
The `render` function is provided by Rails and is evaluated at run-time rather than compile time. It's meant for use inside the Rails runtime environment.

Version 2.1.6 of CodeKit (which I hope to release tomorrow) will bring compile-time includes to Slim using the very simple syntax:

```
include path/to/targetFile.slim
```
