### ISSUE TITLE
Custom .kit output path

### ISSUE THREAD

**Issue by drgullin** [bdkjones/CodeKit2#369]
Custom .kit output paths doesn't work.

I can set any options in the Languages -> Kit -> To this path, like '../' or './' and choose "the project's root folder' or 'The source file's folder', Codekit will always compile a kit file to the same folder as the source file.

So there's no way to compile a .kit file to the parent folder.

**Comment by bdkjones** [comment]
Did you click the "apply" button in the top-right of the output path section after changing the options?

Unlike file settings, output paths don't automatically change when you modify that section of the project settings.

**Comment by drgullin** [comment]
It's always disabled and doesn't react on my edits http://grab.by/xMxA

**Comment by bdkjones** [comment]
Ah, you’re editing the defaults for new projects. Changes to that area will have no effect on projects that are:

1) Already in CodeKit

2) Have previously been in CodeKit and have a config.codekit file in their root folder.

The new project defaults are used only the first time you add a folder to CodeKit that has never been in the app before.
