### ISSUE TITLE
.kit Variables adding blank lines

### ISSUE THREAD

**Issue by unculturedswine** [bdkjones/CodeKit2#372]
I manage several multi-language pages, and have found .kit files to be awesome for managing them. I have 1 .kit template with the HTML, and then my language pages are all just .kit variables that populate in the .kit template to spit out a plain HTML page with all the correct language text. 

Starting around Codekit 2.0.4 I believe the all the variables that I defined created empty lines at the top of my end-result pages. I'm 98% sure this wasn't an issue at the launch of Codekit 2. 

Here is a demo project - http://joelj.me/W5zo

![screen shot 2014-06-16 at 3 11 12 pm](https://cloud.githubusercontent.com/assets/794358/3292258/3e8c0338-f58d-11e3-8687-d41155ab3b9c.png)

**Comment by yratof** [comment]
I've just noticed this too

**Comment by drgullin** [comment]
+1

**Comment by bdkjones** [comment]
Fixed in version 2.1. Should have that released tonight or tomorrow. Thanks!
