### ISSUE TITLE
Show Project's Sidebar on Log

### ISSUE THREAD

**Issue by shshaw** [bdkjones/CodeKit2#375]
Currently with `View > Show Projects Sidebar` enabled, the sidebar only shows up in the Files view. If the Log view is active, it covers the sidebar, which doesn't seem necessary to me. The text shown in the Log doesn't greatly benefit from the extra space without the sidebar and just makes it more difficult to use the Projects Sidebar for switching projects.

The sidebar is also hidden when in the Project Settings view, but that seems more logical since that view has its own sidebar.

**Comment by bdkjones** [comment]
Hmm.. there's no context for having the sidebar in the log view. In other words, changing the selection in the project sidebar would have no effect on the contents of the log, so it doesn't make sense to show the projects sidebar in that view.

**Comment by shshaw** [comment]
Oh, I see. Thanks for the response.
