### ISSUE TITLE
Parent files recompilation

### ISSUE THREAD

**Issue by drgullin** [bdkjones/CodeKit2#376]
When I've imported something into some file (like header.kit into index.kit), I would like **index.kit** to be recompiled, when **header.kit** is saved.

Same for the other languages.

**Comment by bdkjones** [comment]
This is already implemented. If it's not working for you, please post your exact code.

**Comment by drgullin** [comment]
**index.kit:**

```
<!-- @import "_header" -->
<body>
</body>
<!-- @import "_footer" -->
</html>
```

**_header.kit:**

```
<!DOCTYPE html>
<!--[if lte IE 8]><html class="app-nojs app-ie" lang="en"><![endif]-->
<!--[if gte IE 9]><!--><html class="app-nojs" lang="en"><!--<![endif]-->

<head></head>
```

**_footer.kit:**

```
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
```

**Comment by bdkjones** [comment]
Used your exact example. When I save header or footer, index.kit recompiles just fine. When you select index.kit and look at the Linked Files inspector pane, do you see header and footer listed there?

**Comment by drgullin** [comment]
There's no `linked files` pane http://grab.by/xVDO

Here's what I've in Finder http://grab.by/xVDS
Options for the .kit files http://grab.by/xVDW

**Comment by bdkjones** [comment]
There is indeed a Linked Files pane: 

![screen shot 2014-06-19 at 23 49 49](https://cloud.githubusercontent.com/assets/926566/3337228/28631e7c-f847-11e3-94f6-9347912b74e1.png)

**Comment by drgullin** [comment]
There're no imports http://grab.by/xVEg

Please note that my .kit files are placed inside the /views/ folder, while all the html output goes to the / of the project.

**Comment by bdkjones** [comment]
Ok. Zip the whole project and post a download link here.

**Comment by drgullin** [comment]
http://ge.tt/8z1V5Dl1/v/0

Try to open and save **_header.kit**. Codekit won't compile anything.

**Comment by bdkjones** [comment]
Well of course it won't man; you added _header.kit to the Skipped Items list in the project settings! That literally means, "Don't touch this file."

**Comment by bdkjones** [comment]
This is user error. Do not add imported files to the skipped items list.

**Comment by drgullin** [comment]
Oops, sorry.
I've removed these files from the skipped items and now it works as expected.
Thanks!
