### ISSUE TITLE
Exception in CKROLE

### ISSUE THREAD

**Issue by bubblun** [bdkjones/CodeKit2#378]
### Setup
- Google Chrome Version 34.0.1847.116
- Safari Version 7.0.4 (9537.76.4)
- Mac OS X 10.9.3
- CodeKit 2.0.6
### Problem

While working with the new preview server, I encountered serious problems with it. On one project, reloading changes takes from 30 seconds to upwards of 2 minutes. Many times, HTML changes are not incorporated at all.

The behaviour cannot be easily recreated. I checked everything from the CSS files to removing images and SVG data. For one to three reloads that seems to remedy things only to get stuck in the load cycle again.

Every now and then, it spits out an endless array of the following error in the console:

```
Exception in CKROLE: TypeError: Cannot read property 'rules' of undefined lpckrp.js:1
```

![screen shot 2014-06-21 at 13 02 17](https://cloud.githubusercontent.com/assets/1052862/3348658/827be648-f93a-11e3-9a2c-99fa67af093e.png)

The timeline inspector does not show anything. This is weird in itself.

All non-standard plugins and extensions in both browsers are turned off.

Simply hitting reload without using the preview server at all does work as expected. This is how I have worked for the past week.

I have restarted CodeKit with the "shift trick".

The HTML and CSS validate on validator.w3.org as valid HTML5/CSS3.

Unfortunately I cannot provide you with the source code (which would help you the most in locating the problem I guess) as it's a client project and I'm bound by a draconic NDA. But I have experienced this behavior from anything of a small one page site, up to a full-blown WordPress-based portal site.

Possibly something with my install is botched? Should be weird as I have recently reinstalled by system from scratch and have no problems with any other software. I have also completely removed everything regarding CodeKit: config files, plist files, folders, everything and restarted and reinstalled it. Still, it results in the same behavior.

**Comment by bubblun** [comment]
Further testing shows that [grunt-contrib-watch](https://github.com/gruntjs/grunt-contrib-watch) has no problems with the same files.

**Comment by bdkjones** [comment]
Do you have Internet sharing turned on on your Mac?

**Comment by bubblun** [comment]
Indeed I did – unknowingly though. I used it shortly ago to set up a Linux server and must have forgotten to turn it off. Amazing, now it works fluidly, as it supposedly should. Thanks!

When you find the time, would you care to elaborate what the problem with Internet Sharing vs. the preview server is?

**Comment by bdkjones** [comment]
I have no idea what the problem is, but turning on Internet Sharing screws up OS X's ability to resolve local bonjour addresses.
