### ISSUE TITLE
JavaScript output paths not quite right

### ISSUE THREAD

**Issue by aaronadamsCA** [bdkjones/CodeKit2#379]
Version 2.0.6 (17018)

If I ask CodeKit to replace all instances of `assets/js` with `public/js` in my JS output path, it somehow turns this:

`/assets/js/gifts/confirm.js`

Into this:

`/public/js/gifts/confirm.js/confirm-ck.js`

It's also causing the error "Minification failed because this output path could not be created: /public/js/test.js (Check folder permissions or set a new output path for the file.)" which is resolved by creating the unwanted `test.js` directory.

**Comment by aaronadamsCA** [comment]
…Note that if I ask CodeKit to replace instances of `assets` with `public` the issue seems to resolve, but if I use `/assets/` and `/public/` the problem persists (originally I thought the `js` might be confusing it but no).

Those slashes are throwing it for a loop!

**Comment by aaronadamsCA** [comment]
(Note that I originally thought Sass was not subject to the same behaviour, but then I realized the project has Compass installed and so my Sass settings weren't in use, so I removed that part.)

**Comment by bdkjones** [comment]
Right now, you can’t specify a “section” of a path; just an individual component. So `assets/js` is not valid. You can tell CodeKit to replace either assets or js, but not both.

**Comment by bdkjones** [comment]
This issue is fixed in 2.1. You can also now replace multiple components at once. The update should be out tomorrow or Thursday.

**Comment by aaronadamsCA** [comment]
Nice! Great speed here, thanks.
