### ISSUE TITLE
Can't get Codekit2 to 'watch' or compile sass files

### ISSUE THREAD

**Issue by derekshirk** [bdkjones/CodeKit2#381]
Codekit2 is working fine on my computer at work. At home I use the same software and workflow but I can not get Codekit2 to watch or compile sass files that are not within the root directory of the project folder that I drag into codekit2. 

My site structure is as follows: 

WP theme folder (this is what I drag into Codekit2)
- admin
- img
- includes
- js
- sass
  - .sass-cache
  - modules
  - partials
  - rwd
  - style.scss (outputs to style.css in theme folder)
- style.css
- (all other WP .php files)

As soon as I move the style.scss file into the root level of the theme (project) folder CodeKit2 works fine. The thing that has me totally 'miffed' is this exact same workflow works fine at work. All of the sass partial files and modules, when saved trigger Codekit, everything compiles and unicorns rejoice. At home there is nothing but tears. 

I am using Mamp Pro and Sublime Text 3 (I've tried other text editors). In Mamp Pro I have my host/url setup with alias so I can use local.mysite.com. The mamp caching is turned off. I was a previous CodeKit user and upgraded and the only thing I can think of at this point is that there is a preference file somewhere that might be causing an issue (I'm sure that's a long shot)?  The last release of Codekit 1 is still installed on my machine because I need it to continue working, but even when I delete it and hold down shift while opening up Codekit2, it still doesn't work. 

Again, to the best of my knowledge both my work machine and home machine and software are all configured the same way. 

What haven't I tried? What am I missing?

I'm happy to provide some more details if you need them to help troubleshoot my issue. Thanks for any help you can provide.

**Comment by guymeyer** [comment]
Have you tried restarting?

Kidding!

Is the folder in Dropbox?

**Comment by derekshirk** [comment]
I have also tried to enter 'defaults delete com.incident57.codekit2' in terminal. No Luck there.
My machine at home is running OS X 10.9.3 and CodeKit 2.0.6

I am including a link to download a simple website project (freebie) that I downloaded in order to try it as a control test with my sass/partial directory structure just incase there was something wrong in my code.

http://mbx.cm/t/woKZY

Same results. When the style.scss file is in the root directory of the Codekit folder it watches and compiles fine, but as soon as I move the style.scss into the sass folder nothing happens.

**Comment by derekshirk** [comment]
Here are some screenshots of my Mamp Pro configurations

![screen shot 2014-06-25 at 8 10 52 pm](https://cloud.githubusercontent.com/assets/1427548/3394458/952e999e-fce0-11e3-86e3-01b83349cbce.png)
![screen shot 2014-06-25 at 8 11 34 pm](https://cloud.githubusercontent.com/assets/1427548/3394459/952f61bc-fce0-11e3-9385-e3fea6a03079.png)
![screen shot 2014-06-25 at 8 17 22 pm](https://cloud.githubusercontent.com/assets/1427548/3394460/952fd7fa-fce0-11e3-9d04-117d3e5176ef.png)

And here are some screenshots from CodeKit

![screen shot 2014-06-25 at 8 19 52 pm](https://cloud.githubusercontent.com/assets/1427548/3394468/e6ae16fa-fce0-11e3-875c-6ea055f6bf7e.png)
![screen shot 2014-06-25 at 8 20 50 pm](https://cloud.githubusercontent.com/assets/1427548/3394469/e6afaf1a-fce0-11e3-83ac-fbda9134e649.png)
![screen shot 2014-06-25 at 8 19 29 pm](https://cloud.githubusercontent.com/assets/1427548/3394470/e6b07ecc-fce0-11e3-9485-9b5c944dee70.png)
![screen shot 2014-06-25 at 8 19 45 pm](https://cloud.githubusercontent.com/assets/1427548/3394471/e6b12a34-fce0-11e3-9f15-774381aa31f8.png)

**Comment by bdkjones** [comment]
You're likely seeing a bug in Apple's FSEvents API, which is what CodeKit 2 uses to watch files. See this link for workarounds. I tested your demo project on my machine with CK 2.0.6 and everything works as expected in all cases. 

http://feedback.livereload.com/knowledgebase/articles/86239-os-x-fsevents-bug-may-prevent-monitoring-of-certai

**Comment by derekshirk** [comment]
Thank you! Repairing disk permissions did the trick.
