### ISSUE TITLE
asciidoc support 

### ISSUE THREAD

**Issue by gAmUssA** [bdkjones/CodeKit2#39]
Hi Bryan / codekit team, 

I was wondering, how difficult would be to add asciidoc files (*.adoc, *.asciidoc) support in codekit2 since there is a markdown support in place. Asciidoc is a markup syntax (similar to markdown) and asciidoctor is a fast and safe asciidoc processor implementation. This markup widely used on publishing world. Asciidoc supported by github as well.

There are bunch of projects and books that use asciidoc:
http://asciidoctor.org/docs/what-is-asciidoc/#who-s-using-asciidoc

Here is an example (there are many asciidoc files): 
https://github.com/Farata/EnterpriseWebBook/blob/master/ch1_advancedjs.asciidoc

JavaScript implementation:
https://github.com/asciidoctor/asciidoctor.js
http://asciidoctor.org/docs/install-and-use-asciidoctorjs/

Ruby implementation:
https://github.com/asciidoctor/asciidoctor

There is current approach for live editing with asciidoc/asciidoctor
http://asciidoctor.org/docs/editing-asciidoc-with-live-preview/

Thanks

**Comment by bdkjones** [comment]
Is there a C implementation of the compiler?

**Comment by mdavis1982** [comment]
@bdkjones I've had a scout around for a library and can't see one.

**Comment by gAmUssA** [comment]
@bdkjones there are 2 implementations: python (slow) and ruby (super fast. I takes ~1 sec to convert 800 pages book www.enterprisewebbook.com to produce html). Other implementations (java api, javascript) are based on ruby.

**Comment by gAmUssA** [comment]
@bdkjones No, there is no C implementation of asciidoc processor.

**Comment by bdkjones** [comment]
I've decided to close feature request issues on the beta repo. The reason is that I _have_ to get this app shipped and that means locking the feature set so I can concentrate on killing bugs. 

Once the app goes public, I'll take feature requests again and start implementing them for the 2.x releases.

**Comment by gAmUssA** [comment]
@bdkjones Ok! Good luck with a launch!
