### ISSUE TITLE
Linked file is a required value

### ISSUE THREAD

**Issue by drgullin** [bdkjones/CodeKit2#390]
I've removed a kit file and then, an html file.

Now, when I try to click on "reload project" button, I get this error http://grab.by/yvr8

How do I fix that?

**Comment by bdkjones** [comment]
The app's data file has been corrupted somehow. To fix this, quit CodeKit and then relaunch the app while holding down the shift key. This will clear out all existing projects and give you a fresh start.

**Comment by drgullin** [comment]
That's not a nice way to fix the issue, since I've nearly 15 projects imported into CodeKit.

I've fixed this by removing all codekit files from the project folder.

**Comment by bdkjones** [comment]
doesn't matter; all projects will come back with the exact settings they last had next time you add them to the app.

You can even add all 15 at once.
