### ISSUE TITLE
Layout - Bad navigation highlight

### ISSUE THREAD

**Issue by chrfickinger** [bdkjones/CodeKit2#392]
not so easy to read, lightgrey on green :)

see screenshot

![ck21](https://cloud.githubusercontent.com/assets/91317/3594846/1562320c-0ca8-11e4-9409-3d3632f5b416.jpg)

**Comment by guymeyer** [comment]
Would you believe me if I said it was intentional?

Don't believe me.

**Comment by chrfickinger** [comment]
JFYI, seems like it doesn't appear every time. Now its white on green like it should be. It was just broken after adding a new project.

**Comment by bdkjones** [comment]
I'm not able to reproduce this on my end. Can you give me exact steps to make it happen?

**Comment by chrfickinger** [comment]
just 2 clicks:
- create a new google web starter project by clicking on the plus-icon
- choose a project-folder

**Comment by bdkjones** [comment]
Fixed in 2.1.3.
