### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by chrfickinger** [bdkjones/CodeKit2#393]
Broken Link "Web Starter Kit" on Project settings / Web Starter Kit

**Comment by bdkjones** [comment]
Thanks. One day I will ship a bug-free update, but it is not this day.

**Comment by chrfickinger** [comment]
btw, the link to Google Web Starter Kit on your website (http://incident57.com/codekit/help.html#web-starter-kit) points to a wrong target as well :)

**Comment by bdkjones** [comment]
Thanks. App issue is fixed in 2.1.1, which will be out in a few days.

Website issue will be fixed tomorrow.
