### ISSUE TITLE
Missing inspector window for image files

### ISSUE THREAD

**Issue by chrfickinger** [bdkjones/CodeKit2#397]
The Inspector window (with Preview and Image Dimensions) is only available until the image is optimized.

**Comment by bdkjones** [comment]
?
I'm not sure I follow. Please explain a bit more.

**Comment by chrfickinger** [comment]
It's more a feature than a bug :-)
It's great to have the inspector view for images to check dimensions and preview.

check the attached screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/91317/3611685/98a17992-0d9e-11e4-8744-4475b6ab4c31.jpg)

**Comment by bdkjones** [comment]
The inspector should show for optimized images and does on my machine. Try restarting the app. Does the issue persist?

**Comment by chrfickinger** [comment]
yes, it works great for optimized images.
I just would love to see the inspector for unoptimized images as well, because I use the this window as finder replacement :-)

**Comment by bdkjones** [comment]
I'm not getting this behavior on my end. The image inspector shows regardless of whether the selected image has already been optimized. 

Try refreshing the project in CodeKit (click the circular arrow button in the top bar, near the project icon). Then reselect the file. 

Try selecting a bunch of image files, both optimized and unoptimized. Does the inspector show then?

Is this project on a remote disk?

**Comment by chrfickinger** [comment]
Refresh and reselect doesn't help. I don't see the inspector on optimized images.

Selecting a bunch of images shows only the inspector if at least one file is unoptimized.

Project is on a mounted smb volume.

**Comment by bdkjones** [comment]
Does the issue manifest in other projects on the SMB drive? 

Does it manifest when the SAME projects are moved to a local drive and added to CodeKit from there?

**Comment by chrfickinger** [comment]
i just created a screencast.
check: http://youtu.be/D5gqgWIpQBM

Will test on a local drive

**Comment by bdkjones** [comment]
Any updates on this?

**Comment by chrfickinger** [comment]
Just tested on a local drive and again on a smb drive. Seams like the bug is not reproducible anymore. I think, you can close this ticket. Will report if it happens again :)
thanks

**Comment by bdkjones** [comment]
Excellent. Self-closing issues are my favorite kind of issue. Thanks!
