### ISSUE TITLE
Request: Add HTTP DELETE support

### ISSUE THREAD

**Issue by eirabben** [bdkjones/CodeKit2#398]
As of now, the automatic refresh does not support HTTP DELETE requests when performing via Javascript. It would be nice to have this supported.

**Comment by mocon** [comment]
+1 for this one. CodeKit is sweet! Thanks for making such a nice tool.

**Comment by Grilly** [comment]
+1

**Comment by bdkjones** [comment]
DELETE support added for 2.2.1. Should be out tomorrow or early next week, depending on Libsass 3.2. 

Note: you'll need an external server for these requests. CodeKit will proxy them over to the external as required.

**Comment by mocon** [comment]
Thanks!
