### ISSUE TITLE
Codekit auto scrolls on every page

### ISSUE THREAD

**Issue by nicooprat** [bdkjones/CodeKit2#399]
Hi Bryan,

I was going crazy with this bug...!

Configuration :
- Codekit 2.0.6 (with external server configured for autorefreshing)
- Chrome latest
- Mac OS X 10.9.4

I saw Codekit was using a cookie named `ckrp_ypos` to remember the Y scroll of a page to automatically stay where we was left before auto-reloading the page. That's great for development  !

The problem is that this behavior continues as we navigate through the site. So when going from page A to B, page B automatically scrolls, even without refreshing or doing anything related to Codekit.

Would it be possible to auto scroll only after a Codekit-related action ?

Thanks.

**Comment by bdkjones** [comment]
Yea; I'll fix this.

**Comment by bdkjones** [comment]
Fixed for the 2.1.8 release.
