### ISSUE TITLE
Crash report dialog has old app icon

### ISSUE THREAD

**Issue by mdavis1982** [bdkjones/CodeKit2#40]
Nobody should ever see it ( :wink: ) but the crash dialog has the old application icon:

![screen shot 2013-12-18 at 21 03 53](https://f.cloud.github.com/assets/199807/1777725/c85b0fba-6829-11e3-9edf-e6a9963c4fd4.png)

**Comment by bdkjones** [comment]
Ah yes. The most tweeted image of CodeKit and top Google image result when searching for CodeKit. Fixed and retina-fied in Beta 3. Thanks!
