### ISSUE TITLE
SASS Filenames containing a dot are not watched or listed in imports

### ISSUE THREAD

**Issue by wingsline** [bdkjones/CodeKit2#400]
When an imported scss file contains a dot (example _settings.colors.scss), CodeKit doesn't sees it as an import nor compiles the parent file when the _settings.colors.scss is changed.
Tried with the internal and external compiler.

Using the sass --watch from the terminal works as expected.

**Comment by bdkjones** [comment]
Let me guess. In your Sass file, you’re writing: 

```
@import “_settings.colors”;
```

The trouble with this is that “.colors” looks an awful lot like a file extension, doesn’t it? CodeKit says, “Ah, this import statement path has an extension on it, so I don’t have to add “.scss” to the end of the path.”

You will protest: “But of course you do! Everyone knows .colors is not right for a Sass file!”

I will respond: “What about this:”

```
@import “somefile.css”;
```

You will reply: “Oh, well, .css is totally fine for a Sass file. So I guess you just have to worry about .css and .scss. Anything else is just part of the filename.”

I will respond: “Okay, let’s switch to a language that allows you to import files of any type. CodeKit supports several. Now how the hell am I supposed to determine whether the .[text] at the end of your path is a file extension or part of the file name?”

The only way for me to know that is if you NEVER abbreviate the full file name. If you're going to use dots in your name AND leave off the extension, well now we're just playing a fun game called, "Is the crap after the last period an extension or part of the name!?"

And this is why using dots in a filename is a really bad idea invented by hipsters bent on destroying the world. It makes ME, the app developer, have to GUESS at your intent. Anything in programming where the solution is an educated guess is a terrible, terrible pattern.

That said, Sass is a limited case so I’ll update to support goddamn hipsters and their terrible ideas.

**Comment by bdkjones** [comment]
Implemented in 2.1.1. Will be released shortly. 

Thanks!

**Comment by bdkjones** [comment]
Also: no hard feelings. I didn't mean to jump all over you with my response. You're not the first person to fall victim to this and I simply have very strong opinions about periods in file names.

**Comment by wingsline** [comment]
Np :) I was just trying out the https://github.com/inuitcss/getting-started and that's where I encountered the problem.
