### ISSUE TITLE
Google Web Starter Kit - redirect loop 

### ISSUE THREAD

**Issue by randallmckenna** [bdkjones/CodeKit2#404]
I was previously using the Google kit locally (non-codekit), and was able to upload the files & folders to my web server successfully. Then I switched to codekit after it was added (using a fresh framework install) and now when I upload everything to my web server via FTP I get a redirect loop error. 

I also uploaded a fresh framework install to see if it was something I did and I still get the redirect loop error.

Any suggestions?

**Comment by bdkjones** [comment]
Sounds like your .htaccess file is misconfigured. Check the rewrite rules you have specified there.
