### ISSUE TITLE
No display of imports for .kit files

### ISSUE THREAD

**Issue by otheroom** [bdkjones/CodeKit2#406]
In the Linked Files panel, selecting a .kit file doesn’t list anything in “imports” area, even when there are kit includes happening. When you select an imported file it does properly populate the “imported by” area.

Mac OS 10.9.4 / CK 2.1.1 (17625)

**Comment by bdkjones** [comment]
Yea, the only files that are going to display in the imports list are other imported Kit files. If you import files of a random type, such as html, etc, those won't be listed there.

**Comment by otheroom** [comment]
As of 2.1.1 it wasn't listing imported kit files but at some point it started working because I'm seeing them in 2.1.5.
