### ISSUE TITLE
Stuck in Refreshing all enabled projects

### ISSUE THREAD

**Issue by defaria** [bdkjones/CodeKit2#409]
I turn on codekit2 and I get the message on the status bar "Refreshing all enabled projects & frameworks". I cannot do anything until it's done refreshing... and it's never done refreshing. Therefore I cannot work on any project. I cannot remove projects or do anything really.

I removed code kit from my mac.
I removed the preference file
I removed all config.codekit files
*I cannot remove the project via code kit

installed code kit again. Same problem.

I turn it back on, and somehow codekit tries to load those same projects (that do exist) and the same message. How can codekit know about these projects if I removed the config files and removed the preference file? How do I make the message go away so I can use codekit again?

**Comment by bdkjones** [comment]
Quit the app and then launch it while holding down the shift key to clear out existing data and start fresh. 

Then please close this issue. Thanks!

**Comment by defaria** [comment]
That worked... but sadly I had to search for a couple of hours to find that solution on my own. Thanks though.

**Comment by estudiQiero** [comment]
> Quit the app and then launch it while holding down the shift key to clear out existing data and start fresh.

Today (2019), hold down Option key instead shift key. It works.

**Comment by BartMommens** [comment]
> > Quit the app and then launch it while holding down the shift key to clear out existing data and start fresh.
> 
> Today (2019), hold down Option key instead shift key. It works.

Thank you!
