### ISSUE TITLE
Infinite compile loop

### ISSUE THREAD

**Issue by marcaube** [bdkjones/CodeKit2#41]
With Codekit 1 I had a file `main.js` that compiled to `main.min.js`, as per my global configs (not project specific).

After importing the project in Codekit 2, the default output was `/js/min/main-ck.js`. I got into an infinite compile loop the first time I changed that to `main.min.js` and clicked Process. Both file were compiling one after the other rapidly.

I tried to reproduce the bug (deleting the project and re-doing the steps) and was not able to, perhaps there is a timing issue.

**Comment by bdkjones** [comment]
Does this file prepend or append any others? If we can't reproduce it reliably, it's going to be next to impossible to say what's going on.

**Comment by marcaube** [comment]
Yeah, there were 3 files prepended, still haven't been able to reproduce.

**Comment by rpkoller** [comment]
I got today for the first time the infinite loop alert. also on the project i've mentioned here: https://github.com/bdkjones/codekit2beta/issues/79

haven't changed anything on my imports, specially in the field stated as error here. happend on beta 2 and beta 3

![bildschirmfoto 2013-12-21 um 17 37 38](https://f.cloud.github.com/assets/1665422/1796240/89fd1204-6a5e-11e3-847c-722643c9e206.png)

and what is stated that style.scss and _base.scss import eachother is simply not true. my scss looks different :/

**Comment by bdkjones** [comment]
Are you _sure_ they don't import each other, even indirectly through other files?

If so, I need you to send me the project so that I can test with it over here. Please zip it, put it online and then post a link to it here.

**Comment by rpkoller** [comment]
@bdkjones jep i am completely sure that they haven't had imported each other and not even indirectly. 

But i guess in my case everything was caused by the gem mess i had. After cleaning the gem folder and perform fresh installs everything works flawless as well as the infinite import loop alert panel is history again.

**Comment by bdkjones** [comment]
Has anyone been able to reproduce this? It sounds like a one-off random issue.

**Comment by marcaube** [comment]
I was not. I think we can mark it as "Not able to reproduce" and close it.
