### ISSUE TITLE
Yosemite Menu Bar icon (Dark Theme)

### ISSUE THREAD

**Issue by davidjdixon** [bdkjones/CodeKit2#410]
The current release is showing the standard (dark) icon in the Yosemite menu bar when the menu bar is using the dark theme.

please can you change this to use a white icon to follow the default menu bar icons used in Yosemite (if the icon can be made flat as well to complement the new UI of Yosemite/Codekit) that would be a nice addition as well (currently looks to be slightly beveled with inner shadows).

**Comment by bdkjones** [comment]
Status bar icon is updated for the 2.1.8 release and is now compatible with Yosemite's dark mode. It's unhealthy, the amount of time I spent on this getting it to look right on retina and non-retina on 10.8, 10.9 and 10.10. 

There are some alignment quirks when using a retina screen next to a non-retina screen on 10.9 and switching between them while using the CodeKit menu. I wasn't able to overcome these, but they aren't present on 10.10.
