### ISSUE TITLE
Codekit local server issue

### ISSUE THREAD

**Issue by defaria** [bdkjones/CodeKit2#412]
In our studio we access all files from a local mac server. For some reason every time we save a file that needs to be processed by codekit, we get a new server shortcut on our desktop. See attached image. The only way to get rid of them all is by restarting the computer. I am sure this is not a codekit specific issue, but maybe some settings with our server are conflicting with some settings  with codekit that keeps doing that. Any ideas as to what it could be?
![screen shot 2014-07-25 at 1 12 41 pm](https://cloud.githubusercontent.com/assets/1197739/3705443/33a52cd2-141f-11e4-8f80-3d93b5db8a2c.png)

**Comment by bdkjones** [comment]
I literally have no idea what could be causing this. There's nothing in CodeKit that would do this. What version of OS X are you running?
