### ISSUE TITLE
please add "pause/unpause" option to codekit menu bar menu

### ISSUE THREAD

**Issue by davidjdixon** [bdkjones/CodeKit2#414]
When using git (etc), the need to go into the app each time I'm doing a pull/merge etc in order to stop codekit from compiling files is a pretty painful process.

To help mitigate this, I would like to see an option to pause codekit's process in the menu bar context menu, preventing the need to go into the app and select an individual project to turn off and on again.

**Comment by bdkjones** [comment]
Implemented for 2.1.6. 

There will be a new _global_ keyboard shortcut: `command + option + /` Pressing that from within any app will toggle CodeKit's file-watching.
