### ISSUE TITLE
Chrome on Windows reloading.. about every 5 seconds

### ISSUE THREAD

**Issue by mrtwebdesign** [bdkjones/CodeKit2#417]
Actually.. exactly every 5 seconds. 

I'm running CodeKit on Mac and testing output live on Windows. The current stable version of Chrome and Firefox reloads every 5 seconds(I don't believe in IE, there is no IE). I get a flash of the red warning bar, then the page reloads fine. So it looks like self-healing combined with automatic suicide. Perhaps Codekit is developing bipolar disorder?

**Comment by bdkjones** [comment]
I'll be pushing an update tonight to fix this. Thanks!

**Comment by mrtwebdesign** [comment]
Awesome! You've always had great support. And, I can't work without CodeKit anymore. :+1:

**Comment by guymeyer** [comment]
Actually. It's a typo. No joke. :D

**Comment by bdkjones** [comment]
Fixed in 2.1.3
