### ISSUE TITLE
Clarification of LESS tooltips in Language Defaults options

### ISSUE THREAD

**Issue by davesimon** [bdkjones/CodeKit2#42]
Very minor but in language defaults settings for less, the tooltip for "create a source map" corresponds with "enforce strict imports." Although the title is fairly self-evident anyway.

Currently, the "Enable IE compatibility checks" has what is essentially a placeholder tooltip because the LESS docs are somewhat unclear (um...nonexistent?) as to what the option does.

If checked, that option limits data-uri size to 32kb for IE8 compatibility, falling back to relative urls.

**Comment by bdkjones** [comment]
I love easy bugs like this. Fixed in Beta 3.
