### ISSUE TITLE
sass map includes bourbon files that don't exist

### ISSUE THREAD

**Issue by yratof** [bdkjones/CodeKit2#421]
Just checking the console on safari for a site i'm working on and i noticed a 404 for a file. 

`/Applications/CodeKit.app/Contents/Resources/engines/bourbon/bourbon/app/assets/stylesheets/addons/_prefixer.scss"`

So I looked at the sass map, and the first few lines read this:

`{"version":3,"sources":["style.css","../scss/partials/_normalize.scss","../scss/partials/_typography.scss","../scss/partials/_mixins.scss","../scss/modules/_animations.scss","../../../../../../../../../../../Applications/CodeKit.app/Contents/Resources/engines/bourbon/bourbon/app/assets/stylesheets/addons/_prefixer.scss","../scss/modules/_alerts.scss","../scss/modules/_buttons.scss","../scss/modules/_forms.scss","../scss/breakpoints/_base.scss","../scss/plugins/_wpcf7.scss","../scss/partials/_colours.scss","../scss/style.scss","../scss/breakpoints/_mobile.scss","../scss/partials/_grid.scss","../scss/breakpoints/_tablet.scss","../scss/partials/_variables.scss"...`

Now the bizarre thing is that i'm not compiling with prefixer.

![screen shot 2014-08-05 at 10 29 43](https://cloud.githubusercontent.com/assets/1001935/3809382/15abc8a0-1c83-11e4-8a19-46b37c1444eb.png)

I am using bourbon though, called in with `@include 'bourbon'`. But still, something isn't right there, is it?

**Comment by bdkjones** [comment]
Nope. This is correct. The file in question is part of Bourbon; it's not related to AutoPrefixer.
