### ISSUE TITLE
Feature Request: Bring back CodeKit 1-style auto refresh

### ISSUE THREAD

**Issue by pieterdejong** [bdkjones/CodeKit2#422]
On some projects, the CodeKit 2 way of auto refreshing isn't very convenient. Luckily there is the "Also reload file:// URL's in all browsers on my Mac"-feature. But when working with server side languages this won't get you very far. It would be nice to have this function also for addresses containing 'localhost'.

Also, I would love to see a checkbox for disabling the 'ckcachecontrol' functionality.

My current workaround is using CodeKit combined with [Livereload](http://livereload.com) but that's not very efficient.

**Comment by bdkjones** [comment]
Can you show me an example of a project that's not working with the 2.0-style refresh?

**Comment by pieterdejong** [comment]
When you're building a web application and depending heavily on the address in your address bar you might get some issues. Also, configuring WordPress theme development projects in the new version of CodeKit isn't as easy as in the previous version.

**Comment by mohsin** [comment]
+1
I tried codekit with OctoberCMS (based on Laravel) and it didn't work. The caching needs an off switch

**Comment by bdkjones** [comment]
Unfortunately, it's not possible to use the old 1.x style refresh with the new style in 2.0
