### ISSUE TITLE
Disable sourcemap generation

### ISSUE THREAD

**Issue by nicooprat** [bdkjones/CodeKit2#424]
In some projects and for some reason, I don't want to generate source maps with SASS (and Compass).

I couldn't find any option to disable this in Codekit, or to add a flag to the `sass` compiler. And I couldn't find the way to disable it in config.rb neither.

Any idea ? Thanks.

**Comment by otheroom** [comment]
Doesn't unchecking the "Create a source map" option in the Compiling Options panel do what you need?

**Comment by nicooprat** [comment]
Hi,

This checkbox is already unchecked unfortunately. I forgot to mention, I'm using :
- Sass 3.3.14 (Maptastic Maple)
- Compass 1.0.0.rc.0 (Polaris)

Maybe sourcemaps are generated by default with this versions ? I also tried to add this in `config.rb` :

``` ruby
sass_options = {:sourcemap => false}
enable_sourcemaps = false
```

...but had no chance.

**Comment by bdkjones** [comment]
Yea, CodeKit isn't creating a source map if its a Compass project. Compass is doing that on its own.

**Comment by nicooprat** [comment]
Yep I read somewhere that Compass generates sourcemaps by default in the last versions, can't find it anymore. Anybody here have an idea how to avoid that ?

**Comment by bdkjones** [comment]
The next update takes care of this problem for non-compass projects. Sass has moved to an "always create a source map unless you explicitly opt out" approach, so CodeKit had to be updated to take care of that.

For Compass projects, you should be able to control this in the config.rb file.
