### ISSUE TITLE
`coffeescript_error`s when building coffee files that include js

### ISSUE THREAD

**Issue by karanlyons** [bdkjones/CodeKit2#426]
When I'm prepending or appending js files to coffee files I tend to see `coffeescript_error`s in js files.

That shouldn't happen. I think CoffeeLint _might_ be running against all the files in the chain instead of the built `{name}-ck-sourcemap-source.coffee` or—even better—just the `*.coffee` files in the chain.

**Comment by bdkjones** [comment]
Oh, I know. 

The trouble is that CoffeeLint is incapable of skipping backtick-escaped JavaScript in a CoffeeScript file. It's a limitation of CoffeeLint that I wish they would fix.

**Comment by karanlyons** [comment]
Huh, when testing it against CoffeeLint alone (1.5.3), I get a huge amount of line length and trailing whitespace warnings, but nothing like the errors I see through CodeKit. I'd guess that it is properly respecting the backticks (though it obviously complains about having the backticks at all) and only doing general style checks. I don't know why it doesn't behave in the same manner within CodeKit. Perhaps they _just_ fixed this in 1.5.3?

```
$ coffeelint /Users/karanlyons/Desktop/site/js/control-ck-sourcemap-source.coffee                                                                                                              ~ [11:59:02]
  ✗ /Users/karanlyons/Desktop/site/js/control-ck-sourcemap-source.coffee
     ✗ #8: Backticks are forbidden.
     ✗ #10: Line exceeds maximum allowed length. Length is 102, max is 80.
     ...
     ✗ #244: Line ends with trailing whitespace.
     ...
✗ Lint! » 1766 errors and 0 warnings in 1 file
```

**Comment by karanlyons** [comment]
Nah, just checked by pointing CodeKit to 1.5.3. And the error out of CodeKit points to a line:column location that only makes sense in the context of the original js file (unless CodeKit's remapping from the concatenated coffee file):

```
coffeescript_error
[stdin]:1:33: error: octal literal '07' must be prefixed with '0o'
```

Corresponds with:

```
[1] /*! Picturefill - v2.1.0 - 2014-07-25
```

But not with:

```
[1] 
[2] 
[3] ###
[4] --------------------------------------------
[5]      Begin picturefill.js
[6] --------------------------------------------
[7] ###
[8] `/*! Picturefill - v2.1.0 - 2014-07-25
[9] 
```

This matches with the error received if I were to just run that one js file through coffeelint as opposed to the entire concatenated coffee file:

```
$ coffeelint /Users/karanlyons/Desktop/site/js/picturefill.js                                                                                                                                  ~ [12:02:48]
  ✗ /Users/karanlyons/Desktop/site/js/picturefill.js
     ✗ #1: [stdin]:1:33: error: octal literal '07' must be prefixed with '0o'
/*! Picturefill - v2.1.0 - 2014-07-25
                                ^.

✗ Lint! » 1 error and 0 warnings in 1 file
```

**Comment by bdkjones** [comment]
It’s possible. 1.5.3 was just released today. 

Make sure you’re testing the same thing both in and out of CodeKit. Take your JS file and copy all the code from it, then paste that into your CoffeeScript file and wrap it in backticks.

This is the process that CodeKit follows to check and compile Coffee files. It simply mashes the source of every file together, then passes that to the CoffeeScript compiler (which can’t handle multiple input files)

**Comment by karanlyons** [comment]
Sorry, I've got a nasty habit of replying/editing multiple times. But it looks like CodeKit _is_ passing the individual js files through coffeelint for some reason. It may be due to some way I set up my project: would it help if I passed along some of my project data to you?

**Comment by bdkjones** [comment]
Sure, post a download link to the files in question and give me a set of steps to walk through to create the issue.

**Comment by karanlyons** [comment]
This is enough to break stuff: https://dl.dropboxusercontent.com/u/12652/bug.zip
Unzip and try checking syntax on `latte.coffee`, or touching it to force a full rebuild and check.

**Comment by bdkjones** [comment]
K. Please leave this up for a while; it’s going to be next week before I can look at it.
