### ISSUE TITLE
Compiling Markdown inside Jade file

### ISSUE THREAD

**Issue by DinisCruz** [bdkjones/CodeKit2#427]
Hi, with this file

``` jade
doctype html
head
  include ./top.jade
  style
    include ./css/style.css
body
  h1 this is a title aa

  :markdown #in markdow   
```

I get this error:

![image](https://cloud.githubusercontent.com/assets/656739/3885570/36ae4360-21c5-11e4-9f7c-00e169d68535.png)

Without the markdown line:

![image](https://cloud.githubusercontent.com/assets/656739/3885584/5eaf002a-21c5-11e4-95e2-1f98db6f4810.png)

it compiles ok

![image](https://cloud.githubusercontent.com/assets/656739/3885585/669603ce-21c5-11e4-9206-cc2deb4f6537.png)

Note that I have marked installed on this box , here is it working from WebStorm

![image](https://cloud.githubusercontent.com/assets/656739/3885588/825da1e8-21c5-11e4-9ae1-af61f3ec8ce4.png)

**Comment by bdkjones** [comment]
Yep. 

To use filters in Jade, you need to install Jade and the appropriate compiler for the filter in question (Markdown in this case) at the command line. Then, open CodeKit's preferences and use the Advanced tab to switch the app to the external Jade compiler. 

Jade provides filters for many different languages and it's not possible for me to support them all in the app.
