### ISSUE TITLE
POST request failing with External Server Address set

### ISSUE THREAD

**Issue by davidhemphill** [bdkjones/CodeKit2#43]
I have a site that I got working by setting the "External Server Address" option. However, when I make a POST request to a URL, I get a blank white screen. If I change the method to GET, then it works.

I tested this by making a new project in MAMP Pro with the domain name 'cktest.dev', added an index.php file with a form that posts to 'go.php' and a submit button. Go.php just var_dumps a message and then dies(). If I submit the form, I get a white screen, but if I change the form method to GET or hit the go.php by itself it works.

**Comment by mdavis1982** [comment]
@davidhemphill Do you have the "Always use external server" option checked in the project preferences?

**Comment by davidhemphill** [comment]
@mdavis1982 Yes, but I experience the same issue regardless of if it's checked or not.

**Comment by mdavis1982** [comment]
@davidhemphill You said:

> If I submit the form, I get a white screen, but if I change the form method to POST or hit the go.php by itself it works.

I presume you meant if you change it to `GET`? Can you clarify that the `POST` works outside of CodeKit if you just go to `cktest.dev` in the browser please?

**Comment by davidhemphill** [comment]
Yes, when I change it to GET. Sorry about that typo. The POST works on the cktest.dev version.

**Comment by mdavis1982** [comment]
I'm also experiencing this. I presume it has something to do with how the request gets forwarded to the external server. In fact... It seems as though any `POST` request at all fails.

@bdkjones Is there anything able to be done about this?

**Comment by bdkjones** [comment]
Please post the test project online somewhere and put a link here so I can download it and use it to debug.

The very simple one with just a var dump will suffice.

**Comment by mdavis1982** [comment]
@bdkjones You can download my test project here: https://www.dropbox.com/s/hg92fr9bq9z7cqn/web.zip

**Comment by davidhemphill** [comment]
@bdkjones Here's the project in question: https://gist.github.com/davidhemphill/bf14f49c4ef9b389da52

**Comment by bdkjones** [comment]
Fixed.

Post requests will be supported in Beta 3. Note that the support is limited to url-encoded POST requests, not multipart/form-data POST requests (such as for uploading large files). I may add support for the latter at a later date.
