### ISSUE TITLE
UI glitches

### ISSUE THREAD

**Issue by lucien144** [bdkjones/CodeKit2#433]
Switching between Project settings and Log makes me crazy. Why are these 2 quite important buttons so far against each other? Wouldn't be better to stick them together, so when you switching multiple times you don't have to fly over the whole damn screen.

On the other, so far great software.

Thanks.

**Comment by bdkjones** [comment]
Not sure why you'd need to switch between the project settings and log screens; the two aren't really related. 

Nevertheless, cmd+1 and cmd+2 will get the job done fast.
