### ISSUE TITLE
How to set custom project icon

### ISSUE THREAD

**Issue by floq-design** [bdkjones/CodeKit2#435]
Hi
Is there a way to set a custom project icon?

Up until now I've been using CodeKits' built-in icons - but yesterday I added a project with an `apple-touch-icon.png` file in the project root folder and was surprised that CodeKit picked it up as the project icon automatically.

When I try to drag and drop a custom icon for existing projects CodeKit assumes I'm dropping a project folder - and I can't see any option in Project Settings.

I've tested if I can set a custom icon for an existing project by editing the `config.codekit` file where under **projectAttributes** I've edited the **iconImageName** value and that works. Is there no GUI method for doing this?

Muchos gracias

**Comment by bdkjones** [comment]
Right click any image in the project. 

Also, this is not really the place for technical support questions.

**Comment by bdkjones** [comment]
Did not intend that to be mean. I just don't check here regularly, so support questions go unanswered. This spot is for bugs and feature requests so I can track them.

**Comment by henrikhelmers** [comment]
Consider changing this to a feature request for making it easier to change project icon. I tried drag-n-drop and clicking the icon, but no hint about how to do it from there. Not in General Project Settings either.

**Comment by bdkjones** [comment]
Yea, drag-and-drop would be best.

**Comment by sunnywalker** [comment]
I just came across this issue and want to use an image (company logo) not in the project as a project image. Is this planned as a 3.x feature?

**Comment by bdkjones** [comment]
Nope. The image has to be in the project. Drag-and-drop is in 3, though.

**Comment by treiber** [comment]
Just got 3.0, drag'n'drop does not seem to be in there, or am I doing something wrong?

**Comment by treiber** [comment]
Just got the 3.0 (great release btw), but drag'n'drop doesn't really seem to work, or am I doing something wrong?

**Comment by bdkjones** [comment]
Show me what you’re doing in a video.

**Comment by treiber** [comment]
I think I just figured it out, my image was not within then the project, therefore I couldn't add it!

**Comment by bdkjones** [comment]
Dragging an image from the files list to the main button works. Or, right-click an image and choose “set as project icon”.

**Comment by danwood** [comment]
This thread is really old, but it's the top result for my search … anyhow, having Vladimir Putin show up as the default icon for my project is … well, pretty offensive …

**Comment by bdkjones** [comment]
CodeKit 2.x was discontinued in 2016.
