### ISSUE TITLE
Feature request: ability to order projects in projects sidebar alphabetically

### ISSUE THREAD

**Issue by tyssen** [bdkjones/CodeKit2#436]
I know I can drag projects into order but it would be handy to be able to have an option to automatically reorder them by title.

**Comment by bdkjones** [comment]
Implemented. Will be in 2.1.6. 

Note: alphabetical ordering is not "sticky". That is, if you add a new project, it will still go at the bottom of the list, etc. This is needed to continue supporting manual re-arrangement of projects via drag/drop.
