### ISSUE TITLE
Safari on Yosemite; can't get past "Connecting to refresh server"

### ISSUE THREAD

**Issue by robrecord** [bdkjones/CodeKit2#437]
On Safari 10600.1.8 & I just installed CodeKit 2.1.5 (17756).

I load up codekit's refresh server (using external server) and the page loads, but an orange bar informs me "Connecting to refresh server" which won't go away. 

I see no errors in the browser console. No firewalls blocking anything (to my knowledge). Used to work...

What other info would be helpful?

**Comment by bdkjones** [comment]
Reboot your Mac. Test with Chrome. Try a different LAN.

**Comment by robrecord** [comment]
After a restart: Works on Chrome 37, still not on Safari. Cannot test on a different LAN today,

**Comment by bdkjones** [comment]
Tested this on DP8 and it's working over here in Safari.

**Comment by NoahDavidATL** [comment]
I still get "Connecting to CodeKit's refresh server..." all the time... I had to write an extension to display: none that div because I truly don't care if it can't connect to the refresh server. Stop overlaying an orange bar on my page!
