### ISSUE TITLE
CodeKit config file does not update the CoffeeScript "append" list

### ISSUE THREAD

**Issue by ericbae** [bdkjones/CodeKit2#438]
Hello,

We have a team of developers using CodeKit.

Our website has a main CoffeeScript file, which appends about 10 other CoffeeScript files.

When one developer commits the CodeKit config file and another developer opens their CodeKit, the "append" list is empty.

We've tested this quite a few times and it looks like the "append" list is not being read from the config file, but somewhere local.

We tested this.
1. Developer A : main.coffee appends a.coffee, b.coffee
2. Developer B : main.coffee appends c.coffee, d.coffee
3. Developer A commits his CodeKit config file (via Git)
4. Developer B pulls Developer A's CodeKit config file
5. Developer B still has main.coffee file with c.coffee and d.coffee (instead of a.coffee and b.coffee)

Is there a local cache somewhere? Is it possible to delete it? (I think there was an option to do this on CodeKit 1)

**Comment by bdkjones** [comment]
I'm looking into this issue for the next update. In the meantime, using in-file statements rather than drag/drop to set up the concatenation will always work reliably.

**Comment by ericbae** [comment]
How do I set up in-file statements for this? Directly in the Config file?

**Comment by bdkjones** [comment]
See http://incident57.com/codekit/help.html and select the CoffeeScript category.

**Comment by bdkjones** [comment]
Fixed for version 2.1.6. Hope to release that tomorrow evening, Pacific US time.

**Comment by ericbae** [comment]
Updated to the latest version. I'm getting an error when trying to drag a coffeescript file to append. I get the following error...

![screen shot 2014-09-25 at 10 47 53 pm](https://cloud.githubusercontent.com/assets/614459/4404563/745f3100-44b2-11e4-91c9-2351167bd87e.png)

**Comment by bdkjones** [comment]
Please zip the project involved and post a download link, as well as exact steps to reproduce (which file did you drag to which other file, etc).

**Comment by bdkjones** [comment]
In the meantime, use in-file statements to make the concatenation work.

**Comment by ericbae** [comment]
This error occurs for any new project where I'm trying to drag and drop a 'child' coffeescript file to the 'parent' coffeescript file.

Here's the link to the empty project - https://dl.dropboxusercontent.com/u/33161452/test.zip

There are two coffeescript files - home.coffee and append.coffee. I tried dragging "append.coffee" to "home.coffee" and I get an error. Two coffeescript files are completely empty files by the way. I was merely testing the issue.

Codekit config file is also attached.

**Comment by bdkjones** [comment]
Yep. This is a bug introduced in the last update. I've got a fix in the work and will have it out tonight or tomorrow.
