### ISSUE TITLE
Sync Button does not reset options

### ISSUE THREAD

**Issue by shshaw** [bdkjones/CodeKit2#44]
When changing Language Defaults for Javascript within a project's settings, the sync buttons do not update the file's output settings.

Current defaults applied to the file's output settings:
![screen shot 2013-12-18 at 4 03 00 pm](https://f.cloud.github.com/assets/777155/1778160/65c4c5ce-6830-11e3-8660-4b131a216b6c.png)

Changed the defaults and hit Sync button (confirm dialog came up)
![screen shot 2013-12-18 at 4 04 10 pm](https://f.cloud.github.com/assets/777155/1778165/7e989288-6830-11e3-81c9-751bbf48c224.png)

Original defaults still applied:
![screen shot 2013-12-18 at 4 04 14 pm](https://f.cloud.github.com/assets/777155/1778167/8d84c780-6830-11e3-8745-d05504367983.png)

The sync buttons were not causing the file preferences to update, and the sync button for "Initial output path" was occasionally not clickable unless the window was resized which could be related to the scrolling issues (#13)

**Comment by bdkjones** [comment]
Which sync button did you click? There is one per section. Clicking the top one will apply the default file settings. Clicking the bottom one (near the output path area) should reset the output paths for JS files.

**Comment by shshaw** [comment]
Both, and neither would actually update the files view. Even the main sync
button didn't update it.

**Comment by JesusGarciaValadez** [comment]
I agree. I've seen that this behavior happens in SASS and JS. No matter if I set the path in each settings. I have to select the directory manually for each file who has an output path selecting each one separately.

**Comment by BabylonSix** [comment]
This also happens for stylus and jade

**Comment by bdkjones** [comment]
Fixed in Beta 4.
