### ISSUE TITLE
CodeKit interferes with window.scrollY

### ISSUE THREAD

**Issue by etchalon** [bdkjones/CodeKit2#441]
This was driving me mad for a full day, before I realized it was something a miss with CodeKit.

For some reason, when a file is loaded from Safari 8, or Firefox 32.0.3 (Chrome seems fine), the browser always reports the scrollTop as 0, or 1.

This messes with all sorts of libraries (scrollSpy and iScroll are my immediate issues).

I have no insight into why this is happening, though I can provide my current project for an example, if you contact me directly.

**Comment by bdkjones** [comment]
This is correct behavior. CodeKit remembers the scroll position before reloading the page and then sets it back when the page finishes reloading (for full page reloads. Style injections do not trigger this)

This warps the browser back to the position it was before the reload. Otherwise you'd have to manually scroll back down.

Please close.

**Comment by etchalon** [comment]
Bryan,

If this is the correct behavior, that you're overriding window.scrollY to achieve the effect, it needs to be optional.

Many many libraries and techniques poll or query scrollY.

This makes it impossible to develop within CodeKit for quite a few of my projects.

## 

Jack Shedd
Interactive Director, Mess
(sent from my phone)

On Sep 25, 2014, at 6:48 PM, Bryan Jones <notifications@github.com<mailto:notifications@github.com>> wrote:

This is correct behavior. CodeKit remembers the scroll position before reloading the page and then sets it back when the page finishes reloading (for full page reloads. Style injections do not trigger this)

This warps the browser back to the position it was before the reload. Otherwise you'd have to manually scroll back down.

Please close.

**Comment by etchalon** [comment]
I just updated to Build 17908 and the issue seems a good deal worse.

I seem to have two independent scrolling regions now. Very frustrating.

Again, I'm happy to provide a sample project privately. You can reach me @ jshedd@thisismess.com.

**Comment by bdkjones** [comment]
Okay, please post a link to download the sample project and exact steps to reproduce.

**Comment by etchalon** [comment]
Can I email you directly? This project is not publicly launching for a few weeks. I'd rather not have the code circulating on GH :dancers:

**Comment by bdkjones** [comment]
Sure, put it up on Dropbox and send me the download link. My email address is on the about page of the website.

-Bryan

**Comment by etchalon** [comment]
Emailed.

**Comment by etchalon** [comment]
I was able to resolve the issue by removing the 100% height on my body and html elements. 

Still weird, but for now, fixed for me. Closing.
