### ISSUE TITLE
Can't Change Default Bower Components Folder location for New Projects

### ISSUE THREAD

**Issue by ghost** [bdkjones/CodeKit2#445]
Using CodeKit 2.1.5 (17756) on a MBPr 15" mid-2014 with 10.9.5, when I click to change the default settings for new projects I can't click on the field of the Bower Components Folder Location.
![4df80ca0-a04b-4f74-b1a0-4261acac44b7](https://cloud.githubusercontent.com/assets/7997337/4441070/cbab54b6-47cd-11e4-8eb1-7e6e72701796.gif)

**Comment by bdkjones** [comment]
Fixed for the 2.1.8 release. 

The issue is that I'm a dumbass and simply copy/pasted the "project name" textfield when I created this UI screen, but I didn't get rid of the binding that makes that textfield disabled when editing New Project Defaults (for which there is no project name to set).
