### ISSUE TITLE
Request: BrowserSync integration

### ISSUE THREAD

**Issue by Chrisedmo** [bdkjones/CodeKit2#448]
Hey man - first up, I love Codekit. And I was showing a colleague (and now he has it). and we were joking about how the live reload thing is crazy, but thought what it if mirrored your clicks / scroll etc… 

Then a few days later i saw this: https://github.com/shakyShane/browser-sync

Not sure how/if it would be possible - but some kind of integration with this plus your server / reload trick would be insane. 

Thanks.

**Comment by badabam** [comment]
I would also love to see this in Codekit!

**Comment by bdkjones** [comment]
Done. 2.2

**Comment by nicooprat** [comment]
Hi

That works well ! But I was wondering if there's a way to temporarily deactivate it though, because sometimes my colleagues just want to navigate on the site while I'm working on it : not very convenient !

**Comment by bdkjones** [comment]
http://incident57.com/codekit/help.html#browser-sync

**Comment by nicooprat** [comment]
Hmmm I might not be very clear, or I did't understand this doc that I already read, but I can't find any way to temporarily disable BrowserSync.

**Comment by bdkjones** [comment]
![screen shot 2015-02-11 at 10 28 48](https://cloud.githubusercontent.com/assets/926566/6153370/08009726-b1d9-11e4-92ee-995ce84a73b0.png)
