### ISSUE TITLE
Assest don't remember the chosen column to sort by after restart

### ISSUE THREAD

**Issue by rpkoller** [bdkjones/CodeKit2#45]
- Go to the Assets pane
- Click e.g. on the name column, that the list is sorted alphabetically
- Quit Codekit
- Restart Codekit
- Go to Assets pane again
- The sort order got reverted again and lost the chosen alphabetical by name

**Comment by mdavis1982** [comment]
@bdkjones I've marked this as a bug - but is this expected behaviour?

**Comment by bdkjones** [comment]
Yes. This is expected behavior. CodeKit always sorts by the number of stars because Bower is so full of junk it's useless to sort any other way.
