### ISSUE TITLE
Extra options for Slim

### ISSUE THREAD

**Issue by drgullin** [bdkjones/CodeKit2#450]
Thanks for adding a new `include` syntax :+1: 

I wonder why .slim output is always minified, since Slim supports pretty output and many other options
https://github.com/slim-template/slim#available-options

I'd like to suggest the options like:
- Output format - html5 or xhtml (`:format`)
- Indentation - 2 or 4 spaces, or a single tab (`:tabsize`)
- Pretty output checkbox (`:pretty`)

**Comment by bdkjones** [comment]
Those options are available. Choose a Slim file in the CodeKit UI to adjust them or change them for all Slim files in the project at once in Project Settings > Languages > Slim.

**Comment by drgullin** [comment]
Got it, thanks.
