### ISSUE TITLE
CodeKit breaks the default application to open file type

### ISSUE THREAD

**Issue by drgullin** [bdkjones/CodeKit2#451]
When I set "open .sass files always in Sublime application", OS X successfully opens them first time.

If I try to double click on some sass file then, it's opened by a CodeKit app. 
Looks like CodeKit breaks something related to "default app for the file type".

**Comment by bdkjones** [comment]
I don't see that behavior on my machine. Sass files are set to open with Coda 2 by default for me.

Did you click the "Change all" button in the "Get Info" window after choosing Sublime as the default app to open that particular Sass file?

**Comment by drgullin** [comment]
http://grab.by/B0Zq
Text near a checkbox says "open always using this app".
This works well for the other file types, which aren't already assigned to be opened by CodeKit.
There's no "change all" button, just an "open" button instead inside a current popup.

What am I doing wrong?

**Comment by bdkjones** [comment]
Yea, but that only applies to that one file.

Choose any Sass file in the Finder, right-click and choose "Get Info". Look at the "Open With" section.

**Comment by drgullin** [comment]
Thank you Bryan!
