### ISSUE TITLE
HTML5 or XHTML for Slim

### ISSUE THREAD

**Issue by drgullin** [bdkjones/CodeKit2#452]
Slim templates are always compiled using the XHTML syntax.

Example:

```
input type="search" => <input type="search" />
```

While I'm using HTML5 doctype, I would like to have an HTML5 output.

There's a `:format` option for this https://github.com/slim-template/slim#available-options

**Comment by bdkjones** [comment]
Hi Damir,

```
Okay; thanks. I’ll get this implemented. 
```

**Comment by drgullin** [comment]
Any news?

**Comment by bdkjones** [comment]
It’ll be in the next update.

**Comment by bdkjones** [comment]
Done for 2.2
