### ISSUE TITLE
Small glitch in the error log area

### ISSUE THREAD

**Issue by mgrn0** [bdkjones/CodeKit2#453]
I noticed a small visual glitch in the error log output when resized, I recorded it with a screencast: After window resizing the last error log output is cut off when window width is below a certain threshold..

https://dl.dropboxusercontent.com/u/81358/jing/codekit-errorlog.mp4

![2014-10-09_11-10-12](https://cloud.githubusercontent.com/assets/3019226/4573598/22a41c3a-4f94-11e4-8239-d8fbe4fac624.jpg)

Codekit version used is 2.1.7

**Comment by bdkjones** [comment]
Fixed for 2.1.9.
