### ISSUE TITLE
Weird compass errors in Compass 2.1.7 ?

### ISSUE THREAD

**Issue by mgrn0** [bdkjones/CodeKit2#454]
I use codekit 2 for compass projects mainly and I noticed since the last update that no matter what is causing a compass/sass compilation error (use of a non-existant variable, syntax errors, missing bracket, etc) there is always the very same error that does not help pinpoint what is causing the error:

`TypeError on line ["184"] of /Applications/CodeKit.app/Contents/Resources/engines/scss/lib/sass/error.rb: Hash can't be coerced into Fixnum
Run with --trace to see the full backtrace`

I am using codekit's internal compiler for compass as well as sass.

![2014-10-09_11-03-10](https://cloud.githubusercontent.com/assets/3019226/4573666/cb4466d8-4f94-11e4-9f86-fd2e989ff6cd.jpg)

**Comment by bdkjones** [comment]
Thanks. CodeKit doesn't generate those error messages; it simply passes on whatever the Compass compiler said. 

I've tagged @chriseppstein (the author of Compass) in this issue. What he'll need you to do is install the very latest version of the Compass gem on your Mac and then compile your file from the command line, outside of CodeKit, with a syntax error that results in the message you posted above. 

If the command line Compass compiler spits out the same message, it's an issue that will need to be addressed in Compass.
