### ISSUE TITLE
Notification Center Integration not working

### ISSUE THREAD

**Issue by mgrn0** [bdkjones/CodeKit2#455]
I don't know why but I cannot get Notifications to work properly on my current setup (imac, osx 10.9.5, codekit 2.1.7).

Notification Center Preference is on (as below) and other apps show notifications, however codekit does not popup any success messages nor do they show up in the notification center area (the right bar at the edge of the screen):

![screen shot 2014-10-14 at 09 13 53](https://cloud.githubusercontent.com/assets/3019226/4625139/b314b9ce-5371-11e4-8f34-bca1aafb2566.png)

Any ideas or logs that would be helpful to debug this issue? Restarting the mac and restarting the notification center process did not help.

**Comment by mgrn0** [comment]
ah sorry, that was not a codekit issue. clearing the notification center database file and restarting codekit did the trick, if anyone is interested or runs into the same issue some day: 
http://stackoverflow.com/questions/11856766/osx-notification-center-icon/#answer-12363833

```
delete ~/Library/Application Support/NotificationCenter/SOME_UUID.db) 
and then kill the Notification Center process (e.g., from Activity Monitor)
```

**Comment by bdkjones** [comment]
Thanks for the tip!
