### ISSUE TITLE
Feature Request (API): Trigger actions on a file

### ISSUE THREAD

**Issue by subhaze** [bdkjones/CodeKit2#460]
It'd be nice to have the ability to send a `compile`, `check syntax`, `process`, etc command to a file.

I'm not really familiar with AppleScript, but it would be really awesome if you could send back details, especially on the `check syntax` that developers could display.

**Comment by bdkjones** [comment]
Yea, I eventually plan to expose the compile command. Sending feedback from the syntax checkers is an interesting idea. I dunno if AppleScript is robust enough to handle that much response data, but I'll experiment.
