### ISSUE TITLE
API: select project containing path

### ISSUE THREAD

**Issue by subhaze** [bdkjones/CodeKit2#461]
I've found that having a `.` in the name of a folder causes CodeKit to select the wrong project. I have two folders, one named `fbitn` and another `fbitn.files` and when executing the `select project` command for `fbitn.files` it will instead select the `fbitn` project.

**Comment by bdkjones** [comment]
That’s probably got to do with the compiling that takes place to send AppleScript over to a Cocoa app. The solution is to not have periods in your folder names, for now.

**Comment by subhaze** [comment]
Fair enough :)

And thanks for all the quick responses.
