### ISSUE TITLE
Allow self-signed certificates

### ISSUE THREAD

**Issue by subhaze** [bdkjones/CodeKit2#462]
I've a project that needs to run on https so I'm using a self-signed cert from Mamp Pro and when I go to preview the site it shows an error page due to the cert.

"The error returned was: "The certificate for this server is invalid."

**Comment by bdkjones** [comment]
Yea, the handling of SSL certificates is... complex. Post the steps you followed to set up the self-signed cert with MAMP and I'll see what I can do about supporting it with the proxy server.

**Comment by subhaze** [comment]
Yeah, I was afraid of that. As far as setting up the cert I just used the GUI, I've moved up to Pro so that it handles the /etc/hosts and all that fun stuff. So the basic process for me is:

create a new host
updated the name to `example.dev`
keep the box checked for `Name resolution via /etc/hosts`
click the `ssl` tab and generate a key with, US/TN/Knoxville/Company/address@example.com
then save the cert and restart the server

Mamp Pro has a new UI now, but very similar to this process https://tommcfarlin.com/enable-ssl-in-mamp/

[Update]

And I'm using the normal ports 80/443
