### ISSUE TITLE
Combine multiple CSS files? (like @codekit-prepend for CSS)

### ISSUE THREAD

**Issue by dennisfrank** [bdkjones/CodeKit2#463]
I am looking for a way to combine multiple CSS (not Sass) files into one file. It would be extremely useful for all those bower components, where changing the extension to `.scss` is not practical.

I tried `@codekit-prepend` like `// @codekit-prepend "../../../bower_components/owl.carousel/dist/assets/owl.carousel.css"` in my main Sass file but `@codekit-prepend` seems only to work with JS. 

Any ideas?

**Comment by bdkjones** [comment]
Yea. The answer here is that Less and Stylus already offer a way to "inline" CSS imports, which means you write something like:

```
@import (inline) "someFile.css";
```

And the contents of the CSS file replace the import statement. The Sass team is working on implementing this. This is why I've held off implementing a CodeKit-only approach.

Until Sass is ready to go, you can use Stylus or Less to achieve the same thing. Just create a *.styl or *.less file and import all the CSS files using each language's inline syntax. (For Stylus, there's even a checkbox in the CodeKit UI to inline CSS imports).

**Comment by nicolastaffin** [comment]
Yes, this works, but then, less mignification options selected seems not to be applied. (CK2.2)

**Comment by gpapin** [comment]
@bdkjones Do you have any update on the sass inline import of css lib ? According to [this](http://stackoverflow.com/questions/7111610/import-regular-css-file-in-scss-file#answer-30279590) it should work but Codekit always state that it can't find the file if I don't put the .css extension

**Comment by bdkjones** [comment]
The Sass team still hasn't implemented this. I believe a full overhaul of @import was scheduled for their next major release.

**Comment by gpapin** [comment]
Thanks for the update, I'm looking forward to whatever is coming this fall
;)

2015-08-27 17:02 GMT+01:00 Bryan Jones notifications@github.com:

**Comment by Bangkokian** [comment]
The only problem with this is that I've got third party (non-Sass) css files that I'd love to compile into one css file. Is the recommendation here to write a Sass file that imports them all? Would be awesome if this worked consistently like javascript prepend/append.

**Comment by andreasley** [comment]
Inline imports with `@import` in .scss files work if you omit the suffix. For example, if you want to import `somefile.min.css`, do this:

`@import "somefile.min";`

(tested in CodeKit 3.10.2)
