### ISSUE TITLE
Question about config.codekit

### ISSUE THREAD

**Issue by subhaze** [bdkjones/CodeKit2#467]
From a plug-in stand point would it be safe to modify the `projectSettings` or specific file settings if you're vigilant of the `settingsFileVersion` maybe pausing CodeKit first or would this cause some potential issues within CodeKit having this file changed from underneath it?

I read "MODIFYING THE CONTENTS OF THIS FILE IS A POOR LIFE DECISION" but those have gotten me pretty far in life so far :P

But on a serious note, my main thoughts are toggling source maps on/off or toggle a file ignore property, simple boolean adjustments, though... maybe this would be better suited from the API?

**Comment by bdkjones** [comment]
_technically_ you can do this. However, it's extremely dangerous. If you write to that file and the JSON syntax isn't valid, or you assign an incorrect value to something, there are no safety checks In CodeKit and it will likely cause a crash.

Example: the file type property is a 64-bit integer that is a bitwise mask of an enumeration declared in CodeKit's source. So if you plug some random integer in there, CodeKit will definitely do bad things to that file. Lots of the property values aren't very helpful, either. "Output style" for example is usually 0, 1 or 2, which map to enumeration values in CodeKit's source that match the drop down options for languages.

So the official answer is, "poor life decision" but the unofficial answer is, "fuck it, see what happens".

**Comment by bdkjones** [comment]
Eventually, I do plan to expose these settings in the API.

**Comment by subhaze** [comment]
Haha, aight, and thanks for the details. I'll toy around with some small things, see how that goes. If it's worth it, potentially add a 'poor life decision' section.
