### ISSUE TITLE
Feature Request (API): Access to project refresh

### ISSUE THREAD

**Issue by subhaze** [bdkjones/CodeKit2#468]
With this we could use the option of `Auto-Refresh Projects: Never` and easily trigger a refresh when we need it from the comfort of our ~~couch~~ editor.
If the editor has an API to know when new files were added, plug-ins could automatically trigger this and we could leave the polling/remembering to refresh in the past.

**Comment by bdkjones** [comment]
The reason I didn't include this is that CodeKit automatically detects when a project needs to be refreshed and does so. 

If you add a new file, for example, the app refreshes the project right then.

**Comment by subhaze** [comment]
Ah, good to know. I'm curious of the benefits to having it auto-refresh every Xmins?

**Comment by bdkjones** [comment]
It's a catch-all just in case. Really, a legacy setting from CodeKit 1 which didn't auto-refresh. I wasn't totally confident in the auto-refresh detection when I was building 2.0, so I left that in there. Should probably pull it.

**Comment by subhaze** [comment]
Cool, I'll roll with no auto-refreshing and send you another ticket if it doesn't :P
