### ISSUE TITLE
Previewing project running on local server

### ISSUE THREAD

**Issue by C-Benz** [bdkjones/CodeKit2#47]
I'm having issues previewing changes. I think my dev environment may be a bit unique. I have a Mac Mini on my local network on which all my project files are stored. That Mac Mini is running MAMP. To access a project, I just go to 10.0.1.100:8888 (the local address of the Mac Mini) and I get my Apache root which lists all my clients. I then select a directory and then another directory which has the web files. The reason this setup works so nicely is all the other people in my office share the same set of web files. MAMP on the Mac Mini also means we are all seeing the same data as our databases are all the same. 

The problem is when I click the preview button, it takes me to a list of all my clients (the same as my Apache root) instead of into the correct directory for that project. In Codekit, I have set my External Server Address for that project to http://10.0.1.100 and the port to 8888. 

Is this a limitation of the new preview method in Codekit 2?

**Comment by mdavis1982** [comment]
You'll need to add the folder name to the external server: `http://10.0.1.100/foldername`

Can you try that and let us know if it works please?

**Comment by C-Benz** [comment]
Do I do this in my Codekit projects settings in the "External Server Address" field or do I append this to the URL in my browser?

**Comment by mdavis1982** [comment]
@CaptainJuiceBox In the project settings.

**Comment by C-Benz** [comment]
Kinda works but fails to pull in any external stylesheets, javascript, or images. The site I'm testing is a cakephp site which has a htaccess in the root that defines a subdirectory as the webroot where the css, js, img folders exist. I can pull the site up like I normally do by going to 

http://10.0.1.100:8888/CETrend/svn
"CETrend" is the client name and "svn" is the directory with the cakephp web files.

So for Codekit, first I dragged my svn directory in and it added just fine.
Then, I updated my project settings to:
External Server Address: http://10.0.1.100/CETrend/svn
External Server Port: 8888

The page loads and PHP appears to be pulling the proper data from the database in, but it's not able to find any of the external files. If you want I'm more than happy to share my screen over join.me and show you exactly what's happening.

**Comment by mdavis1982** [comment]
Have you checked "Always use External Server" in the same settings area?

**Comment by C-Benz** [comment]
Yeah no dice.

**Comment by mdavis1982** [comment]
I'd say this was a local configuration issue. It's the same issue as #31, #22, #23, #15. Those issues should give you everything you need to get this working.

**Comment by C-Benz** [comment]
Sounds good. I'll just need to adjust my workflow a bit and start using vhosts instead of just navigating to my project directory. Thx for the help

**Comment by bdkjones** [comment]
What folder is the htaccess file located in?

Where does the htaccess file point to for the webroot?

**Comment by C-Benz** [comment]
The site is built on cakephp so there are actually 3 htaccess files. There's one in the root, one in app, and the last in app/webroot. It's this directory (app/webroot) that behaves as the webroot and contains css, js, and img directories.

Here's a screenshot of the structure:
![files](https://f.cloud.github.com/assets/4439110/1779194/3771231c-6843-11e3-88de-177ac53b0809.png)

**Comment by bobrocke** [comment]
I don't know if this adds to this issue or is another problem entirely.

CK2:
External Server Address: http://www.brp.dev
Always use external server

MAMP Pro:
Virtual server: www.brp.dev
Disk location: /Volumes/Data/Sites/vhosts/www.br.dev
There's a WordPress site there.

Clicking preview goes to http://rockbox.local:5757 and the page loads normally (good)
Clicking on the About menu link on that page goes to http://rockbox.local:5757/about-me/ (good)
Clicking on the Contact menu link on the About page goes to http://www.brp.dev/contact-me/ (bad)

Is it my configuration? How do I fix that?

Or is it CodeKit?

**Comment by bdkjones** [comment]
The new "web root" option implemented in Beta 4 should solve this issue. You simply append the path to the folder where the project's web root is located.

**Comment by C-Benz** [comment]
Wow! Beta 13 makes it so easy for me to preview with my server setup. If I'm not mistaken, the new "Preview Subpath" field makes setting up vhosts unnecessary?!

**Comment by bdkjones** [comment]
Yea, the whole thing was designed just for your particular case.

**Comment by C-Benz** [comment]
You are a gentleman Mr Jones.
