### ISSUE TITLE
Yosemite + CodeKit 2.1.8 + External server

### ISSUE THREAD

**Issue by bulleweb** [bdkjones/CodeKit2#470]
Hello,

I have a trouble with CodeKit.
I use an external server address (127.0.0.1:8888), the option "External server Required" is checked but, when i press the button "Preview", the URL in all browser is not correct (http://www.mbp-de-xxxxxx.com:5757 instead of 127.0.0.1:8888).

Regards,
Samuel

**Comment by bdkjones** [comment]
Thanks for getting in touch. Please make sure you watch the Browser Refreshing screencast and/or read the help section about browser refreshing. 

This is correct behavior --- the preview button never loads your external server directly.
