### ISSUE TITLE
Feature Request: Framework languages settings

### ISSUE THREAD

**Issue by jackw** [bdkjones/CodeKit2#473]
Possibly my use case is unique but I have some quite large projects that use the same frameworks (sass and javascript). These frameworks are written in house and it'd be really helpful to have the same language options that are available to projects be available to frameworks mainly so I can disable the javascript from minifying as this is handled in a build script.

**Comment by bdkjones** [comment]
Framework files are imported by files in regular projects. The settings that matter are the ones on the regular project files doing the importing. Those are the settings that will be used when those files are compiled.

**Comment by jackw** [comment]
In that case I'm doing things wrong. Most likely my JavaScript framework should be a project in codekit. Thanks for the explanation.

**Comment by bdkjones** [comment]
Did you watch the Frameworks screencast? Files in Frameworks aren't really meant to compile to output directly.

**Comment by jackw** [comment]
Sorry, yeah I've watched it now. I've reimported what was a framework as a project in codekit and it's behaving itself as expected. Could possibly close this issue, given it was my misunderstanding?

**Comment by bdkjones** [comment]
Awesome. Glad to hear.
