### ISSUE TITLE
Codekit lost all the projects

### ISSUE THREAD

**Issue by ericbae** [bdkjones/CodeKit2#479]
I opened my Codekit this morning to find all the projects are gone.

I had about 7 projects in there. Not a huge deal, I can import each project again one by one, but it's still annoying. This is the second time that happened.

![screen shot 2014-10-27 at 10 39 14 am](https://cloud.githubusercontent.com/assets/614459/4784859/8aa47e00-5d69-11e4-88cb-2531f100e24a.png)

**Comment by bdkjones** [comment]
This happens if you hold the shift key while launching the app. That causes a safe start, which discards the app's data file and gives you a fresh start.

**Comment by pouipouidesign** [comment]
This happened to me this morning, although I don't remember holding the shift key...
I had TONS of projects, I'm in a huge pre-launch hurry, and there's just no way I can import them one by one again: is there any other way to get my data back??

**Comment by bdkjones** [comment]
No, there's not. You shouldn't keep "tons" of projects in CodeKit. That causes the app to use way, way more resources than necessary. Ideally, you should have just the projects you're actively working on in the app and then remove them when you move to other projects. Each project retains its settings so they always come back as you left them.

**Comment by pouipouidesign** [comment]
Well, I have more or less 7 projects "active" at all time, which I think is "a lot" but maybe I'm mistaken ^^

In any case, dropping the folder back on CodeKit does indeed get all my data/settings snugly back in place, so at least that's that.

Thanks for the speedy (if terse) answer! ;)

PS: I really don't think I was holding the shift key though, is there something to be investigated? (ie. if this happens again)

**Comment by ericbae** [comment]
It happened to me today, again. I had 4 projects, which I don't think is many. Like @pouipouidesign, it's not hard to add the projects again, since the codekit config files are there, but I do think there is a problem of CodeKit losing all projects intermittently, and I am definitely not pressing the shift key.

**Comment by bdkjones** [comment]
If it happens again, immediately open Console.app and look for any messages logged by CodeKit. Post those here.

**Comment by ericbae** [comment]
I'm hoping this is the log that was generated by Codekit when it lost all the files (which was about 12 hours ago). Otherwise, I'll post it here next time it happens.

![screen shot 2014-12-17 at 10 21 36 pm](https://cloud.githubusercontent.com/assets/614459/5470385/2230dbca-863b-11e4-96fd-e7fb56c3114e.png)

**Comment by bdkjones** [comment]
Huh. Something is seriously wrong if that's getting logged to the console. Try deleting the app from your system and downloading a fresh copy from the website. Also: try repairing your disk using Disk Utility.

**Comment by etheya** [comment]
Ive just had the exact same thing happen on auto updating the app.... everything has gone when its finished installing the update... :/

**Comment by warrickbayman** [comment]
This happened to me as well. Twice. I have reason to believe that on at least one of of those occasions, I was holding the shift key. But definitely not intentionally. Shift is a fairly important key as far as day-to-day use goes. Is there no way this could be a key-combination? Perhaps "option-shift", which would be a little less likely to be pressed "by accident". I would have thought it to be quite rare that I would be holding the shift key while launching an app, and from now on I'll make sure I don't do so while loading Codekit, but it seems like it does happen on occasion.

**Comment by JonnaIsaac01** [comment]
This happened to me as well. It is the second time (thought it hasn't happened for months). I'm 90% sure I wasn't holding down shift, though I agree with other commenters, that's a commonly used key and wouldn't be completely out of left field for it to be pressed for some other reason during start up. Any updates on this? The issue is closed, but I'm not seeing a resolution. Thanks!

**Comment by bdkjones** [comment]
The shortcut is modeled after Apple's. You hold the shift key while starting a Mac to boot into safe mode.

It's pretty uncommon to be pressing modifier keys while launching apps. The only time you could potentially get into trouble is if you launch CodeKit and then immediately start performing other operations via keyboard shortcut. The window of time in which CodeKit detects the shift key is very, very small. You must press it before the window UI appears on screen.

**Comment by bdkjones** [comment]
There are a couple plugins (the CodeKit Sublime Text plugin—which is not written by me) that auto-quit and auto-launch CodeKit. A few people ran into problems there. They'd be using a keyboard shortcut to switch/close windows in Sublime and the plugin would auto-launch CodeKit, which saw the shift key and cleared everything.

The plugin author changed that behavior a while back. You might check that, though, as well.
