### ISSUE TITLE
libsass with source-maps

### ISSUE THREAD

**Issue by sebastiannm** [bdkjones/CodeKit2#48]
Today libsass has added the possibility to include Source-maps.

As it's not possible with the latest version of CK, I link to the repo with the issue fixed:

https://github.com/hcatlin/libsass/issues/122#issuecomment-30872304

**Comment by bdkjones** [comment]
I tried implementing it, but something does not seem right with libsass. Going to have to work on this.

**Comment by bdkjones** [comment]
Implemented in Beta 5. 

HOWEVER: there is still a fatal bug in libsass that is going to cause source maps to fail in your browser (even though the .map file will be created correctly). See --> https://github.com/hcatlin/libsass/issues/217
