### ISSUE TITLE
Preview Stopped Working - Yosemite - 

### ISSUE THREAD

**Issue by joshsmith01** [bdkjones/CodeKit2#480]
I was working locally with MAMP Pro (3.0.7.2), CK (2.1.8), and Coda2.5. I had already updated to Yosemite a few days prior and everything was working together. 

All of a sudden, CK browser refreshed ( on its own I think ) and then I got this message: 
![screen shot 2014-10-26 at 9 51 12 pm](https://cloud.githubusercontent.com/assets/1550745/4786441/e8f7d170-5d94-11e4-90ba-621169db8072.png)

I tried the Shift restart for CK, no help. I manually removed all the projects from CK. I ran the defaults `delete com.incident57.codekit2` tip, no change. I have refreshed the CK server and MAMP Pro. 

I did  just install the Coda 2.5 plugin, but since have uninstalled it. Still no change in behavior. 

I can, however, see the local site with the non-bonjour link in the 
![codekit_and_new_issue_ _bdkjones_codekit](https://cloud.githubusercontent.com/assets/1550745/4786469/b9589372-5d95-11e4-94ff-6b105fb3c035.png)

I am at loss.

**Comment by bdkjones** [comment]
Have you tried rebooting?

**Comment by joshsmith01** [comment]
I have tried rebooting. The problem remains.

**Comment by bdkjones** [comment]
It sounds like something has broken the bonjour hostname resolution on your Mac. Unfortunately, I can’t specify what the exact cause is. CodeKit just uses the Bonjour networking name; it does not set or alter it.

**Comment by joshsmith01** [comment]
So you're right, it is the bonjour address. I have my computer set to `Joshua-Smiths-iMac` and Code Kit should be using `Joshua-Smiths-iMac.local:5757:xxxx` right, But it is not, nor has it ever. CK uses `server.local:5757:xxxx` with the preview. I suspect that is a holdover from when I had Apple's Server installed on computer. I have since (years ago) removed it. 

In System Preferences > Sharing, I changed my computer's name from `Joshua-Smiths-iMac` to `server` and everything worked perfectly. I then changed it back to `Joshua-Smiths-iMac` and then CK's preview started working but on `server.local:5757:xxxx`.  I just tried to uninstall and reinstall CK but once reactivated it took on its old settings. 

Is there a setting or procedure to change in CK so that it doesn't pick up the `server.local` address?

**Comment by bdkjones** [comment]
No. Every time your Mac wakes, your network status changes, or you start CodeKit, the app asks OS X for the current list of hostnames identifying the computer. This list changes dramatically as you shift networks, etc. CodeKit scans that list and grabs the first one that contains “.local”. In your case, it looks like it’s grabbing the server name instead of your Mac’s actual name. OS X does not provide any order to the list of hostnames; they are returned in a random set. The best thing to do would be to look into removing the “server” bonjour hostname somehow.

**Comment by joshsmith01** [comment]
The quick incorrect solution is to rename my computer to `server`. 

It looks like there are other people struggling with how to remove OS X Server and its remnants from their computers as well. I'll keep digging.

**Comment by joshsmith01** [comment]
This is a host name issue. Server.app must have changed my computer's host name to server and thus my address to server.local:5757. 
I tried to change the host name via Terminal to no avail. Likewise, changing the computer's name in Sharing didn't change the host name, they are two different things. 

I reinstalled Server.app to see if that could change something. At the setup phase of Server.app, there are options to change the Host Name and Computer Name. I changed my Host Name to my computer name. I don't use Server.app but for some reason after the initial installation I was unable to take back control of those settings. 

All is well now, I have a superfluous application on my computer. My workflow works, which is the important thing.

**Comment by morganfeeney** [comment]
Same thing happened to me, I no longer can click preview using the Bonjour service. However if I go direct to localhost:5757 I get the preview. Not ideal.

**Comment by bdkjones** [comment]
See: http://stackoverflow.com/questions/26456803/codekit-2-doesnt-resolve-bonjour-hostname-after-yosemite-10-10-upgrade

**Comment by morganfeeney** [comment]
Thanks, I have tried that and still could only go direct. Not by clicking on the link provided for preview a la CodeKit. So updated my hosts file so now can visit [name].local:5757 still get live reload etc.
