### ISSUE TITLE
HTTP Verbs not supported? 

### ISSUE THREAD

**Issue by prashank25** [bdkjones/CodeKit2#483]
I have a nginx server running locally on mavericks 10.9.5

![screen shot 2014-11-02 at 10 16 31 am](https://cloud.githubusercontent.com/assets/5788844/4874291/d2ff3906-624b-11e4-87cb-9fb939663d23.png)

Http verbs PUT and DELETE gives 405 Method not allowed response when accessed through codekit, if i access them directly, it works fine.

![screen shot 2014-11-02 at 10 23 38 am](https://cloud.githubusercontent.com/assets/5788844/4874299/b77e4996-624c-11e4-8c6d-925c8e2f0777.png)
Accessed through codekit - Doesn't work

![screen shot 2014-11-02 at 10 25 25 am](https://cloud.githubusercontent.com/assets/5788844/4874302/cf57e6a8-624c-11e4-995c-739ba58bd302.png)
Accessed directly - Works

Its not backend issue cuz post/get does work fine.

![screen shot 2014-11-02 at 10 29 43 am](https://cloud.githubusercontent.com/assets/5788844/4874309/3553008c-624d-11e4-9226-ae288a41144a.png)

**Comment by bdkjones** [comment]
Yea, put and delete are currently not supported. It's on my list, though. 

The commands simply aren't all that common these days.

**Comment by tikiatua** [comment]
Hi @bdkjones,

really love codekit and use it almost daily for my work. It would be awesome if you could add the put, patch and delete methods as those are quite handy when developing a RESTful api interface.

**Comment by maxxscho** [comment]
+1 would be cool, if these methods are supported.

**Comment by martinVelicky** [comment]
+1. 

If you working on web-app that is connected to modern REST API, disabling PUT and DELETE makes the development more complicated.

**Comment by ashjmcfox** [comment]
+1

Building an AngularJS application which is powered by a RESTful API. Really needs to support PUT and DELETE. I've had to revert to using MAMP server on its own, which is a shame as I love the live refresh features of CodeKit.

**Comment by bdkjones** [comment]
PUT and DELETE support added for 2.2.1. Should be out tomorrow or early next week, depending on when Libsass 3.2 ships. 

Note: using these verbs will require an external server for the project. You'll flip on the "external server required" switch and CodeKit will proxy the requests.

**Comment by maxxscho** [comment]
Cool! Thx!!

**Comment by ashjmcfox** [comment]
Thank you!
