### ISSUE TITLE
Feature Request: Custom Boilerplates

### ISSUE THREAD

**Issue by subhaze** [bdkjones/CodeKit2#484]
These could act similar to the Zurb Foundation install, where you'd need a clean folder and the boilerplate could be pulled down from a git repo that the user defines.

With this setup we could have base projects for WordPress/Drupal/Static Site/etc... with a custom config.codekit file and hooks for said projects ready to go! <3

**Comment by bdkjones** [comment]
Hi Michael,

```
Thanks. This is on my list!
```
