### ISSUE TITLE
Outdated version of asset being installed via Assets Panel with no update available

### ISSUE THREAD

**Issue by jambox** [bdkjones/CodeKit2#485]
Hey I'm trying to switch over to using your Bower integration for asset management. A couple snags here and there but generally solid.

Found and installed [jQuery Modal](https://github.com/kylefox/jquery-modal) via the Assets panel:
- expected results : install `v0.5.5`
- actual results: installed `v0.5.2`
- config : MBP running Yosemite 10.10, CK 2.1.9, 6'1", brown hair.

There's no update available through the assets panel and, with the limited Bower-specific knowledge I have, it seems there's no problem with the repo's `bower.json` file (proper version is there).

Thanks!

**Comment by subhaze** [comment]
@jambox I'm not much of a bower user either, but I think CodeKit is loading in the proper version. The master branch may have 0.5.5 in the bower.json file but it's only tagged at 0.5.2.

More info can be found at http://bower.io/docs/creating-packages/#register
And the current tags (releases) for jquery modal can be found at https://github.com/kylefox/jquery-modal/releases

**Comment by jambox** [comment]
Sorry for the epic delay in responding! Thank you, @subhaze, for taking the time to answer. I haven't made time to double check this, as I already resolved it another way, but next time I want to use Codekit's assets loader I'll look more closely. Thanks!

**Comment by bdkjones** [comment]
@subhaze is correct. Please have the component author tag a proper release.

**Comment by jambox** [comment]
thanks for chiming in @bdkjones...will do!
