### ISSUE TITLE
Odd way to change the Javascript output suffix.

### ISSUE THREAD

**Issue by newelement** [bdkjones/CodeKit2#49]
It is currently set to -ck, but when I remove the characters to enter in new ones the message pops up to not leave it blank, but it does not give me time to enter anything and it removes focus from the input box. Yeah know I can enter something like -ck.min then erase the -ck. As noted it was difficult at first and I had to work around it.

**Comment by bdkjones** [comment]
Yea, this is intended behavior. I _really_ don't want anyone to overwrite their javascript with a minified version. You might say, "Well, people are smart." To which I would reply: "You haven't seen the emails I get."
