### ISSUE TITLE
external server with custom hostname not work.

### ISSUE THREAD

**Issue by Cyancat** [bdkjones/CodeKit2#490]
Yosemite + CodeKit 2.1.8 + External server

My external server address is `http://030x.local:8080`, which is a custom host defined at my /etc/hosts, and it pointed to 127.0.0.1

Before I upgraded to Yosemite, it works fine. But after I upgraded to Yosemite, it's not working and show as below:

```
What Happened:
CodeKit sent a request to the external server for this resource: http://030x.local:8080/ The error returned was: "The request timed out." (Code -1001)
```

tested on Yosemite safari and Chrome 38

some other information:
- direct access `http://030x.local:8080` works.
- external server set to `127.0.0.1:8080` works.
- not use external server, directly pick up from project folder works fine with auto-refresh.

Looks like the hostname on Yosemite causes this?

**Comment by bdkjones** [comment]
See http://stackoverflow.com/questions/26456803/codekit-2-doesnt-resolve-bonjour-hostname-after-yosemite-10-10-upgrade

**Comment by Cyancat** [comment]
bonjour hostname should be somehow different from hosts setting, I had a bunch hosts set at /etc/hosts which all pointed to 127.0.0.1

Whatever, follow the answer, I set my hostname to `030x.local`
Now I can access `030x.local:5757`to the codekit homepage, but with setting of an external server `http://030x.local:8080`, it still got the error. The result is same.

But the problem itself looks like causing by the hostname issue about Yosemite. 
Blank hostname is really a wired situation.

I will try some other ideas, anything helpful will be very appreciated.

**Comment by bdkjones** [comment]
I'm sorry; I don't understand that response.
