### ISSUE TITLE
Autoprefixer doesn't work

### ISSUE THREAD

**Issue by drgullin** [bdkjones/CodeKit2#494]
Hello.

I'm trying to use autoprefixer with compas, I'm using v2.1.9.

Here's the browser string I use:

```
Explorer >= 8, Firefox >= 10, Chrome >= 10, Safari >= 4, Opera >= 12, Android >= 4, BlackBerry >= 10, iOS >= 6
```

I've switched autoprefixer on for the preprocessors http://grab.by/CHg0
My config.rb looks like http://grab.by/CHg8

When I type something like `box-shadow: none`, I get a same property in CSS, without autoprefixed ones.

What's wrong?

**Comment by bdkjones** [comment]
Post an example project (zipped) that I can test with over here.

**Comment by bdkjones** [comment]
Oh. Wait. I just looked at your config.rb file. Get rid of that `autoprefixer-rails` nonsense. Either use Autoprefixer in CodeKit OR through Rails, but definitely not both.
