### ISSUE TITLE
Codekit not auto-refreshing for imports after a variable is set

### ISSUE THREAD

**Issue by binomialstew** [bdkjones/CodeKit2#495]
Sass files that are imported after a variable is set are not listed in the "Imports" section in Codekit. Because they are not recognized as imported files in Codekit, it does not auto-refresh when they are saved. For example, in the parent sass file:

``` sass
@import init

$variable: true

@import second

@import third
```

In CodeKit, _init.sass is listed as one of the imports in the sass file, but _second.sass and _third.sass are not.

Also, when _second.sass or _third.sass are saved, there is no auto-refresh, although when the parent file is saved, it does import all files successfully and refreshes as normal.

When the variable is set after all imports, auto-refresh and the "imported" list both work as expected.

**Comment by bdkjones** [comment]
Put quotes around the file names.

**Comment by binomialstew** [comment]
I tried both double and single quotes and also tried using the full file names—no difference in result with quotes

**Comment by bdkjones** [comment]
Ok, please post a file I can use to test and the exact expected results.

**Comment by binomialstew** [comment]
When setting up the test files, I found that it actually wasn't the variable. There's a comment above the variable that is causing Codekit to not recognize the imports below it.

``` sass
@import fonts.sass

/* This comment will prevent the following from being imported in Codekit, even though the rest of the file is processed normally

@import jquery-ui.sass
```

**Comment by bdkjones** [comment]
You need to close the comment delimiter. `/*` needs to be matched with `*/`. Or, use the single-line delimiter instead: `//`

**Comment by binomialstew** [comment]
Yep, thanks. Are there any plans for CodeKit to support sass's outdented comments in the future?
