### ISSUE TITLE
Error: invalid option: --no-sourcemap

### ISSUE THREAD

**Issue by funwithtriangles** [bdkjones/CodeKit2#496]
When working on old projects I sometimes have to use external compilers, using old versions of SASS/Compass. Unfortunately I'm getting this Compass error:

`Error: invalid option: --no-sourcemap`

Works fine when I use `compass watch` in the terminal. Wondering if this has something to do with the way CK now ignores most of the `config.rb` file? Is there any way around this?

**Comment by bdkjones** [comment]
This happens when you try to have CodeKit use an older version of Compass or Sass.

The API for Sass evolves as newer versions come out and earlier versions of the compilers don't recognize the newer API. Unfortunately, there's nothing I can do about that.
