### ISSUE TITLE
Problem with Autoprefixer

### ISSUE THREAD

**Issue by saulsolorzano** [bdkjones/CodeKit2#499]
Hi @bdkjones 

I'm having a problem with autoprefixer, I can't add new browsers to the string. The app comes with these
`> 1%, last 2 versions, Firefox ESR`

I can delete, but whenever I try to add one and click the Apply button the new string gets deleted. It's really frustrating. Thanks!

**Comment by bdkjones** [comment]
What version of CodeKit are you running?

**Comment by saulsolorzano** [comment]
The latest, 2.1.9 (18270)

**Comment by bdkjones** [comment]
Edit the string, then press enter. There is no need to hit apply when modding the Autoprefixer string.

**Comment by saulsolorzano** [comment]
Ohhh I went full retard. Thank you very much. Happy holidays

Cheers
