### ISSUE TITLE
Autoconfigure MAMP-"operation caching" window was gone after i've switched spaces right before accepting

### ISSUE THREAD

**Issue by rpkoller** [bdkjones/CodeKit2#5]
An alert panel popped up after the first start of Codekit stating that MAMP is running and that it would recommend to configure MAMPs operation caching. Before accepting i've changed my space to look something up in Safari but when i've returned to the space the alert panel was gone. I've minimized all open windows on the page in the hope it was just put into the background, like most of the time e.g. adium otr acceptance alert panels, but it was gone completely. 

Is there a way to check if Codekit has applied the necessary changes to MAMP anyways and if not how to reinvoke that procedure cuz the alert panel hasn't popped up again. 

i am running Codekit on 10.8.5 if that behaviour might be spaces related.

**Comment by bdkjones** [comment]
Interesting. I'll add a menu command to invoke this manually. For now, you can get the alert back by:
1. Quitting CodeKit.
2. Opening Terminal and typing `defaults delete com.incident57.codekit2
3. Launch CodeKit.

This will trash your preferences and start over.

**Comment by rpkoller** [comment]
But where on the MAMP side i would have to look to see if the configuration already worked (did a quick google for it but no luck with the "operation+caching mamp" line ;) ). Would take a look before i take your described steps. Am just curious if Codekit already took the necessary steps.

**Comment by bdkjones** [comment]
There are about 12 php.ini files buried in the MAMP folder. CodeKit inspects each one and edits it if necessary to disable opCache.

**Comment by rpkoller** [comment]
Ok i've reset the Codekit plist and afterwards the alert panel appeared again. After clicking yes it stated that the modification in the MAMP config worked and that i should restart MAMP in the case it was running. Seems it has worked flawlessly. 

But a manual check if MAMP needs tweaking caching wise and a manual invocation of the procedure would be nice on the user side (as a feature suggestion). For the case that after a MAMP update the caching get reactivated by them for example.

**Comment by Fequois** [comment]
@rpkoller If you are running MAMP Pro you can find it in the settings screen for PHP. If not, you will have to grep it.

On a side note, CK2 also successfully disabled it for me.

**Comment by rpkoller** [comment]
Ah thanks for the heads up @Fequois ! Only tried the trial version of MAMP Pro and haven't noticed there. I guess i will purchase it sooner or later - then it's good to know. At the moment i am just running the standard version. Thanks!

**Comment by bdkjones** [comment]
As discussed, I've added a manual menu option to reconfigure Mamp. It is in Beta 3.
