### ISSUE TITLE
Feature Request : Allow a Project to be used as a Framework

### ISSUE THREAD

**Issue by stef-rausch** [bdkjones/CodeKit2#502]
Currently CodeKit 2 does allow a _code base_ :
- either to be used as a `Project`
- or as a `Framework` only.

I am starting a side project, where I would like to use the implemented features in other projects too.

For the time being the workaround is to remove the project from the project list and to add it to the framework list. Accordingly the other way around, when it's time to continue the development of the side project.

It would be great, if CK would allow **projects to be frameworks** in parallel too.

There should be no issues regarding the `@import` of the files on the framework side :

> It is not possible to define the order in which Framework folders are searched for an imported file. If two CodeKit Frameworks both contain a file named "standard.scss" and you write @import 'standard';, either Framework file may be used in that spot and the one used may change each time you compile the file.

Unique file names should always be chosen.

**Comment by stef-rausch** [comment]
@bdkjones , what are your feelings ?

**Comment by bdkjones** [comment]
Yea, the trouble here is that this starts to create really complex spaghetti dependencies. The better solution is to factor out the code that you want to share between projects and put that code into a Framework. It's much cleaner that way.

**Comment by stef-rausch** [comment]
Thanks for the feedback @bdkjones . That's indeed what I am doing, however, sometimes the framework is a mini project per se. As said one can manually switch depending on the ( developer / user ) hat one has on.
