### ISSUE TITLE
Support ESLint

### ISSUE THREAD

**Issue by rasmusbe** [bdkjones/CodeKit2#503]
Hi,

It would be great if you added support for ESLint, http://eslint.org/

Best regards,
Rasmus

**Comment by d-simon** [comment]
:+1:

**Comment by j5concur** [comment]
I am also in need of this feature from CodeKit (and just purchased 5+1 licenses ... 1 personal and  5 for the team I lead at work).

Has anyone created a hook that will do this?

**Comment by bdkjones** [comment]
Coming very soon.
