### ISSUE TITLE
Allow the watching of any file (based on extension) which will fire a shellscript

### ISSUE THREAD

**Issue by dmyers2004** [bdkjones/CodeKit2#505]
It would be nice to be able to have codekit watch and trigger a shellscript for any file extension.

For example I could have it watch .php files and run some kind of script script. Perhaps much like textmate use to do.

http://manual.macromates.com/en/environment_variables.html

**Comment by bdkjones** [comment]
This is already possible. Add the extensions you want to the "generic page extensions" list in Project Settings. Then, set up a Hook to fire either a Bash script or an AppleScript when the file changes. PHP is already in the list, by default.

**Comment by dmyers2004** [comment]
Does it send the file that changed to the Bash Script or AppleScript? I believe that was one of the major issues. Its great that it sees a file with the .??? changed but if it doesn't tell the script which file it was it's pretty unusable.
