### ISSUE TITLE
GAPI and prepend....

### ISSUE THREAD

**Issue by DDDgfx** [bdkjones/CodeKit2#509]
Im working on a project in coked that uses googles APIs - https://developers.google.com/api-client-library/javascript/samples/samples#LoadinganAPIandMakingaRequest

Doing so requires authentication with a developer key. Their instruction tell you to include the script in the head with this callback function that  provides the key:
<script src="https://apis.google.com/js/client.js?onload=init"></script

... and later, once it loads....

```
 function init() {
    gapi.client.setApiKey('YOUR API KEY');
    gapi.client.load('urlshortener', 'v1').then(makeRequest);
  }
```

Will there be a way to do this in my ordinary coked workflow? by using propound or append?

**Comment by bdkjones** [comment]
This issue seems incomplete.
