### ISSUE TITLE
Compiling SASS hangs

### ISSUE THREAD

**Issue by C-Benz** [bdkjones/CodeKit2#51]
When compiling SASS file, Codekit seems to hang. Just says "Compiling 'main.scss'..."  until I quit Codekit.  If I turn on the libsass compiler everything works great. I saw an issue regarding installing the pre-release of sass but am not sure if the two issues are related.

I'm running OS X 10.9, Coda 2, and working on a project that uses normalize, bourbon, and neat.

**Comment by bdkjones** [comment]
Please zip the project showing the issue, put it online and post a link here so I can test with it. Tell me which file you're saving to produce the issue.

**Comment by C-Benz** [comment]
The site is pretty huge and has a database as well so I'm not sure of the easiest way to get that to you. I did make this video of an issue that's probably related to the issue above. When I add a project, the scss file starts compiling immediately even before I've opened it to make edits.  You can see the video at the dropbox link below:

https://www.dropbox.com/s/3ao1w05cocmv6d1/Gsutah.mov

**Comment by bdkjones** [comment]
Is this project in a folder that's being watched by any other service? SugarSync? Dropbox? An IDE?

Is the project under version control? 

I need a test case that demonstrates the issue. Can you narrow the project down to just the stylesheets that are infinitely compiling, zip that and post a link here?

**Comment by C-Benz** [comment]
It is under version control with Versions (versionsapp.com).  I'm actually not experiencing this anymore though with the latest Beta. We can close this issue for now.

**Comment by C-Benz** [comment]
I take that back. It isn't automatically compiling anymore but it is hanging when compiling using the Ruby compiler. I'll zip it up and get it to you.

**Comment by bdkjones** [comment]
I can't fix bugs if I can't reproduce them. Project needed.

**Comment by bdkjones** [comment]
Seriously. Project needed.

**Comment by C-Benz** [comment]
I'll get it over to ya Monday
