### ISSUE TITLE
Compression and Internal Server stopped working since 2.1.9

### ISSUE THREAD

**Issue by ghost** [bdkjones/CodeKit2#510]
Since updating to 2.1.9 the css compression and internal server has stopped working across all my projects.

I'm on Yosemite (10.10.1) and using MAMP PRO (3.0.7.3) with espresso (2.2.2). Output style is set to :compressed in config.rb.

Rolling back to 2.1.8 fixes the issue, so I have no idea why it breaks. Are there some settings I need to change somewhere?

**Comment by bdkjones** [comment]
Yep. Read the release notes and then update to version 2.2. Compass settings are now controlled in CodeKit's UI.
