### ISSUE TITLE
CTRL-TAB Codekit does not popup

### ISSUE THREAD

**Issue by feekApp** [bdkjones/CodeKit2#517]
Hi,

when the Codekit window is closed (red close button, but Codekit is still active) and CTRL-TAB  is pressed and Codekit is selected, the Codekit window does not popup/show like pressing on the program icon on the dock (or pressing 'show window' in the menubar).

Using Codekit 2.2, OSX 10.10.2

Regards, 
Feek

**Comment by bdkjones** [comment]
Do you have CodeKit set to run from the menu bar only?

**Comment by feekApp** [comment]
HI Bryan,
tnx for the reply.
No I've CodeKit not set as run from the menubar only.

BTW I'am **now** aware not showing the window after "closing" the app via the red close button or CMD-W, is a standard Mac OSX behavior. So now I use more often CMD-H  to close/hide the window. Then the window is available via CMD-TAB (I see I've written CTR-TAB above, should be **CMD**-TAB!).

Regards and tnx,
Feek

**Comment by bdkjones** [comment]
So we’re good to close this?

**Comment by feekApp** [comment]
That's fine with me.
