### ISSUE TITLE
SASS solid strings causing 'unknown word' error

### ISSUE THREAD

**Issue by 8lane** [bdkjones/CodeKit2#519]
See this http://stackoverflow.com/questions/27314697/sass-compiler-custom-rules-exceptions/27315081#27315081 question of what I'm trying to do.

This worked fine in previous versions of CK. In the latest version, Autoprefixer gives me the following errror:

Autoprefixer failed to process the CSS file. It returned this error message: autoprefixer:/Users/xx/custom.css:119:16: Unknown word
right: 0;
background: {theme="header"};
^
width: 100%;

I asked at autoprefixer repo and they said this: https://github.com/postcss/autoprefixer/issues/410#event-233192931

**Comment by dfosco** [comment]
I've had this problem with Liquid templating strings and variables before. 

My workaround was commenting the template bits (CSS style) — not sure it will work for you, but the Liquid compiler disregards the CSS comments, so it worked for both.

**Comment by bdkjones** [comment]
Yea, there's nothing I'm going to be able to do about this. You're writing invalid CSS syntax so of course Autoprefixer is going to throw an error: it IS an error to write that sort of thing. 

I would guess that the "comment-it-out" approach is going to be your only bet. Or, you simply won't be able to use Autoprefixer on that CSS file.
