### ISSUE TITLE
Edited project name in General Project Settings reverts after delay

### ISSUE THREAD

**Issue by noahfrederick** [bdkjones/CodeKit2#52]
There's a minor issue with the process of renaming a project through the General Project Settings panel:
1. Open an existing project
2. Go to the **General Project Settings**
3. Modify the project name in the **Icon and Name** text field and wait several seconds (do not hit enter)

The field will become unfocused and the project name will revert after a delay. Other text fields in this panel do not behave this way.

CodeKit Beta 2 on OS 10.9.

**Comment by C-Benz** [comment]
Same here. The field can keep focus and it still reverts.

**Comment by bdkjones** [comment]
Fixed in Beta 4.
