### ISSUE TITLE
unable to import *.kit file from subfolder [FW]

### ISSUE THREAD

**Issue by 4ntz** [bdkjones/CodeKit2#522]
I have set up a framework that has some subfolders (one for scripts, one for stylus, one for templates). In the "TEMPLATES" folder there are only *.kit files (which are basically HTML code snippets). My Framework looks like this:

FRAMEWORKFOLDER
| - JS
|   --- some.js
|   --- another.js
| - STYLUS
|   --- grid.styl
|   --- another.styl
| - TEMPLATES
|   --- problem.kit (few lines of html code in there)

Importing the problem.kit file into a project via  results in the error: "You're attempting to import a file that does not exist in the specified location nor in any CodeKit Framework: templates/problem.kit"

Importing js and stylus files from framework-subfolders works great, its just the *.kit files that don't want to. Moving the problem.kit out of the subfolder into the "FRAMEWORKFOLDER" (which is the root folder of my framework) and importing it via  works. So it's really down to subfolders I guess.

I would love too keep things organized instead of throwing everything in my FW root folder.

**Comment by neuedeutsche** [comment]
I had that problem myself where i can not import other files into kit files if they are not in the root level.

either way i think the import path should be   (slash in the beginning to indicate root)

as soon as u want to create something a little more complex this issue is actually causing a bit of a headache.

any development on this matter?

**Comment by bdkjones** [comment]
Yep. That was a bug on my end. Fixed for the 2.2.1 release, coming up as soon as Libsass 3.2 goes live.

**Comment by NeoMudaly** [comment]
Has this been resolved? I can not seem to import other files into kit files if they are not in the root level either V2.4. For instance I have section files in subfolders and they cannot import.

**Comment by bdkjones** [comment]
Please show me a concrete example. Thanks.

**Comment by NeoMudaly** [comment]
@bdkjones - The concrete is in the mail ^^
