### ISSUE TITLE
codekit localhost address changed , now I can't preview the projects 

### ISSUE THREAD

**Issue by karimchedid** [bdkjones/CodeKit2#525]
I have problem after i moved back home , i was travelling and was working fine , now am back home i can’t preview my website, the address of my local computer changed,  before it was http://karims-macbook-pro.local:5757/  but now changed to http://karims-mbp.local:5757/ , I have no idea how that happened, now am connected via ethernet to router linksys Wrt1900AC , but i don’t believe it has something to do with it ,   how can i resolve this  the server on codekit was changed it works on bonjour when using the ip
please help 
![screen shot 2015-02-27 at 9 41 08 am](https://cloud.githubusercontent.com/assets/4855346/6409027/4395be76-be66-11e4-9247-712020931d69.png)

**Comment by bdkjones** [comment]
See http://stackoverflow.com/questions/26456803/codekit-2-doesnt-resolve-bonjour-hostname-after-yosemite-10-10-upgrade

**Comment by karimchedid** [comment]
Thanks  worked fine
