### ISSUE TITLE
Unable to 'Apply Settings' in 'General Project Defaults'

### ISSUE THREAD

**Issue by subhaze** [bdkjones/CodeKit2#529]
This may not be a bug and intended, but I was trying to get a base file setup for our team to apply to their project defaults and when I was going to show how to Apply Settings I found that it was greyed out when you're within the General Project Defaults :/

![screenshot 2015-03-16 10 24 04](https://cloud.githubusercontent.com/assets/141903/6668150/3a2ed12e-cbc7-11e4-92f3-0cfab98f6439.png)

**Comment by bdkjones** [comment]
Yea, this is done intentionally because there’s no “restore defaults” option for the initial project settings area and if you apply a file you’re going to change over 1,000 settings in one swoop, which will most likely change something you didn’t anticipate or didn’t want changed.

**Comment by subhaze** [comment]
Understandable, time to write some docs on our defaults, thanks!
