### ISSUE TITLE
Feature: Specify CSS or a stylesheet for the output HTML of a Markdown file

### ISSUE THREAD

**Issue by calvinjuarez** [bdkjones/CodeKit2#532]
It'd be nice to be able to define a default stylesheet—either external or inline—that would be injected into the output HTML.

Maybe you allow specifying a URL or path, or have a larger field for defining CSS directly (which could be copy/pasted in or whatever).  Or both.

For those using Markdown+CodeKit as a preprocessor, this won't be all that helpful, but for editing a README.md and previewing it with the output README.html, it'd be super nice to see it with GitHub's styles applied.

**Comment by calvinjuarez** [comment]
Workaround for this isn't hard.  You can just add your `<link>` or `<style>` to the Markdown file, but it'd be nicer to have that in configs rather than inline, so it doesn't create style conflicts when viewed on GitHub.com or wherever.

**Comment by bdkjones** [comment]
This is now possible using the Metadata feature of MultiMarkdown. See the MultiMarkdown docs for details.

**Comment by bdkjones** [comment]
(Doing this requires CodeKit 2.3, which switched to the MultiMarkdown compiler)

**Comment by calvinjuarez** [comment]
Rad!  Thanks!  Any thoughts on making a way to set it up outside the file itself (in case I don't want it in my repo)?
