### ISSUE TITLE
Question: Any way to compile LESS to two CSS files automatically?!

### ISSUE THREAD

**Issue by raphaelkross** [bdkjones/CodeKit2#534]
Hi!

I have one question, I hope you guys can help me. I have one CSS file and I need the output generated by CodeKit be saved in two files.

Let's say my file is named: styles.less - I would like to have two compiled files:
- styles.css - uncompressed version
- styles.min.css - compressed version

It's possible configure CodeKit to do it automatically?!

Kind Regards,
Rafael

**Comment by bdkjones** [comment]
With Source Maps, the need for this sort of thing is vastly eliminated. You can just output compressed CSS and use the Source Map to see your original Less code in the browser's web inspector.

I am aware that the current version of Less doesn't support maps with compressed output, but I think that will be resolved in the next update (hopefully; that's the Less team's area).

If you really want to do this, create two "master" Less files that each import "styles.less". Set one master file to compile compressed and other uncompressed. When you change styles.less, both master files will recompile to capture the changes.

**Comment by raphaelkross** [comment]
Hi!

Oh, great! Looks like this technique from you will do the trick, my main question was if there was a hidden button that I was missing - thank you for the info.

BTW, amazing software! Definitely, best money I spent with a great app + affordable price!

Kind Regards,
Rafael
