### ISSUE TITLE
codekit wont create folders when attempting to compile md to html

### ISSUE THREAD

**Issue by neuedeutsche** [bdkjones/CodeKit2#539]
i intend a symmetric folder structure for md and corresponding html files.
the export path pattern is set to replace "md" to "html"

**the problem:**
codekit does not create the path automatically and only compiles when the destination folder already exists. I would expect codekit to create the folder if necessary as the md file path suggests.

**when attempting to compile the md file without the "html path" ready i get this error:**
"Compiling failed because CodeKit could not write to the output file path. Ensure you have permission to write to the output path, then try again."

system permissions have been checked and should not be an issue.
export works flawless when i create the path manually (cumbersome)

**Comment by bdkjones** [comment]
Fixed in 2.3
