### ISSUE TITLE
Firefox reload

### ISSUE THREAD

**Issue by user36634** [bdkjones/CodeKit2#54]
Is there a way to get Firefox to do the Live Browser Reload?

**Comment by user36634** [comment]
Clarification. HTML changes will live reload the page, but changes made to Less > CSS are not live reloading the page.

**Comment by hlissner** [comment]
This happens with SCSS > CSS too. My results after some testing:
- Using FF Nightly (28.0a1) -> SCSS > CSS compile sometimes triggers reload the first time, but never again (have to refresh manually)
- Using FF Stable (26.0) -> Same deal, but first reload seems more reliable
- Changing the browser refresh delay doesn't seem to help.

Works fine in Opera, Chrome, Safari, iOS Safari (on iPad and iPhone), so far.

**Comment by bdkjones** [comment]
God. Dammit. I hate Firefox.

**Comment by bdkjones** [comment]
Are you seeing any sort of errors in the browser's console?

**Comment by hlissner** [comment]
I'm getting:

> "exception trying to remove old link element" (lpckrp.js:1)

EDIT:
Seems I get the same error in Chrome's console too, but it still removes the <link> element successfully, whereas it doesn't in firefox.

**Comment by bdkjones** [comment]
ah; okay. That makes it easier. I'll take a look. Can you see if CodeKit 1 is throwing the same error in Chrome when you inject CSS there?

**Comment by hlissner** [comment]
Just tried and no, no errors in Chrome with CK1. The injection works fine too.

**Comment by verpixelt** [comment]
I've created a simple test project: index.html, scss and css folder, with a style.scss/css file. Live reload doesn't work for me at all.

OSX 10.9.1
Sublime Text 3 (latest stable build 3059)
Chrome Version 31.0.1650.63 (also tested Canary Version 34.0.1752.0)
Using the standard Ruby compiler, no source map, no Autoprefixer, no Bless
Using 'Preview' with ....local:5757

**Comment by bdkjones** [comment]
@verpixelt Please zip the test project, put it on the web somewhere, and post a link here so I can download and use it. Thanks.

**Comment by verpixelt** [comment]
Here you go: https://dl.dropboxusercontent.com/u/24391334/ck2TestProject.zip

**Comment by verpixelt** [comment]
I've created another project with the same setup and no it works 0_o

**Comment by user36634** [comment]
@verpixelt I tried your example and it did live reload on the first edit and save of SCSS file, but not the second time or any time after the first.

In the console after the first reload:

"exception trying to remove old link element" lpckrp.js:1

And after the second edit I see:

The connection to ws://computer-name-here.local:5758/ was interrupted while the page was loading. lpckrp.js:1

**Comment by bdkjones** [comment]
Fixed in Beta 3.
