### ISSUE TITLE
Wrong output styles

### ISSUE THREAD

**Issue by Chrisriis** [bdkjones/CodeKit2#540]
When I choose "Compact" or "Expanded" as the output style, it returns "Nested"? 
The "Compressed" style and debug info works as expected though. I got the newest version of Sass and have tried the "shift-start" trick without any luck. I also use the newest version of CodeKit on Yosemite.

I haven't tried to reinstall Codekit yet in case someone knows a quick fix etc.

Anyone else experiencing this issue?

**Comment by a-dg** [comment]
Yes, using LibSass, "Compact" comes out as nested. The standard Ruby compiler works for me, as do the other output styles using LibSass.

**Comment by bdkjones** [comment]
This is because Libsass currently does not support other output styles. The upcoming 3.2 release of Libsass implements them.
