### ISSUE TITLE
Allow user to undo "Skip this folder"

### ISSUE THREAD

**Issue by Andreyco** [bdkjones/CodeKit2#545]
When user performs "Skip this folder" there is no way back to undo this. Please, allow user to undo this. Very simple solution would be checkboxes which would indicate whether or not to watch specified folder for changes.

Removing config file is not an option to undo this. Or am I missing a way how to do this?

Thanks for effort.

**Comment by bdkjones** [comment]
Edit the "Skipped Items" list in the General section of Project Settings. That's all the menu command does: add an entry to that list.

**Comment by Andreyco** [comment]
Missed that. Sorry
