### ISSUE TITLE
Decimal precision for Sass files is acting up

### ISSUE THREAD

**Issue by ghost** [bdkjones/CodeKit2#548]
Accessing the Sass file settings screen will initially show the **Decimal precision** as being unset. The config file shows the correct default value of **10**. Setting it to any value from the dropdown will change the value in the settings file to **0**, once program is closed and reopened. Changing the value manually in the settings file will revert the dropdown back to an unset value.

**Comment by bdkjones** [comment]
Yep. Regression in 2.3. Will issue 2.3.1 tonight to fix it.

**Comment by bdkjones** [comment]
Thanks!
