### ISSUE TITLE
Issue with External Server in XAMPP

### ISSUE THREAD

**Issue by JesusGarciaValadez** [bdkjones/CodeKit2#55]
OS X 10.9.1
Coda 2.0.12

I'm Working with SCSS, and javascript. I have a XAMPP server at http://localhost:80/ with a password if you try to enter with the same path and in the directories under that server doesn't ask for a password. I put this on the external server textfield and the "always use the external server" checkbox checked.

In CK server I have this server name: http://macbook-pro-de-jesus-3.local:5757 and after to make tests and errors, finally can to view my page with all my images, js and css files. 

But, I'm an obsessed  and I want to change it to http://macbook-pro-de-jesus.local:5757. I did it and then restart CK Server and then, nothing happens. No more page. Even retry test and error URL's and nothing.

And CK says that there's no index.html when actually there's one.

![captura de pantalla 2013-12-19 a la s 00 19 38](https://f.cloud.github.com/assets/1066733/1780553/b2b9b66c-6878-11e3-9f28-4f05caec9119.png)

**Comment by mdavis1982** [comment]
@alfabrad Could you try rebooting once you've changed your hostname in System Preferences please? It **shouldn't** make any difference, but I've had issues with it not working properly before. Thanks

**Comment by JesusGarciaValadez** [comment]
Yes. I'm not in home, but when i'm there I'll try it again and give you feedback.

**Comment by JesusGarciaValadez** [comment]
I don't know if this is related but, when I test the same site on another machine with same IDE and OS, this happens again. 

Same problem, no images, no js, no css, but when uncheck the option "always use external server for this project", refresh the page and check again the same option... BOOOM! this fix the problem and all the stuff is displayed. 

I'll check this in home to see if this fix the bug and give my feedback.

**Comment by JesusGarciaValadez** [comment]
well, do not know if the fact of restart the Mac or select and deselect the checkbox  helped because I did both actions, but I can already see again the content of the page.

But the inability to see any items unless the action to select / deselect the checkbox can cause confusion.

This happens equally in two Mac with OS X 10.9.1, Coda 2.0.12, CK2b2 and XAMP 1.8.3-0

**Comment by bdkjones** [comment]
Sorry; I'm not able to understand this one as written. Please clarify.

**Comment by JesusGarciaValadez** [comment]
Well, this happens randomly. Not always. When i'm working in a page and, for example I got the cache version of the file. 

I've tried to delete the cache version restarting the internal server or unchecking the checkbox of "Always use this internal server" and nothing. It only leave to work (the page is not showed). 

Only quitting CK2, restarting XAMPP server and launching again CK2 is when the page is showed again but the same problem with the cache version vía bonjour url. If I write localhost/...... I can view the real version of the page.

I repeat. This behavior of the internal server with not response is very randomly and occurs me in few circumstances and in others not. Even repeating the same steps to try to reproduce it. This for example happend me yesterday and only one time.

Recently i've seen the beta 4 and you say that no delivers cache version of the files. I don't know if this can resolve the problem but, i'll working with CK2 and if I see any inconvenience i'll tell you.

**Comment by bdkjones** [comment]
Have you tried Beta 4? Please don't post any results from previous betas; I'm only interested in what's happening with the latest one.

**Comment by JesusGarciaValadez** [comment]
I just saw that now available the beta 4. This happened to me yesterday afternoon with Beta 3. Right now I'm working with the new version and have not noticed anything unusual.

**Comment by bdkjones** [comment]
Excellent; thanks!
