### ISSUE TITLE
Feature Request: Organize Sidebar projects with Folders.

### ISSUE THREAD

**Issue by adampatterson** [bdkjones/CodeKit2#550]
I have Work, and Client projects in Codekit. 

I also have around 50+ projects sitting in here. about 40 of them actively used.

I would love to organize them with folders based on project type. This is really only an issue for browser refreshing with Python since I have to select to get refreshing to work.

**Comment by bdkjones** [comment]
Yea, the thing is that you should never have 50 projects in CodeKit. Even when projects are disabled, CodeKit is really watching every single item inside them for changes (it just doesn't respond to those changes). 

Keeping 50 projects in the app consumes tons of resources. It's far, far better to keep only a handful of active projects in there and remove ones that you're not currently working on. Re-add them when needed and they'll come back exactly as you left them.
