### ISSUE TITLE
Feature request: save default project properties

### ISSUE THREAD

**Issue by feekApp** [bdkjones/CodeKit2#551]
Hi Bryan,

It would be nice if there would be an option to save default project properties (as set in Menu > File > Edit Defaults for New Project) as a config.codekit file and that you can import this file on a e.g. clean installed mac.

regards,
Feek

**Comment by bdkjones** [comment]
Hi Feek, 

This is not necessary because those defaults are stored in the app's plist file, just as defaults are stored for every other app on OS X. If you'd like to migrate them to a new machine, you simply need to use Apple's migration utility or copy the plist file manually.

**Comment by feekApp** [comment]
Tnx, for the prompt reply!
So no hidden prefs files :) [thumbs-up]
