### ISSUE TITLE
Unable to select files in list after closing the output file path dialog.

### ISSUE THREAD

**Issue by rasmusbe** [bdkjones/CodeKit2#56]
Only did happen once and I don't seem to be able to reproduce it when I tried it again but:

When I closed the JS output file path dialog I was unable to select other files in the file list. The sidebar changed to the new file but the green selection in the file list didn't move.

**Comment by bdkjones** [comment]
Hmm... please keep trying to reproduce this. Otherwise, there's little I can do.
