### ISSUE TITLE
Feature request : PostCSS

### ISSUE THREAD

**Issue by regisphilibert** [bdkjones/CodeKit2#564]
Any chance to add postCSS to the list of compilers?

Cheers and thanks for the great work!

**Comment by calvinjuarez** [comment]
PostCSS's main strength is its ability to use plugins.  Would there be a plugin management system for this?  What plugins would be installed by default?

**Comment by regisphilibert** [comment]
Even though, PostCSS plugins are a must have, I could do without in the confort of CodeKit.

**Comment by regisphilibert** [comment]
Ok. I confused cssnext with PostCSS. My bad, closing.

**Comment by calvinjuarez** [comment]
cssnext would be a really sweet feature, for sure.
