### ISSUE TITLE
"Check for updates" not working

### ISSUE THREAD

**Issue by 1-800-jono** [bdkjones/CodeKit2#566]
Hi - I noticed I have an outdated version of Codekit. When I click on "Check for updates" it doesn't do anything and the option gets grayed-out.

I'm on Macbook pro OSX 10.10.3

Codekit version: 2.3.1

**Comment by bdkjones** [comment]
Thanks for the report. This was a bug in that version of CodeKit; it disabled the updater. Stemmed from a bad Git merge. The fix is to download the latest version of CodeKit from http://incident57.com/codekit manually.
