### ISSUE TITLE
Sub-sub-directory importing ../../header.kit but not CSS

### ISSUE THREAD

**Issue by andrewlobo** [bdkjones/CodeKit2#578]
Hey Bryan,

My root-directory pages and sub-directory pages are working fine. For example, sub-directory pages are pulling ../header.kit without any problem (and header.kit imports css/style.css).

But once I go two directories down (sub-sub-directories), those pages still recognize ../../header.kit, but they're not pulling css/style.css. Running v2.4 on Yosemite.

Many thanks.

**Comment by bdkjones** [comment]
Well, yea. If the import path `css/style.css` works from one level, that same import path will NOT work from a level down because the relative path is not correct from that level. You would need `../css/style.css`

**Comment by andrewlobo** [comment]
Cool, got it. I got tripped up because a root file and sub-directory file were somehow both importing a .kit file from root using the same path, so I figured it would work with the CSS file. All good now. Thanks, Bryan.

**Comment by bdkjones** [comment]
No problem; glad you got it figured out.
