### ISSUE TITLE
Feature request: Support request payloads for HTTP DELETE

### ISSUE THREAD

**Issue by ashjmcfox** [bdkjones/CodeKit2#579]
This relates to issue: [HTTP Verbs not supported?](https://github.com/bdkjones/CodeKit/issues/483)

You previously added support for PUT and DELETE when using an external server through CodeKit.

Is it possible to support request payloads for the DELETE verb?

I have an API which requires a boolean to determine if it should perform a normal or soft delete operation.

```
{
    "softDelete": true
}
```

Thanks.

**Comment by bdkjones** [comment]
Does `DELETE` support a payload? I can't find a reference to it in the spec. If you run this API directly on an Apache server (say, MAMP) does it work correctly?

**Comment by ashjmcfox** [comment]
If the request is made directly to the server, then it succeeds and works as expected. However, you're right - it's not exactly the best approach to have DELETE payloads. The spec states that payloads are not expressly forbidden, they just have no defined semantics.

["A payload within a DELETE request message has no defined semantics"](http://tools.ietf.org/html/rfc7231#section-4.3.5)

I might look into whether the API can be changed to move the payload into the URI as a query parameter.

**Comment by ashjmcfox** [comment]
Found a workaround and modified the behaviour of the API. I'll close this issue. Thanks.
