### ISSUE TITLE
Feature Request: Draggable or Repositioned "Imported By" Panel

### ISSUE THREAD

**Issue by whaaaley** [bdkjones/CodeKit2#580]
![img](http://cl.ly/image/1H0z3C190r0K/codekit-diagram.png)

When you're concatenating a bunch of files it would be nice if you could see everything at once. instead of having a tiny area to scroll up and down. While I'm not exactly sure what I was doing at the time I took this screenshot but I had to close and re-open CodeKit to get it back to a more reasonable size.

Even if this was a super rare bug I ran into, It would be nice if we could drag the imported by panel up and down or have it fixed to the bottom and grow as more files are added. I think I would prefer the later.

**Comment by bdkjones** [comment]
Agreed. You'll like what's coming late this year.
