### ISSUE TITLE
No window appears after starting CodeKit.

### ISSUE THREAD

**Issue by skhotdotcom** [bdkjones/CodeKit2#581]
Hi,

Something strange is happening with CodeKit. After clicking to open the application, no window appears on the desktop to work in. I have the menu bar, but no window. I've tried a few things:
- Restarted mac
- Shift CodeKit startup
- defaults delete com.incident57.codekit2
- right click, show all windows (none appear)
- right click, hide/show
- selecting options from the menu bar (nothing happens -- the About CodeKit screen shows if I have left it open)

The only thing I've been able to get CodeKit to do is load the About CodeKit screen and it is showing "unknown" for all of the compilers (may be a a hit at what is wrong?):
![screen shot 2015-09-10 at 9 28 16 am](https://cloud.githubusercontent.com/assets/3972658/9789472/5cd095ba-579e-11e5-8ec1-a905f33f9909.png)

I'm working with the latest CodeKit (2.4) and Mac OS X (10.10.5)

Any advice?

**Comment by skhotdotcom** [comment]
I removed and reinstalled. That seemed to have worked.

**Comment by bdkjones** [comment]
Yep. It was a corrupted app binary.
