### ISSUE TITLE
Error flagged with call to current FastClick

### ISSUE THREAD

**Issue by otheroom** [bdkjones/CodeKit2#584]
I use [FastClick](https://github.com/ftlabs/fastclick) in several CodeKit projects and just updated the prepend from FastClick 1.0.3 to 1.0.6

The resulting concatenated and minified code appears to be working but CodeKit is giving me this lint error in my mainline code where I invoke FastClick:

`FastClick.attach(document.body);`
`'FastClick' is not defined. — column 5`

FastClick is now has it's code wrapped in an anonymous function:

`;(function () {`

I suspect that's what's tripping up the syntax check and wondering why that's happening and what I can do to eliminate the issue.

**Comment by bdkjones** [comment]
Add `FastClick` to the globals list. Project Settings > Syntax Checkers

**Comment by otheroom** [comment]
Thank you sir.
