### ISSUE TITLE
CodeKit + AirPort = Spooky things happen

### ISSUE THREAD

**Issue by saschalichtenstein** [bdkjones/CodeKit2#585]
hi there,

after upgraded to el capitan i have some strange issues. if i want to preview an project (tested with different projects) , my wlan connection is lost and something's going on with time capsule/airport (indicated by orange light). Chrome is working well. With firefox dev i got same issue as with safari.

thanks for some hints to resolve problem.

**Comment by bdkjones** [comment]
I'd need exact steps to reproduce this. It sounds like a network configuration issue; there's no way for an app like CodeKit to "kill" your wifi connection---the API to do something like that simply does not exist.

**Comment by saschalichtenstein** [comment]
ok here are my steps: starting mac with el capitan, starting codekit with my projects, picking a project and click preview (standard safari), after 5-10 seconds the wifi connection is lost and the airport is doing something (yellow light), after some minutes the wlan connection is back, if i reload the project in browser the same story happens again. for the moment it happens only with CodeKit. MAMP is working well.

here's the log after refreshing the browser:

07.10.15 08:40:32,000 kernel[0]: 22421.381753: apple80211Request[10514] Unsupported ioctl 156 
07.10.15 08:40:32,000 kernel[0]: AirPort: Link Down on en1. Reason 8 (Disassociated because station leaving).
07.10.15 08:40:32,000 kernel[0]: Got incomplete channel sequence length 0, should be 16
07.10.15 08:40:32,000 kernel[0]: 22421.389244: apple80211Request[10514] Unsupported ioctl 181 
07.10.15 08:40:32,000 kernel[0]: 22421.389253: apple80211Request[10514] Unsupported ioctl 156 
07.10.15 08:40:32,000 kernel[0]: 22421.389256: apple80211Request[10514] Unsupported ioctl 181 
07.10.15 08:40:32,000 kernel[0]: Got incomplete channel sequence length 0, should be 16
07.10.15 08:40:32,000 kernel[0]: 22421.389266: apple80211Request[10514] Unsupported ioctl 156 
07.10.15 08:40:32,000 kernel[0]: 22421.389269: apple80211Request[10514] Unsupported ioctl 181 
07.10.15 08:40:32,000 kernel[0]: 22421.389274: apple80211Request[10514] Unsupported ioctl 156 
07.10.15 08:40:32,000 kernel[0]: 22421.389277: apple80211Request[10514] Unsupported ioctl 181 
07.10.15 08:40:32,000 kernel[0]: en1: channel changed to 100,+1
07.10.15 08:40:32,000 kernel[0]: en1::IO80211Interface::postMessage bssid changed
07.10.15 08:40:32,000 kernel[0]: 22421.393963: apple80211Request[10514] Unsupported ioctl 230 
07.10.15 08:40:32,253 symptomsd[334]: -[NetworkAnalyticsEngine _writeJournalRecord:fromCellFingerprint:key:atLOI:ofKind:lqm:isFaulty:] Hashing of the primary key failed. Dropping the journal record.
07.10.15 08:40:32,000 kernel[0]: in6_unlink_ifa: IPv6 address 0x3eb4b33ee95e07bd has no prefix
07.10.15 08:40:32,420 UserEventAgent[45]: Captive: CNPluginHandler en1: Inactive
07.10.15 08:40:32,421 configd[53]: network changed: v4(en1-:192.168.1.11) DNS- Proxy-
07.10.15 08:40:32,720 imagent[711]: [Warning] No incoming push handler for selector: handler:isConnectedChanged:    topic: (null)   command: (null)   context: (null)
07.10.15 08:40:32,922 symptomsd[334]: __73-[NetworkAnalyticsEngine observeValueForKeyPath:ofObject:change:context:]_block_invoke unexpected switch value 2
07.10.15 08:40:32,927 netbiosd[4945]: network_reachability_changed : network is not reachable, netbiosd is shutting down
07.10.15 08:40:35,665 CodeKit[4871]: No valid IP address other than the local feedback address (127.0.0.1) was found. The computer may not be connected to the internet.

**Comment by bdkjones** [comment]
Hi Sascha,

You’re using an Apple Airport router? Have you updated it to the latest firmware? Which generation of the router are you using?

-Bryan

**Comment by saschalichtenstein** [comment]
Hi bryan,

Yes i use a time capsule 4th generation with up to date firmware. I really have no idea what to do because this happens only with codekit at the moment and only chrome seems to be the browser without having those issues. I deactivated also f-secure and firewall but nothing changed.

**Comment by bdkjones** [comment]
There's no way for an app to kill the WiFi connection on a Mac. It's just not possible---there are no APIs to do something like that.

This happens when you use the Bonjour preview address, but does not when you use the IP address, right? That means that what's going on is that when Safari fires up whatever system frameworks are involved in resolving the Bonjour hostname, they're triggering the problem on the router. It's almost like something in 10.11 is crashing or failing, but I have literally no idea what that could be.

This doesn't affect folks with non-Apple routers, so it's something very specific to their hardware/firmware/software. 

Also: do you have any Safari extensions installed?

**Comment by saschalichtenstein** [comment]
yep you're right. it seems that bonjour address makes some problems. i'm going to report it to apple. i also could not get the connection between codekit and the problem but now you gave the hint. thanks. no extensions are installed. i was confused it happens with codekit but not with mamp. so i think you can close this ticket and keep up the good work :)

**Comment by ullewupper** [comment]
I have the same issue with my internet. I lose internet connection too when launching codekit.

**Comment by bdkjones** [comment]
Yea, it's a bug in OS 10.11. Hopefully they fix it in the 11.4 release. Until then, the workaround is to use the non-Bonjour address from the Server popover.

**Comment by ullewupper** [comment]
I don't know much about all this stuff. The strange thing is that internet doesn't work with the cable plugged in but when I switch on my wifi I can connect through wifi.

Setup
Router from internet provider -> cable 1 -> iMac (does not work with codekit)
Router from internet provider -> cable 2 -> airport extreme -> wifi -> iMac (works perfectly)

Well ... anyway ... gonna take a look into the bonjour thingy.
Thanks!
