### ISSUE TITLE
Odd drag and drop behaviour

### ISSUE THREAD

**Issue by Stucks** [bdkjones/CodeKit2#586]
Hi,

I don't seem to be able to drag and drop project folders into the main window. If I hover over the toolbar, or the edges of the window (see red areas of screenshot), It'll allow me to add the project. But hovering over the actual project area doesn't. Adding a project manually still works fine.

Running version 2.4 (19051) on a 2012 rMBP, OSX 10.11.

![codekit](https://cloud.githubusercontent.com/assets/14072398/10433012/c94fc0ea-7106-11e5-93cf-e0c2073fc562.jpg)

**Comment by bdkjones** [comment]
Yea, this issue surprised us on El Cap. I’m going to ship an update in the next day or two to resolve it. In the meantime, just use the “Add Project” command from the file menu.

**Comment by Stucks** [comment]
OK, that's great, thanks.
