### ISSUE TITLE
Bug: Typescript output directory has empty js files

### ISSUE THREAD

**Issue by subhaze** [bdkjones/CodeKit2#591]
The default is set to produce JS files in /js, however, it's produced right next to the .ts file while also creating a /js with the correct name of the .js file, but that file is empty.

**Comment by subhaze** [comment]
I believe this was introduced in the bump to TypeScript 1.6

**Comment by bdkjones** [comment]
Weird. I'll take a look at this tonight.

**Comment by bdkjones** [comment]
I can't reproduce this over here. Can you send me a project that shows the issue and steps to reproduce?

**Comment by subhaze** [comment]
Here's a dropbox link https://www.dropbox.com/s/bg3rngzoqan3dbv/codekit_typescript.zip?dl=0

I'm running:
OSX 10.10.5
CodeKit 2.5.1

I left all the TS stuff as default and just added a couple of example files and ran the TS files via CodeKit. It could be an oversight on a setting I've accidentally set, but something feels off.

You'll see the two TS files in the ts/ and there's the actual JS files right beside them that were produced correctly and then you'll find ts/js with the same JS files but empty.
