### ISSUE TITLE
Foundation 6 Support

### ISSUE THREAD

**Issue by pixeljitsu** [bdkjones/CodeKit2#592]
Any plans to add Foundation 6 as a new project type as you do with F5?  The foundation-sites (https://github.com/zurb/foundation-sites) does not appear in the components list.

**Comment by bdkjones** [comment]
In literally about 1 hour.

**Comment by bdkjones** [comment]
CodeKit 2.6 just went live with Foundation 6 built-in!

**Comment by dcsturm** [comment]
👍 Awesome
