### ISSUE TITLE
SCSS @import does work only partially

### ISSUE THREAD

**Issue by berlindave** [bdkjones/CodeKit2#599]
Hello Bryan,
first to say that I love this CodeKit App, thank you!
I got stuck with a problem. I assume it's not a bug. Probably I'm just too stupid, but perhaps you can help me:
- Zipped Example: https://www.dropbox.com/s/vfbggas7xrbhmbt/ck-weird-behaviour.zip?dl=0
- The main source file is `assets/sass/style.scss`.
  It compiles to `dist/css/style.css`.
  `assets/sass/style.scss` imports `assets/sass/foundation/_foundation.scss`.
  `assets/sass/foundation/_foundation.scss` imports several other files. I'd expect that these files are also compiled to dist/css/style.css.
- But the result I'm getting is:

``` CSS
/*--------------------------------------------------------------
# Foundation
--------------------------------------------------------------*/
/**
 * Foundation for Sites by ZURB
 * Version 6.1.1
 * foundation.zurb.com
 * Licensed under MIT Open Source
 */
```
- CodeKit 2.6.1 (19102), OS 10.10.5

What I'm doing wrong?

Many thanks in advance!
Dave

**Comment by bdkjones** [comment]
Hi Dave,

```
If you’re looking to use Foundation, your best bet is to create a new Foundation 6 Project by choosing File > New Project > New Foundation Project. Everything will be installed where it should be and the import paths will be set correctly.

I’m afraid your Dropbox link is broken, so I couldn’t take a look at your project. 
```

-Bryan

**Comment by berlindave** [comment]
Thank you, Bryan, for your quick reply!

That's what kept me off using the "instant" way for using Foundation 6: I already installed some other files in the project:

> Foundation must be installed in a completely empty folder. If you click "Proceed", CodeKit will permanently delete all existing files and folders in this project. Are you sure?

---

> I’m afraid your Dropbox link is broken, so I couldn’t take a look at your project.

I'm sorry, try this one: https://www.dropbox.com/s/vfbggas7xrbhmbt/ck-weird-behaviour.zip?dl=0

Again many thanks,
Dave

**Comment by bdkjones** [comment]
Ok. First things first: you’re trying to compile Foundation 6 with Compass. That’s a definite no. Delete the “config.rb” file and use Libsass instead. Do not use Compass with Foundation 6. 

Secondly: this is a non-standard Foundation install. It’s missing a bunch of components that are pulled down by Bower when Foundation is installed properly. That’s likely what’s causing this issue. All you’ve got here is the stylesheets for Foundation. Foundation consists of a bunch of third-party libraries as well as many JavaScript files. Those are all missing.

What you want to do is start fresh. Install Foundation in a new project using CodeKit (or install Foundation manually yourself in a new folder) then move whatever existing files you need into place in that new project.

**Comment by berlindave** [comment]
Thank you for your endeavour and your helpful hints!
Meanwhile I switched to http://jointswp.com/ as my WP starter theme and it works like a charm. :)
