### ISSUE TITLE
Error after creating new Zurb Foundation Project

### ISSUE THREAD

**Issue by tobaco** [bdkjones/CodeKit2#6]
I just tried to create a new foundation project, but after installing i got the attached error message. I don't know if this is an error in Codekit or in my system.

![bildschirmfoto 2013-12-18 um 12 07 14](https://f.cloud.github.com/assets/68937/1772648/00856714-67d5-11e3-95e5-fad3ab0668ff.png)

**Comment by bdkjones** [comment]
Do you have another Compass project handy that you know compiles fine in CodeKit 1? If so, try compiling that project using 2.0 and let me know if the same error appears.

**Comment by imapirate** [comment]
Same issue. Installing Zurb via terminal and compiling it works.

**Comment by tobaco** [comment]
same project compiles fine in codekit 1

**Comment by imapirate** [comment]
Using external sass and compass executable it compiles correctly.

**Comment by bdkjones** [comment]
Fixed in Beta 9. Will post shortly.
