### ISSUE TITLE
Codekit window not showing

### ISSUE THREAD

**Issue by tconroy** [bdkjones/CodeKit2#604]
Hello,
Codekit recently stopped appearing for me. I open the app, and it shows as open in my doc and top bar, however the main Codekit window is nowhere to be found. I cannot alt-tab to it or make it visible.

The only fix I found was re-installing the app, but this has happened twice already and would like to not do that every time.

Any ideas?

**Comment by bdkjones** [comment]
Yea, this is caused by corrupt Sparkle data. Look in ~/Library/caches/com.incident57.CodeKit2 and delete everything in there, without the app running. Download a fresh copy and hold shift while launching it.

**Comment by jeffmiranda** [comment]
This worked for me. Thanks Bryan!
