### ISSUE TITLE
The behaviour of live CSS injections on a few VMs

### ISSUE THREAD

**Issue by rpkoller** [bdkjones/CodeKit2#61]
Out of curiosity i've launched VMware Fusion 6.0.3 on 10.8.5. I've just tried out of the box: 

1) On  Ubuntu 13.10 VM (Firefox) - loading a normal webpage worked, myadress.local:5757/ worked as well as changing css, saving, applying changes by live injection. 
2) On Open Suse 13.1 (Firefox) - loading a normal webpage was working but loading myadress.local:5757/ was not. Loading forever with error page in the end. 
3) On Debian (Iceweasel) -loading a normal webpage worked, myadress.local:5757/ worked as well as changing css, saving, applying changes by live injection.  had only a few display issues but nothing reload related. ;)
4) grabbed the oldest vm from modern.ie ^^ ie6 on XP as an elktest ;)))) - normal web pages loaded but  myadress.local:5757/ did not like on Suse.

Hope that helps. Best regards Ralf

**Comment by rpkoller** [comment]
5) ie7 on Vista - normal web pages load but myadress.local.5757 shows: The webpage cannot be displayed

**Comment by rpkoller** [comment]
6) i am connected to the router via wlan  a friends computer i borrowed (win 7) is connected via ethernet. I tried to reach myadress.local:5757 from his box. Firefox worked, Chrome worked, IE 11 failed (white screen with an alert panel asking if i wanna leave the page - and there is a message alongside: Null 

-> after a while an alert box showed: can't establish a connection to codekit. live reload will not work

**Comment by bdkjones** [comment]
Can you get any kind of logs from IE or Windows showing what the problem is? 

Http headers, request results, all of that would be very useful.

**Comment by rpkoller** [comment]
uffff i will give it a try, but i am not that skilled on the windows and ie side, always tried to avoid that combo where it was possible. ;))) but i will try tomorrow and get back to you.

**Comment by rpkoller** [comment]
Hmmm tried to get hold of a few infos but me and windows/ie are no friends at all. I am stuck getting the events viewer going. I will keep trying to get any logs out outlining the issue.

**Comment by rpkoller** [comment]
ouch i guess i figured things out. i was already out of sorts when i noticed and reported that "issue" - now slowly getting back on the track i sort things out. 

no wonder it hasn't worked. as i wrote above i've used the .local bonjour adress. to get things working i would have to install http://support.apple.com/kb/DL999. the non-bonjour adress from the server pane works flawless on every setup i tried so far. 

ahhh i was headblocked. sorry. so i can confirm things work properly.
