### ISSUE TITLE
Text fields reset during refresh

### ISSUE THREAD

**Issue by maxlapides** [bdkjones/CodeKit2#62]
How to replicate issue:
1. Create a new project
2. Edit project settings
3. Start to adjust external server address (or another text field, I think)
4. When project auto-refreshes, the text field is reset to what it was before I started editing it

**Comment by rpkoller** [comment]
In the general tab it happens on the name field. my external server adress field remains the same when i try there (only tried on name and server adress field so far)

**Comment by mdavis1982** [comment]
This is a duplicate of #52.
