### ISSUE TITLE
install bitters 1.2 - OR - install Bourbon 5.0

### ISSUE THREAD

**Issue by guteideen** [bdkjones/CodeKit2#625]
blindly updated bitters to latest version, now I have compiling errors due to bitters 1.4 not playing well with Bourbon 4.2.7. After researching bitters 1.4 needs Bourbon 5.0.
How can I return to Bitters 1.2 or can I install Bourbon 5.0?

**Comment by bdkjones** [comment]
mmm, according to the Bourbon/Bitters pages, 5.0 is still in beta. Once it's officially released, I'll update the built-in version of Bourbon and Bitters in CodeKit.

All you really need to do to use either one is copy the Bourbon/Bitters stylesheet assets into your project and then update your @import statements to point to them.
