### ISSUE TITLE
Incident57.com down?

### ISSUE THREAD

**Issue by KillerDesigner** [bdkjones/CodeKit2#626]
Howdy BDK,

Got an update error just now in CodeKit, then went to site and am receiving 403 Forbidden errors.

You probably already know, but just in case you didn't...

![incident57 403 forbidden](https://cloud.githubusercontent.com/assets/3208524/18810645/94b1cf34-8250-11e6-83b0-3b8fe1026dde.png)

**Comment by bdkjones** [comment]
Oh, I know.

I'm in the middle of what's turning out to be the worst migration ever. My professional advice is: do not change your origin server AND simultaneously activate CloudFlare. DNS goes nuts and takes forever to recover. 

The site should be coming back online now. It's up for me in Seattle (via VPN), but the rest of the world may take time to propagate all the changes. 

I had originally hoped for this to be a smooth transition to a new server. That does not appear to be the case.

**Comment by KillerDesigner** [comment]
Ha, wow. Been there, done something like that.

Is it beer-thirty yet?

Steve
