### ISSUE TITLE
Log visual output - overlapping text

### ISSUE THREAD

**Issue by maxlapides** [bdkjones/CodeKit2#63]
Just a minor formatting issue:

![2013-12-19_14-27-31](https://f.cloud.github.com/assets/1874682/1785400/9c458990-68e3-11e3-832a-6964196a2ae1.png)

EDIT: I forgot to mention that I'm running Mavericks (10.9.1)

**Comment by bdkjones** [comment]
Can anyone get this to happen reliably?

**Comment by Andreyco** [comment]
Yes, this happend to me as well.
- **it only ovelap on last log entry**
- **reopening log entry fixes this**: I click on last (opened) log entry to close it. I click again, so that it opens and everything is OK

**Comment by rpkoller** [comment]
over here in beta 15 everything looks clean and correctly laid out

**Comment by mkoistinen** [comment]
Happens to me all the time. I'm running in 10.8.5 and I believe version 16 (16534).

Now, I just clicked the last log entry to collapse it and it seems to have fixed itself. If it happens again, I'll see if I can reliably recreate this issue.

**Comment by mkoistinen** [comment]
This happens constantly for me, so I've recorded a short video showing/explaining: http://cl.ly/1k2C371y2h0T

**Comment by mkoistinen** [comment]
Fixed for me in Beta 17

**Comment by geebru** [comment]
If this was fixed it seems to have reared its ugly head again.

![screen shot 2014-03-06 at 11 41 52 am](https://f.cloud.github.com/assets/806033/2347562/15f61bbe-a54e-11e3-9615-0c1a36a2b950.jpg)

OSX Mavericks 10.9.2 : CodeKit 2.0 (16828)

**Comment by seanjuarez** [comment]
+1

Still seeing it in CodeKit 2.0.4 (16903).

**Comment by rasmusbe** [comment]
+1

(Codekit 2.0.5)

![screenshot 2014-05-16 15 43 44](https://cloud.githubusercontent.com/assets/2124386/2997519/2fe7f418-dd00-11e3-868b-c34dc415d848.png)

**Comment by bdkjones** [comment]
FINALLY managed to track this fucker down. Fixed for 2.1.9.
