### ISSUE TITLE
The CodeKit Server Does Handle SVG Images?

### ISSUE THREAD

**Issue by bobrocke** [bdkjones/CodeKit2#64]
The home page of my site has an SVG image on it. That image loads fine when accessed directly from Safari on my MAMP Pro virtual server. But when accessed via the CK server, the rest of the page is there, but the SVG is missing.

Is there something I have configured wrong, or does the CK sever not like SVGs?

**Comment by bdkjones** [comment]
Can you zip the project and send it to me so I can test over here? Or see if you can recreate the issue in a small demo website?

**Comment by bobrocke** [comment]
Emailed a .zip.

**Comment by bdkjones** [comment]
Good catch. SVG response headers require a special mime type to be set. Support for SVGs is added in Beta 3.

**Comment by bobrocke** [comment]
But Beta 3 didn't fix it for the test case I emailed you.

**Comment by bdkjones** [comment]
It's working perfectly over here on that test case. That's what I used. 

I see a bob rockefeller logo in my browser at vdk.local:5757 when I click preview. Are you _sure_ you're running the latest beta?

**Comment by bobrocke** [comment]
I'm running what called itself Beta 3 on Github. It is version 2.0 build 15658.

**Comment by bdkjones** [comment]
Definitely working over here. Going to close. Check with Beta 4 when I post that in a few and let me know if it continues.

**Comment by bobrocke** [comment]
I tried it with beta 4 (v2 15773) and still have the problem. But, of course, I'm using a MAMP PRO server to handle requests that the CodeKit server doesn't.

**Comment by bdkjones** [comment]
Try the demo project you sent me without using an external server. There is something finicky on your end, because it's working reliably over here.

**Comment by bobrocke** [comment]
Yes, the demo project works just fine with just CodeKit's internal server (http://rockbox.local:5757). And it works fine from Safari and Chrome to the MAMP PRO server (http://localhost:80). But the SVG is still not served when telling CodeKit to always use the external server at http://localhost and port 80.

Where can I be looking for some debug information and a clue about what's configured wrong where?

**Comment by bdkjones** [comment]
Ah. Finally fixed for the external servers in Beta 7. Will post that version tonight.
