### ISSUE TITLE
AppEngine dev_appserver.py - all POST requests fail

### ISSUE THREAD

**Issue by zengabor** [bdkjones/CodeKit2#65]
Method  POST
Cached  No
Status  Method Not Allowed
Code    405

Looks like all POST requests fails with "Method Not Allowed" on local Google AppEngine. 

However, I don't see the request reach the local app engine dev_appserver.py, the request doesn't show up in the logs.

Would be great to see what CodeKit tries to call, like in Console or somewhere.

**Comment by bdkjones** [comment]
Closed as a duplicate. Please search issues before posting bugs.

**Comment by bdkjones** [comment]
POST request support is coming in Beta 3.
