### ISSUE TITLE
AppEngine dev_appserver.py - CSS not injected

### ISSUE THREAD

**Issue by zengabor** [bdkjones/CodeKit2#68]
Although the browser shows x.local:5757/something and the Sass scss files are successfully compiled the new CSS is not injected into the browser window. Manual refresh works.

(Project had to be set to "Always use my external server for this project" otherwise CodeKit cannot show anything from AppEngine.)

**Comment by bdkjones** [comment]
what is AppEngine? Never worked with it.

**Comment by zengabor** [comment]
It's Google's cloud development platform: https://developers.google.com/appengine/

I use the Python SDK with its local development server, which has worked perfectly with CodeKit 1.x

Gabor

**Comment by hlissner** [comment]
AppEngine appears to use permalinks, so this is likely the same issue as #57 and #15.

**Comment by mdavis1982** [comment]
Closing as this is a duplicated issue as @hlissner said.

**Comment by zengabor** [comment]
Still broken in Beta 4

**Comment by zengabor** [comment]
This looks like #15 indeed

**Comment by zengabor** [comment]
Just for the record: this is fixed in Beta 6 (and probably already in Beta 5). Very good news.
