### ISSUE TITLE
Preview button doesn't direct to the file selected in CK2 Internal Server.

### ISSUE THREAD

**Issue by JesusGarciaValadez** [bdkjones/CodeKit2#69]
Suppose this, I set the External Server Addres like: http://localhost/folder/folder2/ and the External Server Port in 80.

When I click on a file, for example: file.php and click in the Preview button I expect the browser send me to http://my-macbook-pro.local:5757/file.php but this not happend that way. 

The browser's URL always is http://my-macbook-pro.local:5757/ and if I want to see the parse of file.php I have to write manually the "file.php" at the end of the URL. 

There's no way to only select the file to want to see and click "Preview" to see directly the parse content of that file?

**Comment by bdkjones** [comment]
Hmm.

An interesting concept. The preview button will always open the _project_ in the browser; not a specific file. There are edge cases to the suggested approach:
1. What if the selected file is not a page that's meant to be displayed but rather a backend script such as "orderHandler.php"?
2. What assumption do we make when several files are selected?

**Comment by mdavis1982** [comment]
@bdkjones @alfabrad I think this is more of a feature request for the ability to open individual files in the browser. Maybe a contextual menu and an "Preview in browser" or something? I don't know.

**Comment by JesusGarciaValadez** [comment]
@mdavis1982 Yes, yes. It could be more like a request for the ability. I encounter so usefull to open directly each file with a single click rather to write each page manually. :/

@bdkjones About the first point. Well, I think this is more like responsability of the developer to know what is each backend file and for what is. CK2 only meets with display the parsing of the file as if typed manually in the browser.

For the second assumption. Hmmm, I can think of a couple of options.

1.- Disable the preview button. So, do not have to think in how to or how many of those item are displayed.

2.- Contrary to first option, show every item on different tabs. Only displaying html and server side pages. Not images, nor CSS or JS files.

What do you think?

**Comment by bdkjones** [comment]
The preview button is going to remain "Open this project in the browser" because that's very straightforward and simple. You click the Preview button, you see your current project in the browser. Always.

However, I will add a contextual menu item to preview the selected item in the browser.
