### ISSUE TITLE
After "Project could not be saved" error, all projects/frameworks gone

### ISSUE THREAD

**Issue by geebru** [bdkjones/CodeKit2#75]
Mid-project I started getting an error along the lines of "Could not save" (like a dummy I didn't screenshot it). I continued on as usual until I saw it a few more times. Upon quitting it said I had unsaved changes, was I sure - said yes, quit.

Upon reopening the app, all my loaded projects/frameworks are gone. If it happens again I'll be sure to screenshot/cast it but wanted to document that it happened.

_OSX Mavericks 10.9_
_Compiling from Sublime Text 3_
_CK2 Build 15570_

_Set to Hold as this was related to an old build - feel free to close - I'll comment if it happens again._

**Comment by bdkjones** [comment]
I'd run Disk Utility and verify your disk and permissions. That's usually the only thing that causes CodeKit to fail to save.
