### ISSUE TITLE
Compass output css to root folder

### ISSUE THREAD

**Issue by Raslucas** [bdkjones/CodeKit2#76]
Hello there, 

This is not necessarily a bug, but it is something that existed in CK1 and still is present. I am doing some child theming in Wordpress, because of this, files need to be in certain places. I need to output my css file to the root folder of the project, but compass is insistent on it being any folder other than the root. Because of possible original theme updates, I would rather not mess with the site mapping if I don't have to. It is safer to just put the css file in the root of the theme.

This may be a compass thing, but right now I just have to avoid using the compass implementation.

Thank you,

**Comment by sethta** [comment]
This is a Compass thing, not a CodeKit issue. Here's the code I use (added to the bottom of config.rb) to move my style.css and editor-style.css files up one directory to my theme root. Modify it as needed for yourself.

```
# Move style.css to theme home directory
require 'fileutils'
on_stylesheet_saved do |file|
  if File.exists?(file) && File.basename(file) == "style.css"
    puts "Moving: #{file}"
    FileUtils.mv(file, File.dirname(file) + "/../" + File.basename(file))
  end
  if File.exists?(file) && File.basename(file) == "editor-style.css"
    puts "Moving: #{file}"
    FileUtils.mv(file, File.dirname(file) + "/../" + File.basename(file))
  end
end
```
