### ISSUE TITLE
Libsass errors with variable and mixins in subdirectories

### ISSUE THREAD

**Issue by danielbaars** [bdkjones/CodeKit2#77]
When I try to use variables or mixins already declared in (Sass framework) inuit.css and I use the (amazingly fast) libsass compiler I get errors like these:

'error: no mixin named font-size'

'error: unbound variable $giga-size'

When I switch back to the (frustratingly slow) Ruby compiler it compiles without an error.

**Comment by bdkjones** [comment]
This is not an issue with CodeKit; this would be something to file on the libsass page. Thanks.
