### ISSUE TITLE
Unable to set project paths for .kit files

### ISSUE THREAD

**Issue by sathomas** [bdkjones/CodeKit2#78]
Trying to set the Initial output path for new Kit file for a freshly created project.
1. Initially the "To this path" input would not accept key presses.
2. The popup dialog would immediately reappear after being dismissed.
3. After changing select from "The source file's folder" to "The project's root folder", the above problems went away, but the input value was not persisted on save.

**Comment by hartless** [comment]
Same issue here, however changing the select has no effect on the popup reappearing. 

Selecting option "By replacing all instances of this path component" causes the popup to repeatedly appear as well, and not accept key presses.

Switching fields causes multiple popups to appear over each other.

![screen shot 2013-12-24 at 1 35 26 pm](https://f.cloud.github.com/assets/1090636/1806975/42c66f48-6cca-11e3-8bbb-491febd2629d.png)

Seeing similar behavior in Jade and Slim as well.

**Comment by bdkjones** [comment]
Fixed in Beta 4.
