### ISSUE TITLE
I get undefined mixins in one of my projects all the time. 

### ISSUE THREAD

**Issue by rpkoller** [bdkjones/CodeKit2#79]
In one of my project this is literally driving me crazy. I am unsure if it is Codekit related at all or basically more of a compass issue. The project is erroring out on several mixins if called: with undefined mixin `xyz`. prefereably happens with gradients, modular scale and  vertical rhythm (the adjust-font-size-to mixin preferably). It's a Wordpress theme. Tried it in Codekit 1 and Codekit 2 as well as plain 'compass watch' in the terminal. Always the same result. I 've created also a stripped down testcase where everything is working like a charm. Could it be maybe an Cache related issue? I know of the .sass-cache folder but is there also one for compass? Has anyone experienced that kind of issues yet? If it would be Cache related maybe an option in Codekit for deleting the Cache folder would be a good idea? Best regards Ralf

**Comment by bdkjones** [comment]
If you're getting the same result in CodeKit 1, 2 and the command line, the problem is definitely not the app. 

You can disable the cache by adding the appropriate line in your Compass config.rb file. See the Compass docs.

**Comment by rpkoller** [comment]
Sorry was out of order a bit longer than expected and still not completely recovered like i wrote you already in mail before. But i try to catch up a little with pending issues. Back to topic. 

Yep it was mainly a gem issue. I mostly use Team Sass gems and they are in transition to completely depending on Sass 3.3. and Compass 1.0 so step by step gems started to behave odd. Somehow a few gems could be updated anyway and still "work" "somehow". The only exception was Breakpoint. But the others updated but just started to behave odd. Figured things out. Stripped down my gem stack to stable Sass and Compass and the latest versions of team sass gems not requiring Sass 3.3. or Compass 1.0 in any way. Since then everything works flawlessly again - also in Codekit.
