### ISSUE TITLE
Allow custom root directory for local preview

### ISSUE THREAD

**Issue by sathomas** [bdkjones/CodeKit2#81]
I prefer separate `/src` and `/build` folders in my projects, with all of the resulting build artifacts in `/build`. (For me, at least, that makes it easier to deploy -- copy everything in `build` -- and easier to maintain -- `.gitignore` everything in `build`.) Unless I'm missing something, however, there's no way to tell the local preview server to host files from any folder than root. I'm aware that you can enter a path in the URL, e.g. `http://macbook-air.local:5757/build/index.html`, but
- that's an extra manual step that can get annoying, and
- it doesn't work for resources that rely on absolute paths (`favicon.ico` comes to mind immediately).

**Comment by mdavis1982** [comment]
I think this is related to #69 - And I think that this is a feature request more than a bug.

**Comment by sathomas** [comment]
Related yes but definitely different. I'm not asking to preview an individual file. I'm suggesting an option that sets the root directory of the project differently for local web hosting.

**Comment by bdkjones** [comment]
Implemented in Beta 4.
