### ISSUE TITLE
Ability to install bower components under custom directory

### ISSUE THREAD

**Issue by wingsline** [bdkjones/CodeKit2#84]
Some projects might require that the bower components be installed under a custom directory instead of the project root/bower_components. It would be nice to configure the bower components path.

**Comment by sathomas** [comment]
+1

**Comment by bramdevries** [comment]
You can add a .bowerrc file which is basically a json where you add an item **directory** and the folder you want to store your bower components in.

```
{
   "directory": "js/libs"
 }
```

CodeKit will respect this file and install the assets in this folder.

**Comment by mdavis1982** [comment]
This is a duplicate of #27.
