### ISSUE TITLE
TypeScript compilation doesn't work

### ISSUE THREAD

**Issue by gAmUssA** [bdkjones/CodeKit2#85]
Hi,

TypeScript compilation doesn't work.

Example app repo:
https://github.com/gAmUssA/typescript_with_requirejs

Issue video (password - name of this repo)
https://vimeo.com/82482819

»  sys_info
ProductName:    Mac OS X
ProductVersion: 10.9.1
BuildVersion:   13B3116
CK 2.0 (15658)
Bundled TypeScript

Thanks

**Comment by bdkjones** [comment]
Someone didn't watch the video.

**Comment by gAmUssA** [comment]
@bdkjones I watched video 3 times (2 times before to submit this issue) and still not following what you referring to. Please, point me.

Thanks

**Comment by gAmUssA** [comment]
This I found in Console.app after clicked process button 

```
12/23/13 12:29:25.408 PM CodeKit[14959]: LPCompiler was asked to compile a type of file that it does not recognize: /Users/apple/Dropbox/projects/temp-app/app/main.ts
```

Thanks

**Comment by bdkjones** [comment]
I very clearly explained that TypeScript was not working in the beta builds.

**Comment by gAmUssA** [comment]
@bdkjones oh, now I got it. Any ETA?
Thanks
