### ISSUE TITLE
.kit includes not picking up included contents

### ISSUE THREAD

**Issue by sathomas** [bdkjones/CodeKit2#86]
With the following project structure:

```
src/
    css/
        hero.scss
    html/
        index.kit
```

The `index.kit` file has the following statement

```
<style>
    <!-- @import '../css/hero.scss' -->
</style>
```

The dependencies show up in the CK window

![screen shot 2013-12-22 at 9 34 38 am](https://f.cloud.github.com/assets/1731910/1797879/3c6ab394-6b16-11e3-9be5-104b89283c2d.png)

![screen shot 2013-12-22 at 9 34 47 am](https://f.cloud.github.com/assets/1731910/1797880/40bdc918-6b16-11e3-9c27-c64db99b610b.png)

There are no errors in the compilation (though the log display is a bit messed up)

![screen shot 2013-12-22 at 9 36 37 am](https://f.cloud.github.com/assets/1731910/1797882/832404c0-6b16-11e3-9850-9e6cb46413c9.png)

However, the resulting `index.html` doesn't include the contents of `hero.scss`:

```
<style>
        </style>
```

Notes:
- In case it's a bit obscure, the reason for this approach is to inline the essential styles so they're loaded along with the html, avoiding a extra network request to get to first paint. The bulk of my styles affect content "below the fold" and are loaded in the traditional manner as external style sheets.
- And yes, I know I'm including a SASS file instead of a CSS file and the browser won't be able to parse SASS; however, this particular SASS file (and any others included in this manner) are actually pure CSS.

**Comment by sathomas** [comment]
Full contents of hero.scss:

```
#img-atltrails {
    background-attachment: fixed;
    background-position: top left;
    background-repeat: no-repeat;
    background-size: 100%;
    display: inline-block;
    min-height: 0;
    vertical-align: middle;
    width: 100%;
}
#img-atltrails > span {
    display: block;
    height: 0;
    padding-top: 63.4375%;
}
/*
#img-atltrails {
    background-attachment: fixed;
    background-position: top left;
    background-repeat: no-repeat;
    background-size: cover;
    min-height: 100%;
    position: absolute;
    width: 100%;
}
*/
@media not screen {
    #img-atltrails { background-image: url('img/atltrails-xl.jpg'); }
}
@media only screen and (max-width: 400px) {
    #img-atltrails { background-image: url('img/atltrails-sm.jpg'); }
}
@media only screen and (min-resolution: 2dppx) and (max-width: 400px) {
    #img-atltrails { background-image: url('img/atltrails-md.jpg'); }
}
@media only screen and (min-width: 401px) {
    #img-atltrails { background-image: url('img/atltrails-md.jpg'); }
}
@media only screen and (min-resolution: 2dppx) and (min-width: 401px) {
    #img-atltrails { background-image: url('img/atltrails-lg.jpg'); }
}
@media only screen and (min-width: 801px) {
    #img-atltrails { background-image: url('img/atltrails-lg.jpg'); }
}
@media only screen and (min-resolution: 2dppx) and (min-width: 801px) {
    #img-atltrails { background-image: url('img/atltrails-xl.jpg'); }
}
@media only screen and (min-width: 1601px) {
    #img-atltrails { background-image: url('img/atltrails-xl.jpg'); }
}
```

**Comment by sathomas** [comment]
Note: If I remove the `<style>` tags from the including file and incorporate them into the included file, things work as expected.

**Comment by bdkjones** [comment]
Interesting. Please zip this project, put it online and post a download link here. Thanks.

**Comment by sathomas** [comment]
Hmmm... Undoing the changes I made to get it to work and ... now I can't reproduce the problem. Here's a link to the [working project](https://www.dropbox.com/s/mtzh7acrchd2mx0/works.zip).

**Comment by bdkjones** [comment]
Well, I did find a bug while exploring this. If the output folder does not exist, the Kit compiler will now create it instead of failing.

However, I cannot reproduce the issue described in the original report. No matter what I change or where I put the style tags, everything works. I'm going to chalk this up to a typo in the original files before you made changes. Issue closed.
