### ISSUE TITLE
Same folder appears twice

### ISSUE THREAD

**Issue by sathomas** [bdkjones/CodeKit2#87]
See screenshot. `styles` shows up twice. FWIW, I've got `normalize.scss` set to compile to the same folder; suspect that's causing the problem.

![screen shot 2013-12-22 at 1 12 09 pm](https://f.cloud.github.com/assets/1731910/1798213/c2c1506a-6b34-11e3-9cb6-bea3beed5730.png)

**Comment by bdkjones** [comment]
Please zip this entire project, post it online and then put a link here so I can download it and test on my end. Thanks.

**Comment by sathomas** [comment]
The problem wasn't with the project itself but in the `~/Library/CodeKit/CodeKit4.storedata` file. After trashing that, the project reloaded fine. Here's the old file from Time Machine: [`CodeKit4.storedata`](https://www.dropbox.com/s/xu2jlgw2meko82k/CodeKit4.storedata). The project itself is the same as #86 and the link there is still good.

**Comment by bdkjones** [comment]
Have you been able to reproduce this? If so, please reopen. Otherwise, I'm going to mark this as a one-off.

**Comment by sathomas** [comment]
Just happened again with Beta 4:

![screen shot 2014-01-01 at 9 46 10 am](https://f.cloud.github.com/assets/1731910/1829729/9f565b5e-72f3-11e3-8808-40493b07e7ce.png)

I was setting the output path for a new file (`about.md`) and switched the resulting extension from `.html` to `.kit` (while also adding the `_` prefix).

Here's the zipped up project: https://www.dropbox.com/s/suhsd0ghb9ypgrg/atltrails.zip

Here's a copy of the `.storedata` file: https://www.dropbox.com/s/gghyerz9v0h8jg2/CodeKit5.datastore

Here's a copy of the `.plist` file: https://www.dropbox.com/s/yhmnci6x8bzybva/com.incident57.CodeKit2.plist

**Comment by sathomas** [comment]
`Shift+` startup and re-adding the project cleared up the problem, FWIW.

**Comment by bdkjones** [comment]
Have you been able to reliably reproduce this with a set of steps and a demo project?

**Comment by sathomas** [comment]
I don't think I was ever able to reproduce this one reliably. It only happened the two times documented above. I haven't seen it since Beta 4.

**Comment by bdkjones** [comment]
Ok. Closing as unreproducible.
