### ISSUE TITLE
External Server with Projects in Subdirectories

### ISSUE THREAD

**Issue by consindo** [bdkjones/CodeKit2#9]
I have MAMP setup with a bunch of projects as folders under htdocs directory. Adding one of these projects to CodeKit and using the external server doesn't work properly.

The CodeKit server will serve the root page of the external server, but nothing else under it. Adding the htdocs root directory works as expected, but when there's multiple projects in it, it feels dirty.

![screenshot 2013-12-19 00 14 56](https://f.cloud.github.com/assets/1617948/1772706/a60b0c6a-67d6-11e3-860a-8222703076cb.png)

**Comment by bdkjones** [comment]
You need to edit the project settings and add the subdirectory to the address of the external server. It would look something like:

http://localhost:8888/sub_directory
