### ISSUE TITLE
Are we sticking with using the internal server for everything?

### ISSUE THREAD

**Issue by smlombardi** [bdkjones/CodeKit2#90]
It's kind of a pain with Wordpress work.  I need to switch to the actual dev url to correctly log into the dashboard -- if I try it through the CK server, I get an error about cookies and it fails to log in.

So I find myself with tabs open to 2 different urls to work on the same site.  And many times I wonder why i'm not seeing css changes to find I'm looking at a tab with the direct dev url instead of CKs.

It would be great it "bypass internal server" did just that...

**Comment by mdavis1982** [comment]
This is a duplicate of #57. Closing.
