### ISSUE TITLE
CK2 tries to find Safari Resources?

### ISSUE THREAD

**Issue by devilskitchen** [bdkjones/CodeKit2#91]
When I opened CodeKit 2 this morning, it launched and then opened a Finder window to the following location:

```
~/Applications/Safari.app/Contents/Resources
```

(Safari is my default browser.)

Dismissing the window doesn't seem to do any harm, but it's a bit odd.

**Comment by mdavis1982** [comment]
@devilskitchen Are you sure it was CodeKit that did that? And does it happen every time you launch the app?

**Comment by devilskitchen** [comment]
It seemed to be. It's not doing it now. I'll close for the moment.

**Comment by zengabor** [comment]
I have this regularly with CodeKit 1
Very annoying. The only way to fix it is to do a re-login. :(

**Comment by mralexgray** [comment]
I can confirm this... 

`appleeventsd: , error #268435460 (ipc/send) timed out attepting to send eEntitlement for pid 16780, port ( port:26639/0x680f rcv:0,send:31,d:0) from senderPid 16835 (sendEntitlementsToMachPort()/appleEventsD.cp #1916) client-reqs-q
`

and

`Safari: NSWorkspace received an error while attempting to send a 'mvis' AppleEvent to the Finder. The error was Error Domain=NSOSStatusErrorDomain Code=-1712 "The operation couldn’t be completed. (OSStatus error -1712.)" (errAETimeout: the AppleEvent timed out ) (line 1730)`

Each of those errors is repeated three (!!) times, _I think_, on EACH save!  Ay, carumba, help!

PS: For someone (_i.e. studly mcjones_) wanting to fix this.. set `AEDebugReceives` and `AEDebugSends` in your `env` for fun + profit.

**Comment by bdkjones** [comment]
This has nothing to do with CodeKit; it sounds like a bug in the FSEvents daemon that sends file events to registered observers all over the system. If you do a bit of Googling, you'll see that the "resources" folder issue crops up with a variety of other apps as well.
