### ISSUE TITLE
Cachebusting issue with reload

### ISSUE THREAD

**Issue by sethta** [bdkjones/CodeKit2#92]
I am not sure if this is an issue with WordPress and CodeKit, or just CodeKit.

I am developing a WP site using MAMP (OPCache is disabled). I have turned off Pretty Permalinks so I can have the reload feature through CK2. I have also double checked that I have no cacheing plugins installed.

When I save a css file, the parameter new=RANDOM_NUMBER is added to the css on the page so the cache is busted. This is good, and works correctly.

When I save a php file, the page reloads with the correct HTML, but the css reverts back to the initial file. I must then go and resave my CSS file to rebust the cache so it looks correct.

If I do a standard Shift Reload through Google Chrome, the css will not update. I have also tried opening the source and hard refreshing that, but I still have the cached version.

If I switch over to my actual .dev domain instead of the .local:5757, then I can reload the files without an issue.

The main issue arises when working with javascript files. I literally have to write in my own cachebuster on the file using the parameter v=NUMBER after each save to see my changes, or I have to just work on my .dev domain and ignore the autoreload functionality from CK2.

OS: 10.9.1
Editor: Sublime Text 3
File Types: PHP (WordPress), Javascript, CSS (using Compass)

**Comment by smlombardi** [comment]
I am seeing the same issue.

**Comment by bdkjones** [comment]
I've made some changes to CodeKit's internal server to combat caching. They will be in Beta 4, which I'll post this evening. Please update, try again, and let me know if this issue persists after that.
