### ISSUE TITLE
Crash with every save

### ISSUE THREAD

**Issue by yratof** [bdkjones/CodeKit2#93]
Just downloaded the Beta 3 and dragged it to Applications, however, I'd forgotten to rename Codekit 1, so the CK2 overwrote it. 

For a brief moment, I didn't mind, but now, every time I save from CODA2, Code kit just instantly crashes when compiling.

**Comment by yratof** [comment]
I've gone back to Beta 1 which doesn't crash, I haven't tried with beta 2 as the weekend seemed to have skipped past me...

**Comment by bdkjones** [comment]
I need the crash reports. Also, did you try the shift-reset with CK2? What language are you working in --- I need a lot more details in bug reports, please.

**Comment by devilskitchen** [comment]
Beta 3 crashes whenever I add a Project—whether I drag it on or add it through clicking the projects button. I have tried a number of different projects, with differing levels of complexity and file density. I have also tried the Shift-Reset and still no joy.

A couple of crash logs emailed to you, referencing Ticket #93, comment 4.

c

P.S. Late 2006 Mac Pro, 2x2GHz Dual-Core Intel Xeon, 5GB RAM, 1TB HDD, running Mac OS 10.7.5

**Comment by bdkjones** [comment]
I need the zipped projects that are crashing. Are they local on your disk, remote drive, etc. Details.

**Comment by devilskitchen** [comment]
Any and all projects on this machine. Local on my disk. Here's an example: https://www.dropbox.com/sh/qu2ta4p5bfwo2ip/ssrc7NgfO_

**Comment by yratof** [comment]
Merry Christmas Eve.

Crashing details:
- Report: http://cl.ly/T5mf
- Using Coda 2 + Codekit Beta 3 when saving SCSS files
- I've started Codekit while holding shift to clear everything every time.
- Files are on Mac Mini over Network

After restarting the computer, I'm not confronted with this error, rather than it crashing: http://pastebin.com/yeWajVi3
I started a blank project to see if it was the project files doing this, but a blank .scss files gives the same errors

**Comment by bdkjones** [comment]
yratof -- your crash report shows libsass as the culprit. That problem will be solved in Beta 5, which I'm going to post shortly.

This thread has been co-opted by other people reporting crashes when adding projects to the app. If those are still an issue with the latest beta, please open a new thread with an example project and details. 

Fixed in Beta 5.
