### ISSUE TITLE
Scss doesn't compile functions

### ISSUE THREAD

**Issue by yratof** [bdkjones/CodeKit2#94]
Running CK2 compiles my scss file, but ignore my functions and outputs the variables rather than what they should be:

`@return calc((100% - #{$gutter_offset}) / #{$divisor});`

Should output:

`width: calc((100% - 11rem) / 12); }`

But with Codekit 2, i'm outputting:

`width: calc(100% - $gutter_offset/$divisor);`

I'm not 100% sure if that is due to SASS 3.3.0.rc.2 yet

**Comment by bdkjones** [comment]
Yea, this definitely has nothing to do with CodeKit. 

Let the Sass team know about this so they can fix it.

**Comment by yratof** [comment]
Sweet, I'll post it over on sass
