### ISSUE TITLE
Output for Javascript files is not honored

### ISSUE THREAD

**Issue by bakura10** [bdkjones/CodeKit2#95]
Hi,

In my Compass project, I changed the option "Initial output path" for JavaScript files, from "to this path: /min" to "the same folder as the source file". However Codekit does not honor this option and continues to save the file under the /min subfolder.

**Comment by shshaw** [comment]
Possibly related to #44?

**Comment by bdkjones** [comment]
Did you click the 'sync' button to the right of the "Initial Output Paths" title? Changing those options does not automatically affect existing files. Related issues fixed in Beta 4.
