### ISSUE TITLE
Assets, bower failed to install...

### ISSUE THREAD

**Issue by thierrymichel** [bdkjones/CodeKit2#99]
I tried to install some components (normalize.css, jQuery).
Here is the error message :

> Bower failed to install 'normalize-css'. It returned this error information:
> Code: ENOGIT
> Message: git is not installed or not in the PATH 

In the Terminal :
`which git` -> `/usr/local/git/bin/git`
`echo $PATH` -> `[...]:/usr/local/git/bin`

The bower package is not installed and I use npm and rvm.
Am I wrong with something

**Comment by bdkjones** [comment]
Interesting. Git has nothing to do with Ruby, so I don't know what's going on here.

**Comment by mdavis1982** [comment]
@thierrymichel @bdkjones Seems to be a common issue - although nothing to do with CodeKit... It seems to be a config issue, although the system should know where it is. http://stackoverflow.com/questions/20666989/bower-enogit-git-is-not-installed-or-not-in-the-path has a fix.

**Comment by bdkjones** [comment]
Fixed in Beta 8. 

Git is now bundled correctly into the CodeKit application, so Bower will work even if your system does not have Git installed.
